WordPress/openverse

.github/GITHUB.md, .github/workflows/label_sync.yml, data/labels.yml, python/README.md, python/models/label.py, python/models/label_group.py, python/sync_labels.py
Fixes #16.
This PR adds the script and workflow to ensure that the given set of standard labels are present on all repositories, in addition to whatever extra labels the repo has defined.
=> Create workflow to ensure a consistent set of labels

data/labels.yml
This PR removes the word "CC" from the phrase "CC staff members".
=> Drop the word 'CC'

README.md, data/github.yml
Addresses #37.
Now that we have an [Openverse browser extension](https://github.com/WordPress/openverse-browser-extension), it's time to include it in our workflows and project board automations.
=> Include the browser extension in the list of repos

.github/sync.yml
Since all repos have the same owners, it would be good to synchronise the `CODEOWNERS` file from a central location as well.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Include CODEOWNERS file in repo sync

.github/workflows/pr_label_check.yml, data/labels.yml
Fixes #59 by @zackkrida
This PR adds a label for accessibity. This will ideally be used for issues that point out problems and shortcomings with accessibility of our components and PRs that help to improve them.
This makes the most sense for the frontend and extension repos, which are the primary user-facing codebases.
The proper a11y icon (see image) is not an emoji (yet; unfortunately).
The [♿️ wheel chair symbol](https://emojipedia.org/wheelchair-symbol/) is the next best alternative based on the Emojipedia description.
<details>
```
Version 1.1 …
```
=> Add a label for a11y

.github/GITHUB.md, .github/workflows/pr_label_check.yml
This PR adds the check to enforce priority labels on PRs. This should help in PR review scheduling and planning.
<details>
```
Version 1.1
Suite D4700 …
```
=> Enforce the presence of priority labels on PRs

.github/workflows/pr_ping.yml
This PR extends the Slack workflow to also run when a draft PR is marked ready for review.
GitHub Actions are very hard to test. Reading the code very carefully is the only way. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Send Slack ping when PR is marked ready for review

.github/workflows/pr_project_automation.yml
The PR project is supposed to automatically archive merged and closed PRs weekly. The automation was not working as pointed out by @zackkrida in the last meeting.
This PR fixes that automation. The bug was caused by using the _wrong_ kind of quotes around the arguments.
Let the workflow run on its next scheduled trigger.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Fix issues with the PR project automation

data/labels.yml
Adds a CSS label to our technology labels.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license and I have the right …
```
=> Add CSS technology label

data/labels.yml
Adds new technology labels for `💲 tech: bash` and `⌨️ tech: typescript`.
=> Add new tech labels for Bash and TypeScript

.github/workflows/label_new_pr.yml
This PR fixes errors in applying labels when PRs are opened by contributors. This is because PRs by contributors do not get access to credentials and thus fail to trigger workflows.
<details>
```
Version 1.1
Suite D4700 …
```
=> Label PRs by contributors

.github/ISSUE_TEMPLATE/bug_report.md
As discussed, removes the default priority label for bug reports.
=> Update bug_report.md to remove default priority label

.github/workflows/label_new_pr.yml
The `GITHUB_TOKEN` cannot be used to create repository dispatch events.
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Use PAT for repository dispatch

automations/data/labels.yml
Fixes #154 by @chukkyiii
PR adds tooling group with sentry label for issues taht include sentry. 
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```
=> Adding Sentry Label for issues originating from a Sentry report

automations/data/labels.yml
Adds a new `aspect: design` label for tracking design work, as discussed in #214.
=> Add `aspect: design` label

.github/CODEOWNERS
Updates the codeowners file to the  `openverse-maintainers` team, since we intend to add all contributors to the `openverse-developers` team and they might not be prepared to review all PRs.
=> Update CODEOWNERS to maintainers team

README.md
I added a third point linking the Design handbook in the "Helpful links for new contributors", `README.md` file.
=> Adding a link to make design handbook

.github/CODEOWNERS_FRONTEND, .github/sync.yml
Each repository is going to move to being managed by an individual team, so the value in syncing the CODEOWNERS files, which will be unique per-repo, is significantly reduced.
Alternatively, we could track and sync a unique CODEOWNERS file for each repository here, if folks preferred, so they could be updated all at once in the future instead of requiring a discrete PR be made manually for each repo.
=> Stop syncing CODEOWNERS files

.github/workflows/pr_label_check.yml, automations/python/label_pr.py
Fixes #311 by @AetherUnbound 
We can currently open and merge PRs which go entirely unlabeled. This can cause issues with our release notes, since they're sectioned by label ([see the first 2 lines in this set of release notes as an example](https://github.com/WordPress/openverse-api/releases/tag/v2.5.11)).
We should remove them as acceptable options for the PR label check workflow.
After merging, we can create a new MR, which should fail the check if it has the `🚦 status: awaiting triage` label
<details>
```
Version 1.1
1 Letterman …
```
=> No longer allow"🚦 status: awaiting triage" label on MRs

.github/subscribe_to_label.json, .github/sync.yml, .github/workflows/subscribe_to_label.yml, automations/python/label_pr.py
Fixes #297 by @AetherUnbound
This PR adds a new, synced, GitHub action which will automatically @ `WordPress/openverse` and `WordPress/gutenberg-design` for issues that get tagged with "🖼️ aspect: design".
We can always remove or adjust certain groups (or remove the auto-subscribe altogether) down the line if we don't find this helpful :slightly_smiling_face:
Unfortunately due to the nature of GHA, I'm not sure how to test this without merging it first.
<details>
```
Version 1.1
Suite D4700 …
```
=> Auto-subscribe team & Gutenberg design for design issues

.github/GITHUB.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, .pre-commit-config.yaml.jinja, CONTRIBUTING.md, README.md, automations/README.md, automations/python/README.md, brand/README.md, justfile, load_testing/README.md, load_testing/k6/main.js, load_testing/k6/search.js, load_testing/k6/utils.js, prettier.config.js, prettier.config.js.jinja, rfcs/20220217-visual_regression_testing.md, rfcs/20220218-introduce_ui_state_cookie_to_frontend.md, rfcs/20220221-3d_model_support.md, rfcs/20220223-convert_the_store_from_vuex_to_pinia.md, rfcs/20220307-monitoring_across_the_stack.md, rfcs/20220309-feature_flags.md, rfcs/README.md
Fixes #333 by @dhruvkb
Fixes #287 by @sarayourfriend 
See my rationale for the approach here: https://github.com/WordPress/openverse/issues/333#issuecomment-1347478802
Notable, we want to have automated reflow of wrapped text so that writers can ignore it and write however they want. Having prose broken onto shorter lines allows more easily commenting on specific phrases when reviewing documents and discussions.
This also address the single quote issue with JavaScript linting. Naturally, this will create a massive diff in the frontend repository with the switch to double quotes.
I also fixed an issue with the `_js_install` recipe now that package.json has been moved to the top level of the repository.
Checkout the branch, run `just install && just precommit && just lint` and verify that …
=> Auto-format markdown; switch to double quotes for JS

.pre-commit-config.frontend.yaml.jinja, prettier.config.frontend.js.jinja, prettier.config.js, prettier.config.js.jinja
This PR updates the lint configs and templates. 
- Uses double quotes in `prettier.config.frontend.js.jinja` as per the new JS rule code style.
- Includes `*.yaml` extension with the YAML rules to match certain files that have the alternate extension.
This PR should prevent automated sync PRs like https://github.com/WordPress/openverse-frontend/pull/2054 from failing their own CI lint checks.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone …
```
=> Update lint configs and templates to use double quotes

.github/workflows/pr_label_check.yml
Follow up to https://github.com/WordPress/openverse-infrastructure/pull/326 which required label checks for all merges into main, this was causing issues where a maintainer had to add & remove labels to re-trigger the check so a PR could be merged.
This action was previously set up to only run when the labels on a PR change. Since we've made this a required check, it makes sense to have this run unconditionally on every PR commit so that the check can pass (or fail) appropriately prior to a merge.
We might be able to see on this PR!
errors.
<details>
``` …
```
=> Run label check on every commit and label change

.pre-commit-config.yaml, automations/python/issues_with_prs.py, automations/python/label_pr.py, automations/python/models/label.py, automations/python/models/label_group.py, automations/python/shared/data.py, automations/python/shared/github.py, automations/python/shared/log.py, automations/python/sync_labels.py, dead_links/dead_link_tally.py, justfile, templates/.pre-commit-config.yaml.jinja, templates/README.md
Fixes #247 by @krysal
Adds `pydocstyle` as a pre-commit hook and configures some ignores with reasons for each ignore embedded in the configuration.
I had to make tweaks to existing documentation to get the style rules to pass. If we don't like these changes, then honestly pydocstyle or any other documentation linting too probably isn't that helpful for us as these kinds of style tweaks are most of what they enforce.
I also added a guide for how best to iterate on template contributions as it's quite tedious to try to do it any other way.
Review the changes and confirm they're acceptable to enforce in our Python code across the board. Confirm CI linting passes.
errors. …
=> Add pydocstyle and guide for editing templates

.pre-commit-config.yaml, templates/.pre-commit-config.yaml.jinja
Small follow up to #363, while working on https://github.com/WordPress/openverse-catalog/pull/963 I noticed that some of the linting is done on the `retired` directory. We really don't need to do that (and I doubt the term `retired` is used or will be used in any of our other python repos) so I've added `retired` to the excluded list at the top level.
1. Check out the catalog repo at https://github.com/WordPress/openverse-catalog/pull/963
1. Add `retired` to the `.pre-commit-config.yaml` file as it's shown in this PR
1. Run `just lint` and check that the output doesn't include any references to the `retired` folder
errors.
<details> …
=> Don't run pre-commit on retired files

.github/workflows/lint.yml, .pre-commit-config.yaml, templates/.pre-commit-config.yaml.jinja
`pre-commit` uses Poetry to install and manage hook environments. Poetry refuses to install an older version of `isort` because the `pyproject.toml` file uses a deprecated form of the spec (see https://github.com/PyCQA/isort/pull/2078). This PR updates the `isort` version which fixes the underlying issue. 
The alternative would be to pin the older version of `pre-commit` that uses the older version of Poetry that supports the older version of the spec, but this seems better prepared for the future.
See the PR https://github.com/WordPress/openverse-infrastructure/pull/358 which has 2 commits, one with the [lint check failing](https://github.com/WordPress/openverse-infrastructure/actions/runs/4041398877/jobs/6947965085) (before this change) and one with the [lint check …
=> Update `isort` to fix problems with Poetry

.pre-commit-config.yaml, templates/.pre-commit-config.yaml.jinja
Follow up to discussion in https://github.com/WordPress/openverse-catalog/pull/963 and during the Make WP Slack meeting, this adds two further rules to the list of those we'll be ignoring for pydocstyle. This should be backwards compatible with the changes already made for the API repo.
`just lint` passes successfully.
errors.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Add additional rules to ignore for pydocstyle

.github/sync.yml, README.md, automations/data/github.yml
Fixes #374 by @dhruvkb
As the extension isn't maintained and the repo is being archived, all references to the extension repo are to be removed from the codebase to prevent workflows and automations from failing.
[openverse/README.md](https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/README.md?plain=1#L29)
```diff
- - [Browser extension](https://github.com/wordpress/openverse-browser-extension) 
```
[openverse/automations/data/github.yml](https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/automations/data/github.yml#L7)
```diff
- extension: openverse-browser-extension 
```
[openverse/.github/sync.yml](https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/.github/sync.yml#L11)
```diff
- …
```
=> fix: Remove references to the unmaintained browser extension

.github/workflows/label_new_pr.yml, .github/workflows/label_pr.yml
Fixes #338 by @dhruvkb
If the workflow to label new PR fails at any point this applies a "🚦 status: awaiting triage" label to it rather than leaving it unlabelled.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Addition of "waiting for triage" label in case label_pr.yml fails

templates/.pre-commit-config.frontend.yaml.jinja
This PR updates the dependency versions for linting dependencies to match the current versions and the ones updated in https://github.com/WordPress/openverse-frontend/pull/2121
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> Match frontend linting dependency versions to frontend/pull/2121

automations/python/label_pr.py, docs/projects/README.md
Recent runs of the `label_pr` action were failing, but _only against the infra repo_ with the following exception:
```
Traceback (most recent call last):
File "/home/madison/git-a8c/openverse/automations/python/label_pr.py", line 104, in get_authenticated_html
browser.form["otp"] = pyotp.TOTP(os.getenv("GH_2FA_SECRET")).now()
File "/home/madison/.local/share/virtualenvs/python-d7ZGB4cT/lib/python3.10/site-packages/mechanize/_form_controls.py", line 1963, in __setitem__
control = self.find_control(name)
File "/home/madison/.local/share/virtualenvs/python-d7ZGB4cT/lib/python3.10/site-packages/mechanize/_form_controls.py", line 2355, in find_control
return self._find_control(name, type, kind, id, label, predicate, nr)
File "/home/madison/.local/share/virtualenvs/python-d7ZGB4cT/lib/python3.10 …
```
=> Fix authenticated logins for the label PR action

.github/PULL_REQUEST_TEMPLATE/project_proposal.md
Apparently PR templates don't use yaml frontmatter in the same way issue templates do.
=> Remove front matter from project proposal template

.github/workflows/project_automation.yml, automations/python/issues_with_prs.py, automations/python/shared/github.py
Fixes #276 by @krysal
This PR changes the project automation to make it more adaptive to closed PRs. Due to limitations of the GitHub REST API, the previous implementation was only able to check if an issue _had an associated PR at all_; it was not able to check what state the linked PR was in. The PR information isn't returned in the response either, so there was no way to even match linked PRs with issues using the REST API. This meant that cards with linked, closed PRs were also unconditionally moved. Even if we were to move the stale cards from "In progress" to the "Backlog" column, the next run of the project automation would move them back to "In progress".
Instead, I opted to use the GraphQL API which allows for a bit more configuration. The new query is against PRs (rather than …
=> Fix project automation logic around closed PRs

rfcs/20221124-monorepo.md
Fixes #205 by @zackkrida 
This PR writes the monorepo RFC.
Proof of Concept can be seen at <s>https://github.com/dhruvkb/monopenverse</s> https://github.com/dhruvkb/monoverse.
0. Read the RFC.
1. Give your Cs.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```
=> RFC: Monorepo

automations/python/issues_with_prs.py
This PR addresses two issues we've been seeing with the project automation.
The first is the direct result of #396, wherein the moving back and forth of issues between columns completely pollutes an issue's timeline (for an example, see https://github.com/WordPress/openverse-catalog/issues/935). This was resolved by making an additional call to prevent taking any action on closed PRs where the issue also has an open PR. This will thus leave issues in the "In progress" column rather than move them back to the "Backlog" (only for a subsequent call to move them from the "Backlog" to "In progress").
The second issue is that we've been hitting our API rate limit pretty consistently. I determined that this was because we were calling `get_content()` on each card of the 600+ cards on the project …
=> Don't move issues back & forth in project, reduce API calls for project automation

frontend/src/components/VContentPage.vue, frontend/src/components/VSkipToContentContainer.vue
Fixes #449 by @obulat
This PR adds the "skip to main content" link to the content pages (About, Sources, etc).
It also updates the way `VSkipToContent` works. Instead of focusing on the first tabbable element inside the "main content", it focuses on the "main content" itself. This way, when you click "skip to content", the screenreader reads the main content instead of reading the first link.
Go to `/about`, and press `Tab` on your keyboard. You should see the "Skip to content" button appear at the top. When you click on it, if screen reader is on, you should hear the first heading or the text of the main content.
errors.
<details> …
=> Add "Skip to main content" to content pages

.github/filters.yml, .github/workflows/ci_cd.yml
Fixes #795 by @dhruvkb
Adds a 15 minute timeout to playwright tests, e2e tests, and storybook doc generation. This should be a sensible default timeout that leaves space for successful runs to complete.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add timeouts to visual regression, e2e tests, and storybook generation

.github/workflows/ci_cd.yml
I noticed that we weren't receiving any API deployment messages in Slack, even though we've merged PRs which _should_ have initiated an API deploy. After some investigation, I found that we were requiring changes made to the ingestion server prior to deploying the API:
https://github.com/WordPress/openverse/blob/a2782e8b45300be669c90b4da1abd801caa0263b/.github/workflows/ci_cd.yml#L926
Since these services are distinct, we shouldn't need changes made to the ingestion server in order to deploy the API. This PR removes that requirement.
Merge and hope :slightly_smiling_face:
errors.
<details> …
=> Fix `always()` logic for dependent tasks in CI/CD workflow

.github/dependabot.yml, .github/renovate.json, renovate.json
Minor PR to remove a leftover from the monorepo. This keeps a single `renovate.json` file inside the `.github` folder and includes all the workflows for updates as well. 
<details>
```
Version 1.1
Suite D4700
have …
```
=> Merge renovate bot configuration files

frontend/package.json, justfile
Fixes #857 by @dhruvkb
This PR removes the `prepare` script altogether. Without it we can be more deliberate about the steps that need to be taken after running `pnpm install`.
0. Check out the PR and run the Docker build steps as described in `ci_cd.yml`.
```console
$ just frontend/run i18n
$ cp .npmrc .pnpmfile.cjs pnpm-lock.yaml frontend/
$ docker build --tag ovfront frontend
```
3. Verify that all the locales show up.
```console
$ docker run -it --rm -p 8443:8443 --entrypoint /bin/sh ovfront -c 'cat src/locales/scripts/valid-locales.json'
```
errors.
<details>
```
Developer …
```
=> Remove `prepare` script to prevent i18n overwrites inside Docker

frontend/src/stores/search.ts, frontend/src/utils/search-query-transform.ts
Fixes #781 by @obulat
Fixes OPENVERSE-FRONTEND-Z7
This PR adds a validator function `qToSearchTerm` that takes the `q` parameter from router's query, and returns:
- the first string if `q` is a list of strings
- the string of `q`
- blank string `""` if `q` is null or if the first string is null or blank
Try re-creating the app crash described in the linked issue by going to `https://localhost:8443/search?q=cat&q=`. It should set the search term to the value of the first `q`.
If you swap the two `q`s, `https://localhost:8443/search?q=&q=cat`, you should be redirected to the homepage because that's what is expected when the search term is blank.
errors.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_com …
=> Fix crash when more than one `q` parameter is provided in URL

frontend/src/components/VHeader/VHomeLink.vue, frontend/src/locales/scripts/en.json5, frontend/test/playwright/e2e/header-internal.spec.ts
Related to #448
Updates the text for screen readers from "Home" to "Openverse Home" on the header logo link.
Test Openverse using a screen reader and verify the correct text is read out. Also inspect the html and view the "Openverse home" text.
errors.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Update home link screen reader text

frontend/package.json, frontend/src/utils/sentry-config.ts, pnpm-lock.yaml
Updates the Sentry SDK and updates it to allow errors from openverse.org. Currently the Sentry SDK is way out of date on the frontend and not accepting events from openverse.org. This PR updates the SDK and fixed the allowed domains.
I actually need help from @WordPress/openverse-frontend on the best way to test this.
errors.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Update sentry; fix config

automations/data/labels.yml, automations/python/models/label.py, automations/python/models/label_group.py
Addresses a prerequisite for https://github.com/WordPress/openverse-infrastructure/pull/410 and https://github.com/WordPress/openverse-catalog/pull/1037
This PR adds the stack label to the list of labels synced across all repos. It also changes the sync label script to allow an emoji to be defined once for an entire group.
1. `cd automations/python`
1. `pipenv install`
1. `pipenv sync_labels.py` (you will need to have the GitHub credentials in your environment
I've run this for testing locally (without it actually running the set label operation):
```
::info::[shared.data] Reading file /home/madison/git-a8c/openverse/automations/data/labels.yml
::info::[__main__] Synchronizing 50 standard labels
::info::[__main__] • 🟥 priority: critical
::info::[__main__] • 🟧 priority: high …
```
=> Add stack to label sync, allow emoji to be defined for whole group

.gitignore, documentation/reference/frontend/feature_flags.md, documentation/reference/frontend/index.md, documentation/reference/index.md, frontend/feat/feature-flags.json, frontend/src/components/VCheckbox/VCheckbox.vue, frontend/src/components/VCheckbox/meta/VCheckbox.stories.mdx, frontend/src/locales/scripts/en.json5, frontend/src/pages/preferences.vue, frontend/src/styles/tailwind.css, frontend/tailwind.config.js
Fixes #821 by @dhruvkb
This PR
- adds a switch view to the checkbox based on the WordPress design language
- removes dummy example feature flags
- adds feature flag for analytics
- updates the preferences UI to match mockups from #791
- adds documentation for the feature flag system
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add preferences for analytics

frontend/feat/feature-flags.json, frontend/src/stores/media/index.ts, frontend/src/stores/media/single-result.ts, frontend/src/types/media.ts, frontend/src/utils/content-safety.ts
Fixes #854 by @zackkrida 
This PR adds a feature flag `fake_sensitive` to mark roughly half the results as mature. It uses a random (but deterministic) approach which allows results to be marked mature consistently and across Pinia stores and browsing sessions.
This PR makes no UI changes. It is limited in scope to just adding the feature flag and setting up its behaviour. UI changes are already necessitated by #791 so this PR does not put in effort that's destined to be repeated.
0. Enable the flag 'fake_sensitive' from `/preferences`.
0. Search for somethine.
- You will see the console logs printing `Fake mature <uuid4>` for ~50% of results.
- This list should remain the same no matter how many times you refresh the page.
0. Pick any ID out of …
=> Add feature flag for fake marking results as sensitive

ingestion_server/ingestion_server/es_mapping.py
Add a stemming override for the word "universe" so it isn't matched to "universal" or "university".
=> Add a stemming override for the word "universe"

.github/actions/get-changes/action.yml, .github/filters.yml, .github/workflows/bundle_size.yml
This PR
- re-enables the bundle size workflow that had been disabled due to a wrong `if` condition.
- uses the `get-changes` action to only run when there is a possibility of the bundle size to change.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Simplify and fix bundle size workflow

.github/workflows/ci_cd.yml
Small fix/follow up to #786, this prevents the "Add stack label" action from running on anything that isn't a pull request. See a failed run which occurred on the "push" action here: https://github.com/WordPress/openverse/actions/runs/4369574126/jobs/7643514186
Merge :slightly_smiling_face:
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Only run stack label addition step on pull requests

.github/workflows/ci_cd.yml, .github/workflows/generate_pot.yml
Currently the workflow to update the POT file runs on every push to `main`. This is wasteful. This PR restricts the workflow to run only when the file `en.json5` changes.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Only generate POT file if `en.json5` has changed

.github/workflows/ci_cd.yml
This PR adds the `api` to the build image matrix so that the `test-api` job (which runs when the ingestion server has changed) can find the `api` image it needs to spin up. This `api` image will be identical to the last-built one so it will not be published.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Build `api` when ingestion server changes

.github/CODEOWNERS
This PR adds the main maintainer group as the codeowners for the `.github` folder. This addresses an issue we identified in https://github.com/WordPress/openverse/pull/910 wherein reviewers were not automatically selected.
We may even see with this PR!
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add `.github` to CODEOWNERS

.github/workflows/ci_cd.yml
This is a follow up to #925 which is currently affecting #933, #934, and #935. The ingestion server is also necessary for API tests, so we must unconditionally build it when only the API code is changed.
This PR modifies the logic so that the API and ingestion server images are always built for either API or ingestion server changes, only publish behavior is now affected by which service has been affected.
Based on this file being changed _all_ services will change so we won't be able to test this on this PR, but hopefully once merged we will see it work on any of the above PRs.
errors.
<details> …
=> Always build both api & ingestion server images for either service

api/catalog/configuration/logging.py
`console` has `require_debug_true` in the conditions which requires `settings.DEBUG` to be true. It isn't in production (we don't run DEBUG mode in production, even when looking at debug logs), so we need to also pass those logs to the `console_prod` handler which does not have that requirement.
Set `DEBUG=False` locally and confirm you see the logs when settings configured as described in #934 
errors.
<details>
```
Version …
```
=> Add console_prod handler to query logging to allow in production

.github/workflows/ci_cd.yml
Fixes #928 by @obulat 
This PR removes `load-img` action calls from the documentation jobs. Since the documentation makes no use of Docker, the use of this action is redundant and can cause CI to fail instead.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove Docker image loading from docs steps

api/catalog/api/controllers/search_controller.py, api/catalog/api/serializers/media_serializers.py, api/test/auth_test.py
This PR adds 2 search query parameters to the API to allow us to test boosting the results by their `authority` score. To make sure that no one relies on this test parameter, the query parameter `unstable__authority`.
By default, the boost is the same as the `popularity` boost: 10 000. You can also fine-tune the `authority` boost by adding a float value as `unstable__authority_boost`. This number will be multiplied with the default boost. So, if you want the authority boost to be lower than the `standard_popularity` boost, you can set it to a value lower than 1 (e.g., 0.5)
Run the API and go to [http://localhost:50280/v1/images/?q=cat&unstable__authority=true&unstable__authority_boost=1.0](http://localhost:50280/v1/images/?q=cat&unstable__authority=true&unstable__authority_boost=1.0). …
=> Add ability to boost search results by authority

api/catalog/api/middleware/force_debug_cursor_middleware.py, api/catalog/configuration/logging.py, api/catalog/settings.py
- Updates the `console_prod` log handler to respect `LOG_LEVEL` instead of only logging `WARNINGS`.
- Introduces a middleware which forces the db connection to use a debug cursor when `DJANGO_DB_LOGGING` is True. Without this middleware, Django is only able to log DB queries when debugging is enabled, which is a major security risk in production.
I am _not_ a python dev at all and I have no idea what the best way to get test coverage for this is.
=> Log DB queries in production  

api/catalog/api/utils/drf_renderer.py, api/catalog/settings.py, api/test/unit/utils/drf_renderer_test.py
Fixes #970 by @zackkrida 
The view in question in the issue is the browsable API view. You'll get a 405 method not allowed, but the form below is the culprit here.
The new renderer added in this PR removes this form from all the views to prevent this kind of thing happening in any of our browsable views. This has the benefit of still maintaining the browsable API views which are quite useful to all developing the API or using it for their own purposes.
Run the branch (`just up`) and visit the browsable API views. Test something like http://localhost:50280/v1/images/2982c0bf-9c26-4543-a712-4d50a117ded8/report/ specifically. On `main` you'll see a form underneath the JSON blob reporting the method not allowed error. On this branch, you'll see no form.
a parent feature …
=> Use formless default browsable API renderer

.github/GITHUB.md, .github/workflows/new_issues.yml
Fixes #868 by @obulat
This PR adds steps to the `new_issues`:
1. When the issue is opened, it is added to the new Openverse project with "Backlog" status. Its ID and priority are saved in GITHUB_ENV
2. The matching priority label is added to the issue that was added in the previous step.
The code is heavily based on [Automating projects using actions docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions). 
I ran the queries locally, using my own (old) GitHub Personal Access Token with the `project` permission. I hope that our `ACCESS_TOKEN` works, but I am not sure. The token needs to have the `project` permission to run these queries.
The field and field value IDs are hard-coded because getting them from …
=> Add issues to the new Project and set Priority field value

.github/workflows/ci_cd.yml
Fixes #971 by @sarayourfriend 
cc @zackkrida who was asking about this earlier this week.
I _think_ this is the issue: that it was checking for `needs.test-ing` rather than `test-api`. `test-ing` isn't in the needs array. It's a shame that action lint doesn't catch this error... but that makes me wonder whether I'm missing something (is `needs-ing` still available, somehow?).
Anyway, I'm not sure how to test this other than to merge the PR and see if staging API deploys :grin: 
Verify the fix makes sense.
errors. …
=> Fix needs check on api staging deployment

.isort.cfg
Related to #337 by @AetherUnbound
This makes `ingestion_server` as an explicit known first party for `isort`, so that third party imports will be placed above first party imports.
Rearrange the imports in a file under `ingestion_server` (so that a third party import comes after a first party import), then run `just lint isort`. That should fix the import order :)
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Configure ingestion_server as a known first party for isort

frontend/src/utils/decode-data.ts, frontend/test/unit/specs/utils/decode-data.spec.js
Fixes #958 by @obulat
This PR adds a regex to match the strings like "u00e9" (without the backslashes) to the decodeData method we use to clean up the titles and tags on the frontend.
1. Open the pottery image from the homepage: localhost:8443/image/802d76cd-84cf-45bc-81ac-610331dab420
2. Look at the tags. There should be no unescaped unicode strings. There will be some duplicate tags, though, because of this.
errors.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
=> Add decoding of the strings that don't have backslashes

automations/python/label_pr.py, automations/python/shared/github.py
This PR fixes an issue that came up after #786, wherein a PR lacking all labels would have the linked issue labels added _and then removed_, replaced with the "awaiting triage" label. This PR changes the behavior so that all available labels are added always, _in addition to_ the "awaiting triage" label if not all label categories are met.
I ran this successfully against a catalog PR which had the previous, incorrect behavior, and verified that it correctly added (instead of replaced) the "awaiting triage" label: https://github.com/WordPress/openverse-catalog/pull/1048#event-8761162349
errors.
<details> …
=> Add awaiting triage label onto existing labels

.github/release-drafter-api.yml
Necessary for completing the testing in https://github.com/WordPress/openverse/pull/987
Adds the provisional api release-drafter configuration to `main` so that the release-drafter action can use it in the linked PR.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add release-drafter API configuration to enable testing in #987

api/catalog/api/models/media.py
Related to #704 by @obulat
This is the first step of the three-step process we need to follow to remove the `tags_list` from the database for zero-downtime deployments. This PR adds a custom Manager to the AbstractMedia model that prevents querysets from trying to access `tags_list` field as part of the model. 
After this PR is deployed, we will need to drop the `tags_list` column from the database.
After the column is dropped, we can deploy the PR #956 that removes the `tags_list` field from the models and adds corresponding migrations. Note: the `CustomManager` needs to be removed from #956, otherwise we get an error when it is trying to defer the `tags_list` field that doesn't exist.
Run `just up` and search for something (http://localhost:50280/v1/images/?q=cat). In the logs (run …
=> Defer the `tags_list` for media models

.github/workflows/ci_cd.yml, ingestion_server/.gitignore, ingestion_server/ingestion_server/cleanup.py, ingestion_server/test/integration_test.py
Fixes #861 by @krysal
Fixes #654 by @obulat
This PR adds more logging for the data refresh, but its main goal is to be a proof-of-concept of saving the data during weekly data refresh as a preparation step for data normalization.
Data refresh image cleanup steps:
- Add http or https protocol to URLs that don't have a scheme in "url", "creator_url", "foreign_landing_url" fields
- Clean up tags:
- tags that contain anything from the TAG_CONTAINS_DENYLIST set
- AI-generated tags ("provider": "clarifai") with confidence level below TAG_MIN_CONFIDENCE = 0.90
~~This PR also adds a Wikimedia title cleanup step that removes File: prefix and file extension suffix from the image title. This step was added because in the Openverse Inserter PR it was specifically pointed out that those titles are bad …
=> Save cleaned up data during the cleanup step

.github/workflows/ci_cd.yml
In GitHub, required checks which are part of a matrix are not expanded if skipped by an `if` condition. So making them required can block PRs.
The workaround for having them required yet skipping them when no changes is to create a fake job with the same `name` and pass it.
This PR
- creates fakes for the `django-checks` and `playwright` jobs
- uses the hardcoded repo name instead of an env var to prevent failures when building docs
errors.
<details>
```
Version 1.1 …
```
=> Fix issues in the workflow simplifications of #1054

api/catalog/api/admin/__init__.py, api/catalog/api/controllers/search_controller.py
Revert #935 by @sarayourfriend
Since we identified the queries are not coming from internal admin views we can (and should) restore these. I also remove a dangling ES log which makes the production logs too verbose. Let me know if you prefer to keep this behind the `VERBOSE_ES_RESPONSE` flag.
1. Run `just api/up`
2. Check views at http://localhost:50280/admin/ (pass & user: `deploy`)
- http://localhost:50280/admin/api/image/
- http://localhost:50280/admin/api/imagereport/
- and the same for Audio views
<details> …
=> Restore Django Admin views

automations/data/labels.yml, automations/python/label_pr.py, automations/python/shared/data.py
Fixes #884  by @AetherUnbound 
This PR implements both changes mentioned in the issue. 
1) Instead of using a hardcoded list of labels explicitly defined in labels_pr.py, instead now the labels which have set is_required to True are parsed from the labels.yml data file. 
2) The GET_ALL_CATEGORY_LABELS list is replaced and is also dynamically parsed from labels.yml, to do this a new apply_all_available boolean was added for each group. 
Since labels.yml was encoded in utf-8, an optional argument to the load_data function was added to allow specifying the file encoding.
Run the labels_pr.py file, verify that the parsed list equates the original explicitly defined list.
errors. …
=> Use label.yml to determine required labels

.github/workflows/ci_cd.yml
Adds to #1034 by @sarayourfriend 
The deployment was failing after #1034 was merged because GitHub CLI needs `GITHUB_TOKEN` to run inside GitHub Actions. See error log: https://github.com/WordPress/openverse/actions/runs/4571548989/jobs/8070585871
This PR does what the error message says, except using GITHUB_TOKEN instead of GH_TOKEN. They're both [equally valid](https://cli.github.com/manual/gh_help_environment), although `GITHUB_TOKEN` is the name used in the [official docs](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) so I went with that.
errors.
<details> …
=> Add `GITHUB_TOKEN` to GitHub CLI step

.github/renovate.json
This PR changes the Renovate config so that it applies the docker-specific labels appropriately. I noticed in https://github.com/WordPress/openverse/pull/1109 that instead of adding the 4 base labels _and_ the docker label, Renovate instead only added the Docker label. [Based on their documentation](https://docs.renovatebot.com/configuration-options/#labels), it seems like using the `packageRules` directive is the correct way to apply multiple sets of labels rather than using `docker.labels`.
Additionally, the config referenced a repo which is now archived. It's a wonder it was working at all!
I'm not sure how to test this...open to suggestions :slightly_smiling_face:
errors. …
=> Modify Renovate to apply appropriate labels to docker PRs

.pre-commit-config.yaml, automations/python/issues_with_prs.py, documentation/_ext/link_issues.py, templates/.pre-commit-config.yaml.jinja
Similar to https://github.com/WordPress/openverse-infrastructure/pull/456
Fix based on this warning I observed locally when running just lint:
```
[WARNING] The 'rev' field of repo 'https://github.com/rhysd/actionlint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
```
I ran pre-commit autoupdate (and applied the changes to the jinja template) and this PR was the result of the changes.
`just lint`
errors. …
=> Update pre-commit deps, pin actionlint

.github/workflows/new_issues.yml
Related to #818 by @obulat
This PR adds an external TypeScript action that adds an issue to the [Openverse project](https://github.com/orgs/WordPress/projects/75) and sets the Project's Priority custom field value based on the issue's label. The action is based on the `add-to-project` action.
You can see a successful run here: https://github.com/bulatt3/mobile_test/actions/runs/4620463360 (Please ignore the more than 40 unsuccessful runs 😆 )
I think it would be best to move the action to a /WordPress/ repository, but it would be nice to test it before the move.
Merge and see
errors.
<details> …
=> Use `add-to-project-and-label` action

.github/workflows/renovate.yml
Fixes our renovate workflow, which is currently failing: https://github.com/WordPress/openverse/actions/workflows/renovate.yml
GitHub Actions does not appear to play well with an unpinned or semi-pinned version:
```
Unable to resolve action `renovatebot/github-action@v34`, unable to find version `v34`
```
I've pinned it to [v36.0.2](https://github.com/renovatebot/github-action/releases/tag/v36.0.2) in the hopes that a full version pin will be sufficient.
~~I will try to run the renovate workflow from this branch and update the description with that info.~~ Turns out I can't do this because the renovate action isn't set up for workflow dispatch. I'll add that to this PR but I don't think it will affect the action retroactively.
errors. …
=> Pin renovate action to specific version

frontend/package.json, frontend/src/components/VAudioTrack/VWaveform.vue, frontend/tailwind.config.js, pnpm-lock.yaml
We used a separate library, `tailwindcss-labeled-groups`, to be able to use a labeled or named group in tailwind. Now that this functionality is available in Tailwind as a built-in, we can remove the use of this library.
The app should run as it does, normally. The library was used to show the waveform and the played section of it on focus. Check that the waveform displays correctly on focus.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone …
```
=> Use the built-in Tailwind named groups

documentation/projects/proposals/search_relevancy_sandbox/20230331-project_proposal_search_relevancy_sandbox.md, documentation/projects/proposals/search_relevancy_sandbox/index.md, rfcs/search_relevancy_sandbox/20230331-project_proposal_search_relevancy_sandbox.md
2023-04-14
@dhruvkb - I chose you because you've worked on the ingestion server and Elasticsearch in the past and may be familiar (albeit distantly!) with some of these pieces. I know that you're involved in a number of other projects at this moment, so please feel free to opt out if you're currently at capacity.
@sarayourfriend - I chose you because you're familiar with many of the systems at play and have been exploring modifications to Elasticsearch, so your insight into the "user-facing" side of this project would be invaluable.
This PR is the kick-off for the search relevancy sandbox project: https://github.com/WordPress/openverse/issues/392
=> Project Proposal: Search Relevancy Sandbox

api/catalog/api/docs/README.md
Fixes #1235 by @sarayourfriend 
Fix typo in github link of the /api/catalog/api/docs README. Now the link redirects to the correct URL (while previous redirects 
to another domain).
errors.
=> Fix typo in github link

.github/workflows/release-app.yml
Fixes #1189 by @obulat, also fixes an issue preventing the linting from happening on changelog PRs like #1186
This PR modifies the `release-app` workflow in two ways:
1. It stages the generated changelog in git to _specifically ensure_ that `just lint` runs on it. For whatever reason, leaving it as an unstaged file prevents `just lint` from running on it, even though I cannot reproduce that behavior locally (i.e. unstaged & untracked files _are_ linted locally).
2. It changes the way the body of the changelog is inserted into a file so that backticks (`) don't get interpolated by bash. I've confirmed that using single quotes should prevent that locally, but I can't test this fully yet until we have a release that includes backticks in the file.
**Successful release run**: …
=> Ensure the generated changelog gets linted, fix backticks in log

.github/workflows/release-app.yml
This PR updates the release-app workflow to use the `secrets.ACCESS_TOKEN` key as the GITHUB_TOKEN, which should have sufficient permissions to use the github cli to run the deployment workflows.
To test, we'll just see if it works!
=> Update permissions of deployment steps in the Release workflow

api/test/unit/management/commands/generatewaveforms_test.py
This PR fixes the error raised in #1221, changing how a `psycopg2` error is referenced, thus unblocking our upgrade to Django v4.2.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```
=> Update how `psycopg2` errors are referenced

.github/workflows/release-app.yml, automations/python/workflows/write_changelog.py
I am _not_ a shell script expert but am curious if this might fix issues I'm still seeing with drafting certain release notes. See the [recent run here](https://github.com/WordPress/openverse/actions/runs/4735022950/jobs/8404730500) which errored due to a "syntax error near unexpected token `(".
=> Try to prevent additional issues with writing the changelogs to file

frontend/src/components/VAudioTrack/layouts/VFullLayout.vue, frontend/src/pages/image/_id/index.vue, frontend/src/types/analytics.ts, frontend/test/unit/specs/components/AudioTrack/v-full-layout.spec.js, frontend/test/unit/specs/components/ImageDetails/v-image-details-page.spec.js, frontend/test/unit/test-utils/i18n.js
Fixes #1080 by @dhruvkb
This PR adds the `GET_MEDIA` analytics event that is fired when the user clicks the "Get this image" or "Get this audio" CTA button on the single result page.
Set up the analytics events using `just frontend/up` and `just frontend/init`.
Run the app using `just frontend/dev`.
Click on the "Get this image" or "Get this audio"
Check that the event is shown in Plausible: http://0.0.0.0:50288/localhost?goal=GET_MEDIA
errors.
<details>
```
Version 1.1 …
```
=> Analytics event: GET_MEDIA

catalog/Dockerfile, docker-compose.yml
Fixes #1820 by @AetherUnbound
This PR fixes the issue we were seeing with the `tldextract` cache. It does so by creating and owning the `/home/airflow/.cache` directory at image creation time. Previously we were specifically creating `/home/airflow/.ipython` and `/home/airflow/.cache/pytest`; fixing the TLD issue would have required that we add directory creation _and_ a new volume mount for `/home/airflow/.cache/python-tldextract`. That seemed way unnecessary, so I decided to throw everything into `/home/airflow/.cache` (including the `ipython` folder which required changing an environment variable to have it be a subfolder of `~/.cache`).
Before any steps, check out `main` and run `just down -v` to ensure the old volumes are removed. Then check this branch out and run `just build`.
1. …
=> Consolidate all transient dev container dirs for the catalog

.pre-commit-config.yaml
Fixes #1841  by @sarayourfriend 
Removed the template warning comment at the top of .pre-commit-config.yaml as its not longer a template.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Removed comment from pre-commit-config.yaml

.github/workflows/ci_cd.yml, .github/workflows/release-app.yml
Fixes https://github.com/WordPress/openverse-infrastructure/issues/462 by @sarayourfriend 
I'll open a follow-up PR to remove the deployment workflows from this repository.
Dispatches the deployment workflows from the infrastructure repository using repository dispatch.
@dhruvkb You suggested we should use dispatch and wait, but I want to make sure that doesn't cause issues. Specifically it will block CI/CD from running on `main` while the staging deployments are awaited due to the concurrency setting. The release app workflow doesn't have that issue because the concurrency key includes the app name input. Staging deployments are only ~10 minutes or so but I wonder if we need CI on `main` to wait for them or if we can just rely on the fact that the upstream workflow will correctly handle …
=> Dispatch deployment workflows from infrastructure repository

frontend/src/stores/search.ts, frontend/test/unit/setup-after-env.js, frontend/test/unit/specs/stores/search-store.spec.js
Fixes #1870 by @obulat
This PR computes the search path's query parameters if the search type is passed. Otherwise, it uses the query parameters for the currently selected search type.
You can see in the video that the query parameters change based on the search type:
Check the URLs of the search type links in the content switcher. The CI should also pass.
<details>
```
Version 1.1
Suite D4700 …
```
=> Compute search path query parameters for the type passed

frontend/src/components/VContentReport/VContentReportForm.vue, frontend/src/components/VContentReport/VDmcaNotice.vue, frontend/src/types/analytics.ts, frontend/test/unit/specs/components/v-content-report-form.spec.js
Fixes #1082 by @dhruvkb 
This PR adds `REPORT_MEDIA` analytics event.
The DMCA report uses an external form, and there is no way of getting the actual "report submitted" event programmatically from the app (we can, of course, create some automation for the Google form submission, but that is outside of scope for this PR).  I decided to send the event when the user clicks on the "Open form" button for the DMCA report.
The RFC did not contain the `reason` property for the event even though it was mentioned in the docstrings. Do we want to update the RFC, @dhruvkb, or is implementing it here enough?
Set up the analytics by running `just frontend/init`.
Run the app using `just frontend/run dev`.
If you click on "Report content" on the single result page, you should see the event in Plausible: …
=> Analytics event: REPORT_MEDIA

api/catalog/api/models/media.py, api/catalog/api/views/audio_views.py, api/catalog/api/views/image_views.py, api/catalog/api/views/media_views.py
Fixes #1037 by @obulat 
Pass the media identifier directly instead of using the method serializer. This update saves two db statements per report. One query and one update were both redundant.
1. (optional) On main branch run `just api/recreate`
2. Set `DJANGO_DB_LOGGING=True` on your .env file
3.  Restart the service to apply the change and see the logs
```
just down && just api/up && just logs web
```
4. Report on any image, e.g.:
```
curl --request POST \
--url http://localhost:50280/v1/images/<uuid>/report/ \
--header 'Content-Type: application/json' \
--data '{
"reason": "mature",
"description": "Image contains sensitive content"
}'
```
5. Notice there are similar SELECT queries and an UPDATE statement right after the INSERT for the new report
```
openverse-web-1  | [2023-04-27 …
```
=> Simplify report views

catalog/dags/common/popularity/sql.py
The postgres statement timeout for the `create_popularity_constants_view` task in the `recreate_<media>_popularity_calculation` DAGs was not being pulled correctly from the task timeout. As a consequence, when the task's timeout was extended, the actual SQL was not and it still timed out at 6 hours.
Pull this branch, and locally trigger the `recreate_image_popularity_calculation` DAG. Open up the logs for the `create_popularity_constants_view` and you should see a log like this showing the correct timeout:
```
2023-04-28, 00:13:37 UTC] {sql.py:375} INFO - Running statement: SET statement_timeout TO '28800.0s'; 
```
<details>
``` …
```
=> Respect the task timeout in recreate popularity constants task

documentation/changelogs/api/2023.04.12.23.29.59.md
I think this file may have been lost in the monorepo migration, as [this PR](https://github.com/WordPress/openverse/pull/1185) was merged into `main_old` instead of `main`.
=> Reintroduce API changelog 2023.04.12.23.29.59.md

justfile
Related to #1910 by @sarayourfriend
This PR fixes the order of operations in the `attach` recipe to prevent confusion.
Earlier the `attach` recipe would grep in the list of running containers based on in the given service name. However when querying the full tabular output, the query name can match in the image column as well.
By running `awk` first, we reduce the output to its first column i.e. the names of the services. Then running `grep` only matches the right service.
Run `just attach ingestion_server` before and after this change.
<details>
```
Version 1.1 …
```
=> Run `awk` before `grep` in the `attach` recipe

frontend/package.json, pnpm-lock.yaml
Fixes #1930 by @sarayourfriend 
This PR removes `@types/lodash.sortBy`. 
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Remove @types/lodash.sortBy from project

catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py, catalog/tests/dags/maintenance/test_pr_review_reminders.py, catalog/tests/factories/github/__init__.py, catalog/tests/factories/github/pull.json
Fixes #1863 by @sarayourfriend 
Fall back to `main` branch protection for PRs that target branches without their own protection rules.
Check out the unit test and confirm that it sufficiently covers the new case.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fall back to `main` branch protection rules for PRs targeting branches without protection rules

frontend/test/playwright/utils/breakpoints.ts, frontend/test/playwright/visual-regression/pages/pages-single-result.spec.ts
Related to #1959 by @obulat
In https://github.com/WordPress/openverse/pull/1132, I've added `maxDiffPixelRatio` screenshot parameter set to 0.02 to fix the flakiness of the `pages-single-result` test. However, I passed it incorrectly, so it wasn't actually used. This PR passes it using the last parameter of `expectSnapshot` function.
I've also added this change to all of the failing PRs from #1959 description, and they all pass now.
This does not fully fix the root cause of the VR failure, however, I think test is still useful even if the license icons section is off. I would welcome any solution for the root cause, too.
@sarayourfriend, considering that this seems to fix all of the `pages-single-result` flakiness, do you think we should still `skip` the failing test, or would merging …
=> Correctly pass `maxDiffPixelRatio` to add tolerance for pages-single-result VR test

frontend/src/components/VButton.vue, frontend/src/components/VFilters/VSearchGridFilter.vue, frontend/src/components/VHeader/VSearchBar/VSearchButton.vue, frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue, frontend/src/components/VSkipToContentContainer.vue, frontend/src/types/button.ts, frontend/test/unit/specs/components/v-button.spec.js, frontend/test/unit/specs/components/v-modal.spec.js, frontend/test/unit/specs/components/v-popover.spec.js
Related to #1187 by @obulat
This PR removes the `primary` button variant that was replaced with `filled-pink`. This was also the default for the button variant prop which I remove in this PR. In general, there are not many pink buttons in the app, and they should probably not be default. And I think it's better to be explicit about the variant to use for the button (by providing the required `variant` prop) than to fall back on a default.
Another change in this PR was the removal of the VFiltersGrid footer which was not actually used because it was set to `hidden` on screens above `md`, but was hidden in JS when the screen was below `md` (after the move to the VContentSwitcherModal for the filters on mobile).
errors. …
=> Remove primary button variant and make variant required

frontend/src/components/VBackToSearchResultsLink.vue, frontend/src/components/VLink.vue, frontend/src/components/meta/VBackToSearchResultsLink.stories.mdx, frontend/src/pages/audio/_id/index.vue, frontend/src/pages/image/_id/index.vue, frontend/src/types/analytics.ts, frontend/test/playwright/e2e/attribution.spec.ts, frontend/test/playwright/utils/navigation.ts, frontend/test/unit/setup.js, frontend/test/unit/specs/components/v-back-to-search-results-link.spec.js
Fixes #1087 by @dhruvkb 
* Adds `BACK_TO_SEARCH` event to the Events type.
* Fires the event from `VBackToSearchResultsLink.vue` using the `useAnalytics` composable.
=> Analytics event: BACK_TO_SEARCH

api/catalog/api/utils/photon.py, api/test/unit/utils/photon_test.py
Fixes #676 by @sarayourfriend
This PR extracts the params building from the `photon.get` method to reduce it a bit, and also calls `raise_for_status` from the response, as suggested in the issue, to make sure we raise the correct custom exception from unsuccessful HTTP response codes.
The `requests.HTTPError` class inherits from `requests.RequestException`[^1] so there is no need to add it explicitly to the `except` block.
[^1]: https://docs.python-requests.org/en/latest/user/quickstart/#errors-and-exceptions
1. To test this manually, try replacing one DB entry's URL with the sample image URL provided in the issue:
```
https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_the_Turkic_Council.svg
```
2. Make sure that image doesn't have a thumbnail URL; in that case, make it null.
3. …
=> Raise `UpstreamThumbnailException` for unsuccessful requests

documentation/projects/proposals/search_relevancy_sandbox/20230406-implementation_plan_update_staging_database.md
2023-05-03
This is an implementation plan for the first portion of #1107.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/reference/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
The deadline for review for this round is **May 3rd**
=> Implementation Plan: Update staging database

.github/workflows/pr_label_check.yml
The stack label for documentation had an excess space. This causes label check to fail for PRs that target the docs stack.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Fix stack label for documentation

api/justfile, catalog/justfile, justfile
This PR adjust the recipe for `catalog/pgcli` to reduce the number of overrides necessary to define when switching between the Airflow and upstream databases. Additionally, I've reordered the parameters (since with `just` you have to override _all_ parameters in order if you want to change one) so that the fewest need to be changed. Our username and passwords are the same for both databases so I just combined the field.
Lastly, the current config actually didn't work because it was using the airflow creds to connect to the upstream database (which it didn't have access to). I can only speak from personal experience, but almost every time I use the `pgcli` command for the catalog it's to access the upstream database, so I changed the default to be that.
Update: Based on feedback below, …
=> Simplify and reorder parameters to `catalog/pgcli` recipe

catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, catalog/dags/providers/provider_api_scripts/museum_victoria.py, catalog/dags/providers/provider_api_scripts/nappy.py, catalog/dags/providers/provider_api_scripts/nypl.py, catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, catalog/tests/dags/providers/provider_api_scripts/test_metropolitan_museum.py, catalog/tests/dags/providers/provider_api_scripts/test_museum_victoria.py, catalog/tests/dags/providers/provider_api_scripts/test_nappy.py, catalog/tests/dags/providers/provider_api_scripts/test_nypl.py, catalog/tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #1883 by @obulat
This PR replaces `is None` checks for required values with `if <value>` checks because falsy values such as empty string or empty list should also short-circuit the provider API scripts.
All the CI tests should pass.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add checks for required parameters to Provider scripts (K-R)

.devcontainer/devcontainer.json, .devcontainer/post_create.sh, .github/CODEOWNERS, .github/filters.yml, .gitignore, .pre-commit-config.yaml
Fixes #1022 by @dhruvkb 
This PR sets up a dev container that can be used locally (which is awesome) or as a GitHub codespace (not as awesome but still usable).
This container contains everything you need to be immediately productive in two stacks (for now, others maybe later), the documentation and the frontend.
- Navigate to `WordPress/openverse`.
- Click on the "<> Code" button.
- Switch to the Codespaces tab.
- Click on the "..." dropdown button.
- Choose "New with options".
- Change branch to this one `dev_container`. This should automatically apply the "Openverse" dev container configuration.
- Customise any other options to your liking.
- Create the codespace.
The codespace can take quite some time to build and initialise. Grab a coffee or snack in the meantime. Or go for a walk. …
=> Add a dev container supporting docs and frontend

.github/workflows/ci_cd.yml, .github/workflows/pr_label_check.yml, automations/python/shared/actions.py, automations/python/shared/labels.py, automations/python/sync_labels.py, automations/python/workflows/generate_report.py, automations/python/workflows/get_label_groups.py, automations/python/workflows/set_matrix_images.py
Fixes #1195 by @AetherUnbound
This PR is primarily intended to modify the `pr_label_check.yml` GitHub Action workflow so that it reads from the `labels.yml` definition rather then requiring the label groups be explicitly redefined. In order to do this, I factored out some shared functions which read in the labels and convert them to Python objects. I also factored out code in several of our workflow python scripts which would print data to both `stdout` and the `GITHUB_OUTPUTS` destinations. I had to add the `PYTHONPATH` environment variable to the places where we call python scripts in order to have those shared modules load properly.
The effect of this is now any labels we add to the required categories in `labels.yml` will automatically be added to the `pr_label_check` workflow!
The …
=> Determine labels for checks using labels.yml, factor out common workflow utils

catalog/dags/providers/provider_dag_factory.py, catalog/env.template, catalog/tests/dags/providers/test_provider_dag_factory.py, catalog/tests/utilities/dag_doc_gen/test_dag_doc_generation.py, catalog/utilities/dag_doc_gen/dag_doc_generation.py
Fixes #1284 by @stacimc 
Adds an Airflow variable called `CATCHUP_ENABLED` which can be used to override the default catchup settings for provider DAGs.
In production, `catchup` is enabled for all dated DAGs to allow for backfilling -- but this can be very annoying in local environments, because enabling a dated DAG will automatically kick off a very long backfill which you might not want.
Using an Airflow variable allows devs to easily toggle this on and off in local testing, and even allows us to do so in production should the need ever arise. If you want to persist the setting across `recreate`s of the environment, you can set `AIRFLOW_VAR_CATCHUP_ENABLED=false` in your `.env`. 
* Make no changes to the Variables to begin with
* Select a few dated DAGs (eg metropolitan, flickr) and …
=> Add Airflow variable for turning off provider DAG catchup

frontend/src/stores/search.ts, frontend/src/utils/search-query-transform.ts, frontend/test/unit/specs/stores/search-store.spec.js
Fixes #1046 by @obulat 
Fixes #453 by @AetherUnbound 
Vue router supports having separate values for a single parameter in the URL: `q=cat&q=dog`. This is parsed to `context.query` as `{ q: ["cat", "dog"] }`. Our code, however, expects the values for parameters to be strings, not arrays. This causes a 500 error in Nuxt for such URLs.
This PR pre-processes the `query` received from Nuxt context to leave only the first parameter if an array is given. We can safely discard the other values because normally we do not set such parameters using the UI. If we need to pass several values, we use a comma-separated value: `{ license: "by,sa" }` instead of an array. 
Run the app and go to `localhost:8443/search/?q=cat&q=dog`. You should receive the results for `cat`, and `dog` should be discarded as …
=> Handle more than one value for a url query parameter

documentation/_ext/link_usernames.py, documentation/conf.py, documentation/meta/documentation/extensions.md, documentation/meta/documentation/index.md, documentation/projects/proposals/3d_model_support/20220221-project_proposal.md, documentation/projects/proposals/analytics/20221006-implementation_plan_frontend.md, documentation/projects/proposals/analytics/20230307-backend_service.md, documentation/projects/proposals/core_user_interface_improvement/20230314-project_proposal_core_ui_improvement.md, documentation/projects/proposals/document_all_media_properties/20230307-project_proposal.md, documentation/projects/proposals/feature_flags/20220309-project_proposal.md, documentation/projects/proposals/frontend_ui_state_cookie/20220218-project_proposal.md, documentation/projects/proposals/monitoring/20220307-project_proposal.md, documentation/projects/proposals/monorepo/20221124-project_proposal.md, documentation/projects/proposals/popularity_optimizations/20230406-project_proposal_popularity_optimizations.md, documentation/projects/proposals/search_relevancy_sandbox/20230331-project_proposal_search_relevancy_sandbox.md, documentation/projects/proposals/search_relevancy_sandbox/20230406-implementation_plan_update_staging_database.md, documentation/projects/proposals/trust_and_safety/content_report_moderation/20230411-project_proposal_content_report_moderation.md, documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230309-implementation_plan_sensitive_terms_list.md, documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.md, documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230330-implementation_plan_filtering_and_designating_results_with_sensitive_textual_content.md, documentation/projects/proposals/visual_regression_testing/20220217-implementation_plan.md, documentation/projects/proposals/vuex_to_pina_conversion/20220223-project_proposal.md, documentation/projects/templates/implementation-plan.md, documentation/projects/templates/project-proposal.md
This PR makes three primary changes:
- Adds a field for the author in the project proposal and implementation plan templates
- Backfills author information for all existing project proposals that are present in `main`
- Adds a _very simple and naive_ extension to Sphinx which converts specific instances of `@<username>` to links which reference a user's GitHub profile
The upshot of this is that our documentation site now has reviewers **and** the original author, and all of the `@` references are linked to the appropriate GitHub user! This helps provide extra context for folks who may be looking at the documents but not the inciting PRs which created said documents.
**Screenshot**
Check the preview and see how the new project documents look! Also check some other pages to see that there …
=> Add project authors, auto-link GitHub usernames

documentation/justfile
~~This PR adds a `recreate` recipe for the documentation which can be used to easily clean & rebuild the documentation. This is useful for testing whether changes to the documentation would raise warnings on the CI, since only running `just documentation/build -W` doesn't always expose those errors.~~
~~I also needed to call `just build -W` within the recipe explicitly because I don't think it's possible to add arguments to a recipe's dependencies.~~
Per @dhruvkb's comment below, this has been change to instead just add `clean` as a dependency for `build` (similar to the `live` recipe).
Run `just documentation/build` should run `just documentation/clean` first.
<details> …
=> Always run `clean` before `build` for the documentation

api/conf/settings/base.py, api/conf/settings/logging.py, api/conf/settings/oauth2.py, api/conf/settings/openverse.py, api/conf/settings/rest_framework.py, api/conf/settings/s3.py, api/conf/settings/security.py, api/conf/settings/spectacular.py
This PR re-adds the accidentally removed CORS middleware. The absence of this middleware prevents cross-origin requests which consequently prevents using the local API as the server for the frontend.
This was reported by @AetherUnbound.
This PR
- adds `corsheaders.middleware.CorsMiddleware` to `MIDDLEWARE`
- prevents duplication of `INSTALLED_APPS` and middleware when inheriting between settings files
0. Check out this PR and run the dev server: `just api/up`
1. Check that the CORS headers are applied.
```
$ curl -v -H "Origin: http://localhost:50280/" "http://localhost:50280/"
```
<details>
``` …
```
=> Re-add accidentally removed CORS middleware

catalog/dags/common/github.py
This fixes an issue we found after merging #2027 - an undrafted PR was pinged for review only a day after being ready for review, but the PR message said it was 12 days since the PR was ready (see #1891). After some investigation, we found that this is because the GitHub API defaults to 30 events per page in the events endpoint: https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events
This PR adds some very simple pagination to the `get_issue_events` function to enable querying all of the events for a PR prior to determining whether it should be pinged.
Follow the testing instructions outlined in #2027, but note that #1891 _should not_ be included in the list of PRs to ping.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Proj …
=> Paginate GitHub events query for PR reminders

.github/sync.yml
This fixes an issue that came about by #2046 wherein some of the python automation scripts are now necessary on the infrastructure repo in order for those checks to run (see the discussion in https://github.com/WordPress/openverse-infrastructure/pull/503).
This PR adds the `automations/python/` and `automations/data/` folders as sync targets for the infrastructure repo so the actions which require those dependencies can be run there as well. This is significantly easier and less to manage than trying to dispatch the checks from the infra repo to run on this repo.
~~We'll see with https://github.com/WordPress/openverse-infrastructure/pull/503 once these files are synced!~~
I was able to kick off the action here: https://github.com/WordPress/openverse/actions/runs/4952494677/jobs/8858874012 …
=> Add the data & python automation folders as sync for the infra repo

.github/ISSUE_TEMPLATE/airflow_alert.md, .github/ISSUE_TEMPLATE/image_provider_api_integration_request.yml, .github/ISSUE_TEMPLATE/new_source_suggestion.yml, .github/ISSUE_TEMPLATE/project_thread.md, automations/python/print_labels.py, automations/python/shared/labels.py, automations/python/sync_labels.py
This issue was originally intended to only update the issue template labels, but in writing a quick utility to actually print out the labels defined in `labels.yml`, I found that there were some serious issues with the logic changes I made in #2046, namely:
- The logic to unspool the list of list of labels wasn't working, and was still producing a list of lists
- The sync label script wasn't actually pulling existing labels from repos
Example failing workflow: https://github.com/WordPress/openverse/actions/runs/4953650953/jobs/8861350311
This PR makes the following changes to label-related aspects:
- Adds a simple script for printing out the labels (very useful for me since typing emojis is hard on linux)
- Correctly collapses the labels into a single list
- Correctly queries the repos …
=> Fix issues with label automations, update issue templates

justfile, utilities/ps.py
Fixes #1899 by @sarayourfriend
This PR makes two changes to the `just ps` recipe:
1. It changes the recipe itself so that it never reports a failing exit code, meaning it doesn't fail any subsequent jobs
2. It adds some additional error handling to the `ps.py` script so that errors are more clearly reported. 
Here's an example of a failing run:
```
$ j catalog/up "s3 upstream_db"
env COMPOSE_PROFILES="catalog" just ../up s3 upstream_db
env COMPOSE_PROFILES="catalog" docker-compose -f docker-compose.yml -f docker-compose.overrides.yml up -d s3 upstream_db
[+] Running 3/3
⠿ Network openverse_default          Created                                                                                                                                                                  0.1s
⠿ Container …
```
=> Improve error handling and pipe flow for `just ps`

.github/workflows/ci_cd.yml
Companion piece to https://github.com/WordPress/openverse-infrastructure/pull/506
This PR adds a `run_name` to the set of parameters sent for staging deployments. The run name is based on the git commit message of the head commit from the branch that is being deployed. Here's an example of what that should look like:
I'm not sure I can test this even if I run a CI/CD build from this branch, since it won't trigger any deployments. So I think we might just need to merge and see.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add a run name to staging deployment workflows

api/api/utils/photon.py, api/api/views/audio_views.py, api/api/views/image_views.py, api/api/views/media_views.py, api/conf/settings/thumbnails.py, api/test/unit/utils/test_photon.py, api/test/unit/views/test_image_views.py
Fixes #2067 by @krysal
To prevent known errors from Photon due to unsupported file types, this PR adds the following check before making the call to Photon:
1. Get the thumbnail extension from the URL. We can't assume it'd be the same of the main image (in the case of `images/`), so try to guess it first from the URL. I believe it is worth trying this route, since this is where most of the cases will fall.
2. If can't guess the extension from the URL then make a HEAD request to get the content-type of the file, caching the result
3. If the media type is not supported by Photon then raise an exception: [415 Unsupported Media Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415).
If you want to manually check, try replacing the first row (after the header) of the …
=> Check the file type of the thumbnail before passing it to Photon

.github/workflows/ci_cd.yml, automations/python/workflows/get_commit_message.py
Quick follow up after the merge of #2080 which inadvertently broke staging deployments
It appears that the git commit message is interpolated whole-sale into the `run_name` field of the JSON, which was causing problems with parsing. Example:
```json
"actor": "krysal",
"tag": "8bc6ab7988d395c5ab8b74a3c11b1a36890fe5d1",
"run_name": "Check the file type of the thumbnail before passing it to Photon (#2086)
Co-authored-by: Madison Swain-Bowden <bowdenm@spu.edu>
Co-authored-by: Staci Mullins <63313398+stacimc@users.noreply.github.com>"
}
```
Since GitHub Actions provides no faculties for doing string manipulation on expressions besides `join` and `toJSON`/`fromJSON`, I've added a small python script which captures only the first line of the commit message and escapes any double quotes.
I'll try …
=> Add a simple script for getting a sanitized commit message

.github/release-drafter-api.yml, .github/release-drafter-catalog.yml, .github/release-drafter-frontend.yml, .github/release-drafter-ingestion_server.yml, documentation/_ext/link_usernames.py, documentation/changelogs/api/2023.04.12.23.29.59.md, documentation/changelogs/api/2023.04.18.15.27.15.md, documentation/changelogs/api/2023.04.19.00.01.39.md, documentation/changelogs/api/2023.04.23.23.22.14.md, documentation/changelogs/api/2023.04.27.07.29.23.md, documentation/changelogs/api/2023.05.02.21.26.28.md, documentation/changelogs/api/2023.05.15.21.51.49.md, documentation/changelogs/catalog/2023.04.27.02.43.13.md, documentation/changelogs/frontend/2023.04.23.23.07.51.md, documentation/changelogs/frontend/2023.05.02.19.17.32.md, documentation/changelogs/frontend/2023.05.15.22.13.27.md, documentation/changelogs/ingestion_server/2023.05.03.22.29.52.md, templates/release-drafter.yml.jinja
Fixes an issue wherein contributors were no longer linked on a GitHub release page, see https://github.com/WordPress/openverse/releases/tag/api-2023.05.15.21.51.49 vs https://github.com/WordPress/openverse/releases/tag/ingestion_server-2023.05.03.22.29.52
In #2036, I removed the explicit "credits" section from the release/changelog generation in hopes that GitHub's automatic "Contributors" section would suffice. Unfortunately, in that PR I also pre-rendered the GitHub usernames as links (e.g. `[@$AUTHOR](https://github.com/$AUTHOR)` rather than just `$AUTHOR`). This meant that GitHub was no longer doing it's automatic mentioning behind the scenes, and so it could no longer create the "Contributors" section automatically. Per step 8 of their release document creation docs[^1] _(emphasis …
=> Fix release contributions by removing explicit author link creation

frontend/src/locales/scripts/en.json5
Fixes issue reported by **presskopp** [over Slack](https://wordpress.slack.com/archives/C02012JB00N/p1684427883665889).
This PR adds missing full-stops in translation strings.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add full-stops to browse-page strings 

.github/workflows/ci_cd.yml
Fixes #2055 by @dhruvkb
<details>
```
Version 1.1
Suite D4700
of …
```
=> Apply triage labels when no stack filter matches

frontend/feat/feature-flags.json
Makes analytics switchable in production, defaulting to off.
`just frontend/run dev` and make sure the toggle on the `/privacy` page is disabled by default, but also that if you click it it stays "on" after page refresh.
=> Make analytics switchable in production

.github/GITHUB.md
The information about the release drafter sync is no longer accurate, since we have a different process for releases after the monorepo. This PR removes it from `GITHUB.md`.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove outdated docs section on release drafter workflow sync

catalog/dags/common/ingestion_server.py, catalog/dags/data_refresh/create_filtered_index_dag.py, catalog/tests/dags/common/test_ingestion_server.py
Fixes #2105 by @AetherUnbound
This PR fixes an issue with the `create_filtered_<media>_index` DAG wherein it expects that the filtered index will already exist when it is first run. I've changed the configuration of the DAG so that the `get_current_index` step can skip (along with skipping the `trigger_delete_index` step) without skipping any of the rest of the DAG. I did this by using an `EmptyOperator` to manage the control flow - due to the way this DAG is constructed and how the functions are reused elsewhere, I didn't want to have to add `trigger_rule` at every level within the various function calls.
I also made a slight tweak to one of the `ingestion_server.py` logic to raise a `ValueError` instead of an `AirflowException`, since the latter has some airflow-specific meaning that we …
=> Skip the create filtered index steps that expect an index to already exist

documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230506-implementation_plan_frontend_blurring_sensitive.md
Fixes #938 by @sarayourfriend 
This PR adds an implementation plan for blurring sensitive content in the frontend. You can read it here: https://docs.openverse.org/_preview/2118/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230506-implementation_plan_frontend_blurring_sensitive.html
<details>
```
Version 1.1
Suite D4700 …
```
=> Implementation plan: Blurring sensitive content in the frontend

justfile
Fixes #964 by @zackkrida
~~This PR adds the `env` just recipe as a dependency of both the `py-install` and `node-install` recipes, then changes the syntax for the `install` recipe to use just's implicit dependency management. This ensures `env` is run once rather than for each install command when `just install` is run.~~ 
~~Since `up` is the more common recipe, adding it as a dependency to `install` seems reasonable since it shouldn't be necessary to run that frequently.~~
Per @sarayourfriend's comment below, I have change this so `env` is now a dependency of `up`.
I tested this by cloning a fresh repo (not a quick process!) and ensuring that the steps in the Quickstart guide (i.e. `just install` -> `just up`) did indeed succeed now because the `.env` files are created.
Running `just …
=> Include `env` as a dependency for `up` just recipe

frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
Fixes #473 by @obulat
This PR fixes the client-server mismatch on the mobile.
When you open the server-rendered mobile search page (directly opening the address like localhost:8443/search/?q=cat, or refreshing the search page) instead of navigating to it from the homepage, the contents of the recent searches list from the server are different from the local list saved in the local storage. This causes a mismatch of the server-rendered layout and the client-rendered layout. Nuxt re-renders the layout completely instead of adding the event handlers to the server-rendered layout when "hydrating".
To prevent this, we use the `ClientOnly` wrapper component, which stops the Recent Searches from rendering on the server. Recent Searches on mobile will now only render on the client, after the …
=> Wrap the RecentSearches in ClientOnly

frontend/src/components/VFourOhFour.vue, frontend/src/components/VHeader/VHeaderDesktop.vue, frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue, frontend/src/composables/use-search.ts, frontend/src/pages/index.vue, frontend/src/types/analytics.ts, frontend/test/unit/specs/components/VHeader/v-header-desktop.spec.js, frontend/test/unit/specs/components/VHeader/v-header-mobile.spec.js, frontend/test/unit/specs/components/four-oh-four.spec.js, frontend/test/unit/specs/pages/index-page.spec.js
Fixes #1068 by @obulat
This PR adds a `SUBMIT_SEARCH` analytics event that is fired when the search is submitted from the homepage, the search bar in the search page header, and the 404 page.
~This PR also simplifies the `VSearchButton` component removing the version that used a text label, and using it in both the SearchBar and the StandaloneSearchBar (which is used on 404 and home pages, and does not remove the search text when the server-rendered page is hydrated).~ **Edit:** Extracted to standalone PR #2148.
The unused input sizes (standalone/large) are also removed.
Home page directly imports the child components instead of lazy-loading them, because they are always loaded anyways.
Set up analytics (`just frontend/up`, `just frontend/init`) and run the app (`just frontend/run dev`). …
=> Analytics event: `SUBMIT_SEARCH`

catalog/DAGs.md, catalog/dags/common/constants.py, catalog/dags/database/staging_database_restore/constants.py, catalog/dags/database/staging_database_restore/staging_database_restore.py, catalog/dags/database/staging_database_restore/staging_database_restore_dag.py, catalog/dags/database/staging_database_restore/utils.py, catalog/dags/maintenance/rotate_db_snapshots.py, catalog/tests/dags/maintenance/test_rotate_db_snapshots.py
Originally this started as a PR to fix `hook_params` not being templated in the AWS operators, but it turned into much more.
Original issue being fixed: If you have access to production Airflow, here are the logs:
https://airflow.openverse.engineering/dags/rotate_db_snapshots/grid?search=rotate_db_snapshots&dag_run_id=manual__2023-05-22T03%3A56%3A33.707669%2B00%3A00&task_id=create_snapshot&tab=logs
Log output copied:
```
[2023-05-22, 03:56:38 UTC] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/rds.py", line 103, in execute
create_instance_snap = self.hook.conn.create_db_snapshot(
File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
val …
```
=> Fix various issues that existed in the rotate_db_snapshots DAG

api/api/utils/photon.py
Fixes an issue identified by @obulat in which cached types are not taken correctly as Redis returns them not as strings but as binaries, `b'jpeg'`, causing Jamendo thumbnails to fail. Look for example at https://api.openverse.engineering/v1/audio/70fe3934-ac2b-4c15-bd8a-c6912500f07a/thumb/
Here I decode the cached value (if exists) before comparing it with Photon's allowed types.
Similar to instructions in #2086, add this row to your sample_data/sample_image.csv, run `just api/recreate` and visit http://localhost:50280/v1/images/aeeaaff0-1802-495f-b49e-b288d54fa167/thumb/ several times to see if it works.
```
aeeaaff0-1802-495f-b49e-b288d54fa167,2016-11-21 19:08:53.755535+00,2018-09-11 23:38:56.523813+00,provider_api,rijksmuseum,rijksmuseum,569c6833-b521-4b01-96bc-11cb241c7e33,https://www. …
```
=> Decode cached file type for thumbnails

frontend/src/components/VAudioTrack/VAudioTrack.vue, frontend/src/components/VLink.vue, frontend/src/components/VSearchResultsGrid/VAllResultsGrid.vue, frontend/src/components/VSearchResultsGrid/VAudioCell.vue, frontend/src/components/VSearchResultsGrid/VImageCell.vue, frontend/src/components/VSearchResultsGrid/VImageGrid.vue, frontend/src/pages/search/audio.vue
Fixes #2193 by @obulat
#1979 introduced incorrect markup into the search results page: there are two incorrectly nested `li` items:
This PR removes the inner `li`. To do that, it wraps the `VImageCell` with a `li`. To maintain the correct grid layout, the styles are moved from inner element to the `li`.
_Edited to add:_ After @dhruvkb commented that audio cell and image cell should have similar implementations, and should both be wrapped in `li`, I added those changes to the AudioCell. To make sure that the event listeners are correctly handled, I also refactored `VLink` component.
`VLink` wraps two different components:
1. for external links, it is an `<a>` link. All of the normal event handlers (`@click`, `@focus`, etc) work well here. 
2. for internal links, it is a `<NuxtLink>` which …
=> Fix the image cell markup

api/api/constants/media_types.py, api/api/constants/sensitivity.py, api/api/controllers/search_controller.py, api/api/examples/audio_responses.py, api/api/examples/image_responses.py, api/api/serializers/media_serializers.py, api/api/utils/search_context.py, api/api/views/media_views.py, api/test/factory/models/__init__.py, api/test/factory/models/audio.py, api/test/factory/models/image.py, api/test/factory/models/media.py, api/test/unit/conftest.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/serializers/test_media_serializers.py, api/test/unit/utils/test_search_context.py, api/test/unit/views/test_media_views.py
Fixes #1199 by @sarayourfriend 
This PR includes significant additions to the test factories and fixtures in order to facilitate Elasticsearch document creation. I chose this approach over ElasticMock for the following reasons:
1. It allows us to avoid mocking altogether (great for tests generally)
2. It exercises our _actual_ indexes, not fake ones
3. It still follows the general test-data hygiene rules of removing test data after each test case
The last one is the source of some abstraction that is not necessarily easy to follow (in that the parts aren't explicitly connected), but at least somewhat tied together via the `CREATED_BY_FIXTURE_MARKER`. The usage of pytest's `request` fixture is also potentially obscure but is quite common in pytest plugins of any significant complexity. I …
=> Derive document sensitivity markings from filtered index

frontend/src/composables/use-dialog-content.ts, frontend/src/composables/use-focus-on-show.ts
Fixes #2220 by @sarayourfriend
This PR sets `clickOutsideDeactivates` for the popover to make sure that it is closed when you click outside.
This PR also fixes the issue reported by @AetherUnbound in https://github.com/WordPress/openverse/pull/2141#pullrequestreview-1442655633: when the external sources popover cannot be closed in any way but clicking on the "Close" button.
I also tried rebasing this PR on top of #2199 and removing `.skip` from the test - and the test passes.
Run the app, open the search page, scroll to the bottom of the results and open "External sources" popover. Click outside of the popover - it should close.
<details> …
=> Hide popover on click outside

documentation/general/contributing.md, documentation/meta/communication_aliases.md, documentation/meta/documentation/index.md, documentation/meta/documentation/review.md, documentation/meta/index.md, documentation/meta/maintainer_tasks.md
Fixes #2304 by @AetherUnbound 
This PR adds:
- a new page to list tasks maintainers should consider doing instead of opening a new PR. It also gives helpful advice for some of these or links to other parts of the documentation that talk about that task.
- additional documentation to the contributing docs for further ways to help issue backlog maintenance. I added this here, specifically, because it is something anyone can help with effectively, not just maintainers.
- a new page to document communication aliases and their purposes. This is linked to from the issue backlog maintenance documentation and could be used elsewhere in the documentation, I think.
- a new page to give advice for proofreading documentation. This is a separate page because I wanted to put it somewhere that we could …
=> Document non-code maintainer tasks

documentation/projects/proposals/nuxt_3_migration/20230604-project_proposal_nuxt_3_migration.md, documentation/projects/proposals/nuxt_3_migration/index.md
Part of #411
Tagging @sarayourfriend and @zackkrida for their experience with frontend.
[on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
The deadline for review of this round is **2023-06-07**
<details>
```
Developer …
```
=> Add Nuxt 3 migration project proposal

catalog/DAGs.md, catalog/dags/flickr_thumbs_removal.py, catalog/dags/providers/provider_api_scripts/flickr.py, docker-compose.yml
Fixes #1816 by @krysal
Flickr is the last and main provider retaining thumbnails that do not fit our requirements for showing in the Openverse UI (mostly on desktop), so here is a DAG to remove them progressively in batches. This should allow other tasks while running and advance steadily. It uses the new TaskFlow API which comes really handy for a DAG like this.
After the DAG has runs successfully, this will allow us to revert #1812 on the API side.
In minor related changes, I also exposed the port of the upstream_db for being able to use UI software like DataGrip or TablePlus, and fixed a shadowing name in the Flickr DAG.
1. Run the normal flicker DAG to ingest some rows.
2. Modify those rows to have some fake thumbnails URLs
```sql
UPDATE image SET …
```
=> Add DAG to remove Flickr thumbnails

frontend/test/unit/specs/components/InputField/input-field.spec.js
Fixes #2222 by @sarayourfriend 
Fixes the `"should allow changing the type"` test by simply enabling it. I believe this test may have been incorrectly marked as not having an assertion. Previously it was skipped with `xit()` but enabling the test works correctly. 
The test is quite simple, it renders a VInputField and makes sure it can be switched to `type="number"`. I'm not sure of the usefulness of this test but it doesn't seem to hurt to enable it.
Apologies if I'm missing something very obvious here 😊 
Tests should pass.
<details>
```
Version 1.1 …
```
=> Enable "should allow changing the type" test for VInputField

frontend/test/unit/specs/stores/media-store.spec.js
Fixes #2223 by @sarayourfriend
This PR fixes the said test by adding the assertions, and changing the condition for not resetting the images from "page not being undefined" to "shouldPersistMedia being true".
The CI should pass. If the test without `.skip` did not have an assertion, it would fail the CI. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Add assertions to the `fetchSingleMediaType does not reset images if shouldPersistMedia is true`

frontend/src/components/VAudioTrack/layouts/VFullLayout.vue, frontend/src/components/VContentLink/VContentLink.vue, frontend/src/components/VContentReport/VContentReportForm.vue, frontend/src/components/VLink.vue, frontend/src/components/VMediaInfo/VCopyLicense.vue, frontend/src/components/VMediaInfo/VMediaLicense.vue, frontend/src/pages/image/_id/index.vue, frontend/src/types/analytics.ts, frontend/test/unit/specs/components/v-content-link.spec.js, frontend/test/unit/specs/components/v-link.spec.js
Fixes #1078 by @dhruvkb
This PR adds three closely-related analytics events:
- `EXTERNAL_LINK_CLICK`
- `VISIT_CREATOR_LINK`
- `VISIT_LICENSE_PAGE`
The `EXTERNAL_LINK_CLICK` event is fired every time an external `VLink` is clicked, unless `send-external-link-click-event` prop is `false`. This prop is used to replace the `EXTERNAL_LINK_CLICK` event with other custom events such as `GET_MEDIA`, if necessary.
I've also added the analytics events to links in the  copyable HTML media attribution statement:
Normally, clicking the creator link here should send `VISIT_CREATOR_LINK` event. However, it is impossible to get whether the link is the creator or title link from this HTML. I thought of using the heuristics of "if a link follows the word 'by'", but since the attribution HTML is translated, …
=> Add analytics events for external links

documentation/projects/planning.md
Fixes #2249 by @zackkrida 
Updates project thread update documentation, removes the template, and links to some real-world examples from the repo. Oh, and also fixes some unrelated typos.
Let me know if you think this is sufficient information for project leads and contributors on how to leave updates. Keep in mind that folks will be directed to this section from the automated reminders in #2251, which state:
> Hi @${recipient}, this project has not received an update comment in 14 days. Please leave an update comment as soon as you can. See the [documentation on project updates](https://docs.openverse.org/projects/planning.html#providing-project-updates) for more information. …
=> Update project thread update docs

catalog/dags/common/constants.py, catalog/dags/database/staging_database_restore/staging_database_restore.py, catalog/dags/database/staging_database_restore/staging_database_restore_dag.py, catalog/env.template, catalog/tests/dags/database/staging_database_restore/test_staging_database_restore.py
Another step towards completing #1989
This PR adds the truncation steps described in the IP for this work on step 12.3 here: https://docs.openverse.org/projects/proposals/search_relevancy_sandbox/20230406-implementation_plan_update_staging_database.html#dag
We also needed a connection to the staging database (we haven't had the need arise for one yet) so I added a new connection for that. The naming convention we have isn't _great_ but I didn't particularly want to change that at this juncture. I've added this connection to our production Airflow instance.
The DAG definition specifies a handful of tables to truncate, but fortunately all of them reference `api_throttledapplication` either directly or indirectly, so a single `TRUNCATE...CASCADE` will truncate them all (and prevents …
=> Truncate OAuth tables after staging DB restore

catalog/dags/common/github.py, catalog/dags/database/staging_database_restore/staging_database_restore.py, catalog/dags/database/staging_database_restore/staging_database_restore_dag.py, catalog/dags/database/staging_database_restore/utils.py, catalog/tests/dags/database/staging_database_restore/test_staging_database_restore.py
Another step towards completing #1989, builds off of #2207
This PR adds a step to the staging database restore DAG which pulls the most recent API package version and dispatches the staging API deployment workflow with that version. While the deployment workflow itself needs a follow-up update to allow the `openverse-bot` to run deployments, this does correctly trigger the deployment workflow! Example: https://github.com/WordPress/openverse-infrastructure/actions/runs/5096003624
I added a similar mechanism for setting up the GitHubAPI as we had for the RdsHook, it seemed easiest for the two functions we were using it in. I also changed the flow a little to only report completion after the truncate & deployment steps were complete, rather than alongside.
To test this, follow the …
=> Deploy staging API after staging DB restore

catalog/dags/retired/common/etl/scripts/ExtractCCLinks.py
Removes a string reference to an old s3 bucket in the retired ETL pipeline script. 
This bucket has been reclaimed by another user and was flagged in a security review of the repo. This PR really only exists to prevent further warnings, even though this dead, unused code poses no actual security risk.
=> Remove string reference to old s3 bucket

frontend/test/storybook/visual-regression/v-header-internal.spec.ts
Fixes CI failure on main.
The snapshots on main do not match because we expect to see non-hovered version of the internal header modal close button, and we see the hovered one instead (with the opacity overlay).
This PR moves the mouse to (0,0) before taking the snapshot to prevent the hover and fix the mismatch.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix CI Playwright storybook failure

api/Dockerfile
Fixes #2411 by @zackkrida 
Fixes the conflict when copying over audiowaveform dependencies from the Dockerfile by explicitly copying over subfolder contents instead of the subfolders themselves, which already exist as symlinks in the root of the base image and therefore cause an error when attempting to copy over them.
Review the code, CI should pass. After merged, the staging API should continue to work and serve thumbnails. 
You can also checkout `main` and `just recreate`. Observe that the build fails. Then checkout this branch and `just recreate && just up` and observe that everything works.
<details>
```
Developer Certificate …
```
=> Fix API image builds

api/api/utils/search_context.py, api/test/unit/utils/test_search_context.py
Fixes #2407  by @sarayourfriend 
Checks the feature flag before querying the filtered index.
First, confirm you know how to reproduce the issue on `main`. Checkout `main` and update `api/env` to set `ENABLE_FILTERED_INDEX_QUERIES=False` to match the live environment configuration. Next, delete the `image-filtered` alias in your local Elasticsearch cluster:
```
$ curl -X DELETE http://0.0.0.0:50292/image-init-filtered/_alias/image-filtered
```
Confirm the index is deleted by sending:
```
$ curl http://0.0.0.0:50292/image-init-filtered/_alias
```
And confirm the response matches (empty `aliases` object):
```json
{"image-init-filtered":{"aliases":{}}}
```
Now make a request to http://localhost:50280/v1/images/ and confirm you get a 500 about `image-filtered` not existing.
Now, check out this …
=> Check filtered index feature flag before querying in `SearchContext`

api/api/controllers/search_controller.py, api/api/utils/dead_link_mask.py, api/test/factory/es_http.py, api/test/factory/models/media.py, api/test/test_dead_link_filter.py, api/test/unit/conftest.py, api/test/unit/controllers/test_search_controller.py
Fixes #2415 by @sarayourfriend 
Stops `_post_process_results` recursion once the total available hits have been exhausted. Previously, if queries were unable to fill the page_size with live links, `_post_process_results` would continue to iterate until the ES max page depth was met.
For some reason the `Hit` `__repr__` was suddenly failing for me and causing tests to incorrectly fail (call argument mocks use `repr`, apparently). The fix for this was to ensure the document `_id` is a string. Here is the error I was seeing:
```
self = <[TypeError('sequence item 1: expected str instance, int found') raised in repr()] Hit object at 0x7f34bb326c90>
def __repr__(self):
return "<Hit({}): {}>".format(
>           "/".join(
getattr(self.meta, key) for key in ("index", "id") if key in self.meta
), …
```
=> Prevent unnecessary post-process results recursion

frontend/src/components/VFilters/VSearchGridFilter.vue, frontend/src/stores/search.ts, frontend/src/types/analytics.ts, frontend/test/unit/specs/components/v-search-grid-filter.spec.js
Fixes #1070 by @dhruvkb
This PR adds `APPLY_FILTER` event sent when the user selects a filter.
We might want to debounce it, I'm not sure if I should add it here?
Some unrelated changes were also added to clean up the unused ref, and use `storeToRefs` pinia helper to reduce the number of computeds used in the file.
Try clicking on the filters (both in the modal on mobile screen, and the sidebar on the desktop). You should see the event logged in the console, and tracked in Plausible at 0.0.0.0:50288 (if you run `just frontend/up` and `just frontend/init` as described in https://docs.openverse.org/frontend/guides/analytics.html).
<details> …
=> Add APPLY_FILTER analytics event

ingestion_server/justfile, load_sample_data.sh
Addresses #2359 by @sarayourfriend
This PR makes these changes:
- ensures that invalid API calls to the ingestion server using cURL fail locally for non-2xx response codes.
- checks for sample data to be loaded in SQL after issuing `DELETE` and `\copy` to the database.
This PR does not rewrite the script in a different language, like Python, for two reasons:
- It has been tried before (WordPress/openvere-api#830) but it was turned down as it was too much rewriting for the little value gained.
- The current structure of the script is largely a collection of `just` recipe invocations. Switching to Python will not improve any inherent fragility in those recipes.
<details> …
=> Make `load_sample_data` more resilient

documentation/projects/proposals/trust_and_safety/content_report_moderation/20230517-implementation_plan_mature_copy_change.md
2023-06-08
Resolves: #1965
This is the implementation plan for copy/code changes necessary for updating references from `mature` to `sensitive` for various aspects of the frontend and API.
Admittedly I have very little familiarity with the frontend and translations specifically, so my understanding there may be inaccurate. Any guidance in that area would be welcome!
[on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
This discussion is …
=> Implementation Plan: Copy updates `mature` -> `sensitive`

.github/workflows/release-app.yml
Related to https://github.com/WordPress/openverse-infrastructure/issues/541 by @sarayourfriend
Deploy the production API thumbnails service alongside the regular API deployment in Release app workflow.
Both services deploy the same images and everything, so we don't need distinct changelogs or anything else special for the thumbnails.
Make sure I got the workflow dispatch correct. I copy/pasted from the existing step and just made it only run for when API is the app and to dispatch the `api_thumbnails` event specifically rather than `api` event.
- [N/A] I ran the DAG …
=> Add thumbnails production deployment

api/api/views/media_views.py, api/test/unit/views/test_media_views.py
Fixes #2483 by @zackkrida 
Adds a filter to exclude works for which the provider has `filter_content=True`. Please see the comment for why we must use a subquery rather than a join. Note that this **does not** increase the number of queries on these endpoints, as proven by the query counting tests in `test_media_views`.
Reproduce the problem in the issue locally by running `just api/up` on `main`. Visit `/v1/images` and confirm you see results from flickr. Click on one of the single result views from the flickr provider and leave the tab open. Go to `/admin` in another tab (deploy/deploy are username/password) and set filter content to true on the flickr provider from the ContentProvider view. In the single result tab, refresh the page and confirm you can still access the result. Confirm …
=> Filter single media views for hidden providers

api/pytest.ini, api/test/factory/models/oauth2.py
We suppress a warning for `DateTimeField AccessToken\.expires received a naive datetime`, that seems to be raised by tests using our `AccessTokenFactory`, which use `faker` to generate dates that do not have timezone info.
This PR adds tzinfo and removes the suppressed warning.
Run `just api/test` and see that the tests all pass and there are no warnings that match the `DateTimeField AccessToken\.expires received a naive datetime` text.
You can also remove the change to the `oauth2.py` file, but keep the change to `pytest.ini` which stops suppressing the warning, and rerun tests. This time you should see that the warnings were not prevented and do in fact display.
<details> …
=> Add tzinfo in factory generated access tokens

ingestion_server/ingestion_server/api.py, ingestion_server/ingestion_server/tasks.py
Fixes #2399 by @sarayourfriend 
Relevant Sentry docs:
- Multi-thread Sentry: https://docs.sentry.io/platforms/python/troubleshooting/#addressing-concurrency-issues
- Draining the client: https://docs.sentry.io/platforms/python/configuration/draining/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Fpython%2Ftroubleshooting%2F
This PR adds a wrapper function around our multiprocessing entrypoint that runs the worker's actual task wrapped inside a Sentry context. This allows the client cloned by the scheduler (in api.py) to capture messages and exceptions. We also catch any exceptions that occur and pass them to the client. Before allowing the worker to exit, the wrapper flushes the client so that all messages actually make their way to Sentry instead of being lost when the …
=> Fix Sentry configuration for multiprocessing environment

frontend/test/unit/specs/components/v-content-report-form.spec.js
Fixes #2315 by @sarayourfriend
I removed a comment in `v-content-report-form.spec.js`, and replaced implicit `get` assertions in the testing library with explicit assertions.
I did this by using Jest's `expect` function along with `toBeInTheDocument` on the tests instead of `get`.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Replaced get* assertions in testing library with explicit assertions

frontend/src/pages/audio/_id/index.vue, frontend/src/pages/image/_id/index.vue
Fixes #2564 by @obulat
This PR fixes the error that happens when the request for a single image fails, and `image` is `null` in the call to `head`.
It also refactors `head` to use `useMeta`, as the other content pages.
The single result pages should still `"cat" | Openverse` as the title and the image thumbnail as the page's `og` image. I don't think we need tests for this.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Refactor `head` in single result pages

frontend/src/pages/audio/_id/index.vue, frontend/src/pages/image/_id/index.vue, frontend/test/unit/specs/pages/single-image-result-page.spec.js
~~Note: This PR is based on #2583, and should be reviewed after it.~~ [^1]
Related to #2553 by @obulat
This PR adds conditional rendering to the single result page templates to account for the fact that the main media (`image`/`audio`) can be `null`.
This PR was split from the bigger fix to simplify review.
[^1]: I realized that this PR doesn't really need the changes from 2583, so I rebased it on main.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix types in the templates

catalog/dags/data_refresh/create_filtered_index_dag.py
Fixes #2619 by @AetherUnbound
This PR uses the `trigger_and_wait_for_task` method for the point alias step of the `create_filtered_<media-type>_index` DAG. This ensures that the point alias step completes before the deletion is attempted.
1. `just down -v`
1. `just api/init`
1. `just i && just c`
1. Enable the `create_filtered_image_index` DAG, then the `image_data_refresh` DAG
1. Observe that the wait step completes before deletion is attempted.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use trigger_and_wait for alias point step in create filtered index DAG

catalog/dags/data_refresh/create_filtered_index_dag.py
This PR fixes an issue wherein the filtered index creation DAG was checking for the readiness of the unfiltered index rather than the produced, filtered index. In most normal runs this would never raise an issue, because the indices are usually uniform (e.g. `image-12345` and `image-12345-filtered`, so checking against `image-12345` passes). When the create filtered index DAG is run manually, it generates a different suffix for the filtered index, one which doesn't have a matching unfiltered index (e.g. `image-98765-filtered`, which was made from `image-12345`, is trying to check for `image-98765` which does not exist).
This is rectified by running the check against the produced filtered index (suffix + `-filtered`) rather than the index just referenced with the suffix.
1. Checkout `main` …
=> Check readiness against filtered index

catalog/DAGs.md, catalog/dags/data_refresh/dag_factory.py, documentation/projects/planning.md, documentation/projects/proposals/search_relevancy_sandbox/20230530-implementation_plan_staging_elasticsearch_reindex_dags.md
Resolves #1987 by @AetherUnbound 
> **Note**
> This discussion is following the Openverse decision-making process. Information about this process can be found
on the [Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
The discussion is currently in the [Revision round](https://docs.openverse.org/meta/decision_making/process_description.html#revision-round).
The deadline for review of this round is **2023-06-27**.
=> Implementation Plan: Staging Elasticsearch Reindex DAGs

frontend/nuxt.config.ts, frontend/package.json, pnpm-lock.yaml
Fixes #2633 by @sarayourfriend 
This PR removes the eslint module from Nuxt app and greatly improves the DX 🎉 For more info, see the related issue. 
Try duplicating a JS import in one of the components, or adding an unused import. Then, run `just frontend/run dev`. On main, you wouldn't be able to run the app because it would show an error screen. In this PR the app should run normally. However, if you try to commit these changes, pre-commit would prevent you from doing that. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove nuxt eslint module

frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue, frontend/src/components/VAudioTrack/layouts/VBoxLayout.vue, frontend/src/components/VAudioTrack/layouts/VRowLayout.vue, frontend/src/components/VSearchResultsGrid/VImageCell.vue, frontend/src/locales/scripts/en.json5, frontend/src/stores/ui.ts, frontend/tailwind.config.js, frontend/test/unit/specs/components/AudioTrack/v-audio-track.spec.js, frontend/test/unit/specs/components/VSearchResultsGrid/v-image-cell.spec.js
Fixes #2369 by @dhruvkb
This PR adds logic to the image and audio result components to blur their content if their media item has been flagged as sensitive. It also replaces title and creator strings from the DOM with placeholders to prevent any sensitive information from leaking through assistive technology that bypasses CSS and interacts with the DOM. 
1. Enable the `fake_sensitive` toggle in the `/preferences` page.
2. Search for something like 'cat'.
3. Observe blurring of fake-sensitive results in all three views:
- mixed media
- only images
- only audio
<details>
```
Developer …
```
=> Blur sensitive search results

documentation/projects/templates/implementation-plan.md
When reviewing https://github.com/WordPress/openverse/pull/2676 I realised that our implementation plan template is missing what I view as a key section: the step-by-step plan. An ordered list of the steps is so useful for getting a high-level understanding of how the different requirements of the plan fit together and how the implementation will be paced.
I added a new section for this and renamed "outlined steps" to "step details" to further help disambiguation between the new section and the existing one.
I also added a new section for feature flags, because that was also not explicitly required in the implementation plan despite being a critical consideration.
Read the updated template and the description comments I've added or expanded upon and confirm they clearly describe the …
=> Add additional details to implementation plan template

documentation/packages/eslint_plugin/index.md, documentation/packages/index.md, justfile
Addresses undocumented guidelines I noticed when reviewing #2660.
Adds the following new documentation:
1. Expectations for `eslint-plugin` including TypeScript usage, rule documentation, and unit tests
2. New just alias script `p` to ease running `pnpm` package scripts
3. Additional documentation about package development
Read the new documentation and confirm it is clear and sufficiently covers the development guidelines.
<details>
```
Version 1.1
Copyright (C) …
```
=> Add development guidelines/documentation for eslint-plugin

frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue, frontend/src/components/VAudioTrack/layouts/VBoxLayout.vue, frontend/src/components/VAudioTrack/layouts/VRowLayout.vue, frontend/src/components/VSafeBrowsing/VSafeBrowsing.vue, frontend/src/components/VSearchResultsGrid/VImageCell.vue, frontend/src/composables/use-sensitive-media.ts, frontend/src/constants/content-safety.ts, frontend/src/stores/ui.ts, frontend/test/unit/fixtures/audio.js, frontend/test/unit/specs/composables/use-sensitive-media.spec.ts
Related to #2462 by @dhruvkb 
This PR creates a new `useSensitiveMedia` composable for working with sensitive media, and updates the blurring logic to use this composable. This composable is fully tested with a unit test, and forms the basis of the "backend" work for the single result sensitivity UI. It includes hide/reveal methods that aren't used by this PR but will be for the VSafetyWall.
This PR also adds revealedSensitiveResults, a list of UUIDs of revealed sensitive media, to the UI store.
It was extracted into a standalone PR for ease of reviewing.
Check that blurring still works as-expected in the frontend search results, when all relevant `/preferences` toggles are enabled. Check that you like the `useSensitiveMedia` implementation and that test coverage is sufficient. …
=> useSensitiveMedia composable

catalog/DAGs.md, catalog/dags/database/batched_update/batched_update.py, catalog/dags/database/batched_update/batched_update_dag.py, catalog/dags/database/batched_update/constants.py, catalog/tests/dags/database/test_batched_update.py
Fixes #2507 by @stacimc 
More context in #2507, but briefly:
Because the `batched_update` DAG is going to be used to perform potentially very long-running (multiple weeks long) updates, it needs to be able to handle the update task failing and retrying due to Catalog deployments. In the current implementation, when the update task retries it would resume _from the beginning_.
This PR takes the following approach:
* In each DagRun, we create an Airflow variable suffixed with the `query_id` that we use to keep track of the progress of the update, updating it after each batch.
* When the `update_batches` task runs, it checks to see if this variable exists and if so, resumes the update from that point. Otherwise it starts at the beginning.
* An additional clean up task is added at the end to …
=> Make batched_update DAG resistent to mid-update failures

frontend/src/pages/audio/_id/index.vue, frontend/src/pages/image/_id/index.vue
Fixes [#2657](https://github.com/WordPress/openverse/issues/2657) by @fcoveram 
- updates padding around "Back to results" button area, per [figma designs](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=1263%3A62834&mode=design&t=jTbJqJAStXoIpH4F-1)
Image page
Audio page
- update the styling of the buttons as mentioned in the original issue description. the buttons in prod already match the expected changes. please see [this comment](https://github.com/WordPress/openverse/issues/2657#issuecomment-1644346446) for more information
- navigate to an image or audio page from the search results. verify that the padding updates reflects the Figma design in viewport below and above the medium breakpoint (768px) …
=> Update back to results button area

catalog/DAGs.md, catalog/dags/common/constants.py, catalog/dags/common/ingestion_server.py, catalog/dags/common/popularity/sql.py, catalog/dags/data_refresh/dag_factory.py, catalog/dags/data_refresh/data_refresh_task_factory.py, catalog/dags/popularity/dag_factory.py, catalog/dags/popularity/popularity_refresh_types.py, catalog/dags/popularity/refresh_popularity_metrics_task_factory.py, catalog/tests/dags/common/popularity/test_dag_factory.py, catalog/tests/dags/common/popularity/test_sql.py, docker-compose.yml
Fixes #2089 by @stacimc 
Adds a popularity refresh DAG factory that generates `audio_popularity_refresh` and `image_popularity_refresh` DAGs. Each DAG:
* refreshes popularity metrics and constants (recalculating the popularity constants)
* then, triggers a `batched_update` DagRun for each of the providers of this media type that support popularity data
* waits for the batched updates to complete and notifies Slack
* It is currently on a `None` schedule, so must be triggered manually, and has very generous timeouts. These will be revisited in follow-up PRs after testing is done in production.
The `TriggerDagRunOperator` we're using to trigger the `batched_update`s is put in `deferrable` mode, in order to free the worker slot while waiting for the batched updates to complete. This requires …
=> Add popularity refresh DAGs

frontend/src/layouts/content-layout.vue, frontend/src/layouts/default.vue, frontend/src/layouts/search-layout.vue, frontend/tailwind.config.js
Fixes #2683 by @fcoveram
This PR fixes the janky scrolling behaviour on iOS by fixing the order in which the `100vh` and `100dvh` heights are applied. On iOS they were being applied in the opposite order of what's desired, leading to the problem.
Fixing the order as `100vh`, `100dvh` ensures that `dvh` wins, if supported, fixing the issue.
0. Install XCode on your Mac (it's huge, like ~8GB so do not use cellular or limited plans)
0. Visit https://localhost:8443 from Safari in the simulator.
1. Try (and hopefully fail) to reproduce the problem described in #2683.
<details>
```
Developer …
```
=> Fix double-scroll issue on iOS devices

api/conf/settings/logging.py
Fixes #2638 by @AetherUnbound
This PR re-adds the request ID tracking middleware, which allows us to see request IDs across log lines in the API. This was erroneously removed in 098925afa90b26881b4b4d3e2baffa69049692c0. I've added it in a similar manner to how the CORS middleware is currently inserted:
https://github.com/WordPress/openverse/blob/8afb04bc81429cda3f0aa3f8be1d22ad4bd8cbc7/api/conf/settings/security.py#L43-L45
1. `j build && j down -v`
1. `j api/init`
1. Run `j logs web` in the terminal and then submit some requests to the API locally. You should see something like the following (note `[<hash>]` across requests rather than `[none]`):
```
openverse-web-1  | [2023-07-26 22:54:03,277 - log_request_id.middleware -  55][INFO] [afd412a869274145abb82d2c56334262] method=GET …
```
=> Re-add request ID tracking to API middleware

frontend/src/server-middleware/robots.js
This PR restricts all bot traffic to our search result endpoints. This is a temporary experiment to see if this kind of traffic is impacting our API performance.
=> Block crawling on search results views

frontend/test/storybook/visual-regression/v-header-internal.spec.ts
Fixes #2720 by @zackkrida
In the `trace` file in #2473 you can see that the fonts change size about 0.2 seconds after opening the modal. The tests fail because the snapshot is taken before this change.
This PR adds a `sleep` to wait for the change before taking the snapshots.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Add a wait for the fonts to load in the internal header modal

documentation/projects/proposals/additional_search_views/20230719-implementation_plan_additional_search_views.md
Resolves #2560 by @zackkrida
A very rough draft implementation of the additional search view pages is in branch [draft/collection_pages](https://github.com/WordPress/openverse/tree/draft/collection_pages).
> **Note**
> This discussion is following the Openverse decision-making process. Information about this process can be found
on the [Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
The discussion is currently in the [Decision round](https://docs.openverse.org/meta/decision_making/process_description.html#decision-round).
The deadline for review of …
=> Implementation Plan: Additional search views

frontend/src/components/VErrorSection/VServerTimeout.vue, frontend/src/components/VErrorSection/meta/VErrorSection.stories.mdx, frontend/src/constants/content-safety.ts, frontend/src/constants/filters.ts, frontend/src/stores/search.ts, frontend/src/utils/search-query-transform.ts, frontend/test/unit/specs/stores/search-store.spec.js, frontend/test/unit/specs/utils/search-query-transform.spec.js
Fixes #2548 by @dhruvkb
The `mature` query parameter is renamed to `unstable__include_sensitive_results`.
The filter category is renamed from `mature` to `includeSensitiveResults`
The filter object in the search store is changed from `mature: { code: "mature", name: "...", checked: true }` to `includeSensitiveResults: { code: "includeSensitiveResults", name: "", checked: true }`.
We have extensive unit tests for transforming the query to filters in the `search` store, and filters to the API query parameters. They should pass.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
```
=> Rename `mature` to `includeSensitiveResults`

catalog/dags/data_refresh/reporting.py, catalog/dags/database/batched_update/batched_update.py, catalog/dags/database/batched_update/batched_update_dag.py, catalog/dags/popularity/dag_factory.py, catalog/dags/popularity/popularity_refresh_types.py, catalog/tests/dags/database/test_batched_update.py
Some fast-follows after turning on the popularity refresh DAGs in production.
A few quick fast-follows:
- Updates the poke interval for the audio refresh to 1 minute: in production, it took around 5 minutes for the entire audio refresh to complete, so the 30 minute poke interval is much too high
- Updates the `execution_timeout` on the `TriggerDagRunOperator` to 30 days to match the timeout of the batched updates. (In production, the image batched updates are proceeding well, but the image refresh DAG timed out at this step)
- In the `batched_update` DAG, instead of logging the number of rows completed _and the number remaining_, it now logs the number of rows completed and _the percent completed_, which is more useful for large DAGs like Flickr.
- Formats all the `count`s given in the …
=> Clean up Popularity Refresh notifications and adjust poke interval

frontend/src/data/api-service.ts
Fixes #2746 by @obulat
This PR stops the conversion of the error into an object. This will allow us to handle timeout errors correctly.
A follow-up to this PR should be the fix for #632 that actually shows the timeout error page instead of the generic yellow error page as it does not.
To easily simulate timeouts, change the default timeout to 30:
https://github.com/WordPress/openverse/blob/61c7abdeaed0450558859ff949846f9a1497ad13/frontend/src/data/api-service.ts#L8
From the logs it's not clear that the error was converted to an object because it's causing the Promise to reject, and is handled in the same `catch` block.
However, you will see the warning in the console saying "There was an error fetching media providers for image: ECONNABORTED", which means that the error is recognized as …
=> Stop converting timeout error to an object in Nuxt API requests

frontend/nuxt.config.ts, frontend/src/plugins/polyfills.client.ts
Fixes #2745 by the sentry bot
Polyfills the Array.prototype.flatMap method so it works in versions of Chrome < 69. This has occurred enough times to warrant the polyfilling. 
Build locally and confirm the presence of the polyfill in the client bundle by searching for `flatMap:` and confirming it's there. 
We should also see a minuscule increase to the bundle size.
<details>
```
Version 1.1
Suite D4700 …
```
=> polyfill flatMap for Chrome < 69

.github/workflows/ci_cd.yml, api/api/apps.py, docker-compose.yml, ingestion_server/gunicorn.conf.py
Based on https://github.com/WordPress/openverse/pull/2777 and related to the comment here: https://github.com/WordPress/openverse/pull/2777#pullrequestreview-1576169306
Because production is currently stuck on ES 7 until we've figured out why ES 8 caused the queries to take so long, we need to test all our code against both ES versions. Until we've fully transitioned to ES 8 we need to support both versions.
Check the new CI tasks and confirm they've run as expected. Locally, run `OPENVERSE_ES_VER=7 just api/test` locally to test as an example that the environment variable works as expected.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to …
=> Run API and Ingestion Server tests with all relevant ES versions

catalog/dags/providers/provider_api_scripts/europeana.py, catalog/tests/dags/providers/provider_api_scripts/test_europeana.py
Fixes #1268  by @stacimc 
We've been filtering on image create date, rather than update date. Hopefully this switch will both smooth out the number of records processed in regular dag runs, and make re-ingestion either unnecessary or substantially less necessary. 
I thought it would be helpful to have this in place for testing https://github.com/WordPress/openverse/pull/2782
- `just catalog/shell` and `pytest`
- [get a europeana api key](https://pro.europeana.eu/page/get-api) if you don't have one already, and put it in your `catalog/.env` file
- maybe set a more recent [start date](https://github.com/WordPress/openverse/blob/f3232315128c01c97493f673ce00f3353c8f260a/catalog/dags/providers/provider_workflows.py#L205), and then try running the dag on http://localhost:9090/
- check out the …
=> Adjust the date filter in Europeana to pull updates rather than created records

api/Dockerfile, docker-compose.yml
Fixes #2785 by @sarayourfriend 
Switches the API image to have `gunicorn` as the run command, rather than the development command. See the issue for rationale. The development run command is now just in the docker-compose file, which is the primary place for development configuration.
Run `just down && just build web && just api/up` and confirm that the API is accessible. Remember to `just api/init` if you're working on a fresh clone. 
To test the production configuration, comment out the `command` on the `web` service of docker-compose.yml and confirm that it's still accessible. Note that static files will _not_ work in this configuration because in production we rely on Nginx to serve them and we do not have that configured locally! As long as you can access the API and see unstyled DRF …
=> Set API Dockerfile run to production config

documentation/projects/proposals/publish_dataset/20230706-project_proposal.md, documentation/projects/proposals/publish_dataset/20230706-project_proposal_openverse_dataset.md, documentation/projects/proposals/publish_dataset/index.md
Related to #2545
This PR adds a project proposal for the Dataset project. I've tried to get this out quickly so it might be a bit rough. Suggestions are very welcome. I've asked @sarayourfriend (for providing past feedback on this initiative) and @AetherUnbound (for general data expertise) to review from the Openverse side.
I would also appreciate insights from @apolinario on the HuggingFace platform: how it relates to _this project_ but also some of its general functionality which I touch on in the proposal.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
Requested reviewers or participants will be following this process. If …
=> Project Proposal: Openverse Datasets

dag-sync.sh
This PR fixes an issue that arose when #2817 was merged: the commit title `timestamp_created -> timestamp_update (#2817)` broke the Slack message component of the DAG sync since the `>` character was interpreted by Slack as the end of the link definition.
This change adds a step to replace the `<` and `>` character with two variants (`≺` and `≻` respectively). These characters, though they look roughly similar, don't register in Slack as delimiters and thus don't break the message syntax when merged!
This was tested in our Slack instance:
**Before**
**After**
<details>
```
Version 1.1
Copyright (C) …
```
=> Prevent < and > in commit titles from breaking dag-sync slack message

api/Dockerfile
Follows up #1909
This PR removes the exposure of port 3000 from the API Dockerfile.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Unexpose port 3000 from API Dockerfile

catalog/dags/common/popularity/sql.py, catalog/dags/popularity/refresh_popularity_metrics_task_factory.py
In production, we've seen the step to refresh the popularity constants view time out. This PR updates the data refresh and popularity refresh DAGs (both of which currently refresh popularity constants) to instead drop and recreate the view. This approach fixed a similar problem with the matview, so we expect it to help now.
**Note**: We will need to make sure that the data refresh and popularity refresh for a given media type are not running the popularity steps simultaneously, since now the data refresh might try to drop the constants view while the popularity refresh is in the middle of recreating it for example. **This will not be a problem long term, because the popularity steps are in the process of being removed from the data refresh in #2818 (which is just blocked on #2803 but …
=> Drop and recreate pop constants instead of refreshing

api/nginx.conf.template, docker-compose.yml
Fixes #728 by @rbadillap 
There are three main parts to this PR: one direct change, one related change, and another change to support testing.
1. The changes to `docker-compose.yml` add a new `nginx` service that uses the `nginx` image we use in production created using `api/Dockerfile`. This is necessary for testing the changes in this PR and indeed, for easily verifying _any_ changes to `api/nginx.conf.template`.
2. The change to `location /static` to add a trailing slash fixes a small issue and potential (though unlikely) security/misconfiguration issue. Adding a trailing slash `/static/` prevents the rule from matching `/static-somethingelsewedidnotintend`. Likewise, removing the unused `/media` location also prevents potentially obscure security issues. Best to just _not allow_ …
=> Fix nginx redirect for no trailing slash

frontend/src/components/VAudioTrack/layouts/VGlobalLayout.vue
This PR adds blurring to the global audio player to cover the scenario described in https://github.com/WordPress/openverse/issues/377#issuecomment-1686558423.
1. Enable the following flags from `/preferences`.
- `fake_sensitive`
- `sensitive_content`
- `fetch_sensitive`
2. Search for something.
3. Switch to the audio media type so that the row layout of the audio track is shown.
4. Play a blurred track. See that the global audio player is also blurred.
5. Open the blurred track and opt to unblur it.
6. Go back to search results. The global audio player will now be unblurred.
<details> …
=> Add blurring to the global audio player

catalog/dags/common/popularity/sql.py, catalog/dags/popularity/refresh_popularity_metrics_task_factory.py
#2841 modified the popularity and data refreshes to drop and recreate the popularity constants matviews, rather than refreshing them. This was done to address the matview refresh timing out, since a similar strategy had previously worked for the media matviews.
I neglected to realize that this is not possible for the _constants_ matviews, because regular provider DAGs now calculate popularity at ingestion and use this view to do so. Consequently, provider DAGs are failing while the view is being rebuilt.
This PR reverts the changes to drop and recreate the popularity constants matview. Notably, this means we may start to see issues with the refresh taking a very long time again. **The popularity steps are about to be removed from the data refresh …
=> Revert changes to drop and recreate popularity constants views

docker-compose.overrides.yml, docker/es/env.docker, justfile
Related to https://github.com/WordPress/openverse/commit/6cdfb59acf8bfe3aa3dc5528e8846e6ae2d62a4f
I noticed that Elasticsearch was happily using 60% of my system RAM. At one point today this actually caused an OOM issue in my kernel during a `just recreate` run, despite having 32 GB RAM! The overrides file does _not_ work for me (ES just crashes instead of staying within the limit). However, I remembered from the work I recently did to fix our production ES 8 cluster's heap configuration, that ES will respect heap limits passed as JVM args. Therefore, we can get rid of the overrides file (which we didn't really like any way) and use the heap limits. I've set them to half a gig, which should be _just fine_ for local testing.
Checkout this branch and run `just down && just up` and confirm …
=> Fix Elasticsearch memory hogging the right way

catalog/tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Fixes CI failure on Dependabot PR #2869
This is a separate PR and not committed directly to the Dependabot PR #2869 because I don't really know if this is the right fix. Note that the value is set to `False` because [that is the default](https://github.com/apache/airflow/pull/32709#issuecomment-1651437026).
As this PR aims to fix CI failures, CI should pass.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add missing argument in `Pool.create_or_update_pool`

.github/workflows/ci_cd.yml, documentation/meta/ci_cd/jobs/documentation.md
Fixes #2900 by @dhruvkb
Fixes an issue with #2647 which was causing the documentation publishing step to fail because a repo was being checked out inside of another repo (namely the automation used during the CI steps was being checked out to `<workspace>/automation-checkout` when the actual `gh-pages` branch was being checked out to `<workspace>` itself).
~~I'm not sure the best way to test this, I'll follow up with a small doc change which should at least trigger the preview, but we may need to wait for a legitimate docs change in order to see if it is successful or not.~~
I've added a legitimate documentation change, so hopefully we'll be able to see the results once this is merged.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidel …
=> Use a temp checkout path for automation when building docs

catalog/dags/common/popularity/constants.py, catalog/dags/common/popularity/sql.py, catalog/dags/common/sql.py, catalog/dags/data_refresh/dag_factory.py, catalog/dags/database/batched_update/batched_update.py, catalog/dags/database/recreate_popularity_calculation_dag_factory.py, catalog/dags/popularity/refresh_popularity_metrics_task_factory.py, catalog/tests/dags/common/loader/test_sql.py, catalog/tests/dags/common/popularity/test_sql.py, docker/upstream_db/0004_openledger_image_view.sql, docker/upstream_db/0007_openledger_audio_view.sql
Fast fix for urgent production issue.
⚠️ This is a very long PR description, but the goal was for the testing steps to be extremely thorough so it is easy for others to test. The changes are not particularly complicated, but we **do** want to be exhaustive in testing. Please ping me if you need any assistance at all. ⚠️ 
Note: throughout the PR description I sometimes refer only to the tables and views for image for simplicity, but the same is true for audio. This PR's code changes affect both media types, and both should be tested.
Currently we have an `image_popularity_metrics` table (that contains information like the name of the `metric` field in the `meta_data` column to use for calculating pop scores), and an `image_popularity_constants` **view** which contains all the information …
=> Remove popularity constants view

documentation/frontend/guides/index.md, documentation/frontend/guides/translate.md, documentation/frontend/reference/i18n.md, documentation/frontend/reference/index.md, frontend/.gitignore, frontend/nuxt.config.ts, frontend/src/locales/scripts/create-wp-locale-list.js, frontend/src/locales/scripts/get-translations-status.js, frontend/src/locales/scripts/get-validated-locales.js, frontend/src/locales/scripts/locale-fallback.json, frontend/src/plugins/vue-i18n.ts, frontend/typings/nuxt__types/index.d.ts
Fixes #2591 by @zackkrida 
Fixes #2885 by @dhruvkb 
Fixes #2886 by @dhruvkb 
This PR
- fixes a bug where untranslated locales would always be blank
- fixes a bug where locales without ISO would be dropped from the application
- fixes a bug where the `translated` field in the locale was missing in the TS type
- removes fields from `wp-locales.json` that were not used anywhere
- simplifies some code and adds logging in the locale management scripts
- implements fallback locales, with Español covered as an example
- adds documentation for the translation upload, download pipeline (to clarify the meaning of the Node scripts)
- adds documentation about how to use fallback locales
1. Delete all i18n files.
- `frontend/src/locales/*.json`
- …
=> Simplify, improve and document the i18n pipeline

api/api/utils/watermark.py
Fixes tests of #2874.
This PR removes the `FreeTypeFont.getsize_multiline()` function from the watermark script in favor of [`ImageDraw.multiline_textbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.multiline_textbbox). It was already deprecated and is now being removed in the last [Pillow version](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#font-size-and-offset-methods). Thanks to examples in python-pillow/Pillow#6655 I learned how to do the replace.
In `main`, run the tests for the watermark endpoint and observe the warning:
>  /api/api/utils/watermark.py:203: DeprecationWarning: getsize_multiline is deprecated and will be removed in Pillow 10 (2023-07-01). Use ImageDraw.multiline_textbbox instead.
```sh 
just …
```
=> Replace deprecated function from Pillow

ingestion_server/Pipfile, ingestion_server/Pipfile.lock
Fixes #2772 by @dhruvkb 
Dependabot creates PRs for `pycodestyle`, but `pycodestyle` is already included by `flake8` so it can safely be removed.
I just used `just ingestion_server/test-local` which went fine. It would be great for someone who is fully set up with frontend dependencies to also confirm that linting works.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> remove pycodestyle from ingestion server pipfile

catalog/dags/data_refresh/data_refresh_task_factory.py
Fixes #2725 by @AetherUnbound 
This PR adds a `none_failed` trigger rule to the `generate_index_suffix` task in the primary data refresh DAG. It ties together the old index retrieval and old index deletion tasks so both are either run or skipped together. It also adds an `ensure_downstream_runs` task at the end of the data refresh task group to ensure that the task state from promote is reflected downstream (rather than the task state from `trigger_delete_index` which can now be skipped).
**Before**
**After** _(ignore the failures, they're expected and should propagate all the way through to the end of the DAG)
See this comment below: https://github.com/WordPress/openverse/pull/2727#issuecomment-1656160714
When these steps are run on this branch, both the `get_current_index` and …
=> Ensure data refresh can still be run if no initial index exist

frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue, frontend/src/components/VAudioTrack/layouts/VGlobalLayout.vue, frontend/src/composables/use-sensitive-media.ts
Fixes #2927 by @obulat
This PR wraps usages of the `useSensitiveMedia` composable with `computed` so that the value of `shouldBlur` is updated with the prop `audio` changes.
Try to reproduce the problem in the linked issue. If you are unable to, consider the issue fixed.
<details>
```
Version 1.1
Suite D4700 …
```
=> Wrap usage of `useSensitiveMedia` with `computed`

frontend/test/playwright/visual-regression/components/global-audio-player.spec.ts, packages/eslint-plugin/src/rules/no-unexplained-disabled-test.ts, packages/eslint-plugin/test/rules/no-unexplained-disabled-test.spec.ts
Related to https://github.com/WordPress/openverse/issues/3009
Skip the test mentioned in the issue.
To do so, however, I had to fix a bug in the ESLint rule. The regex was too imprecise and would match skipped test nested inside of blocks. This caused the error to occur on the top-most block that contained any skipped block, which is not the intended behaviour. The fix was relatively simple in the end, just to refine the regex to only match the start of the source code block.
CI should pass. Confirm the bug is fixed in the eslint plugin by making changes to the unit tests for the rule and trying to break it further. …
=> Skip flaky global audio visual regression test

frontend/nuxt.config.ts
Fixes #2986 by @obulat 
This PR filters locales by the presence of the `iso` field instead of the `code` field, because the ISO is used to generate SEO links and sitemaps etc.
0. Run the dev server.
1. Observe the number of languages in the locale chooser (it should be ~200).
2. Observe the presence of languages like Emoji and भोजपुरी (they should appear).
3. Check out the PR and restart the dev server.
4. Observe the number of languages drop to ~160.
5. Observe that Emoji and भोजपुरी have disappeared.
6. Observe that warning from `@nuxt/i18n` are not being logged.
<details>
```
Version 1.1 …
```
=> Filter languages by presence of ISO

api/Pipfile, api/Pipfile.lock
Fixes #2895 by @sarayourfriend 
Removed `requests-oauthlib` from api dependencies.
Check out the branch and run api tests:
```
$ just dc build web
$ just api/test
```
Try api calls locally to be sure, such as `curl "http://localhost:50280/v1/images/?q=test"`
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
=> Remove `requests-oauthlib` from api dependencies

documentation/meta/monitoring/runbooks/index.md, documentation/meta/monitoring/runbooks/nuxt_2xx_under_threshold.md, documentation/meta/monitoring/runbooks/nuxt_5xx_above_threshold.md, documentation/meta/monitoring/runbooks/nuxt_request_count.md
Related to WordPress/openverse-infrastructure#606 by @dhruvkb
This PR adds runbooks for the alarms added in the above linked PR.
Read the documentation pages from the preview site.
<details>
```
Version 1.1
Suite D4700 …
```
=> Initialise runbooks for Nuxt 2XX/5XX alarms

api/api/controllers/search_controller.py, api/api/utils/search_context.py, api/api/views/media_views.py, api/test/media_integration.py, api/test/test_audio_integration.py, api/test/test_image_integration.py, api/test/unit/utils/test_search_context.py
Fixes #2926 by @sarayourfriend 
This PR populates the sensitivies for single result view by manually defining the `retrieve` view in the `MediaViewSet` and extending the `SearchContext` to work for single results too.
1. Check out the branch and run the dev server `just api/up` (and `just api/init` if you haven't already)
0. Find a media item that has some sensitive content. To do so, add the the query param `unstable__include_sensitive_results=true` to the URL.
1. Open the same media's detail page, you should see the same sensitivities as the results page.
2. Report some media item as mature. Do the same for this media item. You should see identical sensitivity in the search resuls and single result pages.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a- …
=> Populate sensitivities for single result view

frontend/src/modules/prometheus.ts, frontend/src/plugins/ua-parse.ts, packages/eslint-plugin/src/configs/import.ts, packages/eslint-plugin/src/configs/index.ts, packages/eslint-plugin/src/configs/typescript.ts, tsconfig.base.json
Fixes #3007 by @sarayourfriend 
Enables the import plugin's typescript config and does some additional configuration to improve the relationship between TypeScript and ESLint. In some cases, we disable ESLint rules because TypeScript already handles them. In others, we disable TypeScript checks because ESLint handles them more flexible (i.e., still allows the project to build, which is useful during development, but still shows an error on linting).
Checkout the branch and run `pnpm install && pnpm run eslint` and confirm linting is working. Try something like importing or declaring an unused variable in a frontend file and confirm that you get an ESLint error when running `pnpm run eslint`, but that you do not see a TS error about it when running `just p frontend types`.
- [N/A] I added …
=> Deduplicate checks between ESLint and TypeScript

api/api/migrations/0052_relational_fields.py, api/api/models/audio.py, api/api/models/media.py, api/api/serializers/media_serializers.py
Fixes #2625 by @AetherUnbound 
Updates API help strings to reflect "sensitive" terminology, rather than "mature" legacy terms.
Get the local environment up and running on this branch, then run `just api/test`, and do smoke testing to ensure the API is still running ok (e.g. `curl "http://localhost:50280/v1/images/?q=test"`). 
<details>
```
Version 1.1
Suite D4700 …
```
=> Replace "mature" with "sensitive" in api help strings

api/api/serializers/image_serializers.py, api/api/serializers/provider_serializers.py
Fixes #3034 by @obulat
This PR replaces `ReadOnlyField`s with `SerializerMethodField`s that return constant values for values that never change and are not derived from models:
`OEmbedSerializer`: `version`, `type`
`ProviderSerializer`: `logo_url`
This makes the documentation a little bit clearer and fixes the warnings in logs.
Currently, `logo_url` type is given as `string`, but it always returns `null`. The updated version shows `string or null`. I tried setting it to "only null", but spectacular still throws a warning that it couldn't get the type of the value. `string or null` is more accurate than `string`.
Currently, the documentation says that these values are "default", making it seem like a different value is also possible.
In this PR, the documentation says "Value: 1.0", making …
=> Correctly set up constant fields in API responses

documentation/meta/index.md, documentation/meta/maintenance/elasticsearch_cluster.md, documentation/meta/maintenance/index.md
Related to #2744 which identified a missed step in the ES cluster upgrade process.
I realised there was not a single place where ES cluster maintenance was comprehensively documented. This document includes everything I know about our ES cluster, including how to make configuration changes.
Docs preview: https://docs.openverse.org/_preview/3032/meta/maintenance/elasticsearch_cluster.html
Read the new document and identify any areas that need clarification. Remember the audience is the Openverse maintainers with infrastructure access, so any of the @WordPress/openverse-maintainers with the responsibility for infrastructure maintenance should be able to understand and employ this document.
- [N/A] I ran the DAG …
=> Add Elasticsearch cluster maintenance documentation

catalog/dags/providers/provider_dag_factory.py
Fixes #2917 by @stacimc 
Configures DAG conf options as `params` on the DAG. This gives us the nice form in the UI when triggering a DAG, and adds documentation for the available options. It's also necessary, as the Airflow UI no longer has a `trigger DAG with conf...` option allowing triggering the DAG with an arbitrary conf dict, so we need this in order to be able to use the options.
We need to test that the conf options all still work. I used Wikimedia to test. I'm providing the exact conf options I used for convenient testing, but you could also simulate a more 'realistic' workflow by failing a task and getting the next `query_params` to use from the logs (this is how I got the test data below).
`date`:
* Click the `Trigger DAG` button in the UI and it will automatically open the …
=> Configure conf options as parameters

api/api/controllers/search_controller.py
Fixes #3043  by @obulat 
Replace the deprecated body parameter and using individual parameters.
run `just api/test test/unit/controllers/test_search_controller.py` on terminal. Results are below and passed all the test. 
`test/unit/controllers/test_search_controller.py: 125 warnings
/venv/lib/python3.11/site-packages/elasticsearch_dsl/search.py:712: DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
es.search(index=self._index, body=self.to_dict(), **self._params).body,
test/unit/controllers/test_search_controller.py: 237 warnings
/venv/lib/python3.11/site-packages/elasticsearch_dsl/search.py:712: DeprecationWarning: The 'body' parameter is deprecated and will be removed in a future version. Instead use individual …
=> Replace deprecated body in the ES requests with individual parameters

api/api/serializers/image_serializers.py, api/api/views/image_views.py, api/test/test_image_integration.py
This PR prevents the oEmbed endpoint from crashing when an invalid UUID is encountered. The UUID is now validated in the serializer, leading to DRF's `ValidationError` being raised if invalid. This is handled by DRF and converted to a 400 Bad Request reponse.
Earlier, Django would validate the UUID and raise a Django core `ValidationError` which does not map to a 400 response, and bubbles uncaught till it exits the worker.
1. Visit the oEmbed endpoint `http://localhost:50280/v1/images/oembed/?url=` with the following `url` values:
- valid and existing UUID like `2982c0bf-9c26-4543-a712-4d50a117ded8`
- URL containing valid and existing UUID like `https://abc.xyz/def/2982c0bf-9c26-4543-a712-4d50a117ded8`
- valid but non-existent UUID like …
=> Transfer UUID validation inside serializer

api/Pipfile, api/Pipfile.lock
Fixes #2305  by @krysal 
Remove boto3 dependency from api folder because api doesn't use API bucket.
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> Remove boto3 dependency

frontend/src/components/VErrorSection/VErrorSection.vue, frontend/src/components/VErrorSection/meta/VErrorSection.stories.mdx, frontend/src/components/VExternalSearch/VExternalSearchForm.vue, frontend/src/components/VFooter/VFooter.vue, frontend/src/components/VImageCell/meta/VImageCell.stories.mdx, frontend/src/components/VSearchResultsGrid/VAudioCollection.vue, frontend/src/components/VSearchResultsGrid/VImageGrid.vue, frontend/src/constants/errors.ts, frontend/src/middleware/search.ts, frontend/src/middleware/single-result.ts, frontend/src/pages/audio/_id/index.vue, frontend/src/pages/image/_id/index.vue, frontend/src/pages/search.vue, frontend/src/pages/search/audio.vue, frontend/src/pages/search/image.vue, frontend/src/stores/media/index.ts, frontend/src/stores/media/related-media.ts, frontend/src/stores/media/single-result.ts, frontend/src/stores/provider.ts, frontend/src/types/fetch-state.ts, frontend/src/utils/errors.ts, frontend/test/unit/specs/stores/media-store.spec.js, frontend/test/unit/specs/stores/provider.spec.js, frontend/test/unit/specs/stores/single-result-store.spec.js
Fixes #632 by @sarayourfriend
This PR updates the `FetchState` to always use the `FetchingError` instead of `NuxtError`|`string`|`FetchingError` for the error object. 
`FetchingError` interface provides more information about the error, including the response status code, the string code of the error from axios, the kind of request (single result, search, provider or the related media), and additional details such as the item id.
This interface makes it easier to show the timeout error pages on `SERVER_TIMEOUT` or `ECONNABORTED` errors.
`FetchState` was made a generic to allow the use of `string` and `NuxtError` for the `fetchingError` value. This PR removes this to make fetchState simpler.
To simulate the server timeout, lower the default timeout to 30: …
=> Show timeout errors on the frontend

.github/workflows/renovate.yml
Currently, our Renovate workflow runs every 15 minutes, including on all forks of the main repository. This PR prevents the action from running on forks.
Originally reported by @ngken0995
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```
=> Disable running Renovate on forks

documentation/justfile, documentation/projects/planning.md, documentation/projects/templates/implementation_plan.md, documentation/projects/templates/index.md, documentation/projects/templates/project_proposal.md
This PR
- adds recipes to create project proposals and implementation plans from templates
- updates templates to allow names, hyperlinks and dates to be automatically injected into them
- updates documentation to recommend these recipes to create proposals
Try the recipes `just documentation/init-project` and `just documentation/create-ip`  and check that they work as described in the docs.
<details>
```
Version 1.1
Suite D4700 …
```
=> Create recipes to generate project planning docs

frontend/src/components/VSafeBrowsing/VSafeBrowsing.vue, frontend/src/locales/scripts/en.json5, frontend/src/pages/sensitive-content.vue
Fixes #2550 by @dhruvkb
This PR adds the page for explanation about sensitive content and our filtering techniques.
1. Visit the page directly at `/sensitive-content`.
2. Go to `/preferences` and turn on `sensitive_content` and `fake_sensitive` flags.
3. Make a search query.
4. Find a blurred result, click to open it.
5. Click the link to "Learn more". You should be taken to the `/sensitive-content` page again.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Create the page for sensitive content explanation

api/api/controllers/search_controller.py, api/api/views/media_views.py
Fixes #3149 by @obulat
This PR changes the related endpoint: now, instead of using `MoreLikeThis` query, it gets the title and the tags of the media, and searches for title/tag matches.
We use `or` between the title and tag queries (ES's should, not must) to make sure that there's a match (even if there's no match by title or no match by tags alone). I'm not sure what will happen if both are blank. What happens now?
The related no longer checks for `sensitivities` because it filters out the sensitive and mature results.
It also now returns 10 as the result_count because it does not make sense to return the full result count: there's no way to get other pages of the results, and this piece of information is not meaningful.
On main, the `/related` endpoint makes 3 ES requests. One to get …
=> Use simple query for related

api/api/templates/robots.txt, api/conf/urls/__init__.py
- Added robots.txt file
Fixes #3060 by @dhruvkb 
- Added robots.txt file to the api/templates folder
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> added robots.txt for API endpoints

api/api/controllers/search_controller.py, documentation/meta/monitoring/cloudwatch_logs/index.md
Fixes #3169 by @CodeAnk2829
`api/controllers/search_controller` imports an exception (`RequestError`) that does not exist causes an unexpected error. This PR fixes the issue by replacing `RequestError` with `BadRequestError`.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> fix: Replace RequestError with BadRequestError

api/api/controllers/search_controller.py, api/api/views/media_views.py
Fixes #3149 by @obulat
This PR:
- uses the filtered index for `related` search
- removes the search context building. Search context allows us to return sensitivities for the media items, but since we only use the filtered index, all sensitivities are empty anyways.
~~removes the `mature`: False filter since we use the filtered index~~ (removing this filter would show the user-reported mature items, so I put it back)
- removes `creator` from the fields that are used in the `MoreLikeThis` query
Check that the related endpoints (the `related` in image and audio results) work as expected.
To see this work visually, you can run the frontend Nuxt app using the local API:
1. Set the API_URL variable in the `frontend/.env`: `API_URL=http://0.0.0.0:50280/`
2. Run the API using `just up`.
3. Run …
=> Simplify the related search

api/api/controllers/search_controller.py
This PR changes dot access for `creator` field on `Hit` to `getattr` to account for ES hits (notably from Wikimedia in my testing) that do not have the creator field set.
<details>
```
Version 1.1
Suite D4700
have …
```
=> Handle instances where media items do not have creator

.github/workflows/ci_cd.yml, automations/python/workflows/set_matrix_images.py, docker-compose.yml, documentation/frontend/reference/index.md, documentation/frontend/reference/nginx.md, frontend/Dockerfile, frontend/Dockerfile.nginx, frontend/nginx.conf.template, frontend/nuxt.config.ts, frontend/test/playwright/utils/analytics.ts, justfile
Related to #536 by @sarayourfriend 
Related to #2996 by @obulat
Related to #2993 (does not close because we also need to deploy the nginx container to live environments)
The issue will only be fixed, if we take this approach, after adding the new service to the live deployments.
Adds a new Nginx image for us to publish and use as a reverse-proxy to the frontend service. This enables two things:
1. Per-request logging in a format identical to the API logging. There are improvements we can make here with respect to configuration sharing, but that adds complexity that we can push off for now while we validate this approach.
2. Plausible request proxying that is testable locally.
This PR is still a draft because I need to add building and publishing the image to CI.
Run `just frontend/up` …
=> Add frontend nginx container for logging and plausible proxying

catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py, catalog/tests/dags/maintenance/test_pr_review_reminders.py
This PR fixes the PR review reminder DAG for the case where a PR depends on a PR 3 levels from main (creating a chain of `branch_beyond -> branch_tertiary -> branch_secondary -> main`). This case can be seen (at the current time) in #3162 which depends on #3161 which depends on #3143 which is pointed at main. For some reason, that many levels out from `main`, there's still some branch protection information but nothing which has the required pull request reviews.
Run the PR review request reminder DAG locally and see that it succeeds (whereas current runs on `main` are failing).
Tests should also pass!
<details>
```
Developer …
```
=> Fix PR review reminder DAG for case where base branch is 2+ levels deep

frontend/src/components/VAudioDetails/VRelatedAudio.vue, frontend/src/components/VImageCell/VImageCell.vue, frontend/src/components/VImageDetails/VRelatedImages.vue, frontend/src/components/VSearchResultsGrid/VAudioCollection.vue, frontend/src/components/VSearchResultsGrid/VAudioList.vue, frontend/src/components/VSearchResultsGrid/VAudioResult.vue, frontend/src/components/VSearchResultsGrid/VImageGrid.vue, frontend/src/pages/search/audio.vue, frontend/src/pages/search/image.vue, frontend/src/types/analytics.ts, frontend/src/types/external-source.ts, frontend/src/types/result.ts, frontend/test/playwright/e2e/all-results-analytics.spec.ts, frontend/test/unit/specs/components/v-image-grid.spec.js
Related to #3149 by @obulat
The `SELECT_SEARCH_RESULT` event has a `relatedTo` property that shows whether a search result or a related media was clicked. However, it is not possible to get a ratio of related results to search results because all `relatedTo` identifiers are different. So, you can see how many selected images were related to a particular image, but not "what percentage of clicked images was from the search results and what percentage was from the related section".
This PR adds a `kind` property to the `SELECT_SEARCH_RESULT` event that will allow us to see whether a search result, a related result, or (soon) an additional search view collection result was clicked.
It also renames the props for Image grid to match the props of the audio collection.
Run the app and click on …
=> Add result kind to the `SELECT_SEARCH_RESULT` event

frontend/src/components/VMediaInfo/VMediaTags.vue, frontend/src/components/VTag/VTag.vue, frontend/src/components/VTag/meta/VTag.stories.mdx
Fixes #2773  by @obulat 
Created a VTag component for tags to be clickable. It is visible on the single result page when the `additional_search_views` flag is on.
Added by @obulat: 
Go to `/preferences` and turn on the `additional_search_views` flag. Then, open a single result page. You should see "clickable" tags that match the Figma designs. The tags don't have the correct `href` yet, so nothing happens when you click on a tag.
Also, run Storybook (`just frontend/run storybook`) and check the `VTag` story.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_ …
=> Create VTag component

api/api/views/oauth2_views.py, api/test/test_auth.py
Fixes #2374 by @krysal
This PR fixes the method resolution order of the token `APIView` so that the exception handler will be invoked and a 405 Method Not Allowed response will be sent. When the MRO is incorrect the exception is not handled and results in a 500 Internal Server Error.
1. Make a GET request to the `/v1/auth_tokens/token/` endpoint.
2. Receive a 405 response.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix MRO to return 405 for unsupported methods

api/api/docs/base_docs.py
Fixes #3208 by @AetherUnbound
Just removed the cURL instructions from every endpoint:
```
just api/up
```
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> Remove unnecessary information from API docs

.github/workflows/new_issues.yml
Fixes #445  by @obulat 
Replace `project` with ` 🧭 project: thread, 🧭 project: proposal, 🧭 project: implementation plan` because there is a special board for the Projects and not in the backlog.
- [N/S] I ran the DAG documentation generator (if applicable).
<details>
```
Version 1.1
Suite D4700 …
```
=> Add correct label to exclude

frontend/src/data/media-provider-service.ts, frontend/src/stores/provider.ts, frontend/test/unit/specs/data/media-provider-service.spec.js, frontend/test/unit/specs/stores/provider.spec.js
Fixes #3184 by @sentry-io
This PR logs a warning and returns `[]` from `getProviderStats` if the `data` property in the `/stats` endpoint returns undefined. This is only a fix for the frontend, and API should implement a fix to never returns undefined from `/stats` endpoint.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Hotfix for `undefined` in Nuxt provider data

catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, catalog/tests/dags/providers/provider_api_scripts/resources/metropolitan_museum_of_art/sample_additional_image_data.json, catalog/tests/dags/providers/provider_api_scripts/resources/metropolitan_museum_of_art/sample_response.json
The Metropolitan DAG failed in production trying to ingest an image with url "https://images.metmuseum.org/CRDImages/dp/original/1972.173 RECTO.jpg"
Urlencodes spaces in Metropolitan urls, as this is a valid url.
I noticed and opened #3263 while doing this. See discussion on that issue for why I don't think we should work on that now.
Should be covered by unit tests, but if you want to manually test you can run the metropolitan DAG locally. Set the ingestion date to `2023-10-25` in the conf options to test the day that caused a failure in prod.
<details>
```
Version 1.1 …
```
=> Encode spaces in metropolitan urls

documentation/general/contributing.md
Closes https://github.com/WordPress/openverse/issues/3266
=> Replaced http link with https in contributor.md

docker-compose.yml, frontend/nginx.conf.template
Related to #3274 (does not fix because we also need to deploy the new setting in live environments)
Implements the fix described in the linked issue.
`frontend_nginx` should still work locally and make requests to local plausible. Follow testing instructions in https://github.com/WordPress/openverse/pull/3108 to confirm this.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Add ability to configure Nginx DNS resolver

api/api/controllers/search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py, documentation/api/reference/search_algorithm.md
Fixes #3243 by @obulat
Instead of using `elasticsearch_dsl` for creating the search query, this PR uses a simple dictionary for the 4 query clauses: `filter`, `must_not`, `must` and `should`. This dictionary is then used to create a much cleaner query which is almost identical in function to the existing query. 
The biggest difference is that the url parameter queries (license, aspect ratio, width, extension, etc.) are actually filters. They remove all of the non-matching items from the results, instead of simply assigning them a lower score. Not calculating the score should also in theory make the filters faster.
To make these queries similar to the production queries, I checked "Hide content" in the Flickr ContentProvider object form in Django admin. This should dynamically add this …
=> Simplify search query

api/api/controllers/search_controller.py, api/conf/settings/elasticsearch.py
Today we observed an increase in 5XX errors and unhealthy hosts on the API due to ongoing ES response time issues which are being investigated with #3197. Since we have been unable to determine a cause (yet) of the periodic increases in ES response time, I believe the best mitigation approach in the short term is to **temporarily** increase our timeouts and retries from 10s to 12s and 1 to 2 respectively. The spikes we see in response time are up to 30s, so hopefully this will give the requests enough breathing room to complete without raising 5XX errors.
<details>
```
Version 1.1 …
```
=> Hotfix: Increase ES timeout and retries

api/api/utils/watermark.py, api/test/unit/views/test_image_views.py
Fixes #1234  by @obulat 
<details>
```
Version 1.1
Suite D4700 …
```
=> Watermark exception

api/api/models/image.py
Related to #3310 by @sarayourfriend (leaving the issue open to investigate why the check action didn't catch this)
In https://github.com/WordPress/openverse/pull/3022 we updated the abstract mature media model's help text, and that PR already included a migration to change the help text on the `MatureImage` model. However, we accidentally missed the model-code side change of that, and the model still had the old copy defined. This was causing a migration to revert the help text back to the term "mature". Changing the help text to match the previous migration introduced in the referenced PR, removes the dangling migration.
This PR doesn't result in any migrations, therefore, so there's no care needed for deployment.
Run `just api/dj makemigrations` and confirm the dangling migration that …
=> Fix accidental copy change causing dangling migration

.pre-commit-config.yaml, frontend/package.json, frontend/tsconfig.json, package.json, packages/eslint-plugin/package.json, pnpm-lock.yaml
No issue for this update
This PR updates the TypeScript version to the latest stable, v5.2.2.
I removed `typeRoots` setting from `tsconfig` because with it, type checks were failing with 
```
error TS2688: Cannot find type definition file for '@nuxt/types
│   The file is in the program because
│     Entry point of type library '@nuxt/types' specified in compilerOptions
│ error TS2688: Cannot find type definition file for '@nuxtjs/i18n
│   The file is in the program because
│     Entry point of type library '@nuxtjs/i18n' specified in compilerOptions
│ error TS2688: Cannot find type definition file for '@pinia/nuxt
│   The file is in the program because
│     Entry point of type library '@pinia/nuxt' specified in compilerOptions
│ error TS2688: Cannot find type definition file for …
```
=> Update TypeScript to v5.2.2

documentation/catalog/guides/adding_a_new_provider.md
This PR updates the new provider docs to use the correct just commands.
Fixes #2801 by @stacimc
This PR updates the new provider docs to use the correct just commands . Added catalog in the command
- [] My code follows the established code style of the repository.
<details>
```
Version 1.1
Suite D4700 …
```
=> Upated new-provider docs to use correct `just` commands

.gitignore
This PR ignores `.iml` files inside the project that are automatically created
by IntelliJ when configuring the monorepo as a multi-module project.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```
=> Ignore `.iml` files created by JetBrains inside the project

api/api/controllers/elasticsearch/helpers.py, api/api/controllers/search_controller.py, api/api/utils/search_context.py
Follow up on #3300
#3300 added logging of the time it takes for the ES requests, but the `search_query` parameter is always logged as `None` because the parameter was passed as a non-keyword arg. This PR fixes that and renames the param to `es_query`.
Run the app and perform several search requests (including search, related, stats). You should see the correct value for `es_query` in the logs.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix the "search query" in the time took logs

.github/workflows/ci_cd.yml
Fixes #3310 by @sarayourfriend 
This PR updates the migration check in CI to properly raise errors in case of migration issues.  The flag `--merge` overwrites the `--check` behaviour. Also `--noinput` is redundant.
Just passing `--check` checks for both cases:
- model differs from migrations and a new migration is needed
- two leaf migrations exist and a merge migration is needed
0. Check out the `main` branch to the point where it has a migration issue: b2a397015321a13b22be9df17f2e8447c65d7bf2
1. Run `just api/dj makemigrations --check --noinput --merge`. See no error.
2. Run the fixed command `just api/dj makemigrations --check`. See the expected error.
<details> …
=> Remove `--merge` and `--noinput` flags in Django migration check

api/api/controllers/elasticsearch/helpers.py, api/api/controllers/elasticsearch/related.py, api/api/controllers/search_controller.py, api/api/views/media_views.py, api/test/factory/es_http.py, api/test/media_integration.py, api/test/test_dead_link_filter.py, api/test/test_image_integration.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
Fixes #3306 by @obulat
This PR refactors the way related query is created, using more low-level queries to make them less nested.
The main changes for this PR are within the `elasticsearch/related.py` file. All other changes are just moving the functions to a different file. The `related` function is moved from `search_controller` module to a separate file within `elsticsearch` folder, and some other common functions for pagination to `elasticsearch/helpers.py` file to make the files easier to read.
After opening this PR, I also checked the queries logged by slowlog: all of the queries logged in the recent hours were related queries. 
Using the `simple_query_string` for the list of tags is not performant. This PR converts the query to use the terms query for tags. It will mean that the …
=> Simplify related query to remove nesting and make more performant

api/test/media_integration.py
Fixes the failure of `related` endpoint integration tests when the related items are selected by creator (when the title or tags query do not return any results). For an example see this test run on main (attempt 1): https://github.com/WordPress/openverse/actions/runs/6806564887/attempts/1
This PR adds a check to see if the result is by the same creator (in addition to the checks that there are common words between the related result and the main item)
Marking this as "high" priority because without it, the API tests might be flaky.
The CI should pass and the changes should make sense.
<details>
``` …
```
=> Fix API integration test for the related endpoint

documentation/ingestion_server/guides/index.md, documentation/ingestion_server/guides/migrate.md, documentation/ingestion_server/guides/troubleshoot.md, documentation/ingestion_server/guides/upgrade.md, documentation/ingestion_server/reference/index.md, documentation/ingestion_server/reference/task_api.md
Fixes #3314 by @dhruvkb
This PR documents the process for upgrading and migrating ES indices without API downtime. It also adds documentation regarding the ingestion server `/task` API that the process uses and also documents the process for stopping a reindex job midway in staging.
Read the updated documentation.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Add a guide for upgrading and migrating ES indices

docker-compose.yml, justfile
Docker Compose performs all env var interpolation in the full `docker-compose.yml` file regardless of which services are being started. When using a recipe like `api/init` (that does not refer to the root `justfile`), the vars are not set and Docker Composes raises warnings for missing `HOST_NETWORK_ADDRESS`.
This PR
- sets a default for the `HOST_NETWORK_ADDRESS` env var to suppress warnings raised by Docker Compose
- moves the env var export in the root to the Docker section
You should no longer see errors like the following when running `api/init`.
<details>
```
Version 1.1 …
```
=> Use a default for `HOST_NETWORK_ADDRESS` to hide warnings

frontend/src/components/VSkeleton/VGridSkeleton.vue
Fixes #3268 by @Ashhar-24
As  mentioned in the issue #3268 that `VGridSkeleton` uses `this` in the props' `default` function and this causes a build error in Vue 3.
So I have moved default element count to the `setup` function and the `numElems` is replaced with `elementCount` in the `template`.
Note: if this PR is ready after #3322 is merged, this PR needs to remove the TODO from `packages/eslint-plugin/src/configs/vue.ts`:
```
// TODO: disable after https://github.com/WordPress/openverse/issues/3268 is fixed
"vue/no-deprecated-props-default-this": "off",
```
<details>
```
Version 1.1
Copyright (C) …
```
=> Remove `this` from `VGridSkeleton` props `default`

api/api/controllers/elasticsearch/related.py, api/test/unit/controllers/elasticsearch/test_related.py
Follow up for #3307
The related query uses the `terms` query to match the tags. It was, however, using a `text` field (`tags.name`) instead of a `keyword` field(`tags.name.keyword`), which is bad for performance[^1]. This PR fixes it by adding the `.keyword` suffix to the query. The tests are updated accordingly.
[^1]: [Why you should avoid using `text` fields for `term` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html)
Setting the priority to high because this needs to be deployed together with the other changes to the related query in #3307.
CI passing is a good indication that the change is correct because we have the tests for the related endpoint.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project# …
=> Use the `keyword` field for tags in related query

catalog/dags/common/loader/sql.py, catalog/dags/common/sql.py, catalog/dags/common/storage/columns.py, catalog/dags/common/storage/db_columns.py, catalog/dags/database/batched_update/batched_update.py, catalog/dags/database/batched_update/constants.py, catalog/dags/database/delete_records/constants.py, catalog/dags/database/delete_records/delete_records.py, catalog/dags/database/delete_records/delete_records_dag.py, catalog/dags/maintenance/add_license_url.py, catalog/dags/retired/database/terminate_long_queries_workflow.py, catalog/tests/dags/database/test_batched_update.py, catalog/tests/dags/database/test_delete_records.py, catalog/tests/dags/test_dag_parsing.py, catalog/tests/test_utils/sql.py, docker/upstream_db/0003_openledger_image_schema.sql, docker/upstream_db/0006_openledger_audio_schema.sql, documentation/catalog/reference/DAGs.md
Fixes #3257 by @stacimc 
This PR does a couple of things:
* Adds `deleted_audio` and `deleted_image` DB tables to the Catalog. These tables contain all the same columns as their respective media table, plus two new columns:
* `deleted_on`: timestamp for when the record was "deleted" (ie added to the table)
* `deleted_reason`: small string description for why the record was deleted (eg "deadlink")
* Adds a very simple DAG called `delete_records` that takes as params a `media_type`, `select_query`, and `reason`. Then it:
* Selects all records from the given media table matching the `select_query`, and creates a new row in the corresponding `deleted_media` table that copies all fields over exactly, and adds the `deleted_on` timestamp and sets the `reason` for `deleted_reason`
* If …
=> Add DAG for filtering archived providers in catalog

api/conf/settings/rest_framework.py
Anonymous throttling is currently broken and only works by chance. Given our live API configuration, where we always have X-Forwarded-For, and do not have `NUM_PROXIES` set, DRF's default `get_ident` implementation is using the entire X-Forwarded-For header to build the client identifier. This is a problem because X-Forwarded-For will always include three additional IPs for the reverse proxies in our live environment: Cloudflare's proxy, the AWS load balancer and finally Nginx (which handles static files). The resulting X-Forwarded-For header will look something like this once it reaches Django: `<client IP>, <Cloudflare IP>, <load balancer IP>, <Nginx IP>`.
The most problematic of these are really the load balancer and the nginx IP, because there are 6 load balancers (one for each …
=> Configure the number of proxies to fix anon rate limiting

api/conf/asgi.py, api/conf/settings/logging.py
Related to https://github.com/WordPress/openverse/issues/3353
We want to debug the memory leak behaviour in production. To do so, we'll enable garbage collection debug logging available in Python's `gc` module.
https://docs.python.org/3/library/gc.html#gc.set_debug
The flags are documented here:
https://docs.python.org/3/library/gc.html#gc.DEBUG_UNCOLLECTABLE
Because `DEBUG_LEAK` logs all collected objects, which is an overwhelming amount of logging, we'll start off with just `DEBUG_UNCOLLECTABLE` and `DEBUG_SAVEALL` first, to see if we can find dangling objects. If that doesn't work, we'll enable `DEBUG_LEAK` for a few hours to see if we get any useful information from it.
First try the application on this branch with no changes to environment settings and ensure things work as expected. …
=> Add gc debugging flag to help debug prod thumbnails leak

api/Dockerfile, catalog/Dockerfile, docker/upstream_db/Dockerfile, ingestion_server/Dockerfile
This reverts commit a1d0cc898f9fa1cab518b94f3b7e8b52175eb50c.
Fixes #3157 by @stacimc 
This PR unpins `glibc` that was pinned in #3154 as a security patch. With an updated `python3.11-slim` image containing the patched version of `glibc`, this is no longer necessary.
0. Check the `glibc` version in the current `web` image (`ldd --version` shows this info).
1. Check out this PR and build the `web` image again.
2. Check that the `glibc` version does not change.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Unpin glibc

api/api/constants/media_types.py, api/api/constants/search.py, api/api/controllers/search_controller.py, api/api/docs/audio_docs.py, api/api/docs/base_docs.py, api/api/docs/image_docs.py, api/api/serializers/audio_serializers.py, api/api/serializers/image_serializers.py, api/api/serializers/media_serializers.py, api/api/views/audio_views.py, api/api/views/image_views.py, api/api/views/media_views.py, api/test/media_integration.py, api/test/test_audio_integration.py, api/test/test_image_integration.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py, api/test/unit/models/test_media_report.py, api/test/unit/serializers/test_media_serializers.py, api/test/unit/views/test_media_views.py
Fixes #2849 by @obulat
Fixes #2850 by @obulat
This PR was changed a lot after reviews, mainly removing the query parameters, so I wrote a new description in [this comment](https://github.com/WordPress/openverse/pull/2853#issuecomment-1747352637). The old description is left here for the record.
This PR adds the endpoints for additional search views for both audio and image. The endpoints start with `/v1/images` or `/v1/audio`:
- **Tag** view: `/tag/tag_name`
- **Source** view: `/source/source_name`
- **Creator** view: `/source/source_name/creator/creator_name`.
These endpoints return paginated results because they accept `page` query parameter. They also support query parameters such as `license`, `license_type`, `category`,  [image-only] `aspect_ratio`, `size`, [audio-only] `length`, …
=> Add API routes and controllers for additional search views

catalog/dags/database/delete_records/delete_records.py, catalog/dags/database/delete_records/delete_records_dag.py, catalog/tests/dags/database/test_delete_records.py
Very small change to fix the formatting of the reported `record_count` in the Slack message from the `delete_records` DAG.
Unit test should pass. If you'd like, you can also run the `delete_records` DAG locally with a conf that will select >=1k records, example:
```
{
"reason":"deadlink"
"select_query":"WHERE provider in ('freesound', 'wikimedia_audio');"
"table_name":"audio"
}
```
Then look at the message for the final, `notify_slack` task and it should be formatted properly (`Deleted 4,172 records from the audio table matching query: 'WHERE provider in ('jamendo', 'wikimedia_audio')'`)
<details>
``` …
```
=> Fix delete_records slack formatting

api/Pipfile, api/Pipfile.lock, api/api/utils/image_proxy/__init__.py, api/api/views/audio_views.py, api/api/views/image_views.py, api/api/views/media_views.py, api/test/unit/utils/test_image_proxy.py, api/test/unit/views/test_image_views.py
First step of #2789 by @sarayourfriend
This is the first step to convert the image proxy route to async. It converts the overall view to async. I've split this into a separate PR because (a) it is complex enough on its own and (b) converting the actual `image_proxy.get` function is blocked on sharing the aiohttp client session (for which I'll have another PR up later today, it's already finished I just forgot to push it last night :facepalm:).
So this PR only converts the _view_ side of things to async. It does this by abstracting the thumbnails route in a slightly different way than it was before, which allows the audio and image views to ignore most of the safe-sync-in-async compatibility issues. To make that interplay a little easier, I decided to refactor `image_proxy.get` to use two …
=> Add ADRF and make the thumbnail view async

api/api/controllers/search_controller.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
Fixes #3380 by @obulat
This PR saves a list of `provider_identifier`s for the dynamically-excluded providers to the redis cache, instead of saving the QuerySet.
It also adds two unit tests for the specific functions, but there are also several other tests that test dynamically excluded providers using both cache and the `ContentProvider` model saved in the database.
Run the app, go to `http://localhost:50280/admin`, select one of the `ContentProvider` models and check its "Hide Content" property.
Execute a search (http://localhost:50280/v1/images). Check Redis value for `:1:filtered_providers` (I used the RedisInsights GUI): 
Also, check that on `main`, if you set "Hide content" to true for one of the providers, the value saved in Redis should look like the one in the related issue …
=> Fix dynamically excluded providers caching

.github/workflows/issue_automations.yml, .github/workflows/pr_automations.yml
Follow up to #3390.
This PR fixes the import path to the `.mjs` files by using the full path instead of relative as per a comment on this thread: https://github.com/actions/github-script/issues/168#issuecomment-1034088246 This should really fix the workflows this time.
A point of confusion is that the docs say that `"type": "module"` should be present in `package.json` but `import()` has been working just fine without that so far (see testing instructions in original PR #3375) so it might just work even without that field.
This PR also removes a redundant step from CI that should considerably speed up the workflow.
Compare the code changes against the attached thread.
<details> …
=> Really fix import path for `.mjs` files

api/api/middleware/client_application_middleware.py, api/api/middleware/response_headers_middleware.py, api/api/utils/oauth2_helper.py, api/api/utils/throttle.py, api/api/views/oauth2_views.py, api/conf/settings/base.py, api/nginx.conf.template, api/test/test_auth.py
Also add authorization, app name and verified status to nginx logs
Closes https://github.com/WordPress/openverse/issues/2246 by @sarayourfriend 
Fixes #3368 by @sarayourfriend 
Add logging as described in the issue.
To add the application name and verified status, I added a new middleware. The tests for this are in the `test_auth` suite.
You need to rebuild the nginx image to get the new logging: `just build nginx`. Afterwards, make requests to your local API via the nginx container: `localhost:50270`. Follow that container's logs (`just logs nginx`) and confirm that you see the following JSON log properties:
- `request_id`
- `client_application_name`
- `client_application_verified`
These come from the following headers, respectively, which you should also see on responses:
- …
=> Add middleware to log application name and verification status

api/api/controllers/search_controller.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
Reverts WordPress/openverse#3381
https://openverse.sentry.io/share/issue/65f52cf79486429c86ad957532094188/
and 
https://openverse.sentry.io/share/issue/d5341bad88cf421081b2551b36ef8c33/
=> Revert "Fix dynamically excluded providers caching"

api/api/controllers/search_controller.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
Fixes #3380 by @obulat
This is the updated version of #3381 that uses a new version for the cache key.
Previously saved value is a pickled `QuerySet`, and it doesn't work with the updated code (see https://openverse.sentry.io/share/issue/d5341bad88cf421081b2551b36ef8c33/)
On main, start the api and then go to `https://localhost:50280/admin`. Check "Hide content" for Flickr in `ContentProvider`s and execute a search. It should not return images from Flickr. Log into redis cache and get the value for the 2 versions of the key:
```
just exec cache redis-cli
127.0.0.1:6379 > GET ":1:filtered_providers"
"\x80\x04\x95\xc3\x05\x00\x00\x00\x00\x00\x00\x8c\x16django.db.models.query\x94\x8c\bQuerySet\x94\x93\x94)\x81\x94}\x94(\x8c\x05model\x94\x8c\x11api.models.models\x94\x8c\x0fContentProvider\x94\ …
```
=> Fix dynamically excluded providers

api/conf/settings/rest_framework.py
Related to #3398 
`NUM_PROXIES` needs to be able to be `None` to disable the feature. I got mixed up about the behaviour of 0 value for it and thought it was the same as `None`, but it's drastically different. `None` falls back to default, but `0` tells DRF to use the remote address (IP) of the request, which in the case of requests via proxy, is always the last proxy that handled the request. If you set it to 0, then everyone is getting throttled based on the proxy they went through, meaning they're sharing throttle quotas, rather than through their individual IP.
Run the application and use ipython to verify that `NUM_PROXIES` defaults to None:
```python
In [1]: from conf.settings import rest_framework
In [2]: rest_framework.REST_FRAMEWORK
Out[2]: 
{'DEFAULT_AUTHENTICATION_CLASSES': …
```
=> Allow None value for `NUM_PROXIES`

.github/filters.yml, .github/workflows/ci_cd.yml
This PR
- makes the CI job 'Apply stack labels' do nothing if the stack label is already applied
- classifies `utilities/` under the 'mgmt' stack so that future PRs affecting them are properly labelled automatically
<details>
```
Version 1.1
Suite D4700 …
```
=> Handle existing stack label in CI labelling job

.github/workflows/ci_cd.yml
The `precommit` recipe in our `justfile` allows for authenticated requests to GitHub to set up pre-commit. Since we never set the env var, we were still making unauthed requests and getting rate-limited intermittently.
This PR sets the `GITHUB_TOKEN` env var.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use authenticated GitHub requests to set up pre-commit

api/api/views/media_views.py, api/test/media_integration.py
Fixes #3403 by @obulat
This PR uses the DB to augment ES hits for related media with info that's not in ES. It uses the exact same pattern (and for that matter, code) as `get_media_results`.
Also updated the related media tests to check for the presence of these fields.
Try, and fail, to repro the issue described in #3403 on this branch.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use DB to augment ES hits for related media with required info

automations/js/src/utils/pr.mjs
This PR fixes typos in the `PullRequest` class that cause `isDraft` and `isMerged` info to be incorrect.
Cross-references these fields against the [documentation for the `PullRequest` type](https://docs.github.com/en/graphql/reference/objects#pullrequest) in the GitHub GraphQL API docs.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Fix incorrect variable mapping for PR util

api/env.docker, api/env.template
This PR makes a quick change to the config for the local application to make it clear that the secret key which is used is not an erroneously exposed value used in live environments.
1. Change the key in your `api/.env` file locally if you have one
1. `just a` and check that the API is accessible & searchable at http://localhost:50270
<details>
```
Version 1.1
Suite D4700 …
```
=> Change Django secret key to make it more obvious it's a shim value

frontend/src/locales/scripts/en.json5
Fixes #3377 by @Presskopp 
This would solve https://github.com/WordPress/openverse/issues/3377. Small simple fix.
=> Make punctuation marks consistent for singular & plural strings

.github/workflows/pr_automations.yml
This critical PR fixes a blunder where the labelling script expects `core` to be passed to it but it's not. It also makes it so that the second automation step runs regardless of the failure or success of the first.
<details>
```
Version 1.1
Suite D4700 …
```
=> Pass `core` to the labelling job as well

catalog/dags/common/licenses/constants.py
I noticed this problem while testing locally in Flickr.
In the Flickr DAG, we often get the following error (which is currently silenced in production):
```
Failed to rewrite URL: https://creativecommons.org/licenses/by-nd-nc/2.0/jp/
```
That URL is indeed invalid. These urls, however, are correct (note the swapped components, `by-nc-nd` vs `by-nd-nc`):
- https://creativecommons.org/licenses/by-nc-nd/2.0/jp
- https://creativecommons.org/licenses/by-nc-nd/2.0/
In the Flickr DAG, for each record we get a `license` and `license_version` from the Flickr API. We use our [`get_license_info`](https://github.com/WordPress/openverse/blob/adb56f128ca9f0835e0e882fbe960539a0076a37/catalog/dags/common/licenses/licenses.py#L41) utility to parse out the `license_url` (which ends up being stored in the …
=> Fix incorrectly parsed license url by-nc-nd for Flickr

api/api/utils/image_proxy/__init__.py, api/test/unit/conftest.py, api/test/unit/utils/test_image_proxy.py, api/test/unit/views/test_health_views.py, docker-compose.yml
Fixes https://github.com/WordPress/openverse/issues/3454 by @sarayourfriend 
Also fixes https://github.com/WordPress/openverse/issues/3276 because I really need to stop fixing this every time I spin the app up locally after a week of not running it.
Replaces the error handling code specific to requests exceptions with aiohttp handling. Just something I missed in code and we missed in reviewing #3388.
Review the code changes and confirm I've covered the cases. I had to make a change to one of the error keys but I'll explain it in a comment on that line in the PR.
Tests and CI should pass, of course!
<details> …
=> Fix image proxy get error handling

automations/js/src/label_pr.mjs
This PR fixes the issue where the lack of IDs for the maintainer labels caused the labelling script to fail. All labels must have a node ID to be applied via the GraphQL API.
The PR also improves the logging to show label names instead of the "[object Object]" that is otherwise printed on non-interactive consoles.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Add IDs for the maintainer attention labels

automations/js/src/label_pr.mjs
@sarayourfriend was right in [this review](https://github.com/WordPress/openverse/pull/3481#discussion_r1418094513), I should've used an API to get the label IDs instead of hardcoding them. Using hardcoded labels would mean that the infrastructure repo labelling would not work as those IDs were from the monorepo and only present on the monorepo.
This PR is not critical though as labelling works on the monorepo for now and the infra repo is private and only accessible to maintainers who can label their own PRs till this is merged and pushed.
<details>
```
Version 1.1 …
```
=> Use the GitHub API to get the label's node ID

.github/renovate.json
I noticed the Catalog was missing from these updates, but also why is it limited to development dependencies?
<details>
```
Version 1.1
Suite D4700
indicated …
```
=> Add catalog to dependencies to update by Renovate

api/api/serializers/image_serializers.py, api/api/views/image_views.py, api/test/test_image_integration.py, api/test/unit/views/test_image_views.py
Alternative to #3068 by @dhruvkb 
Fixes #3057
This PR checks that the param passed to the endpoint is an actual URL and that the image exists. In the future, we should make it more strict and check it's actually an Openverse URL (as specified in oembed.com) and review the JSON returned, there are fields missing.
See instructions in the linked PR.
<details>
```
Version 1.1
Suite D4700 …
```
=> Move Oembed endpoint validation onto the serializer

ingestion_server/ingestion_server/distributed_reindex_scheduler.py, ingestion_server/ingestion_server/utils/config.py
#3232
The ingestion server allows setting a `DATA_REFRESH_LIMIT` used to cap the number of records processed in a data refresh. By default on production we don't have a limit. Historically we have represented this by setting the limit to `0`. The copy data step has a simple[ if conditional ](https://github.com/WordPress/openverse/blob/c6ce2c6d819c0c316f64bdd616cf1378976fa766/ingestion_server/ingestion_server/queries.py#L184)before applying limits which meant that 0 was correctly considered "no limit".
When #3232 added logic to the reindexing step to also apply the record limit here, it did not have a similar check. The result is that in production, the default of 0 is applied... and 0 records are reindexed, effectively totally breaking the data refresh.
This PR:
* Adds a check to the …
=> Fix incorrect default production data refresh limit of 0

.github/workflows/ci_cd.yml
Depends on https://github.com/WordPress/openverse-infrastructure/pull/720
Related to #2843.
We can remove the staging thumbnails without having fully decomissioned the production thumbnails and reduce overall infrastructure complexity and get a minor cost savings (compared to waiting to decomission both at the same time).
CI/CD must pass.
<details> …
=> Remove staging thumbnails deployment

api/api/controllers/search_controller.py
Follow up fix of change in #3300
@dhruvkb has flagged that the condition for the sources stats aggregation ES query caching is incorrect and is always `True`. This means that we always query ES instead of using the cached value.
This PR removes the incorrect `or sources` to use cache when the `sources` list are empty in cache.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix source query caching

docker/upstream_db/Dockerfile
This PR updates the `pgcli` version for the upstream database to 4.0.1.
Recently I tried to run `just catalog/pgcli` and when I went to execute some commands I saw the following:
```
openledger> \d
'psycopg2.extensions.connection' object has no attribute 'pgconn'
```
I updated the `pgcli` version and that fixed the issue!
1. `just build`
1. `just catalog/pgcli`
1. Run `\d` and observe that no error occurs
<details>
```
Version 1.1
Suite D4700 …
```
=> Update catalog pgcli version to 4.0.1

catalog/Dockerfile
This PR fixes a critical issue that's causing CI on `main` to fail when building the catalog (example run: https://github.com/WordPress/openverse/actions/runs/7213002475).
It seems the MySQL PGP key may be expired, and that's causing fresh builds of the catalog to fail. The build log failure we're seeing is:
```
> [scheduler 2/7] RUN apt-get update     && apt-get -yqq install       build-essential       libpq-dev       libffi-dev     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*:
0.538 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
0.580 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
0.595 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
0.677 Get:4 http://deb.debian.org/debian bullseye/main amd64 …
```
=> Remove mysql from apt repository sources for catalog due to expired key

catalog/tests/conftest.py, catalog/tests/dags/common/sensors/test_single_run_external_dags_sensor.py, catalog/tests/dags/common/sensors/test_utils.py, catalog/tests/dags/common/test_ingestion_server.py, catalog/tests/dags/providers/test_provider_dag_factory.py
Fixes #2622  by @AetherUnbound 
There will be one `clean_db()` in conftest.py file because tests from multiple test modules in the directory can access the fixture function. `Pool` and `TaskInstance` from `airflow.models` will have a if condition because not all tests runs a filter and deletion for them. There is a override method for fixture on a test module level([link](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#override-a-fixture-on-a-test-module-level)) There are default values `get_test_dag_id`, `get_test_id`, `isPool`, `isTaskInstance` in `conftest.py`. On each test involving `clean_db()`, there should be a `get_test_dag_id()` fixture and options to run `isPool` fixture and `isTaskInstance` fixture by returning True
- run `just down -v`
- run `just catalog/up`
- run `just …
=> Unify DAG creation/database cleaning fixtures for testing

catalog/dags/providers/provider_api_scripts/jamendo.py, catalog/tests/dags/providers/provider_api_scripts/test_jamendo.py
Related to #3499 by @stacimc 
Starts writing Jamendo's `audiodownload_allowed` field to the metadata column, so that we can get more information about how many such records there are and which licenses they represent.
Run the Jamendo dag locally and ingest at least a few 100 records. Verify in pgcli or by inspecting the generated tsv in minio that the column is being written. If you allow the DAG to ingest a few thousand records you should get some results that have `audiodownload_allowed` set to False.
<details>
```
Version 1.1
1 …
```
=> Add Jamendo's audiodownload_allowed field to metadata

api/api/serializers/image_serializers.py, api/api/utils/asyncio.py, api/api/views/image_views.py, api/test/test_image_integration.py, api/test/unit/views/test_image_views.py
Fixes #3457 by @sarayourfriend
Converts the oembed endpoint to async. This was fairly straightforward and hopefully serves as a simpler example of the concept for others to work on additional views, if they wanted.
Unit tests should pass. Test the oembed endpoint as well and confirm it works the same as in staging.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Convert oembed to async

api/api/utils/image_proxy/__init__.py, catalog/dags/providers/provider_api_scripts/inaturalist.py
This PR removes stray commas from 2 locations in the codebase. The presence of those commas makes those lines appear as tuples to Python (which thankfully doesn't affect their behaviour)
This PR should not have any effect.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Remove stray commas in the codebase

.github/actions/load-img/action.yml, .github/workflows/ci_cd.yml, .github/workflows/pr_automations_init.yml, .github/workflows/push_docker_image.yml, .github/workflows/renovate.yml
Fixes #3539 by @dhruvkb 
This PR upgrades actions, workflows and packages related to artifacts. See linked issue for more info.
These are GitHub actions so there's little more that can be done to test these other than just reading very very carefully.
<details>
```
Version 1.1
Suite D4700 …
```
=> Upgrade actions and packages related to artifacts

api/api/utils/throttle.py, api/api/views/media_views.py, api/conf/settings/rest_framework.py, api/test/unit/utils/test_throttle.py
Fixes #3484 by @sarayourfriend 
Fixes #3485 by @sarayourfriend
Adds a new set of throttle classes to match requests with the `openverse.org` referrer header. Refer to the issue for rationale behind this approach. Keep in mind it is a temporary stop gap with known issues we seek to resolve with more advanced approaches later on.
The rollout for this will need infrastructure updates to include the new rate limiting scope environment variables.
Check over the new unit tests. I made significant modifications here to remove artificiallity from the tests. Instead, the tests run against endpoints known to have specific rate limiting configuration (whether the default or otherwise) and confirms that those rate limit scopes are used, based on the rate limiting headers).
To manually test the new …
=> Add referrer based throttle scope

api/api/controllers/elasticsearch/related.py, api/api/views/media_views.py
Fixes #3520 by @AetherUnbound 
This PR changes the 500 exception raised by the `/related` endpoint to 404 instead because that's more appropriate for when the identifier does not point to a media item.
Visit the non-existent related endpoint and observe the response code. See the original issue for examples.
<details>
```
Version 1.1
Suite D4700 …
```
=> Return status 404 instead of 500 when media not found

documentation/_ext/link_issues.py, documentation/_ext/link_usernames.py, documentation/conf.py
Fixes #3542 by @sarayourfriend
This PR changes the implementation of the `link_usernames` extension to be more flexible and resilient to the various text situations that can exist.
In doing so, it now trivially ignores the following contexts:
* Links
* Back `ticks`
* Code blocks (```` ``` ````)
The previous implementation could not ignore any of these without roundabout methods, like requiring leading whitespace. This led to the use of the flaky list of usernames to ignore. The new implementation doesn't need such a list, as it handles all the cases the ignore list targeted without issue, and removes the otherwise arbitrary requirement for leading whitespace. This means forms like `@person-a/@person-b` will work perfectly.
Additionally, the new implementation handles team mentions just as …
```
=> Use more flexible implementation for user mention link documentation extension

api/test/conftest.py, api/test/fixtures/rest_framework.py, api/test/integration/conftest.py, api/test/integration/test_audio_integration.py, api/test/integration/test_auth.py, api/test/integration/test_dead_link_filter.py, api/test/integration/test_deprecations.py, api/test/integration/test_image_integration.py, api/test/integration/test_media_integration.py, api/test/unit/conftest.py
Some potential changes for Dhruv's PR.
=> Use api_client, move fixtures around to share basic defaults

.github/sync.yml, .github/workflows/sync_meta.yml
This PR makes the sync workflow run only when the files it syncs have been changed. While there was no negative effect to the workflow running, it wasted API calls and valuable minutes.
The PR also drops two files from the sync that are no longer present in this repo and raised warnings when syncing was attempted for them.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Fix issues in the sync workflow and narrow down its triggers

catalog/dags/common/loader/provider_details.py, catalog/dags/maintenance/flickr_audit_sub_provider_workflow.py
See https://github.com/WordPress/openverse/issues/3490#issuecomment-1857072575 for additional context.
TL;DR: Internet Archive Book Images looks like a great candidate for a new sub-provider for Flickr, but the catalog does not currently have any images for this user because they were all uploaded prior to 2015. We also do not currently have an effective way to backfill these images, and it appears unlikely that many new ones will be added.
This PR:
* removes the sub-provider, which currently has 0 records
* adds the user id to the list of sub-provider candidates to ignore in the subprovider audit DAG, to prevent us from getting a notification each time it runs.
Since the sub-provider was not added to the API, there are no other changes necessary. To be totally safe we should verify after …
=> Remove Internet Archive Book Images sub provider

automations/data/labels.yml
Fixes #3574 by @AetherUnbound 
This pr adds `aspect:data` label
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```
=> Add "🗄️ aspect:data" label

.github/workflows/release-app.yml
This PR removes the step to deploy production thumbnails from the Release app workflow as the workflow it calls has been removed in WordPress/openverse-infrastructure#727.
See that the workflow is indeed gone and that the step should therefore be removed.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove step to deploy production thumbnails

catalog/dags/common/ingestion_server.py, catalog/env.template, catalog/pytest.ini
This PR removes two filtered warnings for the Airflow/catalog tests that are no longer present, and addresses a deprecation warning that is currently being raised.
> [!NOTE]
> This targets #3572 and should be merged after it.
1. `just catalog/test` shouldn't throw any warnings when the tests complete!
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
=> Update Airflow filtered warnings, address deprecations

catalog/entrypoint.sh
With the merge of #3591 and #3572, we started to encounter errors with the data refresh's HTTP steps. When run locally, the `HttpOperator` steps would raise an exception about how they were unable to find a provider for the connection type `https`. After looking through the Airflow source code for deserializing providers, we realized that the [HTTP Operator is expecting an `http` prefix](https://airflow.apache.org/docs/apache-airflow-providers-http/stable/connections/http.html) (whereas previously `https` was an allowed prefix when performing the lookup for which connection type to use).
We have code in our entrypoint which transforms connection URIs into URL-encoded `https` connection types (see: https://github.com/WordPress/openverse-catalog/pull/480), and this was ultimately where we …
=> HOTFIX: Convert encoded HTTP connection variables to http type not https

documentation/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.md
Fixes https://github.com/WordPress/openverse/issues/1966 by @sarayourfriend
@krysal @stacimc I've chosen y'all to review this plan with me. I'll ping y'all privately about this, but I'd like to schedule time to do a synchronous review, if possible, to avoid the long review process getting even further prolonged by my part-time work schedule.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
This discussion is currently in the …
=> Implementation Plan: Django admin moderator access control and base improvements

catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, catalog/dags/providers/provider_dag_factory.py, catalog/tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #3533 by @stacimc  
Adds a new configuration option, `additional_query_params`, to provider DAGs, such that on every request run, we add these params to the query.
<details>
```
Version 1.1
Suite D4700
have …
```
=> Add additional_query_params to provider DAG configuration

.github/workflows/pr_limit_reminders.yml
Noticed in https://github.com/WordPress/openverse/pull/3653
We were using the incorrect webhook URL for sending Slack DMs.
The message was also using shell math expressions that were printing literally, rather than being evaluated (because `payload` is not evaluated in a shell). GitHub Workflows don't support math expressions, unfortunately, so I added a step to set the variable in the environment file and access it in the payload that way.
Merge and see if it starts passing.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_ …
=> Fix PR limit reminders

.github/workflows/pr_ping.yml
Follow up #3577 and #3651 
Last notification of new PR received has bad formatting.
This is a quick PR to fix it, removing leftovers of when the action used curl calls.
<details>
```
Version 1.1
Suite D4700
have the …
```
=> Fix formatting of PR ping Slack messages

load_sample_data.sh
I set up Openverse from scratch today and ran into a very strange issue with `load_sample_data.sh` that I cannot track down the precise cause of. The version on `main` hangs completely, without any feedback, and apparently passes malformed SQL commands to `psql`.
The changes in this PR get the script running as expected for me again. They also, I believe, somewhat simplify things, through the introduction of two patterns:
1. The new `exec_sql` function which not only DRYs up the code a bit, but also uses what is apparently a more reliable approach for passing a set of SQL commands to `psql`. The same approach is used for interacting with Redis as well.
2. Taking advantage of bash's built-in multiline string support, rather than using docstring style. This is easier to read and keep track …
=> Simplify load sample data

ingestion_server/ingestion_server/authority.py
Related to #744 by @zackkrida 
Add Rawpixel to authority data as CURATED
The boost score given to rawpixel image should change from 80 (default) to 85 (curated)
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```
=> Add Rawpixel to authority data as CURATED

ingestion_server/ingestion_server/api.py, ingestion_server/ingestion_server/cleanup.py, ingestion_server/ingestion_server/db_helpers.py, ingestion_server/ingestion_server/indexer.py, ingestion_server/ingestion_server/ingest.py
Fixes #2019 by @sarayourfriend
This PR adds checks for Elasticsearch and both databases to the ingestion server health check endpoint behind the `check_deps` query parameter. This also refactors the database connection into a `db_helpers` module similar to the `es_helpers` one that already exists. This helped simplify some of the code and centralize _where_ the database connection logic was being defined.
The failed response has a `status` field with a list of possible failures due to the number of upstream services to be checked. If there's a better way to structure that, let me know!
1. `just i` to start the stack
1. Run `curl -L http://localhost:50281/` and verify the output is `{"status": "200 OK"}`
1. Run `curl -L http://localhost:50281/?check_deps=true` and verify the output is …
=> Additional service checks for ingestion server health endpoint

.github/workflows/ci_cd.yml
This PR adds the ability for the CI + CD workflow to deploy to staging from a non-`main` branch when dispatched from the UI. This boolean toggle will cause the workflow to tag the images, publish them on GHCR and deploy them to staging.
<details>
```
Version 1.1
Suite D4700
(a) …
```
=> Allow CI + CD workflow to deploy from a different branch

catalog/dags/common/cloudwatch.py, catalog/dags/data_refresh/data_refresh_task_factory.py, catalog/env.template, catalog/tests/dags/common/conftest.py, catalog/tests/dags/common/loader/test_s3.py
Fixes #3647 by @krysal
This PR adds steps for disabling and re-enabling the actions of the most sensitive alarms when a Data Refresh process is running. I made the most basic changes to achieve this but maybe it can be improved to make these steps not required to continue the DAG execution and make sure that at the end the alarms actions are always re-enabled. Requesting @stacimc's review specifically for that.
We'll need to create AWS credentials for Airflow as well I believe.
Set the AWS environment variables with the credentials of your AWS account. They can be found in the `~/.aws/credentials` file if you have configured the AWS CLI.
```
AWS_ACCESS_KEY_ID=<your_key>
#AWS_SECRET_ACCESS_KEY=<your_secret>
#AWS_DEFAULT_REGION=us-east-1
```
🚨 This will modify production alarms actions 🚨 …
=> Toggle CloudWatch alarms actions during Data Refresh

.github/workflows/pr_ping.yml
This PR adds missing spaces in the notification for when PRs are marked ready for review. Here is what the incorrect notification looks like.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```
=> Add missing spaces in PR ping

documentation/meta/monitoring/runbooks/api_avg_response_time_above_threshold.md, documentation/meta/monitoring/runbooks/api_avg_response_time_anomaly.md, documentation/meta/monitoring/runbooks/api_p99_response_time_above_threshold.md, documentation/meta/monitoring/runbooks/api_p99_response_time_anomaly.md, documentation/meta/monitoring/runbooks/api_request_count_anomaly.md, documentation/meta/monitoring/runbooks/nuxt_avg_response_time_above_threshold.md, documentation/meta/monitoring/runbooks/nuxt_avg_response_time_anomaly.md, documentation/meta/monitoring/runbooks/nuxt_http_2xx_under_threshold.md, documentation/meta/monitoring/runbooks/nuxt_http_5xx_above_threshold.md, documentation/meta/monitoring/runbooks/nuxt_p99_response_time_above_threshold.md, documentation/meta/monitoring/runbooks/nuxt_p99_response_time_anomaly.md, documentation/meta/monitoring/runbooks/nuxt_request_count_anomaly.md, documentation/meta/monitoring/runbooks/unhealthy_ecs_hosts.md
Closes #2504 by @sarayourfriend 
Closes #2505 by @sarayourfriend 
Update the runbooks for stabilized alarms. This PR closes the [ECS Alarms](https://github.com/WordPress/openverse/milestone/15) milestone.
The documentation should be generated correctly from the CI pipeline. Read the updated changes and confirm it all makes sense.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update alarms runbooks

.github/workflows/discussion_ping.yml, .github/workflows/pr_ping.yml
Fixes an issue where quotes in a PR title would cause the Slack messaging to fail. This is due to the way the formatting was changed in #3577.
Example: https://github.com/WordPress/openverse/actions/runs/7616428574/job/20743158171?pr=3689
GitHub Actions Expressions do not allow string substitution, only concatenation and formatting[^1]. Thus there's no easy way to replace the single or double quote characters in a PR title when interpolating them into the payload body. I am _hoping_ that `toJSON` will appropriately escape those characters, but I have no idea if this will work!
[^1]: https://docs.github.com/en/actions/learn-github-actions/expressions#functions
Merge and find out, maybe?
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidel …
=> Wrap PR and discussion titles in `toJSON` to escape them in Slack

catalog/justfile, documentation/catalog/reference/DAGs.md
Follow up from #3696, we identified that the DAG documentation generation CI check was no longer appropriately failing when it should have. This PR corrects the path used to reference the DAGs file and updates the DAG documentation appropriately. 
1. Make a change to the DAGs.md file
1. Run `j catalog/generate-dag-docs true` and ensure that the task fails
<details>
```
Version 1.1
Suite D4700 …
```
=> Use correct path when checking if DAGs.md needs to be regenerated

.github/workflows/pr_limit_reminders.yml
This is a follow-up to #3657 - apparently the folded block syntax `>` [is not supported on GitHub Actions](https://github.com/actions/runner/issues/418#issuecomment-612928525). 
I observed this in #3699 due to this failed run: https://github.com/WordPress/openverse/actions/runs/7634210058/job/20797766111?pr=3699 (I don't think we had a run since merging #3657 that pinged someone yet).
We can't test this, but since it's just concatenating into one big line, hopefully it should just work.
<details>
```
Version 1.1 …
```
=> Do not use unsupported folded chomping multiline YAML block syntax

documentation/projects/proposals/trust_and_safety/content_report_moderation/20230517-implementation_plan_mature_copy_change.md
Related to #2626 and follow up to #2126.
This PR updates the implementation plan for the `mature` -> `sensitive` code changes on the API to avoid a table rename. The maintainers decided that the table rename would be too much effort for too little gain, so this outlines the new set of steps necessary to make the code and copy changes for the API.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update copy changes implementation plan to avoid table rename

ingestion_server/justfile, ingestion_server/test/unit_tests/test_cleanup.py
Fixes flaky failure present in https://github.com/WordPress/openverse/actions/runs/7699638405/job/20983733877
The flakiness is caused by making real outbound network requests and relying on Flickr responding with a success status code. If Flickr is down, or anything else causes Flickr to not respond with a success (unrelated to our SSL testing method) the test fails in a flaky way.
This change prevents those outbound requests entirely.
Marked critical in line with the flaky test policy.
The updated test should pass CI.
<details> …
=> Prevent real network requests in TLS cleanup test

api/api/utils/image_proxy/__init__.py, api/conf/settings/thumbnails.py, api/test/unit/utils/test_image_proxy.py
Fixes #3708 by @aetherunbound
This PR removes the Sentry-shipping of errors that occur in thumbnails on the API. It also removes settings related to that effect.
1. Check out this branch and add the following diff:
```diff
diff --git a/api/api/utils/image_proxy/__init__.py b/api/api/utils/image_proxy/__init__.py
index af8cd65c7..37c85a080 100644
--- a/api/api/utils/image_proxy/__init__.py
+++ b/api/api/utils/image_proxy/__init__.py
@@ -162,6 +162,7 @@ async def get(
try:
session = await get_aiohttp_session()
+        raise ValueError("Whoops!")
upstream_response = await session.get(
upstream_url,
```
2. Add the `SENTRY_DSN` environment variable to point to Sentry.
3. Run `just api/init` and then navigate to http://localhost:50270/v1/images/5c173952-6a45-4380-b9e4-c935263730ab/thumb/
4. …
=> Remove sentry exception capture for thumbnail errors

documentation/frontend/guides/test.md
This came up in https://github.com/WordPress/openverse/pull/3727#issuecomment-1919615370.
This PR adds the storybook snapshot update command to the frontend testing documentation, so folks updating aspects of the frontend have all the necessary commands readily available in the same document.
I also removed all the preceding `$` characters from these commands. Because they're of the `console` type (or perhaps just a code block in general), Sphinx makes it easy to copy the commands from the browser and paste into a shell. However, those commands come with the leading `$` character too which makes them hard to paste and run immediately. This PR removes them all for this document, I'll have a follow up PR that removes them everywhere else. 
View the generated documentation output and verify …
=> Add storybook snapshot update command to testing documentation

documentation/projects/proposals/infrastructure_improvements/20240105_implementation_plan_move_remaining_services_to_openverse_org.md, documentation/projects/proposals/infrastructure_improvements/index.md
Fixes https://github.com/WordPress/openverse/issues/2038 by @sarayourfriend
Part of https://github.com/WordPress/openverse/issues/2037
I've requested review from @AetherUnbound and @dhruvkb:
- Madison, you are the person (I believe) most familiar with Airflow deployment details, so your input the Airflow configuration in particular is critical. You are also deeply familiar with our infrastructure configuration overall.
- Dhruv, you are extremely perceptive about the interconnected dependencies of our API and frontend, and our services in general, and I think you'll be a great person to review the plan. Reviewing this plan may also increase your exposure to any areas of our infrastructure with which you are not already familiar. There are also potential changes to our Terraform …
=> Implementation Plan: Move Airflow and API to openverse.org

.pre-commit-config.yaml
This PR fixes the key name to `pass_filenames` from the previously incorrect `pass_filesnames`. This however presents a conflict
The default value of `pass_filenames` is `true`. By having the incorrect key, we were using the default value, and passing filenames. Fixing the key would either go against the current process (which we know to be working) or be against the original author's intention. So I'm tagging @sarayourfriend for input.
Also priority is set to high because this is a problem with CI.
<details>
```
Version 1.1
1 …
```
=> Fix incorrect key `pass_filesnames`

frontend/test/playwright/e2e/sensitive-results.spec.ts, frontend/test/storybook/visual-regression/v-filter-button.spec.ts, frontend/test/storybook/visual-regression/v-header-internal.spec.ts
Fixes #3713 by @sarayourfriend
Fixes #3714 by @sarayourfriend
This PR attempts to fix the flaky Storybook Playwright tests by adding waits or testing that a font request was sent after the menu button is clicked, to make sure the fonts are loaded before taking the snapshots.
_I merged the sensitive results test fix into this PR since both PRs were failing the CI due to the other test failure (sensitive result fix was failing due to Storybook failure, and the Storybook fix was failing due to sensitive results failure)._
_Instead of going to the homepage, and making a new search to check that sensitive results were loaded, I added a check for sent API request with the sensitive parameter._
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a- …
=> Fix flaky Playwright tests

frontend/src/components/VIconButton/VIconButton.vue, frontend/src/components/VMediaInfo/VMetadata.vue, frontend/src/components/VMediaInfo/VSourceProviderTooltip.vue, frontend/src/components/VPopover/VPopover.vue, frontend/src/components/VTooltip/VTooltip.vue, frontend/src/composables/use-floating-ui.ts, frontend/src/composables/use-popover-content.ts, frontend/src/locales/scripts/en.json5, frontend/src/types/media.ts, frontend/src/utils/metadata.ts
Fixes #2775 by @fcoveram
Fixes #2840 by @fcoveram 
Adds the tooltip that opens when you focus or hover over the (i) symbol next to the Provider or Source in the single result page:
I just realized that the provider definition would not be correct when/if we extract sources from Europeana: here, Europeana is an aggregator which allows us to search for images, but the images themselves are hosted on the __source__ sites, not Europeana.
Here are the Figma links to: 
* [Tooltip component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5354-29979&mode=dev)
* [Help component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=2484-22552&mode=dev). Tooltip is visible in `hover` state
[WAI ARIA …
=> Add source and provider definition tooltips

.github/workflows/ci_cd.yml, .pre-commit-config.yaml, documentation/meta/ci_cd/jobs/preparation.md, justfile
Fixes and issue reported by @dhruvkb and @stacimc they had running the pre-commit hook on their local machines.
The docker image has issues running on arm64, so we will instead run it in CI using the GitHub action, with an utility just recipe to run the same checks locally as needed.
I also updated the CI/CD documentation to explain the new job and document the `lint-codeowners` recipe.'
Marked high because it is affecting the ability for folks to work on the codebase without this tedious interruption.
CI should pass with the new job and the `just lint-codeowners` recipe should work, including `just lint-codeowners all` to enable the experimental checks. …
=> Remove codeowners validator from pre-commit

documentation/frontend/guides/icons.md
Fixes https://github.com/WordPress/openverse/issues/3766
=> Fixed Typo in Frontend Icons.md file

ingestion_server/ingestion_server/distributed_reindex_scheduler.py, ingestion_server/test/unit_tests/test_distributed_reindex_scheduler.py
Fixes #2708 by @AetherUnbound
This PR adds some exception handling to the case where the indexer workers fail their healthchecks. Those exceptions are now raised appropriately in the ingestion server and will be alerted to Slack along with other exceptions.
I added some unit tests for these cases - this is my first time using `pook` and I'm basing it off of other tests in the ingestion server suite, so let me know if I'm doing something that isn't idiomatic!
CI passing should be a positive indicator.
<details>
```
Version 1.1
1 …
```
=> Raise an exception if any indexer workers fail their health check

.github/workflows/generate_pot.yml, .github/workflows/issue_automations.yml, .github/workflows/label_sync.yml, .github/workflows/pr_automations.yml, .github/workflows/pr_automations_init.yml, .github/workflows/pr_ping.yml, .github/workflows/project_thread_update_reminders.yml, .github/workflows/release-app.yml, .github/workflows/renovate.yml, .github/workflows/subscribe_to_label.yml, .github/workflows/sync_meta.yml, .github/workflows/weekly_updates.yml
Fixes #3693 by @AetherUnbound
This PR prevents the following workflows from running on forks:
- `generate_pot.yml`
- `issue_automations.yml`
- `label_sync.yml`
- `pr_automations.yml`
- `pr_automations_init.yml`
- `pr_ping.yml`
- `project_thread_update_reminders.yml`
- `release-app.yml`
- `renovate.yml`
- `subscribe_to_label.yml`
- `sync_meta.yml`
- `weekly_updates.yml`
Merge and find out!
<details>
```
Version 1.1
Suite D4700 …
```
=> Prevent running certain workflows on forks

.github/workflows/pr_automations_init.yml
Fixes #3770 by @AetherUnbound (hopefully, hard to know ahead of time)
**Update**: This PR now only removes `edited` from the `pull_request_review` trigger type. It also adds a concurrency limit, per @dhruvkb's suggestion: https://github.com/WordPress/openverse/pull/3771#issuecomment-1935349558
This PR removes the `edited` type from both the `pull_request` and `pull_request_review` workflow triggers for the PR automation init workflow. I suspect that this particular trigger is unnecessary for any of the actions we actually want to take when the workflow is triggered. It also makes debugging difficult. When looking at the init run history, it's hard to tell which events actually triggered the run in some cases:
I'm hoping that this somehow addresses the issue for why the PR automation was …
=> Remove `edited` type from PR automation init review trigger, enable concurrency

catalog/dags/common/constants.py, catalog/dags/common/sensors/utils.py, catalog/dags/elasticsearch_cluster/create_new_es_index/create_new_es_index.py, catalog/dags/elasticsearch_cluster/create_new_es_index/create_new_es_index_dag.py, catalog/dags/elasticsearch_cluster/healthcheck_dag.py, catalog/dags/elasticsearch_cluster/shared.py, catalog/justfile, catalog/tests/dags/elasticsearch_cluster/test_healthcheck_dag.py, catalog/tests/dags/test_dag_parsing.py, documentation/catalog/reference/DAGs.md
Fixes #3747  by @sarayourfriend 
Adds two new dags to monitor the staging and production Elasticsearch clusters. Each dag runs on a 15 minute schedule.
Both DAGs should run and respond with the appropriate notification or alert based on the cluster health response.
Run these locally by searching for the `monitoring` tag and enabling the two `elasticsearch_cluster_healthcheck`. Both should pass. If production passes but staging does not, make sure you have a new copy of `env.template` at `catalog/.env` because staging ES connection string was only recently added.
<details>
```
Version 1.1
Copyright …
```
=> Add Elasticsearch cluster health monitor DAGs

.github/workflows/draft_releases.yml, .github/workflows/release-app.yml, documentation/api/guides/deploy.md, documentation/catalog/guides/deploy.md, documentation/frontend/guides/deploy.md, documentation/general/deployment.md, documentation/ingestion_server/guides/deploy.md
Fixes #2264 by @sarayourfriend 
Splits release _drafting_ into its own workflow that runs on every push to main.
Updates the release-app to have a single "release" trigger, to always use the latest staging image to deploy production. It derives which app to release based on the released tag.
As the trigger is the release being published, there's nothing we need to do with the release in the `release-app` workflow, everything is now exclusively about (a) getting the images tagged, (b) deploying them (if API or frontend), and (c) opening the changelog PR.
This is annoyingly hard to test. I've tried to write the release drafting workflow in such a way that it will get tested, but I don't know if it will work. There is no way to really test the release app workflow changes without merging and …
=> Separate release drafting from publishing

.github/workflows/release-app.yml
Fixes https://github.com/WordPress/openverse/actions/runs/7879001320/job/21498432707
Releases currently fail to complete due to the `env.APP_NAME` having a newline at the end of the string: https://github.com/WordPress/openverse/actions/runs/7879001320/job/21498432707
Converting it to a single line is necessary because, as Madison pointed out, you cannot use a chomped multiline string (`>-`) in GitHub actions.
This PR also fixes the changelog PR step to only run if the rest of the workflow completes and to use the correct variable in place of `git-tag`. I searched for other usages of `git-tag` to be sure and those were the last remaining ones.
Confirm the change will work as expected based on the information about yaml multiline strings in the linked documentation.
- [N/A] I added or …
=> Fix newline at end of folded env variable string and prevent confusing skips of the changelog PRs

frontend/src/components/VSourcesTable.vue, frontend/test/playwright/e2e/sources.spec.ts
Fixes #3578 by @aetherUnbound
This PR adds the source view links to the names in the table on the `/sources` page.
Make sure that the deployment env is not set to production in your `frontend/.env` _file, otherwise the flag will not switch_
Run the app
Go to `/preferences` page and switch the `additional_search_views` on.
Go to `/sources` page and check that the links work and open the `source` view.
I did not update the snapshots because this feature is under flag. I think it's best to update them after the flag is turned on in staging.
<details>
```
Version 1.1 …
```
=> Add links to additional views to sources table

.pre-commit-config.yaml, ingestion_server/test/update_mocks.sh
Currently the pre-commit lint step uses `sed` to ensure that we do not use ```` ```console ```` in the documentation and instead replace it with ```` ```bash ````.
The `sed` command works for Linux but is interpreted differently on macOS where `-i -e` is interpreted as `-i='-e'` and causes `.md-e` files to to be created for every documentation file when linting using `just lint`. Using `perl` can avoid this problem as that approach is cross-platform (provided `perl` is installed, which is usually is).
This also updates another script that used a similar construct in a different script (with the working and broken operating systems reversed) with `perl`.
1. Check that lint step in CI passes.
2. Intentionally change some occurrences of ```` ```bash ```` to ```` ```console ```` in the docs. …
=> Prevent creation of `.md-e` files in the docs

catalog/dags/providers/provider_api_scripts/nypl.py, catalog/justfile, catalog/tests/dags/providers/provider_api_scripts/resources/nypl/metadata.json, catalog/tests/dags/providers/provider_api_scripts/resources/nypl/response_search_success.json, catalog/tests/dags/providers/provider_api_scripts/test_nypl.py
Fixes #2747 by @krysal
This PR updates the NYPL DAG to use the new v2 API. Fortunately almost nothing changed with the actual API interaction details! So this became a very straightforward change. The only major change was putting the tags in the right place!
I also added the option to pass arguments into the catalog's `ipython` recipe.
1. Get the NYPL API key and add it to `AIRFLOW_VAR_API_KEY_NYPL` in the `.env`
2. Enable the NYPL workflow and let it run for however long you set your `AIRFLOW_VAR_INGESTION_LIMIT` (note that this DAG is _slow_ and will take about 3 hours to run end-to-end for ~3k results).
<details>
```
Developer …
```
=> Update NYPL DAG to use API v2

.github/CODEOWNERS, CODE_OF_CONDUCT.md, documentation/general/contributing.md
This removes the repository specific `CODE_OF_CONDUCT.md` file in favor of the newly added version maintained as the organization's default within the WordPress/.github repository.
While this file will not be included in `git clone`s, it will be displayed on the repository's main page and anywhere else GitHub includes a Code of Conduct link.
This change enables more consistent messaging for the community code of conduct, and allows the file to be updated in one location for all repositories under the WordPress organization.
See https://github.com/WordPress/.github/pull/1.
=> Remove the repository specific code of conduct.

catalog/dags/common/slack.py, catalog/dags/elasticsearch_cluster/shared.py, catalog/entrypoint.sh
Locally, most of our Airflow connections are set via environment variables in `catalog/.env`. In production they are generally set through the Airflow Admin UI. This caused the following issue to be missed in local testing:
We have a script in `entrypoint.sh` which reformats all airflow connection environment variables (containing the string `http`) by urlencoding them and prepending 'http://'. The purpose of this was for convenience with setting up the Slack connections locally (otherwise you have to urlencode part of the Slack uri).
It is not necessary for any of our other connection strings and in fact was causing issues with the Elasticsearch connections -- the reformatted string was not parsed correctly, parsing the entire uri as the `host`.
This PR:
* modifies the `entrypoint` …
=> Fix airflow connections

api/conf/settings/security.py
Fixes #2689 by @AetherUnbound
This PR updates the default value for `BASE_URL` on the API (which is the value that ends up being used in production) from `openverse.org` to `api.openverse.engineering`. The `BASE_URL` value is used in media reports to construct the item URL, and was constructing an incorrect URL which had the path components of the API but pointed to the frontend. Since this is a computed field, simply deploying this change should correct all the links provided on each of those tables.
1. Set `BASE_URL=https://openverse.org/` in your `api/.env` file
1. Run `just api/init` to start the API
1. Run `API_URL=http://localhost:50270 just frontend/run dev:only` to start the frontend
1. Navigate to an image result on the frontend, and submit a report
1. Visit …
=> Use correct `BASE_URL` for the API by default

.github/renovate.json
Spurred by a conversation @dhruvkb brought up about the dependabot security update PRs not including the correct labels, now that we've removed the dependabot configuration in favour of renovate.
I'm hoping this change allows Renovate to open security updates "at any time" rather than waiting for the start of the month.
We can merge this and then the next time a security update comes along, see whether Renovate opens a PR like dependabot does. If we confirm that Renovate is now working to replace that part of dependabot as well, we can fully disable dependabot PRs.
N/A. Merge and wait until the next vulnerability in a dependency happens. And merge and make sure Renovate doesn't suddenly open a huge number of PRs we didn't mean it to.
- [N/A] I added or updated tests for the changes I made …
=> Enable at-any-time security updates from Renovate

catalog/dags/common/loader/s3.py, catalog/dags/providers/provider_dag_factory.py, catalog/dags/providers/provider_workflows.py, catalog/env.template, catalog/tests/dags/providers/test_provider_workflows.py, justfile
Related to #1787 by @obulat 
This does not close the issue, as we still need to run the s3 command noted in the issue to backfill the storage class onto all existing objects.
Updates the provider ingestion workflow DAG to use the standard infrequent access storage class for provider TSVs.
I've documented the rationale behind setting the storage class eagerly, despite immediately accessing it, in the code. I really do not think it makes any sense at all to use a new task to set the storage class down to IA after the DAG is finished, and despite the 10th of a US penny spent on the retrieval fee, we will still save >99.99% of the money we. I really think the difference is incalculable and not worth the code complexity. The note about increased energy usage of an additional task (and all the …
=> Use infrequent access when uploading provider TSVs

frontend/nuxt.config.ts, frontend/src/composables/use-analytics.ts, frontend/src/plugins/analytics.ts
A pre-requisite for https://github.com/WordPress/openverse/pull/3721
Convert the `useAnalytics` composable into a plugin. I've chosen to take an approach where the composable still exists, but just acts as a thin wrapper around `$sendCustomEvent` from the new plugin. This (a) reduces code churn and (b) allows us to confirm that the change behaves exactly as we expected the previous version to behave. All tests asserting against the analytics events continue to work without changes.
All Playwright and unit tests should continue to pass without changes.
Furthermore, to confirm absolutely that the `breakpoint`, `height` and `width` variables still work as expected, run Plausible locally using `just frontend/up` followed by `just frontend/init` to get the custom events loaded. Then visit …
=> Turn analytics composable into a plugin

catalog/dags/common/loader/provider_details.py, catalog/dags/common/requester.py, catalog/dags/providers/provider_api_scripts/museum_victoria.py, catalog/dags/providers/provider_api_scripts/nappy.py, catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, catalog/dags/providers/provider_api_scripts/rawpixel.py, catalog/dags/providers/provider_api_scripts/stocksnap.py, catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, catalog/tests/dags/common/test_requester.py, catalog/tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #1362 by @krysal
Related to #2037 ([Airflow work](https://github.com/WordPress/openverse-infrastructure/milestone/6))
Resuming the work done previous to the monorepo. This PR adds the User-Agent as the default header for all requests in the `DelayedRequester` and `ProviderDataIngester` classes, making it unnecessary to repeat code in providers DAGs, so it was removed from museum_victoria, nappy, rawpixel, stocksnap, and wikimedia_commons.
I added a new `CANONICAL_ORIGIN` reading it from the os environment to replace the old domain referenced in the UA string. Is it better to read it from an Airflow variable? CC @AetherUnbound.
Run one of the above-mentioned DAGs, for example rawpixel, to confirm they continue to work. See the code and updated tests and confirm it all makes sense. …
=> Make User-Agent a default header

documentation/projects/proposals/trust_and_safety/content_report_moderation/20240122-implementation_plan_bulk_moderation_actions.md
Fixes #1967 by @sarayourfriend 
I've chosen @obulat and @sarayourfriend as reviewers. In particular I'd like to call out to @sarayourfriend (as I do in the document itself) that this plan build on and makes some slight change to the work in #3494 that should be carefully reviewed.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
This discussion is currently in the [Decision round](https://docs.openverse.org/meta/decision_making/process …
=> Implementation Plan: Bulk moderation actions

utilities/load_testing/README.md, utilities/load_testing/k6/utils.js
Related to https://github.com/WordPress/openverse-infrastructure/pull/804 which removed `api-dev` as a staging domain.
The subdomain no longer exists, and so it should not be referenced in current documentation.
I considered similarly removing references to `search.openverse.engineering` (and `search-staging`) but the only reference to that are in planning documents, which reference in-time things on those pages, so I feel it doesn't make sense to update them.
Check that I haven't missed any references to the removed domains.
<details> …
=> Remove references to api-dev

.github/workflows/pr_ping.yml
Fixes #3781 by @obulat 
This PR updates the Slack notification workflow to use a JSON file written by a `actions/github-script` step. This should handle all issues related to JSON escaping that previous attempts could not fix. It also combines the new and undraft steps into a single step that can handle both scenarios.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Use GitHub script to handle JSON escaping in Slack message

catalog/dags/providers/provider_api_scripts/europeana.py, catalog/tests/dags/providers/provider_api_scripts/test_europeana.py
Fixes #2784 by @obulat
This PR modifies the Europeana ingester to preemptively fail URLs that are invalid or unusable. See #2784 for what prompted this. Because we automatically add the scheme if it isn't present when attempting to validate the URL, I didn't want to add any machinery to check if the scheme was missing from the beginning of the URL (due to the diversity of sources Europeana includes, I can't check all possible URLs we might get returned back). Dropbox URLs, however, can't really be used by our API as they can't be accessed directly. It seems Europeana actually proxies them itself, here's an example result: https://www.europeana.eu/en/item/2063627/BEL_280_003
This adds a check to throw out any Dropbox URLs ahead of time, so the CSV writing can occur as intended and the …
=> Preemptively fail unparsable/unusable Europeana URLs

frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue, frontend/src/components/VHeader/VSearchBar/VSearchBar.vue, frontend/src/components/VModal/VInputModal.vue, frontend/src/components/VRecentSearches/VRecentSearches.vue, frontend/src/components/VRecentSearches/meta/VRecentSearches.stories.mdx, frontend/src/locales/scripts/en.json5, frontend/src/stores/search.ts, frontend/tailwind.config.ts
Fixes #3194 by @fcoveram 
This PR
- adds support for removing individual queries from recent searches
- updates the UI to match the new mockups
There is a bit of a problem where the recent searches cannot individually be cleared using the keyboard because the keyboard navigation inside the popup does not cover them, but I feel that is acceptable because all recent searches can still be cleared using the keyboard and there is no navigational order that would feel natural for iterating over the popup suggestions as well as their &times; icons.
1. Check out the PR and run the dev server.
2. Search for some terms.
3. Try the new feature of removing individual queries from history.
4. Compare the UI against the mockups in Figma. …
=> Update recent searches to match updated mockups

catalog/dags/providers/provider_api_scripts/inaturalist.py, catalog/dags/providers/provider_csv_load_scripts/inaturalist/create_schema.sql, catalog/tests/dags/providers/provider_api_scripts/test_inaturalist.py
Fixes #3631 by @rwidom
This PR fixes a number of aspects of the iNaturalist ingestion, with the hope that we should be able to turn it back on in production after this!
- Addresses the issue in #3631 by pointing to a "latest" version of the COL data. This link doesn't include a build/date/version number, and so shouldn't need updating down the line.
- Fixed an issue where the media type was not provided when running various `common.sql` methods directly.
- Updated the iNaturalist schemas, which had changed since the last time this was successfully run.
- Use the minimum photo ID when creating the initial ranges, rather than starting from 0
It seems it had been a minute since we've gotten iNaturalist running :sweat_smile: There were quite a few changes, but I think I've covered them all …
=> Various iNaturalist updates

catalog/dags/providers/provider_api_scripts/inaturalist.py
Fast-follow to #3846, the iNaturalist DAG once started was beginning to time out at the `load_<table>` steps. I've bumped this timeout from 10 minutes to 30 minutes in the hopes this will be sufficient.
Should be clear in code but you can also start up Airflow and look at the value passed into the Operator.
<details>
```
Version 1.1
Suite D4700 …
```
=> Extend timeout on iNaturalist table loads

documentation/api/guides/deploy.md, documentation/catalog/guides/deploy.md, documentation/frontend/guides/deploy.md, documentation/general/deployment.md, documentation/ingestion_server/guides/deploy.md
I noticed that some documentation was out of date or slightly unclear while performing a deploy recently.
This PR updates some documentation around rollbacks following the changes to the release process in https://github.com/WordPress/openverse/pull/3755/files. It also tries to clarify some ambiguity I found confusing (in general, referring to "the workflow" without specifying deployment vs release-app).
Read through the documentation and confirm that the updates are **accurate**. I've left a few questions in comments about things I was not 100% sure of, so please correct me!
<details>
```
Version …
```
=> Update documentation for how to perform rollbacks

documentation/projects/proposals/data_normalization/20240227-implementation_plan_catalog_data_cleaning.md, documentation/projects/proposals/data_normalization/index.md
Related to #430 by @obulat
Since the project proposal is clear with what we want to achieve in this case, and in a past attempt, there were more doubts with the technical details than with the proposal itself, here I directly add an implementation plan with the most straightforward path identified.
This proposal also represents work that @obulat pushed last year; it's partly possible due to her effort and the @stacimc's precedent in the batched_update DAG. Kudos to both! 
---
This discussion follows the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
Requested reviewers or participants will be following this process. If you are being asked to give input on a …
=> Implementation plan: Catalog Data Cleaning 

catalog/dags/elasticsearch_cluster/healthcheck_dag.py, catalog/tests/dags/elasticsearch_cluster/test_healthcheck_dag.py
Fixes #3902 by @AetherUnbound
This PR fixes an issue for the Elasticsearch healthcheck DAG wherein the message composition would return `None` because the cluster was green, but the downstream `notify` step was expecting a particular message type. I've corrected this first by adding explicit typing so the expectations are a bit more obvious, and then by raising an `AirflowSkipException` when the cluster health is green (since no alerting is necessary). This likely didn't come up locally because our local ES cluster health is always yellow!
Tests should pass, this is hard to assess locally because our ES cluster health won't be green.
<details> …
=> ES healthcheck: skip message composition task when cluster is green

catalog/dags/providers/provider_api_scripts/cc_mixter.py, catalog/tests/dags/providers/provider_api_scripts/test_cc_mixter.py
Fixes #3901 by @AetherUnbound
To borrow from @dhruvkb's PR in #3904:
ccMixter's API can send malformed JSON so this PR adds addtional handling for the same. This particular case appears at offset 27100:
```json
"file_name" : "salvatore_j_-_128_bpm_matched_Drum_loops_15.mp3", "file_nicname" : 012.2,
```
This PR modifies the bad octal regex to handle cases where a decimal point may be present.
1. Tests should pass
2. Run the DAG locally with `initial_query_params` as `{"format": "json", "limit": 100, "offset": 27100}`, and ensure it passes on this branch
<details>
```
Version 1.1 …
```
=> ccMixter: Handle bad numbers with a decimal point

catalog/dags/common/requester.py, catalog/dags/providers/provider_api_scripts/freesound.py, catalog/dags/providers/provider_api_scripts/phylopic.py, catalog/tests/dags/common/test_requester.py, catalog/tests/dags/providers/provider_api_scripts/test_freesound.py, catalog/tests/dags/providers/provider_api_scripts/test_phylopic.py, catalog/tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #3820 by @AetherUnbound, fixes #1369
#3820 gives an excellent explanation of the problem, but the tldr is that the Phylopic DAG works by first fetching a `build_param` that is used in all subsequent requests for data, and sometimes this `build_param` changes _while ingestion is underway_, causing errors. When that happens we want to identify the issue, fetch the new `build_param`, and start ingestion over from the top.
To accomplish that, this PR ended up making additional changes to the `DelayedRequester`. Currently the requester will, after all configured retries have been exhausted, raise a `RetriesExceeded` error with no other context about what the actual error was from the provider API. This PR updates the requester to instead raise the actual error from the API, which I think …
=> Recover from updated build_param in Phylopic DAG

documentation/projects/proposals/additional_search_views/20230424-project_proposal_additional_search_views.md, documentation/projects/proposals/additional_search_views/20230719-implementation_plan_additional_search_views.md, documentation/projects/proposals/additional_search_views/SUPERSEDED-20230719-implementation_plan_additional_search_views.md
Updates the Implementation Plan in line with the [discussion](https://github.com/WordPress/openverse/discussions/3825) conclusions
This PR updates the IP to move from path parameters to the query parameters. Also, SEO-related changes were added, too.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update the Additional search views IP

catalog/dags/providers/provider_api_scripts/freesound.py, catalog/tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #3908 by @AetherUnbound
Similar to #3907, this PR adds handling for cases where Freesound creator names have spaces in them.
1. Tests should pass
2. Running the DAG locally with `initial_query_params` set to `{"format": "json", "query": "", "page_size": 150, "fields": "id,url,name,tags,description,created,license,type,download,filesize,bitrate,bitdepth,duration,samplerate,pack,username,num_downloads,avg_rating,num_ratings,geotag,previews", "filter": "created:[* TO NOW]", "page": 15}` should pass
<details>
```
Version 1.1
1 …
```
=> Freesound: handle space in creator name when making URL

api/api/examples/audio_responses.py, api/api/serializers/audio_serializers.py, api/test/integration/test_media_integration.py, api/test/unit/serializers/test_audio_serializers.py, load_sample_data.sh
Fixes #3930 by @sentry-bot
This PR marks some audio alt file properties as not required. This fixes the 500 error when serializing CC Mixter items that don't set `bit_rate` on the alt files.
To allow for local tests, this PR adds 10 audio items from CC Mixter to the `sample_audio.csv`
Run the API. Delete the current audio index (I use Elasticvue for this, there is probably a better way to recreate the index) and run `just api/init` to index audio again.
Check that 10 CC Mixter items are rendered correctly: http://localhost:50280/v1/audio/?source=ccmixter
See that this causes 500 without the code changes in this PR, or in prod. 
<details> …
=> Fix audio alt files missing bit rate

catalog/dags/elasticsearch_cluster/healthcheck_dag.py, catalog/dags/maintenance/rotate_db_snapshots.py, catalog/tests/dags/test_dag_parsing.py
Fixes #3803 by @AetherUnbound
This PR adds the `DAG_DEFAULT_ARGS` (which includes automatic failure callbacks) to the DAGs which were missing them. It also adds a test to ensure all parseable DAGs contain the default args, and enumerates those which do not. This will be helpful going forward to ensure we add those defaults to all new DAGs.
1. Tests should pass
2. The affected DAGs should now longer show up with `airflow` as the owner, unlike how they currently do:
<details>
```
Version 1.1
Suite D4700
San …
```
=> Use DAG_DEFAULT_ARGS for all DAGs

frontend/src/components/VButton.vue, frontend/src/components/VSkipToContentButton.vue, frontend/src/middleware/search.ts, frontend/src/pages/image/collection.vue, frontend/src/types/button.ts, frontend/test/playwright/e2e/all-results-keyboard.spec.ts, frontend/test/playwright/e2e/search-navigation.spec.ts, frontend/test/playwright/utils/navigation.ts, frontend/test/playwright/utils/search-results.ts
Fixes #3940 by @sarayourfriend
This PR converts the skip-to-content link to an `a` anchor link instead of using the `VLink` component because this component links to a hash `#content` URL, and `VLink` introduces unnecessary complexity for it.
To stop the media re-loading when clicking on `skip-to-content`, I added a check for hash in the `search.ts` middleware. We don't update anything in the middleware if the navigation was caused by a hash change.
Try searching for something, and then use <kbd>Tab</kbd> to focus the Skip-to-content button, click on the button to navigate to content. You should not see the media reload or the content links change number of results.
<details> …
=> Fix the skip-to-content link reloading the results

frontend/src/locales/scripts/bulk-download.js, frontend/src/locales/scripts/utils.js
Fixes #3938 by @sarayourfriend
This PR adds the locale to the warnings about kebab-cased locale keys.
The locale files contain strings with keys that can be used, for instance, to insert links into them:
`license: "{readMore} about this license.` gets converted to something like `<a href="linkURL">read more</a> about this license`
The keys like `readMore` were first in `kebab-case`. Kebab-cased keys are invalid in the latest versions of Vue i18n, so we converted them to camelCase. However, converting the keys in GlotPress is not easy and takes time. To account for that and make the translations usable, #2433 added a function that converts kebab-cased keys to camelCase. It also adds a warning to keep track if we still have some kebab-cased keys. You can see them when you run `just …
=> Adds locale to the locale kebab-case warnings

frontend/src/components/VImageCell/VImageCell.vue, frontend/src/components/VLoadMore.vue, frontend/src/components/VSearchResultsGrid/VAudioResult.vue, frontend/src/stores/search.ts, frontend/src/types/analytics.ts, frontend/test/playwright/e2e/all-results-analytics.spec.ts, frontend/test/playwright/e2e/audio-detail.spec.ts, frontend/test/playwright/e2e/image-detail.spec.ts, frontend/test/playwright/e2e/load-more.spec.ts
Fixes #3619 by @obulat 
This PR updates the payload of search-related analytics events to include collection information on collection searches. These collection-related values are `null` on other searches. It also adds the existing `kind` custom property to the `LOAD_MORE_RESULTS` and `REACH_RESULT_END` events.
One aspect of this PR I do not like is the accessing the search store inside of the image cell and audio result components. It _does_ feel ideal to use a standardized approach to getting the current search strategy and the value (string of the name of the tag, source, or source/creator) from one centralized place, but I don't like accessing a global store in a component which is repeated several times on the page.
1. Enable `additional_search_views` on …
=> Update payload of collection search analytics events

documentation/projects/proposals/dark_mode/20240313-project_proposal_dark_mode.md, documentation/projects/proposals/dark_mode/index.md
Fixes #3894
2024-03-27
This PR introduces the project proposal for the Dark mode project (#3592)
=> Project proposal for dark mode project

frontend/src/components/TableSortIcon.vue, frontend/src/components/VAudioTrack/layouts/VBoxLayout.vue, frontend/src/components/VMediaTag/VMediaTag.vue, frontend/src/styles/accent.css, frontend/tailwind.config.ts
Related to #3592 by @fcoveram 
While reviewing our tailwind configuration in preparation of #3958, I noticed we still have a number of colors that aren't in use, and one that _was_ incorrectly still in use.
Tests should pass.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Remove unused colors from the tailwind config

catalog/dags/common/sensors/constants.py, catalog/dags/common/sensors/utils.py, catalog/dags/data_refresh/create_filtered_index_dag.py, catalog/dags/data_refresh/dag_factory.py, catalog/dags/data_refresh/data_refresh_task_factory.py, catalog/dags/database/staging_database_restore/staging_database_restore_dag.py, catalog/dags/elasticsearch_cluster/create_new_es_index/create_new_es_index_dag.py, catalog/dags/elasticsearch_cluster/create_new_es_index/create_new_es_index_types.py, catalog/dags/elasticsearch_cluster/create_proportional_by_source_staging_index/create_proportional_by_source_staging_index_dag.py, catalog/dags/elasticsearch_cluster/point_es_alias/point_es_alias_dag.py, catalog/dags/elasticsearch_cluster/recreate_staging_index/recreate_full_staging_index_dag.py, catalog/tests/dags/common/sensors/test_utils.py, documentation/catalog/reference/DAGs.md
Fixes #3891 by @stacimc 
We now have quite a few DAGs that all operate on Elasticsearch or the underlying databases, and therefore must not run concurrently. We've been using the `prevent_concurrency_with_dags` and `wait_for_external_dags` utils to accomplish this in each DAG, by passing in a hard-coded list of the external DAGs we want to either wait on or otherwise prevent concurrency with. Since this list is hard-coded for each DAG, it is extremely easy to miss dependencies especially as DAGs are added and changed. A few were missed in the implementation of the Search Relevancy project so far.
This PR introduces ~two~ **three** new Tags that are used to identify DAGs as being part of a "concurrency group": `production_elasticsearch_concurrency`,  and `staging_elasticsearch_concurrency` …
=> Add elasticsearch concurrency tags for Airflow

automations/js/src/last_week_tonight.mjs
Fixes #3445 by @dhruvkb
This PR makes some alterations to the "Week in Openverse" blog post generation script to group the closed issues/merged PRs for a given repository by the stack label. Since an issue/PR can have more than one stack label, this approach will produce an output where said issue/PR shows up in _each_ of the stacks for which it has a label.
I am no Javascript expert - if there are more sensible ways to do the operations I'm performing in this script, _please_ feel free to share! I'm happy to try and make this more idiomatic :smile:
This can be run locally with node in the `automations/js` directory with the following: `ACCESS_TOKEN=<value> MAKE_USERNAME=<value> MAKE_PASSWORD=<value> node src/last_week_tonight.mjs`. However, example output is below (along with a …
=> Group "week in Openverse" items by stack label

api/api/examples/audio_responses.py, load_sample_data.sh
Addresses an issue introduced in #3931
This PR fixes a syntax issue in the provider insertion step of the load sample data script. I discovered this when I ran the script locally and observed this in the `just api/init` output:
```
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -T db psql -AXqt
ERROR:  syntax error at or near "now"
LINE 1: (now(), 'ccmixter', 'CCMixter', 'https://ccmixter.org', fals...
^
```
I tried to determine why the error wasn't bubbled up any further, but was unable to do so in the short time that I was looking at this.
Run `just api/init` on this branch and observe that the above step succeeds where it previously failed.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_ …
=> Fix load sample data script provider insertion

frontend/src/stores/search.ts, frontend/test/tapes/search/images/creator=strogoscope&source=flickr&unstable__collection=creator_keep-alive.json5, frontend/test/tapes/search/images/creator=strogoscope_keep-alive.json5, frontend/test/tapes/search/images/source=flickr&unstable__collection=source_keep-alive.json5, frontend/test/tapes/search/images/unstable__collection=tag&tags=cat_keep-alive.json5
Related to #3920 by @obulat
This PR implements the first part of the related issue: adds both stable and unstable parameters for the additional search views project.
Until the API changes from #3887 are deployed to prod, this PR can only work with local or staging API.
To test with staging, set API_URL to `https://api-staging.openverse.org/` (either in the `frontend/.env` file, or by running frontend using `API_URL=https://api-staging.openverse.org/ just frontend/run dev`
The additional search view pages should work correctly, and the API requests should contain both `unstable__` and stable params (for collection and tag).
<details> …
=> Update additional search views API params in frontend

frontend/src/utils/case.ts
Fixes #3984 by @krysal
I don't know how to reproduce the issue but I think this small PR should fix it.
–.
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> Check for emptiness of case.split function input

frontend/src/data/api-service.ts, frontend/src/middleware/collection.ts, frontend/src/stores/search.ts
Fixes #3976 by @zackkrida
This PR adds `clearMedia` call to the search store's function setting the collection state. This makes the `setCollectionState` similar to `setSearchStateFromUrl`. To make sure that we don't clear media when non-collection state params change (for instance, if we add filters to the collection views, or if we add `page` parameter to the frontend URL to improve pagination), we first check if the `collectionParams` are different.
Go through the following steps and check that the linked issue is fixed (step 5):
1. Run the app locally using `just frontend/run dev`
2. Make sure the additional_search_views feature is enabled: http://localhost:8443/preferences
3. Search "rabbit" from StockSnap only: http://localhost:8443/search/image?q=rabbit&source=stocksnap
4. Click on …
=> Reset the media store state if collection state changes

frontend/src/locales/scripts/en.json5, frontend/src/pages/search-help.vue, frontend/src/plugins/vue-i18n.ts
Fixes #617 by @obulat
This PR adds comments to the i18n strings that are used inside a full sentence:
```
{
/**
Interpolated into hero.disclaimer.content:
_{license}_ part of "All Openverse content is under a _{license}_ or is in the public domain."
*/
license: "Creative Commons license",
}
```
This allows the translators to correctly select the word forms that match the full sentence.
It would be great if we could automate the creation of such comments, but I didn't find an easy way of doing that.
Still, having such comments is very important for accurate translations.
Run the app locally using `just frontend/run dev`
You should not see any warnings about i18n keys missing in the console on any page of the site.
Also, look through the strings and see check that the comments look correct. …
=> Add context comments to i18n key

frontend/src/components/VMediaInfo/VMediaTags.vue, frontend/src/components/VTag/VTag.vue, frontend/test/unit/specs/components/VTag/v-tag.spec.js
Fixes #3190 by @dhruvkb
This PR is the updated version of #3870 by @Stagge
The VTag component added in https://github.com/WordPress/openverse/pull/3137 has been improved in the following ways:
- All props are forwarded to the inner `VButton` (and the `VLink` component)
- All events are emitted from the inner `VButton`
- The content is displayed with a slot for the content instead of a prop.
- ~~Accessible labels to the links have been added to clearly indicate that the link is a tag.~~ The a11y group advised not to add aria-labels, and use the inner text instead
- Tests for the VTag component has been added.
Run the frontend app using `just frontend/run dev`
Go to `http://localhost:8443/preferences` and switch the `additional_search_views` flag on.
Go to the homepage and search for …
=> VTag improvements

api/api/serializers/media_serializers.py, api/test/unit/serializers/test_media_serializers.py
Fixes #3945 by @obulat
Added warning for invalid sources from input.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add a warning when source query parameter contains invalid values

docker-compose.yml, documentation/catalog/guides/quickstart.md, documentation/frontend/guides/analytics.md, documentation/frontend/reference/playwright_tests.md, documentation/meta/maintenance/elasticsearch_cluster.md, ingestion_server/justfile, ingestion_server/test/integration_test.py, justfile, setup_plausible.sh
Related to #3876 by @zackkrida
This PR only replaces `docker-compose` in `justfile`s and documentation with `docker compose`.
It does not simplify the `docker ps` script.
@zackkrida mentions the replacement of underscores with dashes for container names in the issue: should this be done manually? Would it also affect production? 
I think it's best to keep the scope of this PR small to fix the critical issue of CI failures due to `docker-compose` command not being found.
All of the `just` commands that used to use `docker-compose` should work as usual.
<details>
```
Version 1.1 …
```
=> Replace docker-compose with docker compose in just scripts and docs

documentation/meta/monitoring/runbooks/nuxt_http_5xx_above_threshold.md
This PR adds some information for troubleshooting Nuxt 5XX errors that we found useful this morning when attempting to identify the root cause of an incident. It borrows a bit from the [API 5XX errors runbook](https://docs.openverse.org/meta/monitoring/runbooks/api_http_5xx_above_threshold.html). 
Check the document and make sure it looks okay
<details>
```
Version 1.1
Suite D4700 …
```
=> Add log insights querying information for Nuxt 5XX errors

frontend/test/unit/specs/components/v-modal.spec.js
Fixes #2321 by @sarayourfriend
This PR replaces the last implicit `getBy*` assertion in our unit tests with explicit `expect().toBeFocused`, and closes the milestone 🎉 
The test should pass and should not throw any warnings.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Replace implicit getBy* assertion in `v-modal` test

automations/js/src/project_automation/prs.mjs
My hypothesis behind merged PRs being found in the "Approved" column is as follows.
- When a PR is approved `pr_automations_init.yml` is triggered (call it run A).
- When the PR is quickly merged GitHub immediately moves it to the "Merged" column because that's a built-in automation of GitHub Projects.
- Run A completes and triggers `pr_automations.yml` (call it run B).
- Run B checks that the PR has two approvals and moves it back to the "Approved" column.
This PR handles situations where a PR is merged quickly after a second approval. It does so by explicitly not moving PR based on the PR review decision if it has already been merged.
<details> …
=> Handle PR automations when quick succession of PR approved and merged

api/api/serializers/base.py, api/api/serializers/media_serializers.py
This PR removes the handling for `Hit` instances from the `BaseModelSerializer` because we no longer serialize hits from ES directly but rather always map them to model instances using the UUID identifier.
1. Check that API responds correctly to the requests.
The integration tests for the API should cover most scenarios, including comprehensive checking of example responses so a deep examination is not needed.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove provision for missing fields on `Hit`

catalog/justfile
When running `just catalog/test`, script fails when there is a space in the directory path.
```
just catalog/test
just _mount-test "bash -c \'pytest \'"
env COMPOSE_PROFILES="catalog_dependencies" just ../up 
env COMPOSE_PROFILES="catalog_dependencies" docker compose -f docker-compose.yml up -d
[+] Running 3/3
✔ Container openverse-upstream_db-1  Running                                                                                                                                                        0.0s 
✔ Container openverse-s3-1           Running                                                                                                                                                        0.0s 
✔ Container openverse-load_to_s3-1   Started …
```
=> Fix: Escape space in `just catalog/test` directory injection

frontend/src/stores/media/related-media.ts
Fixes #4006  by @obulat 
This PR removes the line that sends network error to sentry on related endpoint. This line was accidentally left in code in #3850.
First, try these instructions on `main` branch, and then re-run them in this branch.
On `main`, you should see the analytics and the sentry log in the browser console. Here, there should only be the analytics log, nothing should be logged for sentry.
1. Set`logMockCalls` in sentry config to `true`:
https://github.com/WordPress/openverse/blob/2bd852cb62a91cb61386476014a573bd2c266ff3/frontend/src/utils/sentry-config.ts#L10
3. Run the app using `just frontend/run dev`
4. Go to http://localhost:8443/search/?q=cat
5. Set network throttling to slow 3G and click on the first image result
6. Immediately set network throttling to `offline`. The …
=> Related endpoint error is still sent to Sentry

catalog/dags/providers/provider_api_scripts/auckland_museum.py, catalog/dags/providers/provider_api_scripts/brooklyn_museum.py, catalog/dags/providers/provider_api_scripts/cc_mixter.py, catalog/dags/providers/provider_api_scripts/cleveland_museum.py, catalog/dags/providers/provider_api_scripts/finnish_museums.py, catalog/dags/providers/provider_api_scripts/flickr.py, catalog/dags/providers/provider_api_scripts/freesound.py, catalog/dags/providers/provider_api_scripts/jamendo.py, catalog/dags/providers/provider_api_scripts/justtakeitfree.py, catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, catalog/dags/providers/provider_api_scripts/museum_victoria.py, catalog/dags/providers/provider_api_scripts/nappy.py, catalog/dags/providers/provider_api_scripts/nypl.py, catalog/dags/providers/provider_api_scripts/rawpixel.py, catalog/dags/providers/provider_api_scripts/science_museum.py, catalog/dags/providers/provider_api_scripts/smithsonian.py, catalog/dags/providers/provider_api_scripts/smk.py, catalog/dags/providers/provider_api_scripts/stocksnap.py, catalog/dags/providers/provider_api_scripts/wordpress.py
Fixes #1385  by @sarayourfriend 
https://github.com/WordPress/openverse-catalog/pull/821 introduced a default implementation for `ProviderDataIngester::get_media_type`. All overrides of `get_media_type` where a constant or literal value is returned (e.i. single media type providers) are removed.
The only exception is `INaturalistDataIngester`, which modifies the signature of `get_media_type()` to be static. Otherwise, it would be eligible to use the parent method.
<details>
```
Version 1.1
Suite D4700
San …
```
=> Refactor: Remove `get_media_type()` redundant override in providers with a single media type 

dag-sync.sh
Related to #2037
The DAG sync script does not log except when it made changes. This makes it hard to observe in a production environment to confirm that it is working and running as expected (in a systemd timer).
Run `./dag-sync.sh` and confirm it logs and exits as expected ("no changes"... unless there _are_ changes on `main`, in which case you will see something else!).
<details>
```
Version 1.1
1 …
```
=> Add logging to all dag-sync exits

frontend/feat/feature-flags.json, frontend/src/components/VMediaInfo/VMediaTags.vue, frontend/test/unit/specs/components/AudioTrack/v-audio-track.spec.js, frontend/test/unit/test-utils/i18n.js, frontend/test/unit/test-utils/pinia.js
Fixes #4035 by @obulat
This PR makes the `additional_search_views` flag switchable in prod, and turns it on by default, effectively launching the additional search views.
The test setup and checks had to be updated because the single result pages have slightly changed.
Build and run the app using `just frontend/run build` and `just frontend/run start`
Go to `https://localhost:8443/search?q=cat` and select a search result (image/audio). The new page with link buttons and tags as links should be displayed by default.
You should also be able to open the source/creator/tag pages, without setting the preferences previously.
If you go to `https://localhost:8443/preferences`, you can turn `additional_search_views` off to view the site without the additional views. …
=> Turn on additional search views frontend

frontend/src/data/media-service.ts, frontend/src/stores/media/index.ts, frontend/src/stores/search.ts, frontend/src/types/analytics.ts, frontend/test/unit/specs/data/media-service.spec.ts, frontend/test/unit/specs/stores/media-store.spec.js
Fixes #3775 by @obulat
Fixes #2471 by @sarayourfriend 
This PR re-adds the old PR. 
It is not possible to call `useContext` in the media service because there is no Vue instance available there. This is why I rewrote the code to return the parameters to the store, together with the response data. Then, in the store, we use `this.$nuxt.$sendCustomEvent` to send the event with the returned parameters.
Try making searches and viewing tag/source/creator pages. You should see the search time events logged in the console.
<details>
```
Version 1.1 …
```
=> Add `SEARCH_RESPONSE_TIME` event

api/api/utils/image_proxy/extension.py, api/test/unit/utils/test_image_proxy.py
Fixes #3750 by @obulat 
In `api/utils/image_proxy/extension.py`, `_get_file_extension_from_content_type()` was modified to split the returned `content_type` by `; `in order to remove undesirable appended section of string to the file type. I also made sure to strip any preceding `.` that occurred when passing `content_type` to `mimetypes.guess_extension()`. Finally, `None` was returned anytime the call to `mimetypes.guess_extension()` returned `None`.  
When you attempt to go to [the following link](https://api.openverse.engineering/v1/images/cf168b67-00be-4e4c-8985-ccf388afecd5/thumb), the following 415 error is returned:
`{"detail":"Unsupported media type \"Image extension png;charset=UTF-8 is not supported by the thumbnail proxy.\" in request."}`
`charset=UTF-8` is incorrectly appended …
=> Bugfix to ensure image type is correctly extracted from content type

frontend/src/components/VAudioTrack/VAudioTrack.vue, frontend/src/components/VAudioTrack/VGlobalAudioTrack.vue, frontend/src/constants/audio.ts, frontend/src/stores/active-media.ts, frontend/src/utils/sentry-config.ts, frontend/test/unit/specs/components/AudioTrack/v-audio-track.spec.js
Fixes #3487 by @sentry-io
This PR creates a `playActiveAudio` function within the active media store to play the audio and correctly handle play errors for both the `VAudioTrack`'s  and the `VGlobalAudioTrack`'s audio elements.
I'm not sure about the location of this function. At first, I wanted to put it in a separate file, something like `utils/audio.ts`. However, this function needs access to set the store's message and also needs to be able to send a Sentry message. That's why I put it inside the active media store, and added the html audio element as  a parameter. Suggestions on better placement welcome!
I also fixed the error message showing the key instead of the string in the global audio player.
Use an iphone or an iphone simulator.
Run the app using `just frontend/run dev` …
=> Handle global audio play errors

frontend/feat/feature-flags.json, frontend/nuxt.config.ts, frontend/src/pages/preferences.vue, frontend/src/stores/feature-flag.ts, frontend/test/playwright/e2e/preferences.spec.ts, frontend/test/playwright/playwright.config.ts, frontend/test/playwright/utils/navigation.ts, frontend/test/unit/specs/stores/feature-flag-store.spec.js, frontend/test/unit/test-utils/pinia.js
Fixes #4082 by @obulat
The feature flag store was using the env variable to get the deployment environment and the flag state for this environment. However, the env variable is not available on the client. I moved the setting to `publicRuntimeConfig`. To use the config in the feature flag store functions (`getFlagStatus`, `getFeatureState`), I had to move them inside the store itself. Because `this` was not available in some getters that used these functions, I converted them to actions.
I also updated the e2e setup to only set the feature cookies when we explicitly set some feature state in `preparePageForTests`, otherwise we don't set it to not change the default state.
On main, run the app in production mode using `just frontend/run build` and then `DEPLOYMENT_ENV=production just …
=> Fix the feature flags in production on hydration

api/api/constants/search.py, api/api/docs/audio_docs.py, api/api/docs/base_docs.py, api/api/docs/image_docs.py, api/api/serializers/docs.py, api/api/serializers/media_serializers.py
Fixes #4080 by @obulat
Fixes #4081 by @obulat
This PR makes all `unstable__` search parameters visible in the documentation and adds the warning about them being unstable.
It also updates the collection parameters docs: uses a variable for parameter name to ensure that currently we only use `unstable__collection` and `unstable__tag` in the documentation.
Run the API and read the search endpoint documentation. All unstable fields should be displayed and have a warning. The collection params should have `unstable__` prefix.
<details>
```
Version 1.1 …
```
=> Show the unstable params and improve collection docs

catalog/dags/providers/provider_api_scripts/inaturalist.py
Fixes #4103 by @AetherUnbound
_This has to be the longest time I've spent on such a small change :sweat_smile:_
This PR modifies the iNaturalist flow control so that the step which consolidates the statistics from the load data mapped task waits to run until _after_ all tasks have completed. Previous behavior led this task to be marked as `upstream_failed` as soon as any one of the loading tasks within the mapped task failed. See the issue for more information on that.
The new approach 1) simplifies an XCom access (just for readability) and, more importantly, 2) ensures that the `consolidate_load_statistics` step waits until all `load_transformed_data` tasks complete before moving on. I've left the `NONE_SKIPPED` trigger rule on the post ingestion tasks because I think it is worth having …
=> Wait for iNaturalist load completion before compiling statistics

catalog/dags/providers/provider_api_scripts/stocksnap.py, catalog/tests/dags/providers/provider_api_scripts/test_stocksnap.py
Related to #4101
This PR adds some machinery around the `query_params` handling for the Stocksnap DAG so that we can leverage the options we already have available for query parameters for manipulating the page(s) that the Stocksnap DAG operates on. This doesn't address the error described in the above issue, but it should make it much easier to reproduce (since we should now receive a specific page for where the run failed rather than having to wait 9 hours!).
1. Run the Stocksnap DAG locally, with a sensible ingestion limit. This should behave normally. Use `just catalog/pgcli` and `SELECT count(*) from images;` to verify that the ingestion limit records were loaded.
1. Trigger a new Stocksnap run with the `initial_query_params` set to `{"page": 100}`. Use the same commands as above to …
=> Fill out query params for Stocksnap DAG, allow restarts

documentation/projects/proposals/ingestion_server_removal/20240328-implementation_plan_ingestion_server_removal.md
Fixes #3981 by @stacimc
This PR adds the implementation plan for removing the ingestion server, and moving the data refresh into Airflow. 
I have requested reviews from @sarayourfriend and @AetherUnbound. @sarayourfriend's deep knowledge of the infrastructure, and in particular the ongoing work to the catalog deployments, would be extremely beneficial. @AetherUnbound also has expertise in our infrastructure and catalog, and in orchestrating similar distributed tasks using Airflow.
Please read the IP following the decision-making process defined below.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html). Requested reviewers or …
=> Implementation plan: Ingestion server removal

frontend/nginx.conf.template
Fixes #2996 by @obulat
This PR rewrites the error code when Plausible is unavailable (503) to a 424 error to allow us to count frontend 5xx errors separately from Plausible 5xx errors.
I don't know how to test this.
I tried adding the following patch:
```
Subject: [PATCH] Add a redirect on 503 to frontend nginx
---
Index: frontend/nginx.conf.template
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/frontend/nginx.conf.template b/frontend/nginx.conf.template
--- a/frontend/nginx.conf.template	(revision 19cde7cdff2d8b785ebb4dee50966a37be5dd4eb)
+++ b/frontend/nginx.conf.template	(date 1712906826225)
@@ -73,7 +73,8 @@
resolver $OPENVERSE_NGINX_DNS_RESOLVER;
set …
```
=> Add a redirect on 503 to frontend nginx

api/api/templates/admin/base_site.html, catalog/dags/common/slack.py, catalog/dags/database/staging_database_restore/constants.py, catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py, catalog/env.template, catalog/pytest.ini, catalog/tests/dags/common/test_slack.py, catalog/utilities/README.md, documentation/catalog/guides/deploy.md, documentation/catalog/guides/deployment.md, documentation/catalog/guides/quickstart.md, documentation/ingestion_server/guides/deploy.md
Fixes #737 by @AetherUnbound 
Related to #2037
Update the catalog code to use `production` instead of `prod` and never use `dev` under any circumstances to refer to a deployment environment (references to databases are impossible to fix and must remain). "local" is used to indicate a local development environment. "staging" is essentially unused in catalog runtime code, except for when referring to other resources, and those already use the contemporary, non-legacy names.
Realistically this only affects the slack messaging tool, which skip in non-production environments, and pr review reminders, which do the same. This PR updates both to use `production` now.
Because this is related to the new Airflow deployment, which uses the unified environment names, I've also gone ahead and added the …
=> Update catalog to non-legacy environment names and point to new airflow.openverse.org

catalog/justfile, justfile
I kept finding containers that had been left exited but not removed from my system. Recent investigation led me to find that it was the catalog's `generate-docs` recipe, which hadn't added the `--rm`. There isn't a case where we really care to _keep_ the containers after running something with `just run`, so I've removed the instances where we were explicitly calling `--rm` and moved it to the top level `just run` recipe. Now containers will be removed by default and we don't have to declare it for every new recipe which uses `just run`!
Run `just catalog/generate-docs` and then `docker ps -a` and observe that the container which got started to run the documentation generation no longer exists.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_comm …
=> Always remove containers when using `just run`

catalog/dags/providers/provider_dag_factory.py
This PR makes two changes to the reingestion aggregate failures Slack message:
- For cases where the log list is truncated, explanation text is added
- A DAG run link is added to the message so better context can be provided on failures (workaround for #4177)
I made the following change locally, then added the `SLACK_MESSAGE_OVERRIDE` Variable with the value `true`:
```diff
diff --git a/catalog/dags/providers/provider_api_scripts/phylopic.py b/catalog/dags/providers/provider_api_scripts/phylopic.py
index 5a1f53d77..3c67e15f0 100644
--- a/catalog/dags/providers/provider_api_scripts/phylopic.py
+++ b/catalog/dags/providers/provider_api_scripts/phylopic.py
@@ -94,6 +94,7 @@ class PhylopicDataIngester(ProviderDataIngester):
return self.current_page < self.total_pages
def get_batch_data(self, …
```
=> Add DAG run link, explanation of missing failures to agg failure report

catalog/dags/data_refresh/reporting.py, catalog/tests/dags/data_refresh/test_reporting.py
Follow-up to #4067
Here's the report from the most recent audio data refresh:
The current logic is set to show all sources, regardless of whether there was a change or not. This PR changes the logic so only sources that have increased or decreased in size are shown in the final report. While this doesn't have a huge effect on audio data refreshes, it will for image data refreshes since we have significantly more sources there.
Updated tests should pass. Alternatively, run the data refresh locally after `just api/init` and see that no sources are listed in the completion message because none of the counts changed. 
<details>
``` …
```
=> Don't show sources if their count has not changed

catalog/dags/maintenance/add_license_url.py, documentation/catalog/reference/DAGs.md
Fixes #3885 by @krysal
This PR modifies the existing DAG submitted by @obulat to correct all the rows without a `license_url` in their `meta_data` field. Yesterday, I queried upstream DB and the distribution of rows to fix was the following:
```sql
openledger> SELECT license, license_version, count(identifier)
FROM image WHERE meta_data->>'license_url' IS NULL
GROUP BY license, license_version;
+----------+-----------------+----------+
| license  | license_version | count    |
|----------+-----------------+----------|
| by       | 2.0             | 18013988 |
| by       | 3.0             | 109      |
| by       | 4.0             | 20280    |
| by-nc    | 2.0             | 12378526 |
| by-nc    | 3.0             | 84       |
| by-nc    | 4.0             | 34596    |
| by-nc-nd | 2.0 …
```
=> Modify `add_license_url` DAG for more specific null check

catalog/dags/data_refresh/reporting.py, catalog/tests/dags/data_refresh/test_reporting.py
Fixes #1581 by @AetherUnbound 
Round the data refresh percent change report to 3 digits after the decimal, ignoring zeros. E.g. 100.012365 -> 100.0124.
`just catalog/dags/test`
<details>
```
Version 1.1
Suite D4700 …
```
=> Round decimal record difference percent to three decimals after zeros

api/conf/urls/__init__.py, docker-compose.yml
Every time a `just` command involving docker is run, you get a warning:
According to [documentation](https://docs.docker.com/compose/compose-file/04-version-and-name/), it can be safely removed.
This PR also removes some unused imports from the file defining API URLs.
Compare this branch with `main` looking at the output of the `just api/up`, for example.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove obsolete field from docker-compose.yml

catalog/dags/maintenance/add_license_url.py
Follow-up #4124
Some tasks with many items to modify have timed out in production. The DAG continues to run, but it's expected that more batches will time out with the default 1 hour of execution timeout.
This PR fixes the passing of the `TaskInstance` and increases the time to wait for updates.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Extend `update_license_url` tasks timeout to a day and a half

docker/es/justfile, load_sample_data.sh
Fixes #4212 by @krysal 
This PR adds a new command to the delete indices in the `docker/es/justfile` and use it in the script for loading sample data before triggering the ingestion process.
Found them in the linked issue. Try in `main` and then in this branch to confirm it fixes the problem.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Delete base indices before recreation of sample data

api/api/views/health_views.py, api/test/unit/views/test_health_views.py
Fixes #3746
This PR captures `OperationalError`s that are emitted when the database is no longer available and the `connections.ensure_connection()` function is called as part of the health check for the API. Rather than raise an uncaught exception, this instead converts the exception into an HTTP 503 response (similar to if the Elasticsearch cluster is not in a healthy state).
Tests should pass, but additionally, you can observe this operationally:
1. Run `just a` to start the API stack
1. Run `docker stop openverse-db-1`
1. Visit http://localhost:50280/healthcheck/ and observe that a 503 instead of a generic 500 is returned
<details> …
=> Convert OperationalError into unhealthy health check response

api/api/models/media.py, api/api/serializers/media_serializers.py, api/api/utils/watermark.py, packages/python/openverse-attribution/src/openverse_attribution/attribution.py, packages/python/openverse-attribution/src/openverse_attribution/license.py, packages/python/openverse-attribution/tests/test_attribution.py, packages/python/openverse-attribution/tests/test_license.py
Some files specify the license as "publicdomain". Our standard slug for public domain content is "pdm".
Some files in the API have licenses like "publicdomain" and "sa". This PR adds these licenses to the `openverse-attribution` package. This PR also adds some exception handling around the use of `License` (it should not be necessary anymore, but still).
A more comprehensive update for `License` is #4250, this PR is the baseline fix that will enable us to deploy the API again.
0. Change some rows in the DB to have "publicdomain" or "sa" as the license.
1. Go to their detail page.
2. You should not get 500 errors.
<details>
``` …
```
=> Add "sa" as valid license and map "publicdomain" to "pdm"

catalog/dags/providers/provider_api_scripts/science_museum.py
Fixes production error. Blocking on Science Museum full run, needed to enable the provider in production.
(Hopefully last) small fix for Science Museum to try to get a complete dagrun. Handles case where the record data contains no licensing information.
Run the Science Museum DAG with:
```
"initial_query_params":{
"date[from]":1915,
"date[to]":1925,
"has_image":1,
"image_license":"CC",
"page[number]":11,
"page[size]":100
}
```
This should error immediately on `main` but pass on this branch.
Note that if you want to test the full DAG you need to have the admin variable `SKIPPED_INGESTION_ERRORS` configured with this value:
```
{
"science_museum_workflow": [
{
"issue": "https://github.com/WordPress/openverse/issues/4013",
"predicate": "Service unavailable for url"
}
]
}
``` …
=> Fix Science Museum index out of range error

api/api/management/commands/sendapimoveannouncement.py, api/test/unit/management/commands/test_sendapimoveannouncement.py
Part of #3742 by @sarayourfriend (does not fix because the issue also requires _sending_ the email, i.e., running the command in production).
Review the management command. The message text has already undergone review. The placeholder for the make post URL will be replaced before merging, after the post is available next week.
Review the code and confirm tests are adequate and pass.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add management command to send api move announcement email

documentation/projects/proposals/rekognition_data/20240423-implementation_plan_machine_generated_tags_api.md
2024-05-08
Both of you were chosen for your familiarity with the API and our data, as well as adjacent knowledge of Elasticsearch and the implications decribed in this document.
Resolves #4038
[on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
The deadline for review of this round is **2024-05-08**
=> Implementation Plan: Machine-generated tags in the API

.github/actions/setup-env/action.yml
This PR fixes CI breakage when the `setup-python` action tries to access Pipenv virtualenvs when they do not exist. This should not be a problem because Pipenv is slowly, but surely, going away (tracked in #4166).
<details>
```
Version 1.1
Suite D4700 …
```
=> Give up Pipenv cache to fix CI

api/compose.yml, api/justfile, justfile
This PR extracts the content hash from the PDM lockfile and uses that to tag the API image during development so that the image is automatically rebuilt on `just api/up` if the packages have changed.
This means that you will no longer receive messages like in the API container logs:
```
ModuleNotFoundError: No module named 'xyz'
```
0. Check out the PR.
1. Build the `web` image: `just dc build web`.
2. See the tagged image: `docker image ls`.
3. Add a PDM package: `cd api && pdm add cowsay`.
4. Bring up the `web` service: `just api/up`.
5. You should see that it's building the image again because the packages have changed. …
=> Tag API images with PDM content hash

api/api/management/commands/sendapimoveannouncement.py, api/test/factory/models/oauth2.py, api/test/unit/management/commands/test_sendapimoveannouncement.py
Related to https://github.com/WordPress/openverse/issues/3742 by @sarayourfriend
See https://github.com/WordPress/openverse/issues/2037#issuecomment-2097505853 for a description of the problem needing solving in this PR.
I've marked this as critical because we need to get this email sent as soon as possible, which means we need to deploy this to production ASAP so we can run the command there.
Confirm your understanding of the problem as described in the linked comment, then check whether the modified query would solve the issue. For clarity, I have run the query in production as follows:
```
select count(distinct email) from api_oauth2registration where 'name' in (select 'name' 
from api_throttledapplication where verified = true);
```
This returns 1628 rather than the 2 that the …
=> Fix send email query

frontend/src/components/VAudioTrack/meta/VAudioTrack.stories.mdx, frontend/src/components/VAudioTrack/meta/VWaveform.stories.mdx, frontend/src/components/VBanner/meta/VNotificationBanner.stories.mdx, frontend/src/components/VCollectionHeader/meta/VCollectionHeader.stories.mdx, frontend/src/components/VContentLink/meta/VContentLink.stories.mdx, frontend/src/components/VExternalSearch/meta/VExternalSourceList.stories.mdx, frontend/src/components/VFilters/meta/VLicenseExplanation.stories.mdx, frontend/src/components/VHeader/VHeaderDesktop.vue, frontend/src/components/VHeader/VSearchBar/VSearchBar.vue, frontend/src/components/VHeader/VSearchBar/meta/VSearchBar.stories.mdx, frontend/src/components/VHeader/meta/VContentSettingsModal.stories.mdx, frontend/src/components/VHeader/meta/VHeaderDesktop.stories.mdx, frontend/src/components/VHeader/meta/VHomeLink.stories.mdx, frontend/src/components/VHomeGallery/meta/VHomeGallery.stories.mdx, frontend/src/components/VIcon/meta/VIcon.stories.mdx, frontend/src/components/VInputField/VInputField.vue, frontend/src/components/VInputField/meta/VInputField.stories.mdx, frontend/src/components/VMediaInfo/VByLine/meta/VByLine.stories.mdx, frontend/src/components/VMediaInfo/meta/VMediaLicense.stories.mdx, frontend/src/components/VMediaInfo/meta/VMetadata.stories.mdx, frontend/src/components/VRadio/meta/VRadio.stories.mdx, frontend/src/components/VSafetyWall/meta/VSafetyWall.stories.mdx, frontend/src/components/VSelectField/meta/VSelectField.stories.mdx, frontend/test/storybook/functional/smoke-test.spec.ts
Fixes #2219
This PR adds a `smoke-test` to storybook tests. This test iterates over the Storybook sections, opens each page and checks if there are any console logs or warnings that are signs of broken stories.
Some stories were missing props or store setup steps.
Some component stories were using old no-longer-existing variants (e.g., `size` for full layout of `VAudioTrack`)
See the [first commit's CI logs](https://github.com/WordPress/openverse/actions/runs/8959576556/job/24605165720) in this PR to see sample error display:
<details>
<summary> The error log </summary>
```
playwright-1  | Problems {
playwright-1  |   count: 72,
playwright-1  |   problems: [
playwright-1  |     {
playwright-1  |       kind: 'error',
playwright-1  |       message: "Error rendering story …
```
=> Add storybook smoke test

api/conf/settings/sentry.py
This PR makes Sentry ignore ERROR level logs from `django-structlog` which are created when a request responds with 500 status code. By silencing these logs we might be able to see the real reason 500 response was being generated.
<details>
```
Version 1.1
Suite D4700 …
```
=> Ignore `django-structlog` middleware logs in Sentry

catalog/dags/maintenance/update_science_museum_urls.py, catalog/dags/providers/provider_api_scripts/science_museum.py, catalog/tests/dags/providers/provider_api_scripts/test_science_museum.py, documentation/catalog/reference/DAGs.md
Fixes #4261 by @stacimc 
Hopefully this should be the final change needed to get Science Museum back in shape after the API updates in #4105.
The problem is that even though we're now formatting URLs properly:
* We have about 20k records that are not being reingested (possibly because we have to skip some batches due to an error with the provider API), and whose URLs are therefore not reformatted
* Even when the URLs _are_ reformatted, some portion of those continue to 403
We don't want to ingest records with broken links. So this PR does two things:
* Updates the Science Museum DAG to discard records whose URL cannot be reached
* Adds a one-time maintenance DAG which will be used to update and validate all of our existing records, including ones that are not being picked up by ingestion …
=> Update Science museum urls

.github/actions/load-img/action.yml, .github/workflows/ci_cd.yml, automations/python/workflows/set_matrix_images.py, documentation/meta/ci_cd/jobs/api.md
Fixes #1008 by @krysal
This PR separates the API image into `api` and `api_dev`, the former of which is published to GHCR and does not include dev-dependencies, while the latter is used in CI and includes dev-dependencies.
It also updates the `set_matrix_images.py` code to enforce consistency in the outputs so that fallbacks and null-handling is not needed in `ci.yml`.
1. See that CI builds both `api` and `api_dev`.
1. See that CI uses `api_dev` to run the tests (proven by the CI passing, the prod image does not have pytest).
1. See that CI publishes `api` (cannot test without merging the PR unfortunately). …
=> Make API image smaller by not including dev dependencies

frontend/src/components/VSearchResultsGrid/VSearchResults.vue, frontend/src/locales/scripts/en.json5
Fixes #4300 by @obulat
This PR adds the new result aria-labels for all/image/audio results. Since we show the result count in the page title, we don't need to add the result count to the grid label. 
The results grid (images/audio track boxes grid) should have a screen-reader label: "All/image/audio results for <query>".
Run the app locally using `just frontend/run dev:only`
Go to http://localhost:8443/search/image?q=cat)
Turn on the screen reader and navigate to the search results content list.
You should hear "Entering image results for cat content list" (on a Mac VoiceOver). …
=> Fix the aria label for search result grid

frontend/src/pages/preferences.vue, frontend/src/stores/feature-flag.ts, frontend/src/types/feature-flag.ts, frontend/test/playwright/e2e/preferences.spec.ts, frontend/test/unit/specs/stores/feature-flag-store.spec.js, frontend/test/unit/specs/stores/search-store.spec.js
Fixes #4223 by @obulat
This PR sets the flag states on the server init based on the `DEPLOYMENT_ENV` env variable, instead of checking the state every time we access the flag.
The filtering of flags by switchable or by feature groups was moved to the store, too, to simplify the component code.
The CI checks preferences and sensitive toggle, so the CI passing is a good indicator.
Go to `/preferences` and see that the features are displayed correctly and can be toggled.
=> Initialize feature flag state on the server

api/conf/settings/logging.py
Related to https://github.com/WordPress/openverse-infrastructure/issues/895
The API logging after #4263 was a mix of structured and unstructured logs. This makes it basically impossible to reliably parse multi-line logs, because there was a mix of log-line start indicators (either a datestamp or an opening curly brace).
This PR forces all logging to be structured. There are a couple leaks during startup, but I don't think there's a good way to fix those that isn't convoluted.
In doing this, I read through a lot of the structlog documentation and refamiliarised myself with the Python logging config docs as well. We were doing a lot of unnecessary configuration and I was able to remove a significant amount of duplicative or unused configuration. I've entirely removed the plain "console" …
=> Force all API loggers to be structured

catalog/dags/common/constants.py, catalog/dags/data_refresh/constants.py, catalog/dags/data_refresh/copy_data.py, catalog/dags/data_refresh/dag_factory.py, catalog/dags/data_refresh/data_refresh_types.py, catalog/dags/data_refresh/queries.py, catalog/dags/data_refresh/reporting.py, catalog/dags/legacy_data_refresh/data_refresh_types.py, catalog/tests/dags/data_refresh/test_copy_data.py, documentation/catalog/reference/DAGs.md
Fixes #4146 by @stacimc 
This PR adds the new data refresh factory, which generates DAGs containing (for now) the initial steps and the copy data steps.
These new DAGs will create the temp tables in the API and copy the data into them from the catalog. They do not apply constraints, do anything involving indexing, or promote tables. They should not be turned on in production (but it would be harmless if they were accidentally enabled).
In the code, TODOs are intentionally left to indicate where the additional pieces will be added.
Locally, run an image and an audio DAG for a few minutes to ingest some new records (I ran Cleveland and Jamendo).
Now try the `staging_audio_data_refresh` and `staging_image_data_refresh`. These should run successfully. You can trigger them at the same time to …
=> Add new data refresh factory

api/api/admin/__init__.py, api/api/admin/media_report.py, api/test/unit/admin/test_media_report.py
Fixes #4344 by @AetherUnbound
This PR modifies the Django Admin registrations for various media report related views in order to prevent exposing access to the primary media tables in production. Queries that are made to these tables are often naive and, for such a large table, cause significant issues. However, they're extremely useful to have when running the application locally in order to easily create/reference media while we build out the content safety reporting features.
This will necessarily reduce our available features in production, but because of the nature of the failure which caused this, we couldn't have used those features anyway!
Tests should pass. You can also verify this locally by:
1. `just api/init`
1. Visit http://localhost:50280/admin/ and observe that `Image …
=> Prevent exposing Django Admin features referencing media tables in prod

frontend/src/components/VSkipToContentButton.vue, frontend/src/layouts/content-layout.vue, frontend/src/layouts/default.vue, frontend/src/layouts/search-layout.vue
Fixes #4335 by @obulat
This PR fixes the skip-to-content button.
I didn't add the snapshot tests so that we don't have too many. I could add if the reviewers think this necessary.
Run the app and press <kbd>Tab</kbd>. The skip to content button should not be full-width and should look correctly.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix the skip-to-content button

catalog/env.template, docker/minio/env.template
Internal Improvement for #4355
This pull request updates the bucket names in the `env.template` files to use `openverse-catalog` and removes the creation of the `openverse-storage` bucket. This change ensures consistency between local and production environments as discussed in issue #4355.
=> Update bucket names to use openverse-catalog and remove openverse-storage

catalog/dags/legacy_data_refresh/data_refresh_types.py
Fixes #4352 by @AetherUnbound 
Removed
- `refresh_metrics_timeout`
- `refresh_matview_timeout`
- `create_pop_constants_view_timeout`
- `create_materialized_view_timeout`
from the [DataRefresh dataclass](https://github.com/WordPress/openverse/blob/bc457c020d4051d9d4e758fcfc90f635b8f9a9c2/catalog/dags/legacy_data_refresh/data_refresh_types.py#L17)
<details>
```
Version 1.1
1 …
```
=> Remove popularity & matview timeouts from data refresh configurations

catalog/dags/elasticsearch_cluster/healthcheck_dag.py, catalog/tests/dags/elasticsearch_cluster/test_healthcheck_dag.py
Small issue I noticed while we've been receiving ES health Slack alerts:
Since Slack forming isn't actually markdown, the double asterisk `**` was showing up as unformatted when the message should have had bold text. This PR corrects the instances of `**` to use a single `*` instead which will bold the message in Slack.
Tests should pass.
You can also observe this locally by running the following (as a maintainer):
1. `just c i` (to start the catalog & ingestion server resources)
2. `j run webserver variables set SLACK_MESSAGE_OVERRIDE true` (to enable sending the message to Slack)
3. Enable the `staging_elasticsearch_cluster_healthcheck` DAG
for the catalog or `just api/generate-docs` for the API) where …
=> Fix Slack message formatting for ES health alert

ingestion_server/ingestion_server/cleanup.py
Follow up on #4163.
Add several logging points to determine what happens with this step that hangs with production data. Also, skip saving tags to see if we can get the first files for URL fields.
1. make some rows of the image table in the catalog dirty by removing the protocol in one or several of the URLs (url, creator_url, or foreign_landing_url) or modify the tags for low accuracy.
2. `just catalog/up && just api/init`
3. Observe the logs of the ingestion server container.
<details> …
=> Add logs to cleaning steps in the ingestion server and skip saving tags

frontend/src/locales/scripts/create-wp-locale-list.js, frontend/src/locales/scripts/get-validated-locales.js
As discovered by a contributor in [this issue](https://github.com/WordPress/openverse/pull/4224#issuecomment-2119152158), our translations of the Saraiki language were not appearing in production. I realized that the language was being filtered out of our valid translations because it does not have a `langCodeIso_639_1` property in our code. This is because the language is part of the https://en.wikipedia.org/wiki/ISO_639-3 standard, which is essentially v3 of the list of international language codes, and our code was only including languages present in v1. 
Saraiki appears to be the only language impacted by this change
`just frontend/run i18n` and `just frontend/run dev` locally and observe that the `/skr` path now works. You could also count and confirm that the locale chooser now has …
=> Fix frontend to include languages that do not have iso-639-1 codes

api/api/controllers/elasticsearch/related.py, api/api/controllers/search_controller.py, api/conf/settings/__init__.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
Fixes #4076 by @obulat 
This PR proposes an alternative solution to the one proposed in the issue: The search controller should limit the results queried to those associated with existing and not hidden providers. IMO, this is a simpler approach that takes advantage of the existing code structure. It fits the "filtered provider" concept in the sense that it queries for valid providers instead of skipping the "excluded." What I don't know is if we want to update the value of the `FILTERED_PROVIDERS_CACHE_VERSION` variable in this case.
1. Spin up the API, `just a`, and go to http://localhost:50280/v1/images/ to confirm the search is working with the usual providers
2. Hide one of the image providers via Django admin, e.g. StockSnap.
3. Confirm the results for the hidden provider are not …
=> Change search query approach to include only available providers

ingestion_server/ingestion_server/queries.py, ingestion_server/test/unit_tests/test_queries.py
Fixes #4381 by @krysal
As explained in the issue, we're ditching this clause here.
1. Set the environment variable for the limit to a number lower than 5000. Eg.:
```
DATA_REFRESH_LIMIT=1000
```
2. Start a data refresh
```sh
just api/up && just docker/es/delete-index image-init && \
just ingestion_server/ingest-upstream
```
3. Wait for the process to finish; locally, it is very quick (less than a minute), and promote the table.
```
just ingestion_server/promote
```
4. Verify the number of images is correct with `just api/pgcli` and
```
SELECT COUNT(*) FROM image;
``` …
=> Drop `ORDER BY` clause from copy step when adding a limit 

catalog/dags/common/github.py, catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py, catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py, catalog/tests/dags/maintenance/test_pr_review_reminders.py, catalog/tests/factories/github/team.json, documentation/catalog/reference/DAGs.md
Fixes #4327 by @zackkrida
This PR modifies the PR reminder review DAG to use a special urgency level, `contributor` (3 business days), for any pull request that isn't opened by one of the `WordPress/openverse-maintainers` users (or a few other bot accounts). I modified the DAG workflow to use the TaskFlow API syntax, and updated tests accordingly as well.
3 days was chosen for this level based on the linked issue and this documentation: https://docs.openverse.org/general/contribution/good_first_and_help_wanted_issues.html#timing-and-process
The new tests should pass and make sense. We don't have any PRs open right now that qualify for this new ping criteria, but if you have a copy of the GitHub PAT we use, you can test that the DAG still runs as expected with the new dependency.
PRs) or …
=> Always assume special urgency for contributor PR pings

api/api/controllers/elasticsearch/related.py, api/api/controllers/search_controller.py, api/conf/settings/__init__.py, api/test/unit/controllers/elasticsearch/test_related.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/controllers/test_search_controller_search_query.py
This reverts commit 3d7fa0908e5b18d1b53f1a8c8bee713317556d42.
We believe this commit may be the root cause of Elasticsearch performance degradation that caused an outage earlier today. Full investigation on this can be seen below:
`/image-ff1c23632fd149d08239d7c59e11f1a9-filtered/_search`
```json
{
"profile": true,
"query": {
"bool": {
"must_not": [
{"terms": {"provider": ["ccMixter"]}},
{"term": {"mature": true}},
{"term": {"identifier": "image_identifier"}}
],
"should": [
{"match": {"title": "long string not previously searched"}},
{"terms": {"tags.name.keyword": ["long string not previously searched"]}}
]
}
}
}
```
Took **24ms**.
`/image-ff1c23632fd149d08239d7c59e11f1a9-filtered/_search`
```json
{
"profile" true,
"query": {
"bool": {
"filter": [
{"terms": {"source": ["flickr", …
```
=> Revert "Change search query approach to include only available providers (#4238)"

docker/dev_env/Dockerfile, docker/dev_env/entrypoint.sh, docker/dev_env/run.sh, ov
This PR makes the Docker-based setup for Openverse usable on macOS. It has some rather major differences from the Linux-compatible implementation in #4343.
This PR
- drops user management entirely, running the container as the default user
The original approach where user is being supplied to the container via `--user` is inherently incompatible with macOS because there is no `docker` group when running Docker containers on macOS either via Docker Compose or Orbstack.
- changes the preserved volume to target `/opt` instead of from `$HOME`
This is a consequence of removing user management. This works in fundamentally the same way except that the tools need to be configured via env vars to use paths under `/opt`.
- removes redundant/autoinstalled packages, updates package explanations and …
=> Make Dockerfied development environment compatible with macOS

api/api/models/media.py
Related to #703 by @obulat
In the interest of closing this PR, I changed the approach only to warn when the license is computed, as suggested by @obulat. The #703 issue will addressed when we confirm #4318 is not an issue anymore.
---
My understanding is that the computation from `openverse_attribution.license.License` can be removed but we still need the property.
This PR should not be merged until the updated `add_license_url` run is completed and it's confirmed the `image` table in the Catalog does not have more `NULL` values for this field. 
If you are wondering about `audio` I confirmed all items have this field set to something else than `NULL`.
```sql
openledger> SELECT COUNT(identifier) FROM audio WHERE meta_data->>'license_url' IS NULL;
+-------+
| count |
|-------|
| 0     | …
```
=> Warn on `license_url` computation in the API

frontend/src/components/VHeader/VHeaderMobile/VFilterTab.vue, frontend/src/locales/scripts/en.json5, frontend/test/locales/ar.json, frontend/test/playwright/utils/navigation.ts
Fixes #957 by @obulat
This PR adds a common `aria-label` to both the `VFilterTab` and `VFilterButton` (based on feedback provided in #957) which more appropriately conveys in text format what sighted users are expected to understand about the action component. The new label takes the form (in English) of `Filters ({number})`.
I've opted to reduce the set of changes to just this, since the testing translation changes were pretty unrelated and this makes the changeset much smaller.
1. Run the app locally using `just frontend/run dev`
2. Visit http://localhost:8443/search/?q=cats&license=pdm,cc0,by using a wide viewport
3. Right click on the filters button, and click "Inspect Accessibility Properties" (for firefox, not sure what this looks like in Chrome)
4. Verify that the text present for …
=> Improve accessibility labels for filters tab and button

api/api/admin/media_report.py, api/api/models/__init__.py, api/api/models/audio.py, api/api/models/image.py, api/api/models/moderation.py, api/api/templates/admin/api/components/media_additional.html, api/api/templates/admin/api/components/media_decisions.html, api/api/templates/admin/api/components/media_reports.html, api/api/templates/admin/api/media/change_form.html, api/api/templates/admin/api/media/change_list.html, api/api/templatetags/get_attr.py, api/api/utils/moderation_lock.py, api/test/unit/admin/test_media_report.py, api/test/unit/utils/test_moderation_lock.py, load_sample_data.sh
Fixes #3638 by @sarayourfriend 
Fixes #3639 by @sarayourfriend
This PR
- makes it possible for moderators to view the media model list and change pages, in addition to accessing decision pages and making changes to decision-media relationships
- adds soft-locking and warning messages so that moderators can avoid potential conflicts
- makes the media model (and not the media-report model) the root of all moderation activity
- adds additional information to media model change page
- provides comprehensive history of pending/reviewed reports and past decisions for any media item
- adds actions for moderation into the media model change page
This PR also
- breaks admin templates into smaller, more-manageable components
- adheres more closely to Django idioms for site links in the admin
- …
=> Make media items the centre for all moderation activity

.gitignore, docker/dev_env/entrypoint.sh, docker/dev_env/expand_aliases.py, justfile, ov
Fixes #4407  by @sarayourfriend 
cc @AetherUnbound and @dhruvkb who are probably the most interested with this.
An alternative to https://github.com/WordPress/openverse/pull/4408 using a Python-based approach.
This approach has all the features of the bash approach in https://github.com/WordPress/openverse/pull/4408, but none of the disadvantages. It shares the same overall problems like the aliases only being available in the entrypoint. They aren't available inside `just` recipes themselves, for example. I think that's fine though!
Try `ov j`, `ov nuxt`, and `ov welcome`. See if it works and makes sense!
- [N/A] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
for the catalog …
=> Add support for aliases to `ov`

api/api/admin/media_report.py, api/api/templates/admin/api/components/media_complain.html, api/api/templates/admin/api/components/media_decisions.html, api/api/templates/admin/api/components/media_reports.html, api/api/templates/admin/api/media/change_form.html
Fixes #4412 by @dhruvkb 
Fixes #4413 by @dhruvkb
This PR
- updates the sidebar filter to show both moderation queue and all media items
- enables the creation of reports from the media change view
- makes code quality and interface improvements
- use of descriptions as per Django admin UI
- changing hardcoded URLs to `{% static %}`
- showing helpful messages when reports/decisions do not exist
1. Check out the PR and run the dev server.
2. Go to the image/audio list, you should see the moderation queue by default.
3. Click on "All" in the sidebar, you should now see all 5000 media items listed.
4. Open an item that's not in the moderation queue, you should see descriptive messages in the report and decision list sections.
5. Create a report using the form in the "Create report", the …
=> Add report creation, better filtering and more improvements to admin views for media

api/compose.yml, api/justfile, justfile
Fixes #4289 by @dhruvkb 
This PR removes the use of the NGINX based services `nginx` and `proxy` from the `api` profile. This means they will no longer be created when invoking the `api/up` recipe.
Instead these services, along with the main API services `web` and `cache` are part of the `api_extra` profile and they can all be created by invoking the `api/up-extra` recipe (modelled after the `catalog_dependencies` approach). 
This should speed up CI because of fewer services being built and raised.
<details> …
=> Move NGINX-based services out of the API profile

.github/auto-label.json, .github/filters.yml, .github/workflows/ci_cd.yml, .github/workflows/migration_safety_warning.yml, .github/workflows/pr_automations.yml, .github/workflows/pr_automations_init.yml, automations/js/src/label_pr.mjs
Fixes #3823 by @dhruvkb 
Fixes #4203 by @AetherUnbound 
Fixes WordPress/openverse-infrastructure#740 by @dhruvkb
This PR overhauls the complete labelling system to unify it in one place instead of the various disconnected systems.
Now the end-to-end labelling process is handled by the PR automations workflow.
Thanks to @GauranshMathur for bringing this up.
<details>
```
Version 1.1 …
```
=> Overhaul the complete labelling system

ingestion_server/ingestion_server/cleanup.py, ingestion_server/test/unit_tests/test_slack.py
This reverts commit 43d4d09.
Fixes ingestion server deployments to production.
This PR reverts #4163 since it was causing the image data refresh process to hang, and we won't need to file for tags anyway. I re-added the changes to use `perf_counter()` for times and a little fix in the slack unit test to avoid a warning, but I'm happy to omit those in this PR if it's preferred to make those changes separately.
Try `just api/recreate,` which runs the data refresh in the ingestion server, and verify the API results continue working as expected.
- [ x My commit messages follow [best practices][best_practices].
- [N/A] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog PRs) or the media properties generator …
=> Revert "Save cleaned data of Ingestion Server to AWS S3 (#4163)"

catalog/dags/maintenance/trim_and_deduplicate_tags.py, documentation/catalog/reference/DAGs.md
Fixes https://github.com/WordPress/openverse/issues/4199 by @krysal
I've made use of the `batched_update_dag` to trim and deduplicate tags.
The approach is essentially: for each row, filter the list of tags distinct on the trimmed tag name, then set tags to the filtered list.
It's worth noting that I don't know whether doing this "for all rows" by using a `WHERE true` query is safe, and I'm asking for clarification on what the specific limitations of our data transformation are in https://github.com/WordPress/openverse/pull/4143#issuecomment-2143228283.
The update query produced by the batched update DAG looks like this:
```sql
UPDATE image
SET tags = (
SELECT
jsonb_agg(
jsonb_set(
deduped.tag,
'{name}',
to_jsonb(deduped.trimmed_name)
)
)
FROM (
SELECT DISTINCT ON (tag->>'name', …
```
=> Add DAG to trim and deduplicate tags

api/api/utils/waveform.py, api/api/views/audio_views.py, api/test/integration/test_audio_integration.py, api/test/integration/test_image_integration.py
Fixes https://github.com/WordPress/openverse/issues/4218 by @obulat 
I've added error handling in three specific places:
1. When downloading the audio and processing the response. This will cause a downstream exception similar to the 424 of the thumbnails
2. When generating the waveform using `audiowaveform`. This will cause a separate 424 indicating the issue was with waveform generation, not an upstream provider connection issue.
3. When removing the file. This will not cause the request to fail, but will be logged to Sentry for us to investigate. This happens after the request payload is actually generated, and does not need to prevent the request from completing.
Check out the unit tests and confirm they cover the error cases. There's no real way to manually test this that I can see, …
=> More precisely handle waveform generation failures

frontend/src/components/VMediaInfo/VMediaTags.vue, frontend/src/locales/scripts/en.json5, frontend/src/pages/tags.vue
Fixes #4379 by @obulat 
This PR adds copy to the generated tags page. It also renames the page to "Tags". @obulat feel free to merge this into your PR for review there, or reviewers can verify the copy here first if preferred.
1. Run `just f` to start the frontend
2. Navigate to http://localhost:8443/tags and check the copy/formatting
=> Tags page copy

api/api/management/commands/backfillmoderationdecision.py, api/test/factory/models/audio.py, api/test/factory/models/oauth2.py, api/test/unit/management/commands/test_backfillmoderationdecision.py
Fixes #3641 by @sarayourfriend 
This PR adds the command as described in the implementation plan section for [Deprecating and removing report status](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#deprecating-and-removing-report-status). It takes as options the media type, the username of the moderator (in production it should be `opener` but in local we use `deploy`) and a flag for whether to run the command or just get the count of report to process.
Verify that the mapping is according to the specification.
To test manually, create some reports, mark them with a `reason` other than "pending" and run the command.
```
just dj backfillmoderationdecision [--dry-run | --no-dry-run] …
```
=> Add `backfillmoderationdecision` management command

catalog/dags/common/storage/media.py, catalog/tests/dags/common/storage/test_media.py, ingestion_server/ingestion_server/cleanup.py
Fixes #4464 by @AetherUnbound 
The pull requests moved the by tag from the fuzzy match group to the exact match group.
run the command `./ov just catalog/test`
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Moved by tag from the fuzzy match group to exact match

catalog/dags/maintenance/trim_and_deduplicate_tags.py
Related to #4429 
I realised when working on https://github.com/WordPress/openverse/issues/4452 that the deduplication does not actually work on the _trimmed_ name :facepalm:. This fixes that by using the trimmed name in the distinct on clause.
To test, start with a fresh catalog DB (`just down -v && just catalog/init`) then run this sql in `just catalog/pgcli`):
```sql
UPDATE image
SET tags = (
SELECT jsonb_strip_nulls(jsonb_agg(augmented.tag) || jsonb_agg(augmented.new_tag) || jsonb_agg(augmen
ted.old_tag))
FROM (
SELECT
jsonb_build_object('name', '  ' || "name" || ' ', 'provider', provider, 'accuracy', accuracy) t
ag,
jsonb_build_object('name', "name", 'provider', 'magical_computer_vision', 'accuracy', accuracy)
new_tag,
jsonb_build_object('name', "name", 'provider', provider, …
```
=> Fix trim and deduplicate tags deduplication

.github/workflows/pr_automations_init.yml
This PR attempts to fix our PR automation init workflow, which is currently failing on the infrastructure repository. This is because we recently added the `permissions` setting for this line as part of #4438, and [per the GHA documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions):
> For each of the available scopes, shown in the table below, you can assign one of the permissions: `read`, `write`, or `none`. If you specify the access for any of these scopes, all of those that are not specified are set to `none`.
This is based off a suggestion from https://github.com/actions/checkout/issues/985#issuecomment-1364034319
We will have to merge this, then sync the files to the infrastructure repo once merged.
PRs) or the media …
=> Make read contents permission explicit for PR automations

docker/dev_env/Dockerfile, docker/dev_env/exec.py, docker/dev_env/run.sh, docker/dev_env/setup_env.sh, ov
Fixes https://github.com/WordPress/openverse/issues/4490 by @sarayourfriend 
Implements the solution described in the issue for using a persistent container to run `ov`. I've also added support on Linux for running commands as root (macOS already always runs commands in the container as root).
Anecdotally, `ov` commands do run noticeably faster for me. It's a matter of maybe 50-100ms at most, which is less so _faster_ and moreso just plain responsive feeling. If you happen to notice a change here one way or the other, please let me know. I'm curious to know how fast `docker ps` is on macOS hosts that have the virtual machine to contend with (my impression is they should be plenty fast?).
To test this change:
1. Run `ov clean && ov init` to get a brand new environment set up
2. Make sure …
=> Use a persistent container for `ov`

api/api/utils/check_dead_links/__init__.py
Part of https://github.com/WordPress/openverse/issues/4507 by @sarayourfriend 
See the issue for rationale of both the `get_aiohttp_session` change and the new timing logs.
The PR does both, using `time.time` to calculate the request timing.
Run the API locally with `./ov just api/up` (and `./ov just api/init` if you don't have data). Tail the logs with `./ov just logs web` and make an image request with `filter_dead=True` (this matches the production default): http://localhost:50280/v1/images/?filter_dead=True
In your logs, you should see a line like this for each verified link:
```
web-1  | 2024-06-18T03:30:03.753846Z [info     ] dead_link_validation_timing    [api.utils.check_dead_links] filename=__init__.py func_name=_head ip=172.18.0.1 lineno=59 …
```
=> Log dead link verification request timings

documentation/projects/proposals/ingestion_server_removal/20240328-implementation_plan_ingestion_server_removal.md
Fixes #4456 by @AetherUnbound
This PR modifies the ingestion server removal IP to explicitly include a plan for handling the filtering of data which occurs during the current "cleanup" step and _will not_ be handled by the data normalization project.
While the change to the plan is minimal, I added a significant footnote just to provide context, describe what's needed, and then provide suggestions for the future. The suggestions made are **not necessary** at this moment, in my opinion. We can start with just slapping what used to be the "cleanup" step of the ingestion server into the new data refresh DAG and calling it good for now. I do think, though, that we could make an issue for optimizing this down the line and doing it in a more "Airflow-y" manner. It'll require more work to do …
=> Explicitly include Filter Data step in ingestion server removal IP

docker/dev_env/run.sh
This makes `ov` contextual to the working directory, so you can rely on your host CWD inside `ov`. This works because the Openverse repository is mapped with the literal directory path from your host (rather than to a distinct container path), so the CWD will exist in the container, so long as `ov` is run from within the repository.
I considered making this conditional by testing whether `$(pwd)` is actually a subpath of `OPENVERSE_PROJECT`, but running `ov` outside of the repository seems weird to try to explicitly support :thinking: 
Think of something you often do that is CWD contextual. Maybe, for example, running a just recipe from withing a subproject's directory. Or maybe using `pnpm exec`. Or `pdm run`. Now cd to the directory and prefix it with `ov`. Start with `pwd` and you'll …
=> Set `ov` workdir to current working directory

documentation/meta/media_properties/etls.md, documentation/meta/media_properties/index.md
Fixes #4455 by @AetherUnbound
This PR adds a document which visualizes and describes the current and proposed data flows for the project. It also enumerates the ETL steps at each stage to make it easy to understand which operations are happening at which step.
I didn't include any transformations that happen between the client and the frontend because I wasn't aware of them, but please feel free to point them out and I can add them!
Check out the document preview and make sure it makes sense.
<details> …
=> Add data flow diagram for various ETL steps in pipelines

.editorconfig, frontend/Dockerfile.nginx, frontend/nginx/nginx.conf.template, frontend/nginx/snippets/cached_location.conf, frontend/nginx/snippets/nuxt_location.conf
Fixes https://github.com/WordPress/openverse/issues/4470 by @sarayourfriend 
Using a modified version of the Nginx configuration Nuxt suggests here: https://v2.nuxt.com/deployments/nginx/#using-nginx-with-generated-pages-and-a-caching-proxy-as-fallback
To test this, first run Nuxt with Nginx on `main`. For this testing **you may need to comment out the block in nuxt.config.ts** that forces browsers to upgrade requests to HTTPS, as we won't be working with HTTPS for this local testing. Whether you'll need to or not depends on how your browser enforces CSP. If you see CSP errors logged in your browser dev console, comment this block out to solve them.
https://github.com/WordPress/openverse/blob/83ed9647e8b33dbb13b356f2c92f683041506534/frontend/nuxt.config.ts#L20-L26
On `main`, run `ov just …
=> Add caching to frontend Nginx configuration

api/justfile
This PR shortens the PDM hash used by the API image to the first 8 characters.
This hash is useful to automatically build a new API image when the API packages have changed. Truncating it to 8 chars keeps it long enough to avoid collisions while making it short enough to not completely break the table layout the output of `docker image ls`.
<details>
```
Version 1.1
1 …
```
=> Shorten PDM hash to first 8 characters

api/Dockerfile, api/pdm.lock, api/pyproject.toml, api/test/unit/utils/test_image_proxy.py
https://github.com/h2non/pook/pull/132 will introduce breaking changes to pook. There isn't a version released with the breaking changes yet, but if I merged the PR, the Openverse API tests would start failing due to it being affected by the breaking changes that will come in pook v2. The API uses `master` instead of a stable version reference, so anything that changes on `master` could break the API if a new `pdm lock` updates the git revision used in the lock file.
Change `pook` in the API pyproject.toml to use a real version range.
The catalog and ingestion servers also use pook but already use a specific version or range.
CI should pass. This shouldn't have any effect on the actual test runs. Everything the API relied on (why it started using `master`) already exists on the latest …
=> Do not use unstable pook reference for API

setup_plausible.sh
Fixes #942 by @obulat
#943 has made the Plausible setup idempotent. However, it appears that the API response text has changed, and the check for domain does not work anymore. So, when you run `just init` for the frontend again, you get this error:
```
Error: {"error":"domain: This domain cannot be registered. Perhaps one of your colleagues registered it? If that's not the case, please contact support@plausible.io\n"}
```
Checkout this branch and run `./ov just init` twice. You should not see the domain-related error logged in the terminal (the one you would currently see on main. …
=> Fix Plausible setup after domain was already set

ingestion_server/ingestion_server/cleanup.py, ingestion_server/test/unit_tests/test_cleanup.py
Related to #3912 by @krysal
This PR fixes several issues on the Ingestion Server and prepares it to upload the files.
- Saves files of cleaned data to a specific temporary directory locally before being send to S3 (this was an @AetherUnbound's previous suggestion)
- Recreates the temp directory before cleaning to avoid mixing values between different data refresh processes
- **Removes single quotes on cleaned values**. Otherwise, the file has URLs surrounded by `'`, which isn't necessary and makes it quite complicated to save the data in a database table later
- Adds stocksnap to TLS_CACHE manually (for some reason, it was being registered as TLS not supported, which is not true)
1. Spin up the services
```
just a && just c
```
2. Make some rows of the image table in the catalog "dirty" …
=> Remove single quotes in values of Ingestion Server's TSV files

api/compose.yml, catalog/compose.yml, docker-compose.yml, ingestion_server/compose.yml
This PR
- specifies a `pull_policy` of `never` for custom Openverse images that are meant to be built on-device
- <s>removes the `image` field for services where the image name is the same as the default `openverse-<service_name>`</s> (this had to be reversed because ingestion server integration tests would fail)
Effectively, these changes mean that the warning referenced in https://github.com/WordPress/openverse/pull/4526#discussion_r1646764935 will go away. <s>This will be further expanded by #1910 which will expand the second change to apply to more services.</s>
This also makes it safer by ensuring that we never accidentally pull a (potentially nefarious) image named `openverse-*` from the Docker registry.
1. Check out this PR.
2. Remove any number of `openverse-*` images from Docker. …
=> Specify pull policy for `openverse-` images

api/pdm.lock, api/test/unit/configuration/test_link_validation_cache.py, api/test/unit/controllers/test_search_controller.py
Several warning messages have been accumulating in the running of API tests. In `main`, you will see and output like the following below. Most of these can be fixed or silenced and should be addressed given they're just noise in the tests' output.
```python
test/unit/controllers/test_search_controller.py::test_get_result_and_page_count[5-5-0-1-expected1]
/.venv/lib/python3.11/site-packages/_pytest/python.py:1792: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: schemathesis, Hook: pytest_pyfunc_call
ZeroDivisionError: division by zero
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
self.ihook.pytest_pyfunc_call(pyfuncitem=self) …
```
=> Bump `schemathesis` to v3.31.0 and silence warnings on API tests

catalog/dags/database/batched_update/batched_update_dag.py, catalog/dags/database/batched_update/constants.py, catalog/dags/popularity/popularity_refresh_dag_factory.py, catalog/utilities/dag_doc_gen/dag_doc_generation.py, documentation/catalog/reference/DAGs.md
Fixes #4457 by @AetherUnbound
This PR splits the `batched_update` into two separate DAGs as described in the above linked issue: `batched_update` and `automated_batched_update`. None of the parameters for each DAG are changed _at this time_, though they may be affected later as part of the [batched update improvements milestone](https://github.com/WordPress/openverse/milestone/34).
@stacimc this might interest you - this was the first time I've tried to create a dynamic DAG using the TaskFlow API/`@dag` decorator syntax. Turned out to be pretty simple, even if it's a little wonky! I'm happy to change the format to use the `with DAG(...) as dag` syntax if that makes it easier. I haven't seen anyone do it this way in the research I did online, for what it's worth.
1. Run `ov just c` to …
=> Split `batched_update` DAG into automated and manual DAGs

api/api/controllers/search_controller.py, api/api/utils/check_dead_links/__init__.py, api/conf/settings/__init__.py, api/conf/settings/link_validation.py, api/test/factory/es_http.py, api/test/integration/test_dead_link_filter.py, api/test/unit/configuration/test_link_validation_cache.py, api/test/unit/controllers/test_search_controller.py, api/test/unit/utils/test_check_dead_links.py
Fixes #4507 by @sarayourfriend 
Please see the linked issue for the rationale of lowering to 0.8 specifically.
The PR lowers the timeout to 0.8, and makes it configurable via environment variables. That's mostly a convenience/safety net, in case this timeout ends up not working out. The environment variable will allow us to change it without needing to create a new release.
As discussed in the issue, I also added the provider to the timing log lines, which we can use to decide whether we need certain provider-specific timeouts (e.g., if there are particularly slow providers). Adding the provider to the log contents makes it easier for us to check if one provider or other is overly affected by the lower timeout.
CI must pass, and existing tests must pass. Follow instructions from #4508 to …
=> Decrease link validation timeout

documentation/projects/proposals/ingestion_server_removal/20240328-implementation_plan_ingestion_server_removal.md
Updates the ingestion server removal IP to reflect changes discussed [here](https://github.com/WordPress/openverse/issues/3925#issuecomment-2207360055) (moving away from the ASG approach and back to managing EC2 instances more directly).
<details>
```
Version 1.1
Suite D4700 …
```
=> Update ingestion server removal IP with EC2 approach

.github/actions/setup-env/action.yml, frontend/Dockerfile, frontend/Dockerfile.playwright, frontend/bin/playwright.sh, frontend/docker-compose.playwright.yml, frontend/package.json, package.json
Fixes #3807 by @dhruvkb
This PR replaces `pnpm/action-setup@v3` with `corepack enable` for setting up `pnpm` in the CI and Docker containers.
For the Playwright Docker containers, corepack looks into the closest `package.json` file to find the pnpm version, so I added it in the `frontend/package.json`
Since we no longer need to provide the pnpm version to the set up script (it's extracted from `package.json`'s `packageManager` field), I removed the related env variables.
<details> …
=> Update pnpm and use corepack

indexer_worker/indexer_worker/tasks.py
Fixes #4534 by @stacimc  
This PR adds a dataclass with type hints for each field for index worker task status. The task status was stored as dictionary before.
`just build && just up`
Use [elasticvue](https://app.elasticvue.com/cluster/0/indices) to Delete All Documents from one of your existing indices. Eg:  `audio-init-filtered`. The index should now have 0 documents.
Now run just `catalog/shell`, and you should be able to curl the indexer worker.
Replace the target_index name if you don't have audio-init-filtered
Note the start_id/end_id we're using, to make it reindex only 100 records
`curl -X POST -d '{"model_name": "audio", "table_name": "audio", "start_id": 0, "end_id": 100, "target_index": "audio-init-filtered"}' -H "Content-Type: application/json" …
=> Create a dataclass for indexer worker TaskStatus

.github/workflows/ci_cd.yml, docker/dev_env/Dockerfile, documentation/frontend/reference/testing_guidelines.md
Fixes #4535 by @sarayourfriend 
This PR aims to make debugging Playwright test failures caused by snapshot changes easier by modifying the current Playwright CI workflow to run tests with the `-u` option which basically updates modified snapshots automatically. We then upload a gzipped git patch blob of these changes so the initiating user can download and apply the patch to their branch without having to run Playwright updates(which happen to be a resource intensive process) locally.
This can be tested by triggering a failing Playwright workflow due to UI changes. …
=> Make running Playwright to update snapshots easier

catalog/dags/database/catalog_cleaner/catalog_cleaner.py, catalog/dags/database/catalog_cleaner/constants.py, documentation/catalog/reference/DAGs.md
Fixes #3415 by @krysal 
This PR adds a DAG similar to the `bactched_update` but is dedicated to using the files from AWS S3 generated from the ingestion server. I created a new DAG since the `batched_update` would need more tweaks than just loading the data from S3 into a table since the update is performed by joining the newly created table with `image`, and also does the batch updates in parallel using the Dynamic Task Mapping feature of Airflow. Given several `batched_update` runs have been performed with the popularity calculations, it suggests it's possible to parallelize this task as long as the rows to be modified do not overlap. The ingestion server also similarly applies the updates.
This is a proof of concept to see the feasibility of parallelizing the DB updates, making a …
=> Add `catalog_cleaner` DAG

api/api/utils/check_dead_links/__init__.py, api/conf/settings/sentry.py
This PR changes the logger used inside the `_head` function in `check_dead_links` to a new one that will be ignored in Sentry.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Use a separate logger for dead links check that Sentry will ignore

catalog/dags/common/slack.py, catalog/dags/elasticsearch_cluster/healthcheck_dag.py, catalog/tests/dags/common/test_slack.py
Fixes #4613 by @sarayourfriend
This PR adjusts the default messaging pattern in Airflow to remove the environment from the username (see the linked issue for rationale).
It also changes the username and icon for Elasticsearch healthcheck related alerts to make the cluster in question more prominent, and the alert itself distinct from other Airflow alerts. Here's a screenshot of the new alert:
1. Start the catalog and ingestion server stacks with `ov c` and `ov i`
2. Force Slack messages by adding a variable called `SLACK_MESSAGE_OVERRIDE` with the value `true`
3. Kick off either `staging_elasticsearch_cluster_healthcheck` or `production_elasticsearch_cluster_healthcheck`
4. Observe a similar message in Slack
PRs) or the media properties generator (`ov just catalog/generate-docs …
=> Remove env from Airflow alerts, improve ES alert username & icon

frontend/src/utils/attribution-html.ts
Fixes the incorrect HTML for `<img>` tags in our "Credit the Creator" section HTML. Previously, image tags were rendered as `<img></img>` which is invalid HTML. 
Now, `<img>` and other self-closing HTML tags will be rendered as `<img />` (note the closing "/" at the end of the tag) which is valid.
=> Fix HTML creator crediting incorrect image tags

.pre-commit-config.yaml, automations/js/prettier.config.js, automations/js/src/count_user_reviewable_prs.js, automations/js/src/label_pr.mjs, automations/js/src/last_week_tonight.mjs, automations/js/src/project_automation/issues.mjs, automations/js/src/project_automation/prs.mjs, automations/js/src/project_thread_updates.js, automations/js/src/render-jinja.js, automations/js/src/sync_labels.mjs, automations/js/src/utils/html.mjs, automations/js/src/utils/projects.mjs
This PR removes JavaScript logic from the `automations/js/src/project_automation/prs.mjs` file which moves cards into the "Needs 2 Reviews" column of our [PR project board](https://github.com/orgs/WordPress/projects/98?query=sort%3Aupdated-desc+is%3Aopen). 
```diff
-  } else {
-   await prBoard.moveCard(prCard.id, prBoard.columns.Needs2Reviews)
-  }
```
This PR _also_ updates the entire file to conform to our prettier config.
Review the logic and hope it works!
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
=> Remove the "2 Reviews Needed" column automation from the PR board

frontend/src/server-middleware/robots.js, frontend/src/utils/og.ts, frontend/test/playwright/e2e/seo.spec.ts
Fixes #4602 by @sarayourfriend
This PR removes the `/image/` and `/audio/` (and translated versions of both) from the robots.txt to attempt to restore OpenGraph tag-based media unfurling for result links. This was added to attempt to prevent scraping, but we've seen that certain scrapers have proceeded to ignore the robots.txt restrictions anyway. So moving forward, we'll plan on blocking _specific_ crawlers using our network infrastructure rather than attempting to block everything from viewing single results.
1. Run `ov env DEPLOYMENT_ENV=production just frontend/run dev:only` (environment variable is needed to render the robots.txt)
2. Visit http://localhost:8443/robots.txt and see that the image/audio endpoints are no longer present
PRs) or the media properties generator (`ov just …
=> Remove the single-result endpoints from the robots.txt

api/api/admin/media_report.py
Partially addresses #3841 by @stacimc 
This PR
- adds advanced search to media list view, powered by Elasticsearch
- adds source/provider filters to media list view
Combined with the bulk moderation action added in #4654, the linked issue is fully resolved.
0. Check out the PR and run the API.
1. Visit the admin page for image list (or audio list).
2. Search for the following:
- a specific UUID `3b858852-67df-44e1-8d57-683991d3ec67`
- a specific creator `creator:"Al S"`
- a creator with wildcard `creator:Al*`
- a word in the document `cat`
- a word in a specific field `tag.name:cat`
8. Combine your searches with a source/provider filter from the right sidebar for further narrowing.
for the catalog or `ov …
=> Update media list admin view to add ES-powered search

frontend/server/plugins/indexable.ts
Adds a Nitro plugin to set site indexability at runtime and override the build time value. This allows us to have different robots.txt files in staging and production despite using the same image. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Set site indexability at runtime

ingestion_server/ingestion_server/indexer.py
Fixes #3977 by @krysal 
We haven't need to throttle ES for a while. We could do a live test deploying this immediately and start a data refresh before the scheduled for next week.
Run a data refresh and confirms it continues to work properly.
- [n/a] I added or updated tests for the changes I made (if applicable).
- [n/a] I added or updated documentation (if applicable).
- [n/a] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog PRs) or the media properties generator (`ov just catalog/generate-docs media-props` for the catalog or `ov just api/generate-docs` for the API) where applicable.
<details> …
=> Drop Elasticsearch throttling on Ingestion Server

api/Dockerfile
I was seeing an issue on `main` where when I tried to run `ov just build`, I got the following error:
```
------
> [web builder 5/5] RUN pdm install --check --frozen-lockfile --dev:
1.475 WARNING: Lockfile is not compatible with PDM
1.476 Please run `pdm lock` to update the lock file
------
failed to solve: process "/bin/sh -c pdm install --check --frozen-lockfile $PDM_INSTALL_ARGS" did not complete successfully: exit code: 1
error: Recipe `dc` failed on line 209 with exit code 17
error: Recipe `build` failed on line 213 with exit code 17
```
@dhruvkb pointed out that this version might need to be bumped, and indeed it helped resolve the issue on my end!
Check out this branch and run `ov just build`, ensure that everything works as expected.
PRs) or the media properties generator (`ov …
=> Bump the minimum required PDM version for the API

frontend/feat/feature-flags.json, frontend/src/app.vue, frontend/src/composables/use-dark-mode.ts, frontend/test/unit/specs/composables/use-dark-mode.spec.ts
Fixes #4303 by @zackkrida 
This PR adds a `FORCE_DARK_MODE` feature flag.
It also adds a new `useDarkMode` composable which provides the current state of dark mode and some related metadata, currently the css class which should be applied to the body. This composable is read in the setup script of `src/app.vue` and passed to the Nuxt built-in "useHead" composable to set a reactive body class whenever the dark mode state changes.
1. `j f` in the repository root to run the frontend dev server.
2. Visit localhost:8443/preferences
3. Inspect the page with developer tools and observe that the body element has a `.light-mode` class. Enable the `FORCE_DARK_MODE` feature flag and observe that this reactively changes to `.dark-mode.
4. Review the code for quality and sufficient test coverage.
PRs) …
=> Init dark mode with feature flag and body class

frontend/test/playwright/visual-regression/pages/pages.spec.ts
Fixes flake in pages.spec.ts by waiting for the route navigation that occurrs after using the locale chooser. This prevents a race condition where the search input would be populated before the route change, and then the route change would reset the search query
All CI should pass.
Additionally, you can build and start the frontend with `ov j frontend/run build && ov j frontend/run start`, then run Playwright interactively and locally with `just frontend/run test:playwright:local -- --ui pages.spec.ts`. Press the green play arrow next to the "layout color is set correctly" test to run it.
The test should pass _or_ make it through to the end and fail with a small screenshot difference in text rendering based on differences between your local system and the CI :sweat_smile: 
PRs) or the …
=> Fix test flake in pages.spec.ts

catalog/dags/providers/provider_csv_load_scripts/inaturalist/create_schema.sql
This PR fixes the schema for iNaturalist's taxonomy/vernacular table.
We received the following exception on the iNaturalist run this quarter:
```
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(5)
CONTEXT:  COPY col_vernacular, line 451211, column taxonid: "45b65465-9c79-4936-bde1-a14f96dc77eb"
```
I SSH'd into the Airflow container to look at the `VernacularName.tsv` file and indeed at line 451211 there were longer IDs used for taxonomies. I checked the [Catalog of Life schema](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#schema) and a number of columns for `Vernacular` use `text` rather than `varchar`. I changed a number of columns to `text` and verified that this would load correctly locally.
Check out this branch and run the …
=> Convert iNaturalist vernacular VARCHAR columns to TEXT

frontend/src/components/VSearchResultsGrid/VCollectionResults.vue, frontend/src/composables/use-collection.ts, frontend/src/pages/audio/collection.vue, frontend/src/pages/image/collection.vue
Extract common functionality to a composable
Fixes #4721 by @obulat
This PR fixes the audio collection SSR by setting the media to the media from the store (instead of the empty array).
It also extracts the collection functionality into a composable. This reduces the code duplication between the audio/image collection pages.
Another fix in this PR is the re-addition of the `creatorUrl` prop. This prop was lost when migrating to Nuxt 3, and the creator collections did not have the link to their landing pages on source websites.
Run the app.
Search for something in audio, and then click on one of the tags. Refresh the page to see how SSR page looks. On `main` and in production, the page does not show any results, and there is an error logged in the console. In this PR, the page works …
=> Fix audio collection page SSR error

frontend/src/components/VContentReport/VContentReportForm.vue, frontend/src/components/VFilters/VFilterChecklist.vue, frontend/src/components/VFilters/VLicenseExplanation.vue, frontend/src/components/VHeader/VHeaderInternal.vue, frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue, frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue, frontend/src/components/VHomepageContent.vue, frontend/src/components/VMediaInfo/VMediaDetails.vue, frontend/src/components/VModal/VModal.vue, frontend/src/components/VModal/VModalContent.vue, frontend/src/components/VPopover/VPopover.vue
The fix for #3582 will touch several component. This PR converts those component to `script setup` to make the further review for that fix easier.
Most of the changes are just removing the extra syntax, moving the script to the top of the file, and converting the props definition to `defineProps`.
There are three other changes to the modal:
- add an exposed `close` function so that the modal can be closed programmatically from a parent file
- for the close button inside the modal, add `stopEventPropagation` so that in the future a click on the close button does not trigger closing of the modal because it's a click outside of the modal (the parent content settings modal can get closed when the top-level licence explanation modal's close button, which is …
=> Convert modal-related components to script setup

api/api/utils/aiohttp.py, api/api/utils/check_dead_links/__init__.py, api/api/utils/image_proxy/__init__.py, api/api/utils/image_proxy/dataclasses.py, api/api/utils/image_proxy/extension.py, api/compose.yml, api/conf/settings/thumbnails.py, api/test/unit/utils/test_aiohttp.py
Fixes #4570 by @sarayourfriend
This PR decreases the thumbnail upstream request timeout as discussed in the linked issue. It also decreases the timeout for the HEAD request for the extension to the same default value. Finally, it adds timing logs for both these requests so we can further evaluate appropriate timeouts for each. For example, hopefully we can decrease the HEAD request timeout significantly (like 0.5 seconds at least). But, because the analysis in the linked issue was done with timings of the entire thumbnail request, it's not possible to know which part of the request actually takes 4 seconds. Therefore, the total timeout of outbound requests is now 8 seconds, which is still way lower than the 25 total seconds and still a good improvement in line with the goals of the issue. …
=> Decrease thumbnail upstream timeout and add timing logs for thumbnail requests

frontend/src/composables/use-api-client.ts, frontend/src/data/api-service.ts, frontend/src/plugins/02. init-stores.ts, frontend/src/plugins/03. analytics.ts, frontend/src/stores/feature-flag.ts, frontend/src/stores/media/index.ts, frontend/src/stores/media/related-media.ts, frontend/src/stores/media/single-result.ts, frontend/src/stores/provider.ts, frontend/src/utils/decode-media-data.ts, frontend/test/playwright/e2e/recent-searches.spec.ts, frontend/test/playwright/utils/page.ts, frontend/test/playwright/visual-regression/pages/search-with-banners.spec.ts, frontend/test/unit/specs/stores/media-store-fetching.spec.js
Fixes #4737 by @obulat
The failures were caused by race conditions when setting up the feature flag store. 
When setting up the state, we need the `runtimeConfig`'s `deploymentEnv` to compute the feature flag statuses and states. Sometimes it was called when the Nuxt context necessary for `useRuntimeConfig` wasn't available, and this caused errors down the line. This only happened on the server.
This PR adds a check if the Nuxt app context is available to the feature flags store. If it's not available, it is possible to get the `deploymentEnv` from the runtime env variable (`NUXT_PUBLIC_DEPLOYMENT_ENV`). It also throws an error when the env variable is not available - but that should never happen.
Some code is also refactored to avoid calling feature flag store from deeply nested …
=> Fix Playwright test failures when Nuxt context is not available

frontend/src/app.vue, frontend/src/components/VModal/VModalContent.vue, frontend/src/layouts/search-layout.vue, frontend/src/stores/ui.ts, frontend/test/playwright/e2e/recent-searches.spec.ts
_Marked as critical because this issue does not allow search on mobile when the banner is not dismissed_
Fixes #4729 by @obulat
This PR adds a `--header-height` CSS variable that is then used to compute the height of the modal backdrop, and the modal offset from the top to make sure that any banners inside the header element are taken into account.
I tried to also fix #2603 in this PR, but because clicking "Skip to content" _navigates_ to a `#content` hash route, it requires a [router options](https://nuxt.com/docs/guide/recipes/custom-routing#router-options) [scroll behavior changes](https://router.vuejs.org/guide/advanced/scroll-behavior).
1. Clear the `ui` cookies in your browser, or use _incognito_ mode.
2. Use the _mobile, narrow_ screen width.
3. Run the app and go to …
=> Fix mobile recent searches modal with banners

ingestion_server/ingestion_server/cleanup.py, ingestion_server/test/unit_tests/test_cleanup.py
Fixes #4644 by @AetherUnbound
This PR adds an additional layer of filtering during the "tags cleanup" step of the (current) ingestion server which filters out tags that correspond to a specific provider. For the time being, only `rekognition` tags are filtered.
I have been having some trouble getting `ov` to run these commands, but it might just be my desktop.
Running `just ingestion_server/test-local` should run the tests, which all should pass!
<details>
```
Developer …
```
=> Preemptively filter out Rekognition tags

api/api/utils/aiohttp.py, api/api/utils/check_dead_links/__init__.py, api/api/utils/image_proxy/__init__.py, api/api/utils/image_proxy/dataclasses.py, api/api/utils/image_proxy/extension.py, api/compose.yml, api/conf/settings/thumbnails.py, api/test/unit/utils/test_aiohttp.py
Reverts WordPress/openverse#4746
I'll copy my explanation of why `raise_for_status` caused the issue from our incident report here:
> As [Staci] noted, we added `raise_for_status` in the check dead links HEAD request. This caused non 2xx responses to raise a ClientResponseError. These are caught with ClientError. But the except block in the function calls logger.error with the exception object. Adding raise_for_status incorrectly classified dead link responses as errors rather than expected responses that we wanted to catch. The except block is only written to handle unintentional errors, i.e., errors in making the request at the networking level, rather than the response we receive. That’s why it catches ClientError instead of specifically ClientResponseError. The latter is raised for …
=> Correct response handling for checking dead links

api/api/utils/image_proxy/__init__.py, api/api/utils/image_proxy/dataclasses.py, api/api/utils/image_proxy/wikimedia.py, api/api/views/image_views.py, api/conf/settings/thumbnails.py, api/test/factory/models/image.py, api/test/factory/models/media.py, api/test/unit/utils/test_image_proxy.py, api/test/unit/views/test_image_views.py
Related to #3075 by @krysal  and #2442 by @obulat 
Wikimedia's thumbnail service supports all file types (as far as I can tell). Therefore, we can use it to generate thumbnails, and then use Site Accel. to proxy and cache the images (to relieve Wikimedia's servers from future thumbnail requests, though they operate their own cache, for what its worth).
The concept behind this PR is to dynamically generate the thumbnail URL to retrieve from Wikimedia, and then pass _that_ to Site Accel. instead of the real URL.
The rationale behind doing this in the API is because these thumbnail URLs need to be constructed at runtime for us to manipulate the parameters for compression and size to fit our needs.
1. Run the API and Airflow locally. You'll use Airflow to ingest some wikimedia images to your …
=> Generate Wikimedia thumbnail URLs on the fly

docker/dev_env/Dockerfile
This PR addresses an issue where `ov just install` was unable to complete successfully due to missing libraries within `ov`:
```
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /opt/.local/share/pdm/venvs/python-pdZ_qQeR-3.12
Synchronizing working set with resolved packages: 37 to add, 0 to update, 0 to remove
✔ Install idna 3.7 successful
✔ Install asttokens 2.4.1 successful
✔ Install pexpect 4.9.0 successful
✔ Install pure-eval 0.2.2 successful
✔ Install matplotlib-inline 0.1.7 successful
✔ Install pycparser 2.22 successful
✔ Install mechanize 0.4.10 successful
✔ Install decorator 5.1.1 successful
✔ Install ptyprocess 0.7.0 successful
✔ Install parso 0.8.4 successful
✔ Install pyjwt 2.8.0 successful
✔ Install prompt-toolkit …
```
=> Add dependencies necessary for cffi installation to dev environment

api/api/utils/check_dead_links/__init__.py, api/test/unit/utils/test_check_dead_links.py
Related to https://github.com/WordPress/openverse/pull/4748
https://github.com/WordPress/openverse/pull/4748 missed another critical issue in the error handling of the dead link validation routine, which is that we only want to log non-timeout errors. As explained in the comment I've added, timeouts are somewhat expected, and are not errors we can do anything about and do not need to be reported to Sentry. We have other methods of visibility into them (especially with the new timing logs).
Unit tests should pass.
If you lower the timeout for dead link checks by setting `LINK_VALIDATION_TIMEOUT_SECONDS` to something like 0.2 seconds, and then run a query locally with `filter_dead=True`, you should _not_ see errors logged for those timeouts, just the timing logs.
- [N/A] I added or updated …
=> Do not logger.error timeout errors in dead link checks

catalog/dags/providers/provider_api_scripts/freesound.py, catalog/dags/providers/provider_api_scripts/smithsonian.py, catalog/requirements-prod.txt, catalog/tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #4594 by @stacimc
> [!WARNING]
> This **should not** be merged until a deployment can be made immediately after, since it introduces new dependencies.
This PR makes two major changes:
- Replaces the `retry` with `backoff`
- Adds an exponential backoff to all requests made to Freesound during ingestion
The latter change is relatively straightforward: we encounter tons of exceptions during the Freesound ingestion process that seem to be transient and ultimately get resolved when checked later. However this causes significant disruptions in the execution of the DAG itself, since it often requires that maintainers restart the DAG with `SKIP_INGESTION_ERRORS` enabled for it. This change allows requests to be retried with an exponential backoff up to a max time (2 minutes for now) if they …
=> Replace retry with backoff, add backoff to all Freesound requests

catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
Fixes the Wikimedia DAG when running locally with verbose logging enabled. The `get_batch_data` method was returning `dict_values` rather than a list, causing an error in the construction of the verbose logs.
Optionally, try running the Wikimedia DAG locally on `main` and verify that you see the `"TypeError: 'dict_values' object is not subscriptable"` error. Then checkout this branch, run `ov j up`, and re-run the DAG. The error happens immediately, so you only need to make sure that some records are logged.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a- …
=> Fix Wikimedia provider when verbose logging enabled

catalog/dags/common/storage/columns.py, catalog/pytest.ini
This PR addresses the following deprecation warnings that appear when running the catalog's tests.
```
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
dags/common/storage/columns.py:33
/opt/airflow/catalog/dags/common/storage/columns.py:33: DeprecationWarning: In 3.13 the default `auto()`/`_generate_next_value_` will require all values to be sortable and support adding +1
and the value returned will be the largest value in the enum incremented by 1
calculate_value = auto()
tests/dags/common/loader/test_sql.py: 87 warnings
tests/dags/providers/provider_api_scripts/test_inaturalist.py: 1 warning …
```
=> Fix or ignore deprecation warnings in the catalog

catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
Fixes #4734 by @sarayourfriend
This PR moves the branch protection cache from the module to within the scope of the `get_min_required_approvals` function. Based on the way Airflow manages its workers and processes, this cache was created at module import time and persisted throughout the duration of the Airflow scheduler process. Scoping this to the function ensures that it's recreated on every DAG run.
Tests should continue to pass!
<details>
``` …
```
=> Only cache branch protection within the scope of the function

catalog/dags/maintenance/airflow_log_cleanup_workflow.py, catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, documentation/catalog/reference/DAGs.md
Fixes #4750 by @sarayourfriend
This PR fixes a few instances of brackets within the DAG docstrings that would produce invalid HTML in the resulting document that gets rendered for the documentation site.
Run the following, and HTML should be output (without raising any errors):
1. `ov just documentation/live`
1. `ov pnpm exec prettier documentation/_serve/catalog/reference/DAGs.html`
<details>
```
Version 1.1 …
```
=> Fix DAG docstrings so they no longer produce improper HTML

frontend/src/components/VBanner/VAnalyticsNotice.vue, frontend/src/components/VBanner/VBanners.vue, frontend/src/components/VBanner/VNotificationBanner.vue, frontend/src/components/VBanner/VTranslationStatusBanner.vue, frontend/src/components/VHeader/VFilterButton.vue, frontend/src/components/VHeader/VFilterIconOrCounter.vue, frontend/src/components/VHeader/VHeaderDesktop.vue, frontend/src/components/VHeader/VHeaderMobile/VContentSettingsButton.vue, frontend/src/components/VHeader/VHeaderMobile/VFilterTab.vue, frontend/src/components/VHeader/VHeaderMobile/VSearchBarButton.vue, frontend/src/components/VHeader/VHeaderMobile/VShowResultsButton.vue, frontend/src/components/VHeader/VHomeLink.vue, frontend/src/components/VHeader/VLogoButton.vue, frontend/src/components/VHeader/VPageLinks.vue, frontend/src/components/VHeader/VSearchBar/VSearchBar.vue, frontend/src/components/VHeader/VSearchBar/VSearchButton.vue, frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue, frontend/src/components/VHeader/VWordPressLink.vue, frontend/src/components/VRecentSearches/VRecentSearches.vue, frontend/test/playwright/visual-regression/pages/errors.spec.ts, frontend/test/tapes/search/images/q=galah&license_type=modification_keep-alive.json5, frontend/test/tapes/search/images/q=galah_close.json5, frontend/test/tapes/search/images/q=galah_keep-alive.json5
This PR converts the header-related components to `script setup`. This is the basis for the work on combining the mobile and desktop headers.
- remove `defineComponent`
- convert `props` to `withDefaults` and `defineProps`
- convert `emits` to `defineEmits`
- remove returns
The CI should pass, and the headers should work as usual.
<details>
```
Version 1.1 …
```
=> Convert header-related components to script setup (23)

frontend/src/components/VHeader/VHeader.vue, frontend/src/layouts/content-layout.vue, frontend/src/layouts/default.vue, frontend/src/layouts/search-layout.vue
Fixes #4764 by @obulat
This PR extracts `VHeader` component (wrapper over the `VBanners` and `VHeader<Internal|Desktop|Modal>`). This allows us to only have the height computation, saved in a CSS variable, necessary to correctly set the modal height and offset in search layout both when the banners are visible and when they are not.
The CI should pass and the header should work correctly on all layouts (content pages, home page, search pages).
<details>
```
Developer …
```
=> Extract `VHeader` as a wrapper for header and banners

documentation/projects/proposals/rekognition_data/20240530-implementation_plan_augment_catalog_with_rekognition_tags.md
This was prompted by a discussion in #4643.
This PR adds some clarity around the Rekognition tag filtering step, including adding an explicit step to implement the filtering using an inclusion-based list after the tags are inserted. See the discussion linked above for rationale, and the text changed for what's described.
<details>
```
Version 1.1
Suite …
```
=> Add specifics of Rekognition tag filtering to implementation plan

frontend/src/components/VRadio/VRadio.vue, frontend/test/playwright/e2e/all-results-keyboard.spec.ts, frontend/test/playwright/e2e/audio-detail.spec.ts, frontend/test/playwright/e2e/audio-results.spec.ts, frontend/test/playwright/e2e/filters.spec.ts, frontend/test/playwright/e2e/global-audio.spec.ts, frontend/test/playwright/e2e/header-internal.spec.ts, frontend/test/playwright/e2e/image-detail.spec.ts, frontend/test/playwright/e2e/preferences.spec.ts, frontend/test/playwright/e2e/recent-searches.spec.ts, frontend/test/playwright/e2e/report-media.spec.ts, frontend/test/playwright/e2e/search-navigation.spec.ts, frontend/test/playwright/e2e/search-query-client.spec.ts, frontend/test/playwright/e2e/search-query-server.spec.ts, frontend/test/playwright/e2e/sensitive-results.spec.ts, frontend/test/playwright/e2e/skip-to-content.spec.ts, frontend/test/playwright/e2e/sources.spec.ts, frontend/test/playwright/utils/components.ts, frontend/test/playwright/utils/i18n.ts, frontend/test/playwright/visual-regression/pages/errors.spec.ts
Fixes #619 by @sarayourfriend
This PR audits the Playwright tests to not use hard-coded strings, replacing them with i18n translations
It also replaces some `page.locator` with `page.getByRole` selectors, and uses better selectors for checkboxes.
The CI should pass, and the changes should make sense. The Playwright tests should not have hard-coded strings left.
<details>
```
Version 1.1 …
```
=> Replace hard-coded strings in Playwright tests

catalog/dags/database/batched_update/constants.py
Fixes #4814 by @AetherUnbound 
This PR reduces `UPDATE_TIMEOUT` to 30 days and sets `DAGRUN_TIMEOUT` to the sum of `UPDATE_TIMEOUT` and `SELECT_TIMEOUT`
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
=> fix: Reduce timeouts for batched update

catalog/dags/common/cloudwatch.py
…freshed (Issue #4826)
Fixes #4826 by @AetherUnbound
This pull requests adds the Elasticsearch 90% CPU alarm to the list of alarms which get disabled for the refresh data.
<details>
```
Version 1.1
Suite D4700 …
```
=> Added 90% ES CPU alarms to those disabled for the data refresh

api/api/utils/check_dead_links/__init__.py, api/api/utils/image_proxy/__init__.py, api/api/utils/image_proxy/extension.py, api/api/views/image_views.py, api/test/unit/utils/test_check_dead_links.py, api/test/unit/utils/test_image_proxy.py
Fixes https://github.com/WordPress/openverse/issues/4774 by @stacimc 
Okay, this is a bit of a big one. We can split it up, but I'm running out of time before I need to end working for the week, and I needed to get this all down at least somewhere. The changes here (except the PIL ones) are all related to the linked issue, either by just ignoring the errors as non-actionable the way we discussed, or by actually fixing some of them (hopefully).
The main difference there being the refactor to treat aiohttp client responses as async context managers. This, apparently, is necessary when using aiohttp. I wrote the original code that introduced aiohttp, and I don't know how I missed this, or how the application was able to keep working so long with it missed, especially in such heavily …
=> Fix handful of networking issues including silence errors

api/api/utils/image_proxy/extension.py, api/test/unit/utils/test_image_proxy.py
Fixes https://github.com/WordPress/openverse/issues/4888
`log` will be unbound if the exception is a timeout error. We intentionally do not log timeouts, as noted in the code comment in this block, so the fix is to ensure `log` is only used when it is bound, which is inside the block guarded by the exception being anything but a timeout error.
Cause a timeout locally by lowering `THUMBNAIL_EXTENSION_REQUEST_TIMEOUT` to something very low, and request a thumbnail. You should not see an exception about the unbound local `log`. …
=> Fix unbound access of `log` (when the captured exception is a timeout)

.github/workflows/tag_docker_image_and_trigger_deployment.yml
Fixes this failure: https://github.com/WordPress/openverse/actions/runs/10782697007/job/29903186115
Same issue that we found in #4866, but for the release GitHub workflow rather than CI/CD where we noticed it in the original PR.
I've searched for `just lint` in our GitHub Workflows and this is the only other one, I think.
Make sure I didn't miss other cases where Vale would run in GitHub Workflows where PDM would need to be available.
for the catalog or …
=> Make PDM available when linting in release app

catalog/dags/data_augmentation/rekognition/add_rekognition_labels.py
When I kicked of the Rekognition DAG in production, we saw the following exception:
```
botocore.exceptions.SSLError: SSL validation failed for https://migrated-cccatalog-archives.s3.s3.amazonaws.com/kafka/image_analysis_labels-2020-12-17.txt hostname 'migrated-cccatalog-archives.s3.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```
Upon investigating the internals of the `S3Hook`, it looked like the `get_client_type` call was explicitly setting the `endpoint_url` for the `s3` client to be `s3.amazonaws.com`, which something (either `smart_open` or `boto3` itself) was _also_ tacking on another `s3` after the bucket name. 
https://github.com/apache/airflow/blob/1da4b146e954f78280dbe7bbbef452d58c8f728c/airflow/providers/amazon/aws/hooks/base_aws.py#L704 …
=> Create S3 client for smart_open from session

docker/dev_env/run.sh, ov
Fixes #4931 by @d3jawu
This PR specifies `ov` to build and run a Linux amd64 image. This fixes builds breaking on macOS because the k6 RPM repo does not supply aarch64 builds which is the default architecture used unless specified with the `--platform` flag.
1. Check out the PR.
2. Try to build `ov`: `ov build`
3. Try to initialize `ov`: `ov init`
<details>
```
Version 1.1 …
```
=> Specify `amd64` platform to fix `ov` builds on macOS

catalog/dags/maintenance/add_license_url.py
Fixes #4318 by @krysal 
When checking on a few items remaining, I noticed the `license_url` was already present in the `meta_data` column with the value of `NULL`. These caused the DAG to have virtually no effect on how the update statement was written; at the merge, the `NULL` value replaced the actual value. Fortunately, this has an easy fix.
1. Download [this CSV](https://gist.github.com/krysal/1ccc4c2f4c963596581638758d69bdf1)  of sample rows
2. Load it into the catalog DB 
1. Copy the file into the upstream DB container: `docker cp /path/to/images_missing_md_license_url.csv [container-id]:/tmp/sample_rows.csv`
2. Connect with pgcli: `just catalog/pgcli`
3. Import the file into the table: `COPY image FROM '/tmp/sample_rows.csv' DELIMITER ',' CSV HEADER;`
4. Enable the `batched_update` …
=> Fix `add_license_url` DAG for last items

frontend/src/components/VSelectField/VSelectField.vue, frontend/src/styles/tailwind.css
Related to #4911 by @zackkrida
Fixes the extra white halo around the focus ring in `VSelectField` (used by the theme switcher and the language switcher).
This was caused by the browser's default styles: they add an outline by default when a `select` element is focused. We remove some of the default styles, but the outline style is still set to `auto`, and that adds a visible white outline in Chrome (but not in Firefox).
We cannot use Tailwind's `outline-none` class here to remove the outline because it does not actually remove the outline, it adds the following styles instead:
```
outline: 2px solid transparent;
outline-offset: 2px;
```
That's why I added a new utility class, `outline-style-none` here.
Run the app and use the keyboard to navigate to the theme or language switcher in the …
=> Fix `VSelectField` focus ring

api/Dockerfile
Fixes #4680 by @sarayourfriend 
Simplify the audiowaveform installation in the API Dockerfile by using audiowaveform's published deb packages from their GitHub releases, as discussed in the linked issue.
Pinging @dhruvkb for review because of his familiarity with this to begin with, plus I need to make sure that someone on macOS (an arm64 computer, really) tests this.
Checkout the branch and run `ov j build web && ov j up --force-recreate`. Then `ov j api/dj generatewaveforms --max_records=2` and confirm that waveforms are successfully generated for 2 audio files. If you already have waveforms for all audio files, you'll need to remove them manually (left up to you) or start over with API test data using `ov j down -v && ov j api/init`.
- [N/A] I added or updated tests for the changes I …
=> Simplify audiowaveform installation in API Dockerfile

frontend/src/components/VHomepageContent.vue
Fixes #4811 by @d3jawu
Removes "Testing Nuxt 3" text hidden in markup.
Copy text across header and sub-heading on frontpage. "Testing Nuxt 3" is no longer present.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Remove "Testing Nuxt 3" text from markup

documentation/conf.py, documentation/meta/missing_changelogs.md
Fixes #4726 by @sarayourfriend
Based on an environment variable conditionally removes the changelogs
<details>
```
Version 1.1
Suite D4700 …
```
=> Conditional removal of changelogs

catalog/dags/data_augmentation/rekognition/add_rekognition_labels_dag.py
The Rekognition label insertion DAG recently timed out, at the initial timeout of 5 hours. In the time it's run so far, about 20 million records have been processed. The new timeouts are generous, but they should finish within that time boundary knowing what the current processing time is.
The timeouts should be available in the DAG UI when running locally. 
<details>
```
Version 1.1 …
```
=> Modify Rekognition insertion timeouts

catalog/pytest.ini, catalog/tests/dags/common/sensors/test_single_run_external_dags_sensor.py, catalog/tests/dags/common/sensors/test_utils.py, catalog/tests/dags/database/staging_database_restore/test_staging_database_restore.py, catalog/tests/dags/providers/test_provider_dag_factory.py
When running `ov just catalog/test` recently, I noticed that we had a few new deprecation errors:
```
================================================================================================= warnings summary =================================================================================================
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
tests/dags/common/sensors/test_utils.py:12
/opt/airflow/catalog/tests/dags/common/sensors/test_utils.py:12: RemovedInAirflow3Warning: Creating a DAG with an implicit schedule is …
```
=> Address deprecations, make DeprecationWarning and RemovedInAirflow3Warning raise error

packages/js/k6/package.json, packages/js/k6/rollup.config.ts, packages/js/k6/src/crypto.ts, packages/js/k6/src/frontend/constants.ts, packages/js/k6/src/frontend/scenarios.ts, packages/js/k6/src/http.ts, packages/js/k6/src/utils.ts, pnpm-lock.yaml
Fixes https://github.com/WordPress/openverse-infrastructure/issues/1031 by @obulat
This PR adds signing requests with an HMAC to enable bypassing WAF rules, so that k6 requests do not get rate limited.
Follow the test instructions in this infrastructure PR: https://github.com/WordPress/openverse-infrastructure/pull/1048
These must be tested together.
You should also be able to run the k6 tests against your local frontend, without passing `-e signing_secret`. Run your frontend with `ov j p frontend prod` and then in another terminal, run the k6 tests:
```shell
ov j k6 frontend static-en -e FRONTEND_URL=https://staging.openverse.org/ -e scenario_vus=1 -e scenario_iterations=1
```
PRs) or the media …
=> Sign k6 requests with HMAC to enable WAF bypass

frontend/src/styles/tailwind.css, frontend/tailwind.config.ts
This PR organises colors into groups in the `tailwind.css` and `tailwind.config.ts` files for clarity.
This PR removes redundant and/or unused colors and also adds missing colors.
| Action | `tailwind.css` | `tailwind.config.ts` |
|-|-|-|
| Removed | `color-gray` | `colors.gray.DEFAULT` |
| Removed | `color-gray-13-0` | `colors.gray-opacity.13.0` |
| Removed | `color-white-0` | `colors.white.0` |
| Removed | `--color-bg-zero` | `backgroundColor.zero` |
| Removed | | `colors.gray.light-gray` |
| Removed | | `colors.gray.dark-gray` |
| Added | `--color-bg-blur` | |
This PR also uses functions to generate color shade and opacity scales in `tailwind.config.ts`. Typing out 13 shades for each color is [understandably more readable](https://github.com/WordPress/openverse/pull/4690#issuecomment-22 …
=> Organise and fix bugs in color definitions

catalog/dags/common/loader/provider_details.py
Part of https://github.com/WordPress/openverse/issues/4856 by @sarayourfriend 
This PR adds Katmai National Park Service as a flickr-based source. https://www.flickr.com/photos/99350217@N03
I will kick off a batched update to backfill existing works from Katmai with the new source string.
Confirm I have the creator ID correct, I don't think there's anything else to test, though you can run Flickr ingestion locally with these "additional query params" and check that source is set to `katmai_nps`:
```json
{
"max_upload_date": 1701349200,
"min_upload_date": 1690812000,
"user_id": "99350217@N03"
}
```
PRs) or the media properties …
=> Add Katmai NPS source from Flickr

.vale/justfile, api/justfile, automations/js/justfile, automations/python/justfile, catalog/justfile, docker/cache/justfile, documentation/justfile, frontend/bin/playwright.sh, frontend/justfile, indexer_worker/justfile, justfile, packages/js/k6/justfile, packages/python/openverse-attribution/justfile
This PR fixes a problem we've run into several times, and never really found a suitable ("nice") solution for. 
Without these changes, when we pass just's collected arguments lists (`+args` and `*args` type things), the underlying bash call that just makes will cause arguments to be split on _any space_ and follow difficult to track rules about quotation mark escaping. Commands like this, were simply impossible, without abstract levels of quote escaping:
```shell
ov env DC_USER="airflow"  just exec scheduler airflow dags trigger staging_audio_data_refresh --conf '{"index_suffix": "init"}'
ov just api/test -k "test_image_proxy or test_check_dead_links"
```
The `--conf` argument would have its quotes stripped and turn into `{"index_suffix": "init"}`, passed to the underlying command, which …
=> Fix just argument splitting on pass-through recipes with complex args

.github/workflows/ci_cd.yml
Fast follow to #4924.
The linked Pr accidentally included steps in the staging deploy job that weren't validated or ready yet.
N/A, merge this to fix failing staging deploy jobs.
<details> …
=> Remove steps for unprepared k6 after staging frontend deploy

automations/js/src/project_thread_updates.js
Fixes #4912 by @zackkrida 
See [the linked issue for rationale](https://github.com/WordPress/openverse/issues/4912).
This PR just removes that status from the list of statuses for which the script will send reminders.
Review the code change, IIRC there is no good way to test this without just letting it run after merging. …
=> Do not ping for project update reminders on shipped projects

.github/.lighthouserc.yml, .github/workflows/ci_cd.yml, justfile
Fixes #646 by @obulat 
This PR adds a new CI/CD job to collect Lighthouse CI results for each frontend change.
The new CI job must pass.... click in to see the nice table of results logged in the "Display Report" step
For now, that's as far as we'll go. It's already telling us some pretty useful (and worrisome!) things. In the future we can explore other methods of displaying results (e.g., https://www.foo.software/docs/lighthouse-check-github-action/intro, which requires a small amount of additional infrastructure work to get running, S3 and some IAM stuff). [See this comment for more details about why other free and easy options are not currently available](https://github.com/WordPress/openverse/pull/4994#issuecomment-2375613390).
- [N/A] I added or updated tests for the changes I made …
=> Collect lighthouse CI on each frontend change

frontend/src/pages/preferences.vue, frontend/test/playwright/e2e/attribution.spec.ts, frontend/test/playwright/e2e/preferences.spec.ts
Fixes #4995 by @sarayourfriend
Fixes the test by adding a check for the copy button: it is only enabled after the app has finished hydrating.
A different test (checking the preferences switch sets the cookie value) was found as flaky, so I added a check to that test as well.
The CI should pass (several times?)
<details>
```
Version 1.1
Suite D4700
San …
```
=> Fix flaky test from #4995

.github/workflows/ci_cd.yml
Fixes #5020 by @obulat
This PR fixes the `Run k6 frontend all against local Nuxt` failure when a PR is merged to main. 
Part of the action is to post the load testing results as a comment to the PR. However, when the PR is merged to main, there is no `pull_request` associated with the event, and the comment cannot be found. 
This PR adds a step that checks that the CI is running on a pull request (and not from a fork). The commenting steps (creating the comment, finding the previous comment, and updating the comment) only run if this step's output is `true`.
The CI should pass (both in this PR, and when this PR is merged into main)
for the catalog or `ov just api/generate-docs` for the API) where …
=> Fix the load test comment condition

frontend/server/plugins/sentry.ts, frontend/src/plugins/01.sentry.client.ts
Fixes #4713 by @krysal
Fixes #4788 by @zackkrida 
This PR removes the extra logging and adds ResizeObserver error to the ignored list. It was on the ignored list before Nuxt 3 migration.
The CI should pass. Try running the app (or look into the CI logs), the Sentry init step should not log the integration list, only the dsn, release and environment.
<details>
```
Version 1.1 …
```
=> Improve Sentry init log and ignore non-actionable error

frontend/package.json, pnpm-lock.yaml
Fixes #4949 by @zackkrida 
This PR updates Plausible packages to fix the logging issue.
Run the app using `ov just frontend/run dev`, and change the media type using the homepage search bar. You should see the analytics event logged in the console. 
Build the app, run it, and change the media type. You should not see the analytics events being logged.
<details>
```
Version 1.1 …
```
=> Update plausible to fix logging

frontend/src/components/VSkeleton/VBone.vue, frontend/src/components/VSkeleton/VGridSkeleton.vue, frontend/src/components/VSkeleton/meta/VGridSkeleton.stories.ts, frontend/src/styles/tailwind.css
Fixes #4829 by @fcoveram
This PR updates the skeleton colors to match the updated designs.
It also fixes the number of columns when the sidebar is visible: the `isSidebarVisible` prop wasn't passed, so the number of columns was set the same when the sidebar was open, and the screen was narrower, as when it was closed.
It also moves some styles to Tailwind classes, and simplifies the Storybook story.
Open the browser devtools and set slower speed in the "Network" tab's throttling settings.
Try searching for something in Openverse. Use some new search terms to prevent loading from cache. You should see loading skeletons. The number of columns in "All content" view should match the number of columns in the results when the filters sidebar is open (In staging, you can see that there are more …
=> Update loading skeletons

frontend/test/playwright/e2e/preferences.spec.ts, frontend/test/playwright/utils/assertions.ts, packages/js/eslint-plugin/src/configs/index.ts
Fixes #5001 by @obulat
This PR updates the preferences test to make it less flaky:
- to find the switch, we use the `getByRole` Playwright locator with the `checked` property set to `true` or `undefined`. We add an extra expect, checking that the switch is enabled. This function is extracted to `expectCheckboxState`, which is added as a valid `expect` to the Openverse ESLint plugin.
- instead of testing the saved cookie value that is not visible by the users, we reload the page and check the switch state. If the state was saved in a cookie, then the state on page load should be updated.
- an extra check with the snapshot of all of the feature flag store state is added.
The Playwright e2e test should pass in the CI. I will re-run this step several times to make sure that the test is not …
=> Make the preferences test more robust

catalog/tests/dags/data_refresh/test_task_dependencies.py
Fixes #4340 by @stacimc
The new data refresh has already been added to the `load_sample_data` scripts, such that it is run each time a contributor runs `ov j api/init` and also in CI. This adds a lot of coverage for the "happy path" of the data refresh.
In addition to this, however, it's important to test that certain vital task dependencies are maintained. While developing the data refresh I found that it's surprisingly easy to accidentally break the dependency graph in a manner such that, while a normal data refresh works as expected, an upstream task failure may not cascade properly. TL;DR: it's easy to introduce a change that seems fine, but causes elasticsearch reindexing/promotion to occur _even if the `copy_data` step fails_. This is a huge concern because it could result in bad or …
=> Add tests for data refresh task dependencies

automations/python/workflows/set_matrix_images.py
This PR fixes CI by building the `catalog` image when the CI jobs are running for the API. Without the `catalog` image being built, the CI fails at the step when sample data is to be loaded.
<details>
```
Version 1.1
Suite D4700
license document, but changing it …
```
=> Add `catalog` to list of images built for API tests

catalog/dags/providers/provider_api_scripts/wordpress.py, catalog/tests/dags/providers/provider_api_scripts/test_wordpress.py
I was trying this DAG locally and getting zero results every time. It turns out the `format` query parameter breaks the response entirely:
This is empty: https://wordpress.org/photos/wp-json/wp/v2/photos?format=json
Whereas this works fine and returns JSON every time: https://wordpress.org/photos/wp-json/wp/v2/photos
Removing the format query parameter from the DAG fixes the issue.
Run the DAG on `main` and confirm you get zero results in `pull_image_data`.
Run the DAG on this branch, and confirm you now get the full result set.
for the catalog or `ov just api/generate-docs` …
=> Fix WP Photo Directory DAG

frontend/nuxt.config.ts, frontend/src/locales/scripts/get-validated-locales.js
Fixes #5024 by @obulat
The Nuxt i18n module sets the `lang` value of the `html` element using the `language` property of the locale. Previously, we were using one of the ISO properties of the locale, but this is incorrect. The value we need is in `slug` property.
Previously, we set `language` as `langCodeIso_639_1 || langCodeIso_639_2 || langCodeIso_639_3`.
This means that all variants of Spanish would overwrite each other because they all had the same ISO values (`{ "langCodeIso_639_1": "es", "langCodeIso_639_2": "spa", "langCodeIso_639_3": "spa" }`), even though their slugs were different (`es`, `es-mx`, etc). If you look in the header language links on https://staging.openverse.org, you will see that we only have a single language for all regions.
[Fix frontend to include languages …
=> Correctly set locale `language` property

documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20240903-implementation_plan_undo_split_filtered_indices.md
Part of https://github.com/WordPress/openverse/issues/3336 by @AetherUnbound 
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
The deadline for review of this round is **2024-09-25**.
- [N/A] I ran the DAG documentation generator (`ov just …
=> IP: Undo split indices for sensitive text detection

frontend/src/pages/preferences.vue, frontend/test/playwright/e2e/preferences.spec.ts
Fixes #5001 by @obulat
The flakiness was caused by the fact that we cannot test if the preference was fixed in a robust way. Even if we detect that the switch state changed, it does not yet mean that the feature flag state was updated.
I updated the preference page to add the easily queriable state of the feature flag to the page. 
Now, if we assert that the state text is correct, we can be certain that the feature flag was updated (and it wasn't only the switch update). 
<details> …
=> Fix flaky e2e preferences test

catalog/dags/common/loader/reporting.py, catalog/dags/providers/provider_dag_factory.py, catalog/tests/dags/common/loader/test_reporting.py
Improves reporting associated with #5038
#5038 identified and fixed an issue where the WordPress Photo Directory provider DAG was ingesting 0 records, but without raising any errors that would have alerted us in Slack. This PR adds logic to `report_completion` to raise an alert in Slack if a _non-dated_ DAG ingests 0 records, to help catch these critical issues.
This is limited to non-dated DAGs because, since they ingest all data for a provider without a date-range, we can be confident something is wrong if 0 records are ingested. For some of our dated DAGs (specifically, Europeana and Finnish Museums), it's actually expected to have some 0-record ingestion days. In the future, we may consider more complex logic for non-dated DAGs, for example by specifying a number of days at which we …
=> Add Slack Alert for non-dated provider DAGs with no data

api/api/controllers/search_controller.py
Fixes #706  by @dhruvkb 
The transitional cache invalidation code used for migrating to the new
cache format is no longer needed. This change simplifies the codebase
and removes unnecessary cache operations.
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Removed obsolete cache invalidation code from get_sources function

.github/workflows/ci_cd.yml, .github/workflows/k6.yml, docker/dev_env/Dockerfile, packages/js/k6/justfile, packages/js/k6/src/frontend/constants.ts
Fixes https://github.com/WordPress/openverse-infrastructure/issues/1031 by @obulat 
This PR:
- Adds an intentionally flexible new run-k6 GitHub Workflow for usage both with manual dispatch and programmatic dispatch via the GitHub CLI during other workflows (we could also leverage that to e.g., run some subset of k6 against production on a regular basis irrespective of deployments, managed using Airflow)
- Changes `FRONTEND_URL` to use a generic `service_url` variable so prepare for also having API tests in k6... this allows us not to need to change the variable name based on the other inputs.
- Adds an `ls` recipe to the k6 justfile for listing the namespaces and scenarios.
- Dispatch that workflow after the staging frontend deploys.
Review the testing runs here: …
=> Run k6 after staging deployments

packages/js/k6/src/frontend/scenarios.ts
Fixes #5069 by @obulat
This PR removes the `ar` locale from k6 locale list, adding the docstring with the reason for it.
Hopefully, after merging this PR, we can see that the staging k6 load test passes (it currently fails)
<details>
```
Version 1.1
Suite D4700 …
```
=> Exclude `ar` from k6 load testing

catalog/dags/data_refresh/distributed_reindex.py
The `get_record_id_range` task of the data refresh, which gets a range of record ids to pass to the indexer workers for copying, was incorrectly always querying against the production API. This means on a staging data refresh it will fail at this step (due to the temp table not existing in prod).
This PR just updates the DAG to select the correct DB.
Run the `staging_audio_data_refresh` locally and check the logs for the `get_record_id_range` task. See that it now correctly reports `Retrieving connection 'postgres_openledger_api_staging'`.
You can also run the `production_audio_data_refresh` locally and see that it is connecting to: `Retrieving connection 'postgres_openledger_api'`.
PRs) or the media properties generator (`ov just …
=> Use the correct environment DB for getting the record count of media

catalog/dags/data_refresh/distributed_reindex.py
Related to #5083 by @stacimc 
We think that the indexer worker port being misconfigured in production to 8002, when it is 8003 locally, may be causing/part of the issue with #5083. Rather than changing the port we try to access from the data refresh, we're going to update the indexer worker in production and this code will no longer be required.
CI should not fail.
<details>
```
Version 1.1 …
```
=> Remove logic to change port to 8002 for prod data refresh

catalog/dags/common/elasticsearch.py
This PR adds logging of the elasticsearch `wait_for_reindex` response to assist in debugging the hanging task in the staging data refresh which does not appear locally.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Log response in wait_for_reindex

frontend/src/components/VFooter/VFooter.vue, frontend/src/components/VThemeSelect/VThemeSelect.vue
Fixes #5085 by @obulat 
This PR
- removes `<ClientOnly>` around `VThemeSelect` in the footer
- updates the `VThemeSelect` component to use `Ref`s instead of `ComputedRefs`s
- uses `onMounted` and `watch` to keep the refs updated
These in combination lead to the layout shift being eliminated and avoid server-client hydration mismatches.
<details>
```
Version 1.1
1 Letterman …
```
=> Prevent layout shift by removing `<ClientOnly>` on the theme selector

.gitignore, justfile
Fixes #2938 by @stacimc
This PR updates the `env` recipe to make it "smarter". Instead of copying over the file and overwriting changes, the Python script now keeps changed env values and even extra env key-value pairs in the file.
Assume the following `env.template` file:
```
key_one=value_one
key_two=value_two
```
Assume the following `.env` file:
```
key_one=new_value_one
key_three=value_three
```
After `just env` the `.env` file would be as follows.
```
key_one=new_value_one
key_two=value_two
key_three=value_three
```
0. Make some changes to the `catalog/.env` file. You could change some values, delete some keys or add some new keys.
1. Run `just env`.
2. See that the changes are preserved, deleted keys are restored and custom extra keys are kept at the bottom of the file.
3. Confirm …
=> Create env files from templates in a change-preserving way

frontend/src/components/VSelectField/VSelectField.vue
Fixes #5117 by @obulat
This PR adds `selected` to the individual option that is selected to make the correct option selected in SSR. This prevents a change after the page is loaded.
Go to the homepage and check that the correct option is selected when the page renders initially, not after the page is mounted.
<details>
```
Version 1.1
Suite D4700
San …
```
=> Manually set option's selected prop

catalog/dags/data_refresh/dag_factory.py, catalog/dags/data_refresh/reporting.py
This PR adds the target environment to the Slack notifications reporting the end of the new data refreshes. This is necessary to easily visually distinguish a Staging refresh from a Production one.
Run the `staging_audio_data_refresh` DAG locally and check the logs for the `report_record_counts` DAG. You should see:
`Staging data refresh for audio complete! :tada:`
Similarly, verify that the environment is reported in the logs of the `production_audio_data_refresh`.
<details> …
=> Include env in data refresh Slack notifications

catalog/dags/common/elasticsearch.py, catalog/dags/data_refresh/create_and_populate_filtered_index.py, catalog/dags/data_refresh/dag_factory.py, catalog/dags/data_refresh/data_refresh_types.py, catalog/dags/elasticsearch_cluster/create_proportional_by_source_staging_index/create_proportional_by_source_staging_index_dag.py
Updates the `create_and_populate_filtered_index.trigger_and_wait_for_reindex.wait_for_reindex` task to take its poke interval from the data refresh config. This allows us to poke more frequently for the audio filtered index, as it typically completes in well under thirty minutes.
Run the `staging_audio_data_refresh` and `staging_image_data_refresh` locally. Ensure they pass. The filtered index is created so quickly it's difficult to verify the behavior of the poke interval locally, but you can check the task instance details to verify that it is now set dynamically. …
=> Configure poke interval for the filtered index creation by environment

catalog/dags/common/constants.py, catalog/dags/data_refresh/alter_data.py, catalog/dags/data_refresh/data_refresh_types.py
By default, Airflow only allows creating a maximum of 1024 dynamic tasks at a time (this is configurable but it's not advised to raise this number). The `alter_data` step of the data refresh fails in the image data refresh because it tries to create batches of 100_000 records at time, but there are so many image records to process that we exceed the number of available batches (we get about 9k batches) and overload XCOMs.
This PR updates the `alter_data` steps to allow the batch size to be configured by media type, and updates image to use batches of 1,000,000 records. It still respects the configured `DATA_REFRESH_ALTER_BATCH_SIZE` environment variable as well.
Run the `staging_image_data_refresh` locally. You'll see that it creates batches of 1000 records; this is because we have …
=> Make alter data batch size configurable by media type

api/api/docs/audio_docs.py, api/api/docs/base_docs.py, api/api/docs/image_docs.py, api/api/examples/audio_responses.py, api/api/examples/image_responses.py, api/api/examples/oauth2_responses.py, api/api/serializers/source_serializers.py, api/api/utils/pagination.py, api/test/test_examples.py
Fixes #4885 by @zackkrida 
This PR corrects the OpenAPI examples for
- stats, search and related endpoints (for both image and audio media types)
- removes unnecessary nesting under `application/json` everywhere
- removes redundant variables and arguments (code-quality improvements)
0. Check out the PR and run the API dev server.
1. Visit the OpenAPI spec at http://localhost:50280/v1/.
2. Check that the OpenAPI examples, specifically for the endpoints with corrections mentioned above, are correct.
<details> …
=> Fix incorrect OpenAPI examples

api/pdm.lock, api/pyproject.toml, api/test/unit/utils/test_aiohttp.py
Related to #4901
Following the first steps of suggestions in the issue, this PR updates aiohttp to see if it helps with the runtime errors after deploying it.
Rebuild the image and run the API.
```
just recreate
```
<details>
```
Version 1.1
Suite D4700 …
```
=> Bump aiohttp to 3.11.2

api/api/admin/media_report.py
Fixes #5174 by @krysal
This PR adds pagination to the media views in the admin and prevents showing more than 50 entries at once. So the API doesn't break when trying to access them.
1. `just api/up`
2. Import [reported audio-related tables](https://github.com/user-attachments/files/17834696/audio_reports.zip). I created these TSV files from the staging DB using TablePlus and imported them locally using the same software. It's a little cumbersome because it's a table-by-table import (5 tables), but it works!
3. Go to http://localhost:50280/admin/api/audio/ and see the pagination.
<details>
``` …
```
=> Limit number of items in admin media pages

api/api/admin/media_report.py
Fixes #5174 by @krysal
As mentioned in the issue discussion, this PR optimizes the `source` filter by getting the list from the source table. The provider filter is removed as it involves a similar query and we need to confirm this works first.
Run the API, `just api/up`, and observe the filter changes at:
- http://localhost:50280/admin/api/audio/ and
- http://localhost:50280/admin/api/image/
<details>
```
Version 1.1
Suite D4700 …
```
=> Get sources list for filter from content_provider table

api/Dockerfile, catalog/Dockerfile, docker/dev_env/Dockerfile, frontend/Dockerfile, frontend/Dockerfile.playwright, indexer_worker/Dockerfile, ingestion_server/Dockerfile
This PR prevents annoying Docker warning annotations on PRs, specifically for the intentional violation of the rule `InvalidDefaultArgInFrom` in our `Dockerfile`s.
The PR should not have warning annotations from the [`docker/build-push-action`](https://github.com/docker/build-push-action) for this specific class of warnings.
<details>
```
Version 1.1
Suite …
```
=> Add `syntax` and `check` declarations in `Dockerfile`s

documentation/projects/proposals/relicensing/20241028-implementation_plan_relicensing.md, documentation/projects/proposals/relicensing/20241028-project_proposal.md, documentation/projects/proposals/relicensing/index.md
This PR adds the project proposal and implementation plan for the license changes. 
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> Add project proposal and IP for license migration

api/api/admin/media_report.py
Fixes (maybe) #5174 by @krysal 
In #5175, the number of rows shown in the media list pages was cut, but it turns out the next expensive query is still happening, so this is a quick fix.
```sql
SELECT COUNT(*) AS "__count" FROM "image"
```
Here, I disable the option that makes that query when visiting these pages. The count can be optimized later (with an [ estimation](https://hodovi.cc/blog/best-practises-for-a-performant-django-admin/)). 
Run the API and observe the `[django.db.backends]` logs when visiting http://localhost:50280/admin/api/image/ (or the audio version). 
```
just logs web
```
Search for `__count` and you should find nothing, unlike in the `main` branch where the query is recorded.
for the …
=> Prevent from counting media tables in admin

env.template, justfile
A situation that somewhat exasperates me is that every time the `just up` command runs, it prints several lines to the terminal, and running it every day creates a long list of `.env.bkp-<date>` files. These files aren't modified often, so I prefer to skip this process.
An alternative could be to create a variable to make the execution of `just _env` quiet.
Follow up on #5099.
1. Run the command and observe the files recreation is skipped.
```sh
SKIP_DOTENV_FILES_RECREATION=true just env
```
2. Confirm the `just up` recipe works as it used to do it.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 …
```
=> Add option to skip dotenv files recreation when `just up` runs

frontend/package.json, package.json, packages/js/api-client/package.json, pnpm-lock.yaml
Fixes #5197 by @obulat
The most recent version of i18n/shared package added `create` function:
https://github.com/intlify/vue-i18n/blob/0bd4e68b84d163302819dd21ef4d5fcb6b989f3a/packages/shared/src/utils.ts#L85
In the CI in Playwright, one of the i18n packages was updated to 10.0.5 version, while other dependent packages stayed on 10.0.4, so the imported `create` function wasn't found. I'm not sure why that only happened in the CI, but didn't happen for me locally.
Originally, I thought that the problem was with the mismatch of `vite` versions, so it is updated to the latest version here, too. It should be compatible with the other dependencies.
for the catalog or `ov just …
=> Fix the CI by fixing the i18n dependencies, and updating vite to v6.0.1

.github/ISSUE_TEMPLATE/project_thread.md
Fixes #2011 by @zackkrida
Add a comment to project_thread.md to mention using docs.openverse.org links for plans
It's a readme edit
<details>
```
Version 1.1
Suite D4700
By …
```
=> docs: mention using docs.openverse.org links for plans in project_thread.md

frontend/src/stores/ui.ts, frontend/test/unit/specs/stores/ui-store.spec.ts
Related to #5179 by @obulat 
Revert "Fix frontend memory leak (#4864)" - to see how a memory leak affects the CPU and memory values under load test
This reverts commit a5d966d2
**_This commit will be reverted after the k6 load testing checks are done_**
<details>
```
Version 1.1
Suite D4700 …
```
=> Introduce a memory leak to check k6 tests

.github/workflows/k6.yml, frontend/src/stores/ui.ts, packages/js/k6/src/frontend/scenarios.ts
Fixes #5179 by @obulat
The frontend k6 load test runs against the local Nuxt app on every CI run. Initially, when the test was added to run against the staging environment, it failed due to CPU limitations. To address this, we temporarily increased the staging CPU from 0.25 vCPU to 2 vCPU. However, our goal is to restore the staging environment to its previous resource levels while still reliably detecting potential memory leaks.
The k6 load tests run agains the locally-ran Nuxt app in the GitHub-hosted CI runners on every CI run, and then again after the PR is merged, against the Nuxt app deployed on staging. The GitHub-hosted CI runners use 4 CPU processor and 16 GB of RAM [^1]. 
This PR adjusts the k6 test settings to maintain a constant request rate while preventing the tests from …
=> Modify k6 load tests

frontend/src/components/VLicense/VLicense.vue, frontend/src/components/VLicense/VLicenseElements.vue, frontend/src/composables/use-dark-mode.ts, frontend/src/composables/use-icon-names.ts
Fixes #5227 by @obulat
This PR replaces the `computed` values for icon names with `ref` that are updated in `onMounted` (which runs after the hydration is done). The license icons and the theme icons are affected, but I can revert the change for the theme switcher if #5236 is the preferred approach, @dhruvkb .
Select the "system" mode and refresh a single result page. Make sure your system is set to dark mode by default (or use the browser devtools). Refresh the page and see that there are no client-server mismatch warnings: neither for the theme switcher (sun/moon icons) nor for the license icons on every image result: …
=> Update the icon color in `onMounted`

frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
Fixes #5190 by @obulat
This PR checks if the search input template ref value is not null before focusing it or setting the selection. I'm not sure when this value can be null, but Sentry does show that this can happen. 
This PR also replaces the template refs in `VMobileHeader` with the new [`useTemplateRef` helper](https://vuejs.org/api/composition-api-helpers.html#usetemplateref).
The CI should pass
<details>
```
Version 1.1
Copyright (C) …
```
=> Handle case when the input template ref is falsy in the mobile header

frontend/src/components/VThemeSelect/VThemeSelect.vue
Fixes #5215 by @fcoveram 
This PR changes the theme selector to listen on the `focus` event on the `<select>` field instead of `click` so that bug in Safari can be mitigated.
0. Verify that the bug cannot be reproduced in Safari.
1. Verify that the behaviour in other browsers like Firefox and Chrome hasn't changed.
<details>
```
Version 1.1
Suite D4700
San …
```
=> Track `focus` event instead of `click` to support Safari

catalog/dags/common/cloudwatch.py
Fixes #4882 by @AetherUnbound 
This PR updates the alarm names in the catalog so they can be correctly toggled by Airflow. This follows the inclusion and subsequent name normalisation of the alarms from WordPress/openverse-infrastructure#1110.
<details>
```
Version 1.1
Suite D4700 …
```
=> Handle new 90% alarms in alarm toggle

api/pdm.lock, api/pyproject.toml
For some reason, dependabot is not detecting these dependencies (see the list in #255), so I'm doing it here.
Confirm the API continues to run normally.
Watch the CI workflow passing.
<details>
```
Version 1.1
Suite D4700 …
```
=> Bump dev and test dependencies of the API

.github/workflows/ci_cd.yml, api/Dockerfile, api/compose.yml, api/pdm.lock, api/pyproject.toml, indexer_worker/Dockerfile, indexer_worker/compose.yml, justfile
Follows the series of dependency updates covering Renovate missings.
Confirm the API continues to run normally. Watch the CI workflow passing.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
=> Bump and unify PDM in the api/ and indexer_worker/ to 2.21

documentation/general/contributing.md
Fixes: https://github.com/WordPress/openverse/issues/5254
=> Added https instead of http in wordpress design channel slack link 

frontend/feat/feature-flags.json, frontend/src/components/VFeatureNotice/VDarkModeFeatureNotice.vue, frontend/test/unit/specs/composables/use-dark-mode.spec.ts
This PR sets the feature flag to `switchable`, and `on` by default both in production and in staging. It also adds the link to the draft announcement Make post.
Run the app and see that the link leads to the draft post (maintainers only, you need to be logged int to see the draft). The theme switcher should be on by default.
<details>
```
Version 1.1
Suite …
```
=> Launch the dark mode

.pre-commit-config.yaml, frontend/package.json
Tiny fix I noticed when testing the `ov` PR.
This PR replaces several commands we use for type testing with the Nuxt's `nuxi typecheck`, which generates the types in the `.nuxt` folder, and then runs the checks.
Previously, we were running `nuxi prepare` (which runs more steps than simply creating the types) twice in the precommit check.
The typecheck in the CI should pass.
<details>
```
Version 1.1 …
```
=> Use `nuxi typecheck` to make the frontend types check in pre-commit faster

api/api/views/media_views.py, api/conf/settings/sentry.py, api/conf/urls/__init__.py, api/test/test_schema.py
This PR fixes issues with schemathesis arising in #5273.
- Extends schemathesis' content-type conformation tests to handle 404 responses from Django and DRF.
- Switches to DRF's path-based `SimpleRouter`.
- Fixes a double definition of the `DEBUG` setting field.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
=> Fix broken schemathesis tests

frontend/shared/types/analytics.ts, frontend/shared/types/collection-component-props.ts, frontend/shared/utils/query-utils.ts, frontend/src/components/VImageResult/VImageResult.vue, frontend/src/components/VMediaInfo/VGetMediaButton.vue, frontend/src/components/VMediaInfo/VLicenseTabPanel.vue, frontend/src/components/VSearchResultsGrid/VAllResultsGrid.vue, frontend/src/components/VSearchResultsGrid/VAudioCollection.vue, frontend/src/components/VSearchResultsGrid/VAudioResult.vue, frontend/src/components/VSearchResultsGrid/VImageCollection.vue, frontend/src/composables/use-route-result-params.ts, frontend/src/pages/image/[id]/index.vue, frontend/src/stores/media/index.ts, frontend/test/playwright/e2e/all-results-analytics.spec.ts, frontend/test/playwright/e2e/all-results-keyboard.spec.ts, frontend/test/playwright/e2e/attribution.spec.ts, frontend/test/playwright/e2e/audio-detail.spec.ts, frontend/test/playwright/e2e/image-detail.spec.ts, frontend/test/playwright/e2e/search-navigation.spec.ts, frontend/test/playwright/utils/search-results.ts
Fixes #5005 by @zackkrida
Fixes #5107 by @obulat
This PR updates the analytics events so that we can analyze results for relevancy for their search queries.
When the user interacts with a search results, we can assume that the result is relevant to their search [^1]. There are several events that are sent when the users interact with a single result: `SELECT_SEARCH_RESULT` on the search result page, and `COPY_ATTRIBUTION`, `GET_MEDIA` and `RIGHT_CLICK` on the single result page. 
This PR adds the data on which search term was the media returned for, and what position it had in the result list. Now, we will be able to analyze not only which items the users click on on the search results for the specific query, but also which items they are downloading, or copying the attribution for. I …
=> Update the analytics events for relevancy

frontend/server/api/sources.ts, frontend/src/stores/provider.ts, frontend/test/unit/specs/stores/provider.spec.ts
Fixes #5287 by @obulat
This PR uses the server route with `defineCachedFunction` to cache the `/stats` response for an hour. This is following SWR (stale-while-revalidate) principle, so if a request to update the stats fails, the cached (even outdated) version is still returned.
This PR also simplifies the provider store to combine the fetch state for images and audio into a single object since we don't really need the distinction between the media types.
The requests don't add the auth token to the API request, but it should be okay because the request is only sent once an hour.
Run the app locally, and open the `localhost:8443/sources` page. You should see the log about `/stats` requests (for audio and images) in the terminal (not the browser console). Now, reload the page several …
=> Add sources cache to Nuxt app

.github/workflows/ci_cd.yml, frontend/Dockerfile, frontend/nuxt.config.ts, frontend/package.json, frontend/sentry.server.config.ts, justfile
Follow up on #5279
This pull request updates the Docker build process to address an issue with environment variables not being properly read by Sentry during image builds. This prevented the source maps from being created and sent to Sentry. The `release` also wasn't set, so the source maps did not work.
In our CI pipeline, when a pull request is merged into the main branch, the process builds a Docker image that will then be deployed to production. We need to generate the source maps and release for this image, and not other builds.
To generate and upload the source maps and release, Sentry needs the auth token. This is set in CI only on the push to main (when a PR is merged) or when release is triggered manually through the Actions GUI. This way, the source maps are generated and sent …
=> Add required variables for Nuxt Sentry setup

.github/workflows/ci_cd.yml, frontend/Dockerfile
Follow up on #5284
This PR uses the `.env.sentry-build-plugin` file that is expected by the plugins that build Sentry module for the server (rollup for nitro and vite for nuxt) to provide the auth token. Simply adding the env variable did not work.
See that the release worked on the commit that added `pull_request` to the conditions.
<details>
```
Version 1.1
1 Letterman …
```
=> Use .env.sentry-build-plugin for Sentry auth token

api/api/models/audio.py, api/api/serializers/audio_serializers.py, api/api/views/audio_views.py, api/api/views/media_views.py, api/test/integration/test_dead_link_filter.py, api/test/unit/models/test_audio.py, api/test/unit/views/test_audio_views.py
Fixes #5274
This PR prevents audio list requests with `?peaks=true` from making N+1 queries by fetching all `AudioAddon` models from the DB in a single call.
With DEBUG logging enabled, make API calls to the `/v1/audio/` endpoint with `?peaks=true`. You should see only 2 total calls to the DB, where the second call is for audio addons:
```sql
SELECT
"api_audioaddon"."created_on",
"api_audioaddon"."updated_on",
"api_audioaddon"."audio_identifier",
"api_audioaddon"."waveform_peaks"
FROM "api_audioaddon"
WHERE "api_audioaddon"."audio_identifier" IN (
'134d47ed3cd448f1b34e2671a428b463'::uuid,
-- more UUIDs
'2708c8f651254cbd992373e55359f1a8'::uuid
);
```
for the catalog or `ov just api/generate-docs` for the …
=> Pull all addons in one DB request

frontend/nuxt.config.ts, frontend/package.json, frontend/sentry.client.config.ts, frontend/sentry.server.config.ts, frontend/server/api/sources.ts, frontend/src/app.config.ts, frontend/src/pages/preferences.vue, pnpm-lock.yaml
Fixes #5296 by @obulat
This PR changes the way the `release` value is set for the Sentry module on the client. It uses a `sentryRelease` value in the `nuxtConfig` set to the `process.env.SEMANTIC_VERSION`. Using a different name for the variable (i.e., not the corresponding `NUXT_PUBLIC_SENTRY_RELEASE` one) makes sure that the value is not changed during the runtime.
This PR also adds a `platform` tag to easily filter server/client events in Sentry UI.
To test that the release is baked in during the build time, you can use different values for `SEMANTIC_VERSION` env variable during build/runtime. To do that:
1. Build the app using `ov env SEMANTIC_VERSION=build just frontend/run build`
2. Start the app with a different value: `ov env SEMANTIC_VERSION=start just frontend/run build`
3. Go …
=> Fix Sentry client setup

load_sample_data.sh
This fixes an issue I identified while trying to run `ov just init` - see [the Make WordPress Slack](https://wordpress.slack.com/archives/C02012JB00N/p1734561799110209)
This PR modifies the `ov just init` script to start the catalog stack at the very beginning, so that it's ready and initialized for the `just catalog/cli` commands that come later in the `load_sample_data.sh` script.
Run `ov just init` and observe that it fails:
```
just dc exec -u airflow  "$@"
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker compose -f docker-compose.yml "$@"
service "scheduler" is not running
error: Recipe `dc` failed on line 266 with exit code 1
error: Recipe `exec` failed on line 339 with exit code 1
error: Recipe `cli` failed on line 89 with exit code 1
error: Recipe `init` failed …
```
=> Start the catalog service as part of `ov just init`

api/pdm.lock, api/pyproject.toml, packages/python/openverse-attribution/pdm.lock, packages/python/openverse-attribution/pyproject.toml
This PR downgrades the Python version to the previous one, 3.11.*, partially reverting #5095, to see if the API memory utilization slows down. Ideally, it should return to acceleration levels previous to release from [November 4th](https://github.com/WordPress/openverse/releases/tag/api-2024.11.04.06.41.58) (below 50% after 2 weeks).
The highest peak on the graph coincides with the update of aiohttp (#5165) but we wanted that to fix #4901. It may have been drived by the Django v5 upgrade too, see release from [2024.11.17](https://github.com/WordPress/openverse/releases/tag/api-2024.11.17.18.36.17). So it's easier to test the Python version downgrade first. If that doesn't alleviate the problem, we can go back to version 3.12 (or even further, bump to 3.13) and revert the aiohttp update.
I …
=> Downgrade the API's python version back to 3.11

frontend/package.json, pnpm-lock.yaml
While trying to fix the build problems in the Storybook update PRs, I found that Nuxt version mismatch causes some problems, so updating Nuxt to the latest version here. I don't know why Renovate did not open Nuxt PR.
The CI should pass, and the app should work as usual
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
=> Update dependency Nuxt

api/pdm.lock, api/pyproject.toml
This update might help address the memory leak problem. This PR is based on the Python update PR (#5327)
Here's the summary from ChatGPT of why upgrading might help solve memory leak problems:
- **Fixed Paused Connections on Streaming** ([#10169](https://github.com/aio-libs/aiohttp/pull/10169)):  
There was a bug where connections used for streaming downloads could return to the pool in a paused state. Even though we don’t iterate over chunks manually, calling `await upstream_response.content.read()` in the thumbnail is still “streaming” under the hood. This could lead to connections remaining half-open, causing a buildup of idle connections and potentially leading to memory or resource leaks.
- **Improved Keep-Alive and `force_close` Handling**:  
In various **3.11.x** patches, aiohttp …
=> Update `aiohttp` to last patch version 3.11.11

api/api/utils/image_proxy/__init__.py
Related to #5334.
This attempts to close the idle db connections by using the `django.db.close_old_connections()` function[^1] after getting image thumbnails. Previously, in #5328, it was suggested that the `await upstream_response.content.read()` call could be the origin of the problem, so I put the db function in a `finally` block close to it.
N/A. CI should pass, and we will see how it behaves in production.
[^1]: https://docs.djangoproject.com/en/5.1/ref/databases/#connection-management
<details>
```
Version 1.1
1 Letterman …
```
=> Close old db connections after getting thumbnails

frontend/src/components/VAudioTrack/VAudioTrack.vue, frontend/src/components/VAudioTrack/VWaveform.vue, frontend/test/unit/specs/components/AudioTrack/v-audio-track.spec.js
Fixes #2202  by @obulat 
An audio-related error is observed across all audio cells in the content view. Specifically, all cells incorrectly display an error message regardless of their state. This occurs because the application does not validate whether the audio.id matches the activeMediaStore.id when setting the message. As a result, messages intended for the active audio track are incorrectly shown for all audio tracks.
A reliable way to test this behavior is to find `.oga` audio files in Safari.
1. Run the app locally and go to http://localhost:8443/search/audio?q=cat&extension=oga
2. Click on Play: you should see the error message only on the active track.
Compare with the same in production: you see that the error message is displayed on every track.
PRs) or the media properties …
=> Only show audio message when track ID matches active

documentation/meta/maintenance/elasticsearch_cluster.md
This PR adds or updates commands for an ES node replacement. We used this document yesterday, and @dhruvkb and I observed it required some changes.
Docs are generated automatically. Proofread the updated page using the link provided in the first comment below.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update instructions for ES node replacement

catalog/dags/common/slack.py, catalog/dags/data_augmentation/rekognition/add_rekognition_labels_dag.py, catalog/dags/elasticsearch_cluster/create_new_es_index/create_new_es_index_dag.py, catalog/dags/elasticsearch_cluster/create_proportional_by_source_staging_index/create_proportional_by_source_staging_index_dag.py, catalog/dags/elasticsearch_cluster/point_es_alias/point_es_alias_dag.py, catalog/dags/elasticsearch_cluster/recreate_staging_index/recreate_full_staging_index_dag.py, catalog/dags/maintenance/rotate_envfiles.py, catalog/dags/popularity/popularity_refresh_dag_factory.py
Fixes #4884 
- `notify_slack` method now determines dag_id through context variables
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> Updated notify_slack method

catalog/dags/maintenance/rotate_envfiles.py
This PR fixes the bug with missing `dag` param when `notify_slack` is invoked as a function.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix missing `dag` parameter in Slack notification
