data/github.yml

This PR updates the name of the scripts repo in the YAML data file.

Update repo names in datafile

---

data/labels.yml

Suggestions to the wording and emoji are welcome

Add an "internal improvement" label

---

.github/GITHUB.md
.github/sync.yml
.github/workflows/label_sync.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml
.github/workflows/pr_label_check.yml
.github/workflows/project_automation.yml
.github/workflows/sync_meta.yml

This PR increases the quality of documentation for the workflows. Each workflow now has a link to its documentation placed in this repo.
Workflows are synced from here to each of the individual Openverse repos. This change ensures that documentation about what a workflow does is only a click away.
<details>
```
Version 1.1
Suite D4700
By …
```

Improve documentation for workflows

---

.github/workflows/new_prs.yml

Project automations for PRs from forks fail because of the secrets not being accessible. The `pull_request_target` event should allow the actions to run in a more secure context by using workflow code from the target branch instead of the head. In this context the actions should have access to secrets and run as expected.
See the [GitHub event docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) for more information.
<details>
```
Version 1.1
Suite D4700
San …
```

Update PR automation for forks

---

.github/PULL_REQUEST_TEMPLATE.md

This PR proposes some simplification to our PR template, by removing sections, renaming sections, and shifting things around a bit. This is intended to encourage the use of the template by lowering the work required to fill out, but also making things clearer and more straightforward.
These changes are also totally _up for discussion_, other ideas are very welcome!
This PR is using the modified template! Review this very PR and compare it to another one using the old templates.
<details>
```
Version 1.1
Suite D4700 …
```

Simpler and clearer pull request template

---

.github/GITHUB.md
.github/workflows/new_prs.yml

This PR changes the board name used in automations to the new [Openverse PRs](https://github.com/orgs/WordPress/projects/8) board.
<details>
```
Version 1.1
Suite D4700 …
```

Update board name to track PRs in a separate project

---

.github/workflows/sync_meta.yml

This PR adds the priority label on PRs made by the sync action so that they don't fail CI checks. The priority was set to "🟧 priority: high" because these PRs should me immediately merged.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```

Add priority label to sync PRs

---

.github/GITHUB.md
.github/workflows/discussion_ping.yml

This PR adds a new workflow which is similar to the existing PR notification workflow (and draws heavily from it). This workflow will send a notification to the slack channel when a new discussion is made in any Openverse repo.
I'm not quite sure how to test this!
<details>
```
Version 1.1
Suite D4700 …
```

Add a workflow for a notification on new discussions

---

README.md

The missing protocol caused the link to be broken.
* Go to https://github.com/WordPress/openverse
* Click on the "Community Site" link.
* Notice that is a link relative to the GitHub repository.
* Go to https://github.com/jeherve/openverse/tree/patch-1
* Click on the "Community Site" link again.
* The link  should now work.
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Readme: fix link to Openverse P2

---

data/labels.yml

Fixes #126 by @zackkrida 
<details>
```
Version 1.1
Suite D4700 …
```

Add technology labels

---

.github/sync.yml

This PR syncs the PR ping workflow with the `Automattic/openverse-infrastructure` repository to enable notifications from that repo into Slack.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```

Add PR ping functionality to the infra repo

---

.github/workflows/discussion_ping.yml
.github/workflows/label_sync.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml
.github/workflows/pr_label_check.yml
.github/workflows/pr_ping.yml
.github/workflows/pr_project_automation.yml
.github/workflows/project_automation.yml
.github/workflows/sync_meta.yml
.github/workflows/weekly_updates.yml
.pre-commit-config.yaml
data/labels.yml

Corresponds to WordPress/openverse-api#435
This PR lints YAML files with Prettier, in much the same way as the API repo does.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

Lint YAML files using Prettier

---

.github/GITHUB.md
.github/release_drafter.yml
.github/sync.yml
.github/workflows_downstream/draft_release.yml
data/labels.yml

Fixes #68 by @zackkrida
This PR brings the release drafter workflow and configuration to this repo. This
- ensures a consistent changelog in all Openverse repos
- reduces the burden of managing the versioning logic in multiple repos
- keeps the changelog close to the labels due to their tightly coupled nature
Workflows are quite hard to test. A careful read while referring to the [docs](https://github.com/release-drafter/release-drafter) might be useful. Comparing against an existing config (such as the [one from `openverse-api`](https://github.com/WordPress/openverse-api/blob/main/.github/release-drafter.yml)) might help.
<details> …

Centrally sync release drafter configuration

---

rfcs/20220218-introduce_ui_state_cookie_to_frontend.md

<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with …
```

RFC: Introduce UI state cookie

---

rfcs/README.md

Adds a draft README for the `rfcs` folder.
The format section is just based on my own past experience with this sort of thing and what I've seen working. I am eager for input here from others especially if there are missing sections that should be added.
<details>
```
Version 1.1
Suite D4700 …
```

Add RFC README.md

---

rfcs/README.md

This PR is a follow up to #163 which adds a minimum wait period for RFCs before they can be merged. This is to allow time for feedback from contributors and the community, even if consensus is reached via 2 approvals.
<details>
```
Version 1.1
Suite D4700
indicated …
```

Add minimum wait period to RFCs

---

rfcs/20220217-visual_regression_testing.md

<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with …
```

RFC: Visual regression testing

---

rfcs/20220223-convert_the_store_from_vuex_to_pinia.md

<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with …
```

RFC: Migration from Vuex to Pinia in the front-end

---

.github/sync.yml
.github/workflows/label_new_pr.yml
.github/workflows/label_pr.yml
.github/workflows/pr_label_check.yml
python/Pipfile
python/Pipfile.lock
python/label_pr.py

Fixes #175 by @AetherUnbound 
Fixes #75 by @dhruvkb 
This PR sets up the action to label PRs based on info from their linked issues. It follows this algorithm:
- if the PR has linked issues, iterate over them to find the issue with all 3 categories of labels (`aspect: *`, `goal: *` and `priority: *`)
- if a fully-labelled linked issue is found, apply the labels from that issue on the PR
- else, apply the `🚦 status: awaiting triage` label.
GitHub actions are notoriously hard to test. But the Python script can be tested locally.
0. Populate the `.env` file with a GH access token in the `ACCESS_TOKEN` variable.
1. Run the script as 
```
pipenv run python label_pr.py --pr-url <any PR url that ACCESS_TOKEN can access>
```
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contribut …

Create a workflow to label a PR based on its linked issues

---

python/label_pr.py

This PR fixes the PR labeller from overwriting exising labels on PRs, like it did [here](
https://github.com/WordPress/openverse-frontend/pull/1097#event-6217015405) and [here](https://github.com/WordPress/openverse/pull/185#event-6217104825).
<details>
```
Version 1.1
Suite D4700 …
```

Prevent PR labeller from overwriting labels on labelled PRs

---

.github/workflows/label_pr.yml
.github/workflows/label_sync.yml
.github/workflows/pr_project_automation.yml
.github/workflows/project_automation.yml

Fixes #183 by @dhruvkb 
Updated Python Workflow YAMLs to use "3.10" as the Python version.
<details>
```
Version 1.1
Suite D4700
(b) …
```

Update Python workflows to run on Python 3.10

---

rfcs/20220221-3d_model_support.md

Combined from WordPress/openverse-frontend#889 and WordPress/openverse-catalog#370
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open …
```

RFC: 3D Model Support

---

.github/ISSUE_TEMPLATE/feature_request.md

Removes priority and aspect labels from the feature request template.

Update feature_request.md label template to remove priority and aspect

---

.github/workflows/label_new_pr.yml
.github/workflows/label_pr.yml
.github/workflows/label_sync.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml
.github/workflows/pr_project_automation.yml
.github/workflows/project_automation.yml
.github/workflows/sync_meta.yml
.github/workflows/weekly_updates.yml

Fixes #182 by @dhruvkb 
Just a find and replace job of `secrets.ACCESS_TOKEN` to `secrets.GITHUB_TOKEN`.
Not sure how to test.
<details>
```
Version 1.1
Suite D4700 …
```

Remove access token usage

---

rfcs/20220307-monitoring_across_the_stack.md

I accidentally merged a linting error into main, sorry!
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

Fix linting error

---

.github/workflows/label_sync.yml
automations/data/labels.yml

Fixes #221 by @sarayourfriend 
This PR changes the label sync action to use the @openverse-bot's access token instead of the `GITHUB_TOKEN` to sync labels. This is because the bot can access other repos, while the built-in token cannot.
<details>
```
Version 1.1
Suite D4700
(a) …
```

Fix broken label sync action

---

automations/data/labels.yml

This is a small PR to change the wording of the "critical" and "medium" labels to use "addressed" instead of "fixed". Some issues are work that doesn't necessary involve a _fix_, but could be critical or medium priority nonetheless.
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Change priority label wording from "fixed" to "addressed"

---

README.md

Fixes #[156] by @[AetherUnbound]
Change the "good first issues" url on the [Helpful links for new contributors](https://github.com/WordPress/openverse#helpful-links-for-new-contributors) section of the README.md file
<details>
```
Version 1.1
Suite D4700 …
```

Change a 'Helpful links for new contributors' url of the readme.md file

---

automations/js/src/weekly_report.js

This script isn't being used but I think it'd be best to remove this old, deleted key.

Update weekly_report.js to remove old auth token

---

automations/python/Pipfile
automations/python/Pipfile.lock
automations/python/label_pr.py

This PR allows the labelling action to run on PRs in private repos, using `mechanise` and `pyotp` to login into the GitHub UI and scrape it. This is borderline insane and the only reason we need to do this is because GitHub still has no API for finding issues linked to a given PR.
GitHub Actions are hard to test. The only recourse is to clone the repo, populate the `.env` file and trigger the script locally. Or read the code carefully.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Add mechanism to access pages in private repos

---

.github/workflows/label_pr.yml

Fixes #258 by @AetherUnbound
Follow up on #248 to add the requisite secrets to the workflow environment.
We'll have to merge this and see, unfortunately! I have added those secrets to the repo.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```

Add GitHub secrets to label PR workflow env

---

.github/actionlint-matcher.json
.github/sync.yml
.github/workflows/actionlint.yml
.github/workflows/discussion_ping.yml
.github/workflows/label_pr.yml
.github/workflows/pr_ping.yml
rfcs/20220307-monitoring_across_the_stack.md

Fixes #245 by @sarayourfriend 
Adds `actionlint` as a synced workflow action.
Checkout this branch. Make a change that should cause actionlint to fail like referencing a non-existing property on `github` context or malformed yaml. [Install `actionlint`](https://github.com/rhysd/actionlint/blob/main/docs/install.md) and confirm that the errors are fixed.
<details>
```
Version 1.1
Suite …
```

Add actionlint

---

load_testing/justfile

Fixes #272 by @dhruvkb 
<details>
```
Version 1.1
Suite D4700
of …
```

Switch to proper host for macos detection

---

.github/ISSUE_TEMPLATE/sentry_bug.md

Fixes #212 by @zackkrida 
Adds a simple template for Sentry error reporting. 
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Add sentry bug issue template

---

load_testing/justfile

Small follow up to #257, this PR ensures that the Docker container gets removed automatically once the container exits. 
Run `just api` in the `load_testing` directory and ensure that when the container exits it is also removed.
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Remove load testing container after run

---

CONTRIBUTING.md

I modified the "Keeping in Touch" section to add the prioritization meeting session we are having every four weeks.

Adding the prioritization meeting session in the description

---

.github/ISSUE_TEMPLATE/discussion.md

Fixes a small issue in the discussion template where `[]` are rendered as text instead of checkboxes due to a missing space in between them.
- [] This (`[]`) isn't a checkbox
<details>
```
Version 1.1
Suite D4700 …
```

Add space to change `[]` into checkboxes

---

.github/ISSUE_TEMPLATE/sentry_bug.md

Related to #154 by @sarayourfriend 
Includes the label in the issue creation for saving clicks and time.
See the [template](https://github.com/WordPress/openverse/blob/main/.github/ISSUE_TEMPLATE/sentry_bug.md) after merging.
<details>
```
Version 1.1
Suite D4700 …
```

Add sentry label to issue template

---

.github/ISSUE_TEMPLATE/sentry_bug.md

Follow up of #303.
Accidentally broke the sentry issue template so this should fix it.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
```

Remove trailing comma, fix sentry issue template

---

CONTRIBUTING.md

This PR adds a few more potential contributions that community members can make beyond those that are already mentioned within the CONTRIBUTING.md document. This was spurred on by a recent question from our Make WP Slack community.
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Add more possible contributions to CONTRIBUTING.md

---

.github/workflows/actionlint.yml
.github/workflows/lint.yml

Related to #267 by @sarayourfriend 
This pull request Adds concurrency settings for workflow
<details>
```
Version 1.1
Suite D4700 …
```

Add concurrency settings for workflow

---

automations/python/label_pr.py

This PR updates the scraping logic used in the labelling action based on changes to the GitHub UI markup.
<details>
```
Version 1.1
Suite D4700
indicated in …
```

Update scraping logic to keep up with GitHub UI

---

.github/sync.yml

Follow up to #318, I forgot to update the file name in the synced files list as well :see_no_evil: Sorry for the multiple PRs, it's frustrating there's no easy way to test this all!
<details>
```
Version 1.1
Suite D4700 …
```

Update synced files list to new subscribe-to-json filename

---

.github/workflows/weekly_updates.yml

Switch to a `pnpm install` for the weekly update cron action.
This doesn't currently cache pnpm dependencies as we do on the frontend but I think that's okay given the once-per-week nature of this script.
Fixes #327 by @zackkrida 
Thanks to @AetherUnbound for the quick diagnostics here!
Merge and try a manual run of the action, I suppose.
<details>
```
Version 1.1
Suite D4700 …
```

Fix the week in Openverse posts

---

justfile

This PR updates the `_js-install` recipe to execute `pnpm install` instead of `npm install` because the package manager was changed to `pnpm` to match that in Openverse frontend.
<details>
```
Version 1.1
Suite D4700 …
```

Use `pnpm` in Just recipe to install JS deps

---

.github/subscribe-to-label.json
.pre-commit-config.yaml
automations/js/src/weekly_report.js
load_testing/k6/main.js
load_testing/k6/search.js
load_testing/k6/utils.js
pnpm-lock.yaml
prettier.config.js
renovate.json

Fixes #317 by @obulat 
This PR removes the `pretty-format-json` hook, and expands the coverage of Prettier to include all files except Markdown `.md` files. This means that JSON files will now be formatted by Prettier which 
- preserves unicode such as emoji
- is more standardised in the JS world
<details>
```
Version 1.1
Suite D4700
By …
```

Expand Prettier to eliminate pretty-format-json

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixes #329 by @AetherUnbound 
- Removes the `Implementation` section from Feature Request issue template
- Removes the `Resolution` section from Bug Report issue template
After merging, we can create a New issue and select the Feature Request or Bug Report template and check if there are any sections for Implementation or Resolution. 
<details>
```
Version 1.1
Suite D4700 …
```

Removed "Implementation/Resolution" section from issue templates (#329)

---

.github/workflows/pr_label_check.yml

Fixes #344 by @krysal 
Modified the label action to agile pathway.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```

Change the label checker action

---

.github/workflows/pr_label_check.yml

Follow up to #347, this PR fixes an issue where the new label check action was not configured to use the `repo_token` as [specified in the action documentation](https://github.com/agilepathway/label-checker).
This affects:
- https://github.com/WordPress/openverse-infrastructure/pull/305
- https://github.com/WordPress/openverse-api/pull/1039
- https://github.com/WordPress/openverse-catalog/pull/921
We can try and open a PR after this one is merged or modify the labels on an existing one before merging any of the downstream sync actions.
errors.
<details>
``` …
```

Add repo token to label check workflow

---

rfcs/20221006-frontend_event_tracking.md

This is an RFC which outlines a solution for collecting analytics events on the frontend. Please see the ['files changed' diff](https://github.com/WordPress/openverse/pull/312/files) for the full text.
- @krysal 
- @dhruvkb 
2022-1-16

RFC: Frontend event tracking

---

templates/.pre-commit-config.frontend.yaml.jinja

Fixes #2096: https://github.com/WordPress/openverse-frontend/pull/2096
Currently, #2096 is failing linting stage of the CI because it raises warnings. Adding `remake` to eslint_exclude removes those warnings.
Merge and see?
errors.
<details>
```
Version 1.1
Suite D4700
By making a …
```

Add remake to eslint_exclude

---

.github/workflows/pr_project_automation.yml

Fixes #391 by @AetherUnbound 
This PR fixes the failing PR Project automation that clears out the closed and merged PRs from our project board after the weekly development chat.
This workflow had been failing for a very long time because of an incorrect token 🤦.
errors.
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Change authentication token

---

.github/workflows/weekly_updates.yml
package.json
pnpm-lock.yaml

This PR restores the functionality of the weekly Make post workflow.
See the last successful run (https://github.com/WordPress/openverse/actions/workflows/weekly_updates.yml) after so many failures.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Restore the functionality of the weekly Make post

---

docs/projects/README.md

Quick follow up to #366, this is a small change to make the term "rollback" consistent everywhere it was intended to be used.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```

Change 'Reverted' to 'Rollback' in project docs

---

.github/workflows/ci_cd.yml
.github/workflows/generate_pot.yml
.github/workflows/sync_meta.yml
api/justfile
automations/js/justfile
automations/python/justfile
frontend/justfile
ingestion_server/justfile
justfile
nginx/justfile

This PR improves the monorepo workflow (both human workflow and GitHub Actions workflows).
- Adds color for logical separation in the root `just` output. Who doesn't like a splash of color?
- Removes all mentions of the `monorepo` branch, that's `main` now.
- Prevents both frontend and API from being deployed on each change. Only the changed one has to.
- Fixes an actionlint error and rectifies incoherent indentation.
errors.
<details>
```
Version 1.1
Suite D4700
San …
```

Improve the monorepo workflow

---

README.md

Makes this image a bit more useful by leveraging it as a link to Openverse.org.

Wrap README image in an openverse.org link

---

automations/data/github.yml

As mentioned above, this removes the API and frontend repos from the project automation, since they are now part of the "main" repo. This should hopefully reduce the number of times we run into the GitHub API limit, since it appears that #396 has been moving issues back and forth in the archived repos.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Remove the API and Frontend repos from project automation

---

.github/filters.yml
automations/js/package.json
automations/js/src/last_week_tonight.mjs
frontend/Dockerfile.playwright
frontend/bin/playwright.sh
frontend/docker-compose.playwright.yml
frontend/package.json
pnpm-lock.yaml

Fixes #773 by @dhruvkb 
This PR
- replaces the use of `node-fetch` in automations with Axios
Shamefully hoisting conflicting versions of `node-fetch` can break either the frontend or the automations (depending on the hoist order). This will most likely be fixed after Nuxt 3 migration (see nuxt/nuxt#14146) but for now, not using `node-fetch` is stabler.
- updates the scope of files that trigger the frontend test-suite
The frontend being a workspace package means that changes to the root `package.json` and `pnpm-lock.yaml` will affect it.
- removes duplicated fields from inner `package.json`
`pnpm` will read these fields from the root `package.json` anyway. The `Dockerfile` for Playwright which was coupled to the `packageManager` field has been decoupled as well.
a …

Use Axios instead of node-fetch

---

.github/sync.yml

See https://github.com/WordPress/openverse-infrastructure/pull/377 and https://github.com/WordPress/openverse-catalog/pull/1002 for context
This PR excludes a few new issue templates from syncing to the catalog and infrastructure repos, since they're not necessary or relevant to either of those repositories.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Exclude monorepo-specific issue templates from sync

---

frontend/src/pages/about.vue

Fixes #567 by @krysal
Updates the "issue" link on the about page to point to the issues landing page. This is much clearer for users who do not already have a GitHub account or who aren't logged in.
Go to the /about page locally and click the "issue" link. Observe you are taken to the catalog issue list.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Update issues link on the about page

---

frontend/nuxt.config.ts

Fixes #817 by @obulat
This PR specifies the absolute path to the `tailwind.config.js` file in the PostCSS config. Since in the pnpm workspace dependencies are sometimes in the inner `node_modules` and sometimes outer (shameful hoisting is really a PITA), the relative path doesn't work reliably and the default nature of checking the root directory is not acceptable to us.
1. Modify the frontend code and verify that HMR works.
errors.
<details>
```
Version 1.1 …
```

Specify absolute path to Tailwind config to restore HMR

---

frontend/src/stores/ui.ts

Fixes #782 by @obulat
The package we use for managing cookies, `cookie-universal-nuxt` parses each cookie value (which is a string) as JSON, converting them to types like `number` or `boolean`.
This PR prevents cookies with incorrect values from being read into the store. The following checks are applied:
- the `uiBreakpoint` cookie is checked against the keys in `ALL_SCREEN_SIZES`
- the `uiIsFilterDismissed` and `isMobileUa` are checked to be of boolean type
- the `uiDismissedBanners` is checked to be an array using `Array.isArray`
If these conditions are not met, the cookie is not read and the store's default values are used instead.
1. Using the developer tools, fiddle with the cookie values.
2. Check that invalid cookies are automatically …

Handle incorrect types in cookie value

---

frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
frontend/src/components/VHeader/VSearchBar/VSearchBar.vue
frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue

Adds `action="search"` to the search forms on Openverse. With this change, the user is able to submit openverse searches when JavaScript is disabled. The site is surprisingly usable without JavaScript; the core flow of searching and selecting single results works quite well.
This also fixes a rare, but occasional, bug, where the user could submit a search before the page's JavaScript bundles have finished loading and parsing. The form submits as a standard html form without an action assigned, so appears to the user like a page refresh.
Run the frontend locally, disable JS, and submit a search from the homepage.
Additionally, do the same on `main` and observe the search does not work.
errors. …

Add actions to search forms

---

.github/actions/get-changes/action.yml
.github/workflows/ci_cd.yml
.github/workflows/pr_label_check.yml
automations/python/label_pr.py

This PR adds the "stack" category as an _optional_ label to add for the `label_pr` workflow. It also moves the `get-changes` step into a separate, composite action which can be reused.
The PR adds the auto-stack-adding action to the `ci_cd` workflow; I was initially going to add it to the `label_pr` since I'm concerned about race conditions happening between the `label_pr` action and the stack-labeling step. But it would be a bit more work to convert `PR_URL` into fields that the label action can actually use, so I held off for now. Let me know if y'all think that would be a better approach, I can take the time to set that up.
errors. …

Add stack label if available, make get-changes composite action

---

justfile

Fixes #845 by @dhruvkb
This PR prevents cURL from piping into `grep`. This allows us to write the cURL output to a file, `cat` it, then run `grep` on it. By splitting up the steps we can better identify the cause of the problem.
Also since we're no longer piping into `grep`, cURL no writes to a pipe that's closed midway, which should fix the problem entirely.
No failures in [5 CI attempts](https://github.com/WordPress/openverse/actions/runs/4343546105/jobs/7587473745) makes me think it's fixed now.
errors.
<details>
```
Version 1.1 …
```

Identify and fix cause of cURL error 23 when setting up pre-commit

---

.github/workflows/ci_cd.yml

Fixes #908 by @AetherUnbound
This PR adds the `get-image-tag` step as a dependency (via `needs`) of the nginx job which actually uses that value when building the image. This was not previously defined as a dependency, and so while the action unfortunately didn't throw an error, it built the image without a version defined.
We should be able to see that this builds the nginx image with the correct semantic version as part of the CI/CD run.
errors.
<details>
```
Version 1.1
1 Letterman …
```

Add get-image-tag as dependency for nginx build step

---

frontend/package.json
package.json

Fixes #827 by @obulat
To stop warnings about missing peer dependencies, we move the settings to the root `package.json`.
Try re-installing dependencies by running `just frontend/run dev` or `just install`. You shouldn't see warnings about missing peer dependencies (react, consola etc)
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Move peerDependencyRules to root package.json

---

frontend/package.json
pnpm-lock.yaml

Replaces #582 (as a base for the pinia update)
The renovate-bot update in #582 is updating some unrelated libraries. Some, like typescript version reversion, cause CI to fail. This PR updates the Vue version to the latest 2.x. It is useful for the Vue features, and it also allows us to minimize the changes in a pinia update.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Update Vue from 2.7.10 to 2.7.14

---

.github/workflows/deploy-production-api.yml
.github/workflows/deploy-production-nuxt.yml
.github/workflows/deploy-staging-api.yml
.github/workflows/deploy-staging-nuxt.yml

Fast follow to #886, this PR adds a number of pieces that were missed from the move from a composite action to a callable workflow, namely:
- Concurrency settings for deployments
- Initiation user validation check
- Allowing the workflow to be called directly with an image tag
This is applied from https://github.com/WordPress/openverse-infrastructure/pull/415
I think we'll only be able to test some of these pieces _after_ a merge.
errors.
<details>
```
Version 1.1
Suite …
```

Add user validation, concurrency, manual runs to deployment workflow

---

frontend/src/stories/Introduction.stories.mdx

Fixes #929 by @obulat
This PR fixes the links on the main Storybook page.
Check out the Storybook preview.
errors.
<details>
```
Version 1.1
Suite D4700
have the right to …
```

Fix links on the main Storybook page

---

api/catalog/api/admin/__init__.py

Related to https://github.com/WordPress/openverse/pull/933
If the heavy queries are coming from admin (which it looks like they are), then we can disable the media model admins and avoid them. If they aren't coming from here, then we've already cut out one potential source of these queries and can look elsewhere.
Run the application locally and visit `/admin` and confirm that the deregistered admin views are no longer available. Check `/admin/api/image` for example to check specifically that it's absolutely not available.
errors.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Proje …

Deregister media model admins and dependents

---

.editorconfig
api/catalog/configuration/logging.py

Related to #933
Adds DB logging as a new option `DJANGO_DB_LOGGING`. Requires `LOG_LEVEL=DEBUG`.
We could inline it for all `DEBUG` settings or, if we wanted to avoid needing to change the environment variables (but why, it takes seconds to do so) we could inline it at `INFO` level, but then we'd need to revert this PR, wait for CI and image build etc, to remove it rather than just update the environment variables and redeploy (to an image already built).
Modify `api/.env` to add `LOG_LEVEL=DEBUG` and `DJANGO_DB_LOGGING=True`. `just down` then `just up` to get the new environment variables and confirm that DB logging is working.
errors. …

Add Django DB logging option

---

setup_plausible.sh

Fixes #942 by @obulat
This PR makes the `./setup_plausible.sh` Bash script idempotent. Now it can be re-run as many times as you wish with no negative effects.
Run the `./setup-plausible.sh` file many times.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Make Plausible setup idempotent

---

CONTRIBUTING.md

The link to Dev flow gave me a 404 error. I put in the correct link.
errors.
<details>
```
Version 1.1
Suite D4700
have the right …
```

Fix link to dev flow docs

---

load_sample_data.sh

I worked with @AetherUnbound to try and get the stack running on git-bash in Windows. Here was the error that we received: 
```
$ ./load_sample_data.sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "C:/Program Files/Git/usr/bin/bash": stat C:/Program Files/Git/usr/bin/bash: no such file or directory: unknown
```
We discovered that removing the absolute path when referencing bash in the docker-compose commands allowed this to be run on Windows.
1. `just init` should work on any system
errors.
<details>
```
Version 1.1 …
```

make init script more system agnostic

---

documentation/guides/general_setup.md

Fixes #960 by @glowatsk
Fixes #966 by @Wbrown633
Add paragraph from older docs that mentions coreutils. Added link to install homebrew.
Proofread updated docs. 
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

Update general setup guide for macOS

---

frontend/src/components/VAudioTrack/VAudioTrack.vue
frontend/src/components/VSearchResultsGrid/VImageCell.vue

Fixes #953 by @obulat
This PR makes the `searchTerm` optional, and only adds the `searchTerm` param to the URL if it's available.
When you search for something, audio and image links should have a URL param `searchTerm`. For single results, the Related audio/images should not have the `searchTerm` URL param, and there should be no warnings in the console on single result page.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```

Make `searchTerm` for VAudioTrack and VImageCell optional

---

.github/workflows/weekly_updates.yml
automations/js/src/last_week_tonight.mjs

This PR changes the Make Post to be published instead of a draft.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Change post status to 'publish'

---

api/catalog/api/controllers/search_controller.py
api/catalog/api/utils/check_dead_links.py
api/test/audio_integration_test.py
api/test/dead_link_filter_test.py
api/test/unit/utils/check_dead_links_test.py

Fixes #900 by @obulat
Fixes the linked issue with the strategy discussed in the issue.
I also went ahead and renamed `validate_images` to `check_dead_links`. I chose a dead-link-specific name because the method is already quite complex, and I wanted to avoid the assumption that additional validations could get loaded into that process. If that's a point of contention though, I can change it to just `validate_results` or something.
Run the app locally and ensure it runs. There are no thingiverse results locally so you'll need to rely on the unit tests to confirm that specific behaviour.
errors.
<details> …

Treat any non 200 status as failure for thingiverse

---

documentation/guides/general_setup.md

1. Go to the documentation/guides/general_setup.md and verify that the existing for pipenv install is not working.
2. Verify that the new url that I added does work.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```

Update to new link for pipenv install instructions

---

.github/workflows/new_issues.yml

Fixes #983 by @obulat 
This PR adds a `GH_TOKEN` to the workflow that adds new issues to the new Project board and assigns a priority custom field value based on the priority label.
Merge and see.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Add GH_TOKEN to the gh steps

---

api/env.template
api/justfile
docker-compose.yml

Fixes #993 by @krysal
This PR adds the missing `target` config to build the correct stage for the `web` service (the Dango app).
Try `just api/recreate` and see the API working normally at http://localhost:50280.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Fix local build of the API and add its `recreate` just command

---

.github/workflows/ci_cd.yml

This PR adds the CNAME to the `peaceiris/actions-gh-pages` usage that was lacking it. The intention is the same as #1005.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Add CNAME in other use of `actions-gh-pages`

---

.github/workflows/new_issues.yml

Fixes #1012 by @obulat 
This PR adds the missing variables to the workflow.
I'm not sure if the `ISSUE_ID` can be passed like this, on the workflow level, or whether it should be moved to the step level.
Merge and see
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Pass ISSUE_ID and PROJECT_ID to the new_issue workflow

---

.github/workflows/new_issues.yml

As stated in the name of the PR, we need to use `node_id` of the issue in GraphQL, instead of `id`.
See the error `gh: Could not resolve to a node with the global id of '1639954892'` in [the latest run](https://github.com/WordPress/openverse/actions/runs/4514866097/jobs/7951463409)
Priority set to high as this is necessary to move to the new Project.
Merge and hopefully this time see
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Use the `issue.node_id` for GraphQL API

---

.github/dependabot.yml
.github/workflows/sync_meta.yml

Quick PR to ensure we're adding the (now required) "stack" label to various automated PRs, namely those for dependabot and our file sync.
Examples of recently failing PR: https://github.com/WordPress/openverse-infrastructure/pull/424
Merge & find out
errors.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```

Add stack label to dependabot & sync label PRs

---

frontend/Dockerfile

This PR pins the version of pnpm used in the frontend Dockerfile by hardcoding it into the Docker image. This is a hotfix to solve broken frontend builds on `main`.
A cleaner solution would be to use build args to determine the pnpm version from the `packageManager` field in the `package.json` file.
Check that builds were [failing before](https://github.com/WordPress/openverse/actions/runs/4543475924/jobs/8008267406) and [passing after](https://github.com/WordPress/openverse/actions/runs/4543850320/jobs/8009146165) this fix.
errors.
<details>
```
Version …
```

Pin pnpm version in frontend `Dockerfile`

---

.github/workflows/new_issues.yml

The first part of the workflow, `Add new issue to project`, passed 🎉 
The second one failed because the variables were not available. The GITHUB_ENV variables can only be shared between steps, so I converted the jobs into steps here.
> You can make an environment variable available to any subsequent steps in a workflow job by defining or updating the environment variable and writing this to the GITHUB_ENV environment file. The step that creates or updates the environment variable does not have access to the new value, but all subsequent steps in a job will have access.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
Merge and see
errors. …

New issue automation fix: convert the jobs into steps to share env variables

---

.github/actions/build-docs/action.yml
.github/workflows/ci_cd.yml

This PR
- changes the outputs to use underscores instead of hyphens (for documentation reasons in #1001)
- merges multiple similar jobs into one matrix job
- new `django-checks` job combines the following old jobs:
- `test-redoc`
- `validate-openapi-spec`
- `django-check`
- `check-migrations`
- new `playwright` job combines the following old jobs:
- `nuxt-playwright-e2e`
- `nuxt-playwright-vr`
- `storybook-playwright`
- makes the deploy jobs use the `get-changes` job and let the `publish-images` job handle the test passes and failures
- merges the documentation preview and publish jobs into one job `emit-docs`
- enables GlotPress bulk download in docs generation
- removes stale references to the old 'release' trigger event
Since this is a clean up of the CI, check that CI passes.
`Update …

Simplify CI + CD workflow

---

frontend/nuxt.config.ts
frontend/src/static/opensearch.xml

Follow up to #842, this updates a few other references (namely the opensearch XML) to reflect a more accurate record count.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Update other references of media count to 700 million

---

.github/workflows/ci_cd.yml
.github/workflows/release-app.yml

Fixes #1033 by @sarayourfriend 
Fixes the problem using the method described in the issue.
Merge and see. You can try the command (on staging please!) locally for yourself if you'd like to confirm that it works.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Dispatch workflows instead of regular reuse to show deployment runs

---

.github/workflows/ci_cd.yml

This PR passes the actor to the deploy workflows with the `-f` flag so that the deploy can be authorised and the right person can be tagged for initiating the workflow.
Related to WordPress/openverse-infrastructure#447.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Pass actor for staging deploys with the `-f` flag

---

frontend/test/storybook/visual-regression/v-filter-button.spec.ts

The CI failure due to a snapshot test.
@sarayourfriend first reported a CI failure in the filter button storybook test.
This PR adds a wait of 500 ms to make sure that the focus ring has the expected appearance before taking a snapshot.
This change will be removed in #1002, once the transitions are removed from button borders. Instead of adding a TODO note to remove the wait here, I will add a comment to remove it in #1002.
The deleted test is a mixed up version of both (the name says focused , but the code is actually for resting state), and it was a leftover from copy-pasting 
errors.
<details> …

Add a wait to filter button test to fix CI

---

.github/workflows/release-app.yml

Fixes an issue noticed by @dhruvkb in https://github.com/WordPress/openverse-infrastructure/pull/449#issuecomment-1493463599
Part of https://github.com/WordPress/openverse-infrastructure/pull/447
@dhruvkb does this fix the issue as you described it?
Merge and give the release-app workflow a try.
errors.
<details>
```
Version 1.1
Copyright (C) …
```

Fix prod deployment workflow dispatch call

---

.github/actions/setup-env/action.yml
.github/workflows/bundle_size.yml
.github/workflows/ci_cd.yml
.github/workflows/generate_pot.yml
.github/workflows/release-app.yml
.github/workflows/weekly_updates.yml

- #1102
- Update ci to use "github.token" instead of "inputs.github_token" in setup-env
- Also remove github_token from ci_cd.yml
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Update ci to use github.token

---

.github/workflows/ci_cd.yml

Contrary to the expectations set in #1066, a bland and unhelpful report was received.
This PR rectifies that.
errors.
<details>
```
Version 1.1
Suite D4700
have the right …
```

Add `SLACK_WEBHOOK_TYPE` env var to reporting job

---

frontend/src/components/VAudioTrack/VPlayPause.vue
frontend/src/components/VBanner/VNotificationBanner.vue
frontend/src/components/VContentReport/VContentReportPopover.vue
frontend/src/components/VExternalSearch/VExternalSourceList.vue
frontend/src/components/VFilters/VFilterChecklist.vue
frontend/src/components/VGlobalAudioSection/VGlobalAudioSection.vue
frontend/src/components/VHeader/VHeaderDesktop.vue
frontend/src/components/VHeader/VHeaderInternal.vue
frontend/src/components/VHeader/VHeaderMobile/VContentSettingsButton.vue
frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue
frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
frontend/src/components/VHeader/VHeaderMobile/VSearchBarButton.vue
frontend/src/components/VHeader/meta/VSearchBarButton.stories.mdx
frontend/src/components/VIconButton/VIconButton.vue
frontend/src/components/VIconButton/meta/VIconButton.stories.mdx

Fixes #618 by @sarayourfriend
This PR adds a required prop named `label` to `VIconButton` to make sure that a button always has an accessible name. It uses a `label` prop instead of `aria-label` attr to make the validation easier, especially for elements that wrap around `VIconButton`.
Try removing the `label` prop for one of the `VIconButton`s. You should see a warning in the console.
The CI failures will be fixed by #1137.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Make `label` prop required for VIconButton

---

docs/projects/templates/implementation-plan.md

This PR adds an implementation plan template, similar to the [project proposal template](https://github.com/WordPress/openverse/blob/19791f51c063d0979112f4b9f4eeace04c8cf5ff/docs/projects/templates/project-proposal.md) and based on the [implementation plan description](https://github.com/WordPress/openverse/tree/19791f51c063d0979112f4b9f4eeace04c8cf5ff/docs/projects#implementation-plans-status-in-rfc) of our project notes document.
I, personally, find it difficult to start with an empty page, so hopefully this will be a useful guide for folks writing implementation plans! I'm sure this could be structured better or that I might be missing some aspect; any feedback is welcome.
errors. …

Add an implementation plan template

---

frontend/bin/get-custom-event-names.js

Fixes #1142 by @obulat
When you add events to the analytics module, you probably add some TS statements that don't have a name property. This causes a failure when setting it up using `just frontend/init`.
This PR adds optional chaining to only check the statements that do have a `name` property.
Try adding an event to the `analytics` module, or open one of the PRs that do.
Run `just frontend/init` without this change - you should see an error message.
Try adding this change - there init should work correctly.
errors.
<details>
```
Version 1.1
Copyright …
```

Add a check for `statement`'s name to fix the failure

---

.github/workflows/ci_cd.yml
.github/workflows/deploy-production-api.yml
.github/workflows/deploy-production-nuxt.yml
.github/workflows/deploy-staging-api.yml
.github/workflows/deploy-staging-nuxt.yml
.github/workflows/release-app.yml

Follow up to https://github.com/WordPress/openverse-infrastructure/pull/461, this changes the deployment name from `:` to `-` in the hopes that it will display properly in GitHub's Action UI:
If this PR alone makes it show up correctly in the sidebar we'll know! Otherwise we might have to merge first.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Change deployment workflow name from colon to dash

---

.github/workflows/release-app.yml

Our current release-app workflow doesn't succeed because the release draft action needs content writing permission: https://github.com/WordPress/openverse/actions/runs/4681450663/jobs/8294065163
I tried testing this but I think it's causing other errors that are preventing the workflow from succeeding. We may need to merge this to see if it works.
Failed runs:
- https://github.com/WordPress/openverse/actions/runs/4681626535
- https://github.com/WordPress/openverse/actions/runs/4681916169
errors.
<details>
```
Version 1.1 …
```

Add content write permission to release app workflow

---

frontend/src/composables/use-analytics.ts
frontend/src/stores/feature-flag.ts

This PR ensures that the `plausible_ignore` flag is set in `localStorage` immediately instead of the current buggy implementation where the flag is only set if the analytics is switched on, then off.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Disable Plausible at init

---

automations/data/labels.yml

This PR adds a few new project-related labels, based on a [discussion in our Make WP slack about project-related automation](https://wordpress.slack.com/archives/C02012JB00N/p1681228425809849?thread_ts=1681227888.069269&cid=C02012JB00N).
The labels are:
- [🧭 project: thread](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20thread) - this reused the existing `project` label so our [project tracker](https://github.com/orgs/WordPress/projects/70/views/1) still works
- [🧭 project: proposal](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20proposal)
- [🧭 project: implementation plan](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20implementation%20plan)
Check the above links!
a parent feature …

Add project labels

---

documentation/projects/proposals/detecting_sensitive_textual_content/20230308-implementation_plan_filtering_and_designating_results_with_sensitive_textual_content.md
documentation/projects/proposals/detecting_sensitive_textual_content/20230309-implementation_plan_sensitive_terms_list.md
documentation/projects/proposals/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.md

Fixes #937 by @sarayourfriend 
Opened 30 March, **due 13 April**.
I've requested reviews from Staci and Dhruv as the IP touches Airflow, API, and ingestion server changes. Staci and Dhruv are both knowledgeable in at least one or several of these areas. If either of y'all are unable to review this, please let me know and I'll ask someone else.
Read the IP. I do not have any outstanding questions, but please focus on the plan and make sure that it makes sense and is feasible. If you have suggestions for how to break any steps up into separate PRs, please share those especially.
errors. …

Implementation Plan: Filtering and designating sensitive results in the API

---

documentation/changelogs/api/2023.04.12.23.29.59.md

Manual cleanup of the automatically created API changelog. I used a PR instead of pushing directly into the branch to easier see the changes.
The changelog should contain api-related changes, and no api-related change should be removed here.
errors.
<details>
```
Version 1.1
Suite D4700
By …
```

Changelog/api 2023.04.12.23.29.59 manual cleanup

---

catalog/Dockerfile

This PR links the `openverse-catalog` image in GHCR to the https://github.com/WordPress/openverse repository using the `LABEL` directive of the `Dockerfile`.
A similar label is also present in the API, ingestion server and frontend images.
errors.
<details>
```
Version 1.1
Suite D4700
By …
```

Add `LABEL` to link repo with GHCR image

---

documentation/reference/ci_cd.md

Fix the hammer emoji

---

docker/es/justfile
ingestion_server/ingestion_server/api.py
ingestion_server/ingestion_server/indexer.py
ingestion_server/ingestion_server/static/mock_sensitive_terms.txt
ingestion_server/ingestion_server/tasks.py
ingestion_server/ingestion_server/utils/sensitive_terms.py
ingestion_server/justfile
ingestion_server/test/integration_test.py
load_sample_data.sh

Fixes #1196 by @sarayourfriend 
Adds a new `create_and_populate_filtered_index` action to the ingestion server. To do this, we needed a location for test sensitive terms so Falcon serves this statically. The deployed ingestion servers are not exposed to the internet so this is fine to leave on for the deployed services.
This PR also adds creating the filtered indexes to `load_sample_data.sh` so that `api/init` creates the filtered indexes.
**I may need to update the timeouts in the ingestion server tests to accommodate CI**.
Run the ingestion_server unit tests locally.
Run the `just api/init` script locally. Re-run it to make sure it's idempotent. Run `just down -v` and then `just api/up && just api/init` to check the full process top to bottom.
a parent feature …

Add `create_and_populate_filtered_index` action to ingestion server

---

api/catalog/api/views/image_views.py
api/test/unit/views/image_views_test.py

Fixes #1811 by @zackkrida 
This _should_ partially revert the work in #898 to only use upstream thumbnails from SMK. 
Tests should pass, API should work locally and use the full image url for thumbnails, except for SMK.
errors.
<details>
```
Version 1.1
Suite D4700 …
```

Only use upstream thumbs with photon for SMK, for now

---

frontend/Dockerfile

https://openverse.org/version.json does not report a release because the `RELEASE` argument is not being passed. I don't know when this broke but probably sometime in the last month and a half or so of monorepo changes and build unification that accidentally excluded the frontend specific build variable (but not the API or others).
Rather than maintaining separate variables that can be more easily forgotten or incorrectly removed, this PR updates the frontend Dockerfile to use the same argument name as the API Dockerfile. This argument is already passed for the frontend image build, it's passed to all builds, in fact, so no other changes are necessary.
You can test it locally, but there's not much to test here. Let the image build in CI and test the version endpoint on it.
`Update …

Update frontend Dockerfile to use same release ARG as API

---

api/justfile
catalog/justfile

The command is not working on `main`.
This PR completes the default credentials to connect to the database seamlessly.
Just try it here and compare with the `main` branch.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Fix `pgcli` just commands for the api and catalog

---

.github/PULL_REQUEST_TEMPLATE.md
.github/sync.yml
prettier.config.js

Prevents getting PRs like WordPress/openverse-infrastructure#469 from @openverse-bot 
This PR selects the specific issue template to sync with the infrastructure repository. It also makes prettier ignore the `PULL_REQUEST_TEMPLATE.md` file so the checklist can have a correct format again.
N/A
<details>
```
Version 1.1
Suite D4700
By …
```

Pick specific issue templates to sync

---

frontend/nuxt.config.ts
frontend/src/components/VCopyButton.vue
frontend/src/components/VMediaInfo/VCopyLicense.vue
frontend/src/components/VMediaInfo/VLicenseTabPanel.vue
frontend/src/types/analytics.ts
frontend/test/playwright/e2e/attribution.spec.ts
frontend/test/playwright/playwright.config.ts

Fixes #1081 by @dhruvkb
This PR adds the `COPY_ATTRIBUTION` analytics request. It also changes the `VCopyButton`'s emitted event to not include the attribution text as that is not going to be used anywhere.
This PR is based off of #1140 which should be reviewed before this PR.
I used the e2e tests because unit tests turned out to be really complicated to write, with several layers of slots in the `VTabs` component and the `Symbol()` provide/inject.
I also added an environmental variable to the Playwright tests in the `playwright.config.ts` to be able to detect if the app is running in a _real_ prod mode or _playwright_ prod mode, and set the Plausible to track localhost if it's in a _playwright_ prod mode. This way, we can test the requests that are being sent.
Set up the analytics as …

Analytics event: COPY_ATTRIBUTION

---

.github/workflows/ci_cd.yml
documentation/guides/frontend/index.md
documentation/guides/frontend/miscellaneous.md
documentation/guides/frontend/playwright_tests.md
documentation/guides/frontend/storybook_tests.md
documentation/guides/frontend/test.md
documentation/guides/frontend/testing_guidelines.md

Related to #777 by @dhruvkb
This PR moves the documentation guides from /frontend directory to the documentation site. The links are updated.
I've added a file I called "miscellaneous" to house the information that used to be in the openverse-frontend README and that is linked in the testing guidelines. Naming suggestions welcome!
I understand that the information architecture is not perfect in this PR, but improving it is out of scope for this PR.
Hopefully, the docs will be built and linked in the comments here.
errors.
<details>
```
Version 1.1 …
```

Move Nuxt testing docs to the Docs site

---

.github/actions/load-img/action.yml
documentation/reference/ci_cd/actions.md

This PR includes the frontend in the list of images that the `load-img` action can set up.
<details>
```
Version 1.1
Suite D4700 …
```

Include frontend in the `load-img` action

---

.pre-commit-config.yaml

Fixes #1840 by @sarayourfriend 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
```

Pass `--fix` option to Ruff in pre-commit

---

.github/sync.yml
catalog/justfile
catalog/requirements_tooling.txt

Fixes #1844 by @sarayourfriend 
In addition to what the title indicates, this removes some leftovers from release drafter changes.
Try:
```
just catalog/recreate
```
Everything should work as usually.
<details>
```
Version 1.1
Suite D4700 …
```

Add `catalog/recreate` just command and remove a file

---

documentation/projects/proposals/popularity_optimizations/20230406-project_proposal_popularity_optimizations.md

2023-04-21
@AetherUnbound and @obulat chosen for your expertise in the Catalog.
cc @rwidom likewise!
This is the project proposal for the [popularity calculation optimizations project](https://github.com/WordPress/openverse/issues/433). Implementation details will be specified in the upcoming implementation plan, upon approval of the project proposal.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/reference/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the process and follow it.
This discussion is currently …

Project Proposal: Popularity calculation optimizations

---

catalog/dags/common/storage/audio.py
catalog/dags/common/storage/image.py
catalog/dags/common/storage/media.py
catalog/tests/dags/common/storage/test_media.py

Fixes #1886 by @obulat
This PR updates the `ImageStore` and `AudioStore`'s `add_item` method, moving `foreign_identifier` to the required parameters. 
The `MediaStore` required params check is updated to always raise an error if a required param does not have a value.
The CI should pass. These steps are tested in the existing tests already. The test for required fields adds `license_info` because a missing license info should also raise an error for consistency.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```

Make foreign_identifier required in `add_item`

---

documentation/meta/ci_cd/jobs/ingestion_server.md
documentation/meta/ci_cd/jobs/preparation.md

This PR changes three incorrect H3 headings into the correct H2. Resolves some warnings raised by Sphinx.
<details>
```
Version 1.1
Suite D4700
indicated in …
```

Fix heading hierarchy in job documentation for CI + CD workflow

---

catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
catalog/utilities/dag_doc_gen/dag_doc_generation.py

Fixes #1864 by @sarayourfriend 
Add better handling for multi-heading DAG docs by increasing every heading found in a DAG doc by 2 levels.
You can try making changes to a DAG doc to see how it affects the output. The proof that this works as expected is that I was able to remove the Wikimedia Commons DAG docstring's artificial heading increases. Folks can now write docstrings with headings correct for the context in the code and it will automatically be fixed to match the embedded context in the generated DAGs documentation.
<details>
```
Developer …
```

Accommodate multi-heading DAG docs

---

.github/workflows/migration_safety_warning.yml

Fixes #1895 by @obulat
This PR replaces the repo name to fix the migration check in CI.
After merging this PR, #956 should pass the CI
<details>
```
Version 1.1
Suite D4700 …
```

Fix CI migration checks

---

catalog/dags/data_refresh/data_refresh_types.py

Extends the timeouts for the `create_popularity_constants_view` and `create_materialized_popularity_view` steps of the `recreate_image_popularity_calculation` DAG to match the timeouts for refreshing those views.
This should allow us to enable the DAG and fully recreate the matviews, which will hopefully run more quickly than the refresh.
`just catalog/up`, then start the `recreate_image_popularity_calculation` DAG locally and inspect the `Task Instance Details` for the two named tasks. Verify that the correct `execution_timeout` is configured.
<details>
```
Version 1.1 …
```

Update timeouts for image popularity view creation

---

.github/workflows/release-app.yml
documentation/changelogs/catalog/index.md

I forgot to push the last commit to https://github.com/WordPress/openverse/pull/1828 that actually added the catalog to the release-app workflow :facepalm: This PR cherry-picks the commit from that branch.
Add `catalog` to the release-app workflow.
N/A. Merge and use the workflow.
<details>
```
Version 1.1
Copyright (C) …
```

Actually add catalog to the release-app workflow

---

.github/release-drafter-catalog.yml
automations/js/justfile

Fixes https://github.com/WordPress/openverse/actions/runs/4815345913
Adds the missing release drafter
N/A, output is generated
<details>
```
Version 1.1
Suite D4700 …
```

Add release drafter configuration for catalog

---

catalog/docker-compose.yml

Relative paths are relative to the compose file, not the execution directory. This was changed incorrectly during the monorepo switchover.
Note: It probably makes more sense to keep this configuration in the infrastructure repository as it's only relevant there and splitting the locations for the deployment configuration makes it more difficult to debug these issues (requiring PRs in multiple places).
N/A
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guideli …

Use path relative to `docker-compose.yml` file

---

.github/filters.yml
.github/workflows/ci_cd.yml
.github/workflows/pr_label_check.yml

This PR
- adds labelling for more stacks than covered before (like documentation, catalog and mgmt)
- uses `github-script` instead of duplicating the step for every stack
- removes use of `actions-ecosystem/action-add-labels` (last updated in Oct 2021)
- uses updated stacks from #1933
https://github.com/actions/labeler suggested by @krysal is great but we already have a list of changesets in `filter.yml` based on stacks and we can prepend "🧱 stack:" to them more easily compared to maintaining a separate `labeller.yml` file.
<details>
```
Version 1.1 …
```

Update labelling system to reduce duplication and cover more stacks

---

frontend/src/components/VSearchResultsGrid/VImageCell.vue
frontend/test/unit/specs/components/related-images.spec.js

Fixes #793 by @obulat
This PR improves search result accessibility by using h2 for result titles instead of spans.
<details>
```
Version 1.1
Suite D4700 …
```

Replace span with h2 on image search results

---

.github/filters.yml
.github/workflows/ci_cd.yml
.github/workflows/pr_label_check.yml
automations/python/workflows/set_matrix_images.py

Fixes #1859 by @dhruvkb
This PR
- separates the CI + CD workflow from the filters of each stack into its own
- updates `filters.yml` to cover more files for each stack
- adds new stacks to the `filters.yml` file
See #1934.
This allows us to determine when each stack has actually changed. Now, when the CI + CD workflow changes, we can run the complete suite of tests, but only emit docs, publish Docker images, and perform a staging deploy when a service has actually changed.
<details>
```
Version 1.1
Suite D4700
San …
```

No docs, Docker images or deploys if CI + CD workflow changes

---

.github/dependabot.yml

Fixes #801  by @dhruvkb 
Configured Dependabot.yml to include the directories documentation/ and automations/python/
<details>
```
Version 1.1
Suite D4700 …
```

Configure dependabot.yml to include the documentation and automations/python directories

---

frontend/test/playwright/visual-regression/components/content-report-form.spec.ts

Skip for #2020
N/A
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```

Skip flaky content-report-form test

---

.github/actions/build-docs/action.yml
.github/workflows/ci_cd.yml
.github/workflows/weekly_updates.yml
automations/js/src/last_week_tonight.mjs
documentation/meta/ci_cd/actions.md
frontend/src/locales/scripts/bulk-download.js

Fixes #1991 by @dhruvkb
Reported by @dd32
This PR removes the username/password authentication for WordPress.org. This does not affect bulk downloads as they can be downloaded without authentication as well.
This PR is accompanied by an infra PR https://github.com/WordPress/openverse-infrastructure/pull/491 to remove the secret from GitHub's secret store.
If everything works well, we can deprecate and remove the rate-limited separate download code from the repo.
- Check out the PR.
- Remove all existing locale JSON files from `frontend/src/locales/`
- Download translations using `just frontend/run i18n:get-translations`
- Even without any env vars or credentials, the translations are downloaded in bulk
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Proje …

Remove authentication in bulk translation downloads

---

.github/ISSUE_TEMPLATE/discussion.md

Update discussion.md template to remove typo

---

automations/data/github.yml
automations/data/labels.yml

Fixes #1194 by @AetherUnbound 
This PR makes a few changes:
* Adds the `☁️  provider` labels to the set of defined labels
* Adds the new stack labels to the defined set as well
* Removes `openverse-catalog` from `github.yml`, prevent it from being accessed as part of various automations
I've already run the sync script off this branch, check out the labels here! https://github.com/WordPress/openverse/labels?q=provider
<details>
```
Version 1.1
Suite D4700 …
```

Add provider & new stack labels to label sync, remove catalog repo from github config

---

documentation/meta/ci_cd/jobs/api.md

Fixes #2047 by @AetherUnbound 
The PR removes the mermaid diagram from API jobs.
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Remove mermaid diagram in API jobs

---

catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
catalog/dags/providers/provider_api_scripts/cleveland_museum.py
catalog/dags/providers/provider_api_scripts/finnish_museums.py
catalog/dags/providers/provider_api_scripts/flickr.py
catalog/dags/providers/provider_api_scripts/freesound.py
catalog/dags/providers/provider_api_scripts/jamendo.py
catalog/tests/dags/providers/provider_api_scripts/test_brooklyn_museum.py
catalog/tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
catalog/tests/dags/providers/provider_api_scripts/test_finnish_museums.py
catalog/tests/dags/providers/provider_api_scripts/test_flickr.py
catalog/tests/dags/providers/provider_api_scripts/test_jamendo.py

Related to #1883 by @obulat
This PR replaces is None checks for required values with if <value> checks because falsy values such as empty string or empty list should also short-circuit the provider API scripts.
After @AetherUnbound's suggestion to add tests, I split the PR into 2 (or 3) to make the changes easier to review. This PR contains changes for first 6 providers. I've also waited for the changes to LicenseInfo to be merged to avoid merge conflicts.
I've added tests to all but `freesound`, which already has appropriate tests: `test_get_record_data_returns_none_when_missing_data` and `test_get_record_data_returns_none_when_data_falsy`
I tried running the providers locally, and they all saved some data without errors.
The tests should pass, and the additional tests should test the …

Add checks for required parameters to Provider scripts (A-J)

---

catalog/dags/common/licenses/licenses.py
catalog/dags/providers/provider_api_scripts/science_museum.py
catalog/dags/providers/provider_api_scripts/smithsonian.py
catalog/dags/providers/provider_api_scripts/smk.py
catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
catalog/dags/providers/provider_api_scripts/wordpress.py
catalog/tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_hq.json
catalog/tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_legacy.json
catalog/tests/dags/providers/provider_api_scripts/resources/smk/image_data_hq.json
catalog/tests/dags/providers/provider_api_scripts/resources/smk/image_data_legacy.json
catalog/tests/dags/providers/provider_api_scripts/test_science_museum.py
catalog/tests/dags/providers/provider_api_scripts/test_smithsonian.py
catalog/tests/dags/providers/provider_api_scripts/test_smk.py
catalog/tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
catalog/tests/dags/providers/provider_api_scripts/test_wordpress.py

Related to #1883 by @obulat
This PR was originally created to replace the None checks for required values with `if <value>` checks because falsy values such as empty string or empty list should also short-circuit the provider API scripts.
After @AetherUnbound's suggestion to add tests, I split the PR into 3 to make the changes easier to review. This PR contains changes for the last 5 providers (from "S").
I wasn't aware about the recent addition of an Exception when one of the required param is missing. After this, we have to make sure that the provider API scripts check for truthiness of the required parameter values before returning the data in `get_record_data` function.
The tests should pass, and the additional tests should test the changes.
Check that all of the possible "falsy" …

Add checks for required parameters to Provider scripts (S-Z)

---

.dockerignore
.github/workflows/ci_cd.yml
api/Dockerfile
automations/python/workflows/set_matrix_images.py
catalog/Dockerfile
docker/upstream_db/Dockerfile
documentation/general/general_setup.md
frontend/Dockerfile
frontend/Dockerfile.playwright
frontend/justfile
ingestion_server/Dockerfile
utilities/load_testing/Dockerfile

Fixes #2040 by @sarayourfriend 
This PR
- makes the repo root an additional build context (named `repo_root`)
- uses this build context in the building of the `openverse-frontend` image
- eliminates the need to first move files into the `frontend/` directory and then delete them inside the `Dockerfile`
The images should build and CI should pass. Additonally,
- Check out the PR.
- Build the frontend image locally.
```bash
$ just frontend/build-img
```
- Run the frontend.
```bash
$ docker run --rm --port 8443:8443 openverse-frontend:local
```
<details>
```
Version 1.1 …
```

Use additional build contexts to build frontend Docker image

---

api/api/utils/throttle.py
api/api/views/health_views.py
api/conf/settings/rest_framework.py

Fixes #1924 by @sarayourfriend 
Increase the throttle rate for this endpoint as per suggested in the issue (albeit giving it a leeway). I believe this is the first use of the `ExemptOAuth2IdRateThrottle` class as well, seems suitable in this case though I don't think we make many of these requests authenticated.
Run the django app and try to make several requests to http://localhost:50280/healthcheck/ See
<details>
```
Developer Certificate …
```

Add throttle classess for health check endpoint

---

documentation/projects/proposals/popularity_optimizations/20230420-implementation_plan_popularity_optimizations.md

2023-05-08
Feedback welcome from all; @AetherUnbound and @obulat chosen as reviewers for expertise in the Catalog. Also calling out in advance: because of  folks' availability this week I anticipate that the clarification round may need to be extended, and am happy to do so!
Also pinging @rwidom, whose insight here would be very valuable.
Fixes #1873 by @stacimc 
Implementation plan for project #433.
This discussion is following the Openverse decision-making process. Information about this process can be found [on the Openverse documentation site](https://docs.openverse.org/reference/decision_making/index.html). Requested reviewers or participants will be following this process. If you are being asked to give input on a specific detail, you do not need to familiarise yourself with the …

Implementation Plan: Decoupling Popularity Calculations from Data Refresh

---

docker/upstream_db/0003_openledger_image_schema.sql
docker/upstream_db/0006_openledger_audio_schema.sql

Fixes #2087 by @stacimc 
Adds `standardized_popularity` to the media tables in the Catalog DB.
We will also need to add them manually in production:
```pgsql
ALTER TABLE image ADD COLUMN standardized_popularity DOUBLE PRECISION;
ALTER TABLE audio ADD COLUMN standardized_popularity DOUBLE PRECISION;
```
1. Pull this branch.
2. Recreate the Catalog (`just catalog/recreate`)
3. Open a db shell (`just catalog/pgcli`)
4. Inspect the image and audio tables to see that the column was added:
```
openledger> describe image;
+-------------------------+--------------------------+--------------------------------------+
| Column                  | Type                     | Modifiers                            |
|-------------------------+--------------------------+------------------------------------- …
```

Add `standardized_popularity` to Catalog media tables

---

.github/workflows/renovate.yml

The Renovate GitHub action has been failing for some time: https://github.com/WordPress/openverse/actions/workflows/renovate.yml
(specific example): https://github.com/WordPress/openverse/actions/runs/4999513415/jobs/8955975824
The failure was:
```
Error: Unable to resolve action `renovatebot/github-action@v36`, unable to find version `v36`
```
The [latest GHA release is v37.0.0](https://github.com/renovatebot/github-action/releases/tag/v37.0.0), so I've set this to explicitly use the whole version string.
I triggered a Renovate run from this branch that ran successfully: https://github.com/WordPress/openverse/actions/runs/4999635555/jobs/8956190532
<details> …

Fix renovate GitHub actions version number

---

api/api/utils/photon.py
api/test/unit/utils/test_photon.py

Follow up to #2086.
This PR check if the "Content-Type" header exists in the the response to the HEAD request for checking the 
I don't know how to reproduce this error manually but I added a case in the automated tests. Please check that.
<details>
```
Version 1.1
Suite D4700 …
```

Add safe check for Content-Type in photon

---

justfile

This PR adds a few recipes/aliases to add shorthand for certain steps.
Namely:
- `b` for `build`
- `d` for `down`
- `l` for `logs`
- `a` for api up
- `c` for catalog up
- `i` for ingestion server up
- `f` for frontend up
Run `just` and see the new recipes/aliases, try a few out!
<details>
```
Version 1.1
Suite D4700
By making a …
```

Add aliases and shortcuts for common "up" recipes

---

docker/upstream_db/Dockerfile

Fixes an issue where failure when running a `psql` command wouldn't appropriately bubble up to the user. We encountered this issue in #2096 - the initial `load_sample_data.sh` script was actually failing, but it wasn't reporting this failure because it was occurring in the middle of a few `psql` commands. This then caused tests to fail downstream for seemingly unrelated reasons, since the setup appeared to succeed.
This PR adds the `ON_ERROR_STOP` option to the [`psqlrc` file](https://www.postgresql.org/docs/current/app-psql.html) in the `upstream_db` container, which now causes failed `psql` commands to exit before proceeding. In other words, failures in the `load_sample_data.sh` script while ingesting data are appropriately reported.
1. `just build`
1. `just down -v`
1. Delete a few …

Add ON_ERROR_STOP option for psql operations in upstream_db

---

.github/workflows/actionlint.yml

Follow up to https://github.com/WordPress/openverse-infrastructure/pull/506 where the actionlint version was bumped in the infrastructure repo to include new GHA features, but was overwritten by our sync process in https://github.com/WordPress/openverse-infrastructure/pull/515
This changes the actionlint action to use a Docker image ([an alternative mentioned in their docs](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions)) with the `latest` tag so we're always using the most up-to-date version.
CI should pass!
<details>
```
Version 1.1 …
```

Use the latest docker image for actionlint

---

api/api/controllers/search_controller.py
api/api/serializers/audio_serializers.py
api/api/serializers/image_serializers.py
api/api/serializers/media_serializers.py
api/api/views/media_views.py
api/test/unit/controllers/test_search_controller.py
api/test/unit/serializers/test_media_serializers.py

Fixes #2070 by @dhruvkb
This PR
- adds a new query param, called `internal__index`
- this param, only accessible behind authentication, allows choosing a different index to use when searching
- this param conflicts with the `qa` param, and only one of the two can be set at a time
1. Using the ingestion server API, create a new index for image and audio, name it something like `index-foo` and `audio-bar`.
2. Search for something. Note the top few results. They should be the same when searching the default index and from the new one.
3. Randomly delete some of the top few results from the new index. You can do this in Elasticvue.
4. Observe no change when searching the default index but new results when searching the new one.
5. Use can also keep …

Add `internal__index` param, walled behind auth

---

justfile

Fast-follow to #2134 - I fumbled the syntax for running the frontend in the alias for it. This PR fixes that (I've also tested that it works locally to confirm).
Run `just f`
<details>
```
Version 1.1
Suite D4700 …
```

Fix just alias for frontend

---

documentation/404.md
documentation/Pipfile
documentation/Pipfile.lock
documentation/conf.py

CSS is broken on the docs site for 404s that aren't on the root: https://docs.openverse.org/api/not_real.html
This is caused by CSS references rendered relative to the file on disk. Because GitHub is serving the same static page on sub-paths in the URL, the CSS reference breaks.
This [sphinx plugin (sphinx-notfound)](https://sphinx-notfound-page.readthedocs.io) that @obulat found fixes this precise issue by rendering a 404.html for you with absolute URLs. I deleted the existing 404.md because the content of that page was no more or less descriptive or helpful than the default one provided by the plugin.
Run `just documentation/build` and confirm that `documentation/_build/404.html` has absolute rather than relative references for the CSS files in `head`. You can also pull the 404.html …

Fix 404 rendering with relative CSS references

---

api/api/serializers/oauth2_serializers.py

Fixes #2168 from Sentry
This PR adds validation to the `name` field in `OAuth2RegistrationSerializer` to prevent `IntegrityErrors` from arising in the database when a duplicate name is provided.
0. Create two applications with the same name.
1. The second one will return a 400 response like so
```
HTTP/1.1 400 Bad Request
{
"name": [
"An application with this name already exists."
]
}
```
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```

Validate `name` field to replace `IntegrityError`s with 400 response

---

frontend/src/components/VButton.vue
frontend/src/components/VHeader/VSearchBar/VSearchBar.vue
frontend/src/components/VHeader/VSearchBar/VSearchButton.vue
frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue
frontend/src/components/VInputField/VInputField.vue
frontend/test/unit/specs/components/InputField/input-field.spec.js
frontend/test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js

Related to #1187 by @obulat
This PR replaces the "plain" variant in the search button with the "transparent-tx" variant. It allows us to remove the old way of adding border/focus ring.
I've also simplified the component and used it in all search bars (instead of using a separate component in the standalone search bar in 404 and home pages), and removed the old input sizes.
~~Most of the snapshot changes are movement of the file from one folder to another (v-button-old -> v-button) or fixing of the name (removing of the second "png" from it).~~ -> These changes moved to #2137
This PR was extracted from #2120 to make it easier to review.
All of the styles should stay the same, and the search button in the header search bar, the home page and the 404 page should look and act the same. …

Update the search button

---

.github/PULL_REQUEST_TEMPLATE/project_proposal.md
documentation/general/deployment.md
documentation/meta/decision_making/additional_practices.md

While working on another PR, I noticed that a reference in the project proposal PR template was inaccurate. I went through our monorepo to replace references to `/reference/` (now `/meta/`) and `/guides/` (now `/general/`).
Try the new links out!
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```

Update references to moved documentation pages

---

frontend/feat/feature-flags.json
frontend/src/components/VContentSwitcher/meta/VSearchTypeButton.stories.mdx
frontend/src/components/VContentSwitcher/meta/VSearchTypePopover.stories.mdx
frontend/src/components/VContentSwitcher/meta/VSearchTypes.stories.mdx
frontend/src/components/VSearchGrid.vue
frontend/src/composables/use-search-type.ts
frontend/src/stores/search.ts
frontend/test/playwright/visual-regression/pages/homepage.spec.ts
frontend/test/unit/specs/stores/search-store.spec.js

Fixes #2138 by @obulat
This PR renames the "external_sources" feature flag to "additional_search_types" as the flag enables showing additional search types in the content switcher.
It also enables showing the additional search type external sources if the flag is enabled, instead of falling back to image on "all_content", "video" and "model_3d" pages.
Go to "/preferences" and turn on the "additional_search_types" flag.
Then select additional search types (video, 3d models) in the content switchers (in the header, in the search bar on the homepage). When you are on a video page, you should see the video source links in the external sources popover, not the image sources.
<details> …

Make additional search types flag clearer and add external sources for additional types

---

documentation/meta/ci_cd/flow.md
documentation/meta/ci_cd/jobs/preparation.md

This PR adds the `add-stack-label` step to the "Preparation" section of the CI/CD docs, as well as an explanation for that and the `lint` job.
Check the rendered preview and make sure the mermaid diagram looks okay!
<details>
```
Version 1.1
Suite D4700 …
```

Add documentation for add-stack-label and lint steps of CI prep

---

api/api/utils/photon.py

Fast-follow to #2243 to use the `tallies` Redis DB instead of the default one. The values being tracked here are for analysis reasons and so it makes sense to move them to that DB, particularly since the key prefixes have also changed.
Testing steps for #2243 should also apply, you'll just need to use `-n 3` in the `redis-cli` call to indicate you're connecting to the tallies database.
<details>
```
Version 1.1
Suite D4700 …
```

Use tallies redis DB for thumbnail tallies

---

.github/filters.yml
.github/workflows/ci_cd.yml
documentation/meta/ci_cd/jobs/api.md
documentation/meta/ci_cd/jobs/frontend.md
documentation/meta/ci_cd/proof_of_functionality.md

Addresses #1851 by @dhruvkb (cc: @sarayourfriend)
Fixes #2248
This PR
- makes Playwright tests (trio of jobs: Nuxt E2E, Nuxt VR and Storybook VR) the definitive proof-of-functionality for the frontend
- updates the steps for publishing docs and GHCR images rely on `playwright` instead of `nuxt-build`
- updates docs
- updates the incorrect glob filter which prevented changes to MDX stories from compiling docs (see #2229)
<details>
```
Version 1.1
Suite D4700 …
```

Make criteria for pushing frontend images to GHCR same as that of deployment

---

api/justfile
docker/nginx/justfile
documentation/api/guides/https.md
documentation/api/guides/index.md
documentation/api/guides/quickstart.md
documentation/general/quickstart.md
justfile
utilities/ps.py

Fixes #2192 by @krysal
This PR adds documentation on how to access the API over HTTPS using the `proxy` service included in the Docker Compose configuration. Hopefully this can help us make a calculated choice on whether to keep this process, improve it or remove it altogether and reduce some code from the codebase.
It also makes 2 other smaller improvements.
- Updates the `ps` script to fix `https` for proxy@50243 and align the container ports
- Adds an alias `s` to the root `justfile` to quickly spinning up the documentation live server.
Read the [preview docs @ `/api/guides/https.html`](https://docs.openverse.org/_preview/2201/api/guides/https.html)
<details> …

Add documentation for accessing API over HTTPS

---

docker-compose.yml
docker/upstream_db/Dockerfile

Replace https://github.com/WordPress/openverse/pull/2258 to match live environments
Match Postgres version to live environments
CI and tests should pass.
<details>
```
Version 1.1
Suite D4700 …
```

Upgrade postgres Docker 13.7 match live environments

---

frontend/src/components/VItemGroup/meta/VItemGroup.stories.mdx
frontend/src/components/VModal/VModalContent.vue
frontend/src/components/VModal/meta/VModal.stories.mdx
frontend/src/components/meta/VButton.stories.mdx
frontend/test/unit/specs/components/v-modal.spec.js

Fixes #2216 by @sarayourfriend
Fixes #2217 by @sarayourfriend
Fixes #2218 by @sarayourfriend
This PR fixes the errors in Storybook stories that stop them from building.
I've opened a single PR to fix three stories because the fixes are just single-line changes.
The errors were caused by recent changes: `variant` and `size` are now required props for `VButton`. Another change was `svg` `name` property was using incorrect prop.
Run storybook using `just frontend/run storybook` and check that `VButton`, `VItemGroup` and `VModal` stories don't have errors. Also check the link in the published storybook preview.
<details>
```
Developer …
```

Fix stories

---

catalog/DAGs.md
catalog/dags/database/staging_database_restore/staging_database_restore_dag.py

Quick addition for #1989 and #1990 which adds instructions for adjusting the variable for skipping the staging database restore DAG.
<details>
```
Version 1.1
Suite D4700 …
```

Add instructions for skipping the database restore DAG to docs

---

frontend/test/unit/specs/components/v-content-report-form.spec.js

Fixes #2221 by @sarayourfriend
Changes the test to check if the button is disabled when the text in the form is shorter than the required minimum 20 characters, since it is impossible to send the report anyways when the button is disabled.
The test changes should make sense.
<details>
```
Version 1.1
Suite D4700 …
```

Fix content report form unit test

---

frontend/src/middleware/search.ts
frontend/src/middleware/single-result.ts
frontend/src/pages/audio/_id/index.vue
frontend/src/pages/image/_id/index.vue
frontend/src/pages/search.vue
frontend/src/stores/search.ts

Fixes #2234 by @obulat
This PR converts the route guards (`beforeRouteEnter` etc) to named and typed middleware. This middleware sets the "back to search" link URL on the single result pages, and the search term on the search pages. The "back to search" link is moved to the search store because `route.meta` does not behave the same way in the `middleware` as it did in the route guards.
There are some navigation tests in the CI that should pass.
<details>
```
Version 1.1
Suite D4700
Everyone …
```

Convert route guards to middleware

---

api/api/utils/search_context.py

Fixes #2306 by @AetherUnbound 
Use `identifier.keyword` instead of `id` to query the filtered index.
Unit tests should pass. Try the testing instructions from #2057 as well.
Luckily the test data factories are written in such a way that the unit tests themselves don't need to change at all and still properly test the functionality :tada: 
<details>
```
Version 1.1
Suite D4700 …
```

Use stable identifier for filtered index presence

---

documentation/projects/proposals/search_relevancy_sandbox/20230518-implementation_plan_staging_index_rapid_iteration.md

2023-06-07
Sara is AFK for the first few days of this review process so I've extended the clarification round to account for that.
Resolves #1985
This PR is the implementation plan for rapid iteration on ingestion server configurations.
[on the Openverse documentation site](https://docs.openverse.org/reference/decision_making/index.html).
The deadline for review of this round is **2023-06-07**

Implementation Plan: Rapid iteration on ingestion server index configuration

---

frontend/test/playwright/visual-regression/components/header.spec.ts
frontend/test/playwright/visual-regression/pages/homepage.spec.ts

Related to #2357 by @zackkrida 
Related to #2377 by @zackkrida 
Skips flaky tests identified in the linked issues, while a fix is worked on. Relates to SVG issues.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```

Skip flaky tests related to SVGs

---

ingestion_server/ingestion_server/es_mapping.py
ingestion_server/ingestion_server/indexer.py
ingestion_server/ingestion_server/utils/sensitive_terms.py
ingestion_server/test/integration_test.py

Fixes #2328 by @AetherUnbound 
See the issue for the long explanation for why we are switching to `terms` query.
The summary is that:
- `terms` queries allow exact matching, fixing a separate issue where the terms were still querying tokenised text, resulting in false positives
- `terms` queries are subject to a separate, much higher limit than other queries.
I can't test this locally due to #2362. I've executed the equivalent query against staging with the actual sensitive terms list and confirmed it does not cause any clause count errors.
You should be able to `just down -v && just api/up && just api/init` and then see a successfully created filtered index. All existing tests should pass without modification.
- I can't do this, see testing instructions above.
- [N/A] I ran the DAG …

Fix sensitive term reindex query

---

catalog/dags/data_refresh/data_refresh_task_factory.py
catalog/env.template

Fixes #1893 by @AetherUnbound
This PR allows the data refresh pool to be determined by the `DATA_REFRESH_POOL` environment variable, while still defaulting to `data_refresh` for production. For local development, `default_pool` can be used which prevents the need for developers to add a pool every time they recreate the stack.
1. Add `DATA_REFRESH_POOL=default_pool` to your `catalog/.env` file
1. Run `just catalog/recreate` and `just i` (to launch the ingestion server)
1. Run one of the data refresh DAGs and observe that you don't need to create a `data_refresh` pool in order for it to complete!
<details>
```
Developer Certificate …
```

Determine data refresh pool by environment variable with default

---

automations/data/labels.yml

Fixes #2339 by @sarayourfriend
I added new technology labels, and updated the descriptions of existing ones.
<details>
```
Version 1.1
Suite D4700
indicated …
```

Updated and added new technology labels

---

automations/data/labels.yml
catalog/docker-compose.yml

Fixes #2414 by @AetherUnbound
Defined specific log rotation policies to scheduler and webserver services in docker-compose stack
<details>
```
Version 1.1
Suite D4700 …
```

Defined log rotation policies in docker-compose

---

api/api/utils/photon.py

Fixes #2419 by @sarayourfriend  
Adds a 10s timeout to head requests in `check_image_type`. Not sure we need a test for this but I'm happy to add one based on suggestions. Seems like we'd just be testing the internals of the request library.
<details>
```
Version 1.1
Suite D4700 …
```

Add 10s timeout to check_image_type head requests

---

.eslintignore
frontend/src/locales/scripts/utils.js

Fixes #2432 by @obulat
This PR adds the locale `json` files to eslintignore as they are gitignored anyways. This CI fix was applied in #2398, but it's better to merge it ASAP because the CI fails without it.
Another fix is converting the keys (that are between `###` characters in `pot` files in GlotPress, and between `{}` brackets in Vue i18n json files) from kebab-case to camelCase.
Run `just frontend/run i18n` to load the translation files. Then, go to `nl` locale with a migration notice: `http://localhost:8443/nl?referrer=creativecommons.org`. You should see the "read more" link and "CC Search" in the notice.
The CI eslint step shouldn't show the messages from the linked issue. …

Ignore locales; fix kebab-cased translation keys

---

frontend/tailwind.config.js

Fixes #2439 by @obulat
Updated the settings to use theme("colors.dark-charcoal.default")

fix: Changed the default color in Tailwind CSS

---

.devcontainer/devcontainer.json
.github/actions/load-img/action.yml
.github/actions/setup-env/action.yml
frontend/package.json
package.json
pnpm-lock.yaml

Fixes #2429 by @obulat
This PR updates nuxt to version 2.17, and node to version 18.16 🎉 
It also updates some related dependencies.
With this update, the migration to Nuxt 3 will not be as urgent anymore. At least, it won't be tied to Node 16 EOL.
I tried building and running the Docker image locally, and it worked. @sarayourfriend, do we need any changes in the infrastructure to match this change?
I'm not sure how best to test this locally, because I had to completely remove node from my machine to use v18.
<details>
```
Version 1.1 …
```

Update Nuxt to 2.17 and node to v18.15.0

---

.github/workflows/ci_cd.yml
documentation/frontend/reference/storybook_tests.md
documentation/meta/ci_cd/jobs/frontend.md

Follow-up to #2447
This PR adds changes from the comments in #2447:
- renames the CI job from `storybook_vr` to `storybook` to reflect that the tests now run both functional and visual regression tests.
- Updates the documentation to add more details about storybook functional tests.
The changes should make sense and be readable. The CI should pass.
<details>
```
Version 1.1
Suite D4700 …
```

Update Storybook Playwright test CI job name and testing docs

---

api/api/utils/image_proxy/__init__.py

Fixes #2184 by @sarayourfriend 
A tag value in Sentry is limited to a maximum length of 200 characters, so I though it will be better to include the upstream URL as context instead. This also provides more flexibility and we can include the params and headers sent to Photon.
I also added a tag to these requests to remember they account for multiple exceptions consedensed into one. This was done to avoid consuming our quota of events in Sentry. It does not account for the `THUMBNAIL_ERROR_INITIAL_ALERT_THRESHOLD` but we should probably just remove that setting in favor of the alert frequency.
<details>
``` …
```

Add upstream URL when sending Photon request exceptions to Sentry

---

.pre-commit-config.yaml
documentation/projects/proposals/visual_regression_testing/20220217-implementation_plan.md
frontend/src/components/VButton.vue
frontend/src/components/VHeader/VPageLinks.vue
frontend/src/components/VHomeGallery/VHomeGallery.vue
frontend/src/components/VSelectField/VSelectField.vue
frontend/src/components/VTabs/VTabs.vue
frontend/src/constants/audio.ts
frontend/src/constants/content-report.ts
frontend/src/constants/deploy-env.ts
frontend/src/constants/errors.ts
frontend/src/constants/feature-flag.ts
frontend/src/constants/license.ts
frontend/src/constants/media.ts
frontend/src/data/api-service.ts
frontend/src/stores/feature-flag.ts
frontend/src/types/button.ts
frontend/src/types/item-group.ts
frontend/test/playwright/e2e/search-types.spec.ts
frontend/test/playwright/utils/breakpoints.ts
frontend/test/playwright/utils/navigation.ts
frontend/test/storybook/visual-regression/v-footer.spec.ts
frontend/test/storybook/visual-regression/v-header-internal.spec.ts
frontend/test/storybook/visual-regression/v-media-reuse.spec.ts
frontend/test/storybook/visual-regression/v-notitication-banner.spec.ts

I didn't open an issue. This is a problem that prevented #2490 from being committed.
The prettier dependencies in `pre-commit.config` were not updated to match the versions in `frontend/package.json`, so we were not able to use `satisfies` in TypeScript (the prettier support for it was added in prettier v2.8).
Priority is set to critical because this mismatch prevents changes from being committed.
See that the versions in `pre-commit.config` match those in `package.json`, and the CI passes.
<details>
```
Version 1.1
1 Letterman …
```

Sync pre-commit deps with package.json

---

frontend/src/components/VAudioDetails/VRelatedAudio.vue
frontend/src/components/VAudioTrack/VAudioTrack.vue
frontend/src/components/VAudioTrack/VGlobalAudioTrack.vue
frontend/src/components/VSearchResultsGrid/VAllResultsGrid.vue
frontend/src/composables/use-analytics.ts
frontend/src/pages/audio/_id/index.vue
frontend/src/pages/search/audio.vue
frontend/src/stores/active-media.ts
frontend/src/types/analytics.ts
frontend/test/playwright/e2e/audio-detail.spec.ts
frontend/test/playwright/utils/analytics.ts

Fixes #1083 by @dhruvkb 
This PR adds `AUDIO_INTERACTION` event which is fired when the user pauses, plays or seeks on an audio:
- in the All content view (the audio box layout)
- in the Audio search view (the audio row layout)
- in the single audio result page's main audio (the audio full layout)
- in the related audio (the audio row layout)
- on the global audio player (you have to use a very narrow screen to see it).
To make sure that this event is not very bad for performance, this PR adds a `debounced` event, which is only fired every 500 ms.
Open all of the components listed in the description above and try interacting with the audio. You should see the event logged in the console. Try clicking really fast - you should only see events every 500ms. …

Add AUDIO_INTERACTION event

---

frontend/package.json

Fixes #2536 by @sarayourfriend 
I've updated the `dev` script to run the watch script for copying `en.json5` to `en.json`.
Run the frontend locally via `just frontend/run dev` and confirm that changes to `en.json5` are immediately reflected in `en.json` and that the frontend recompiles itself as a result (with the changes present).
<details>
```
Version 1.1
Suite D4700 …
```

Copy `en.json5` to `en.json` in frontend dev script

---

frontend/src/constants/content-safety.ts
frontend/src/stores/media/index.ts
frontend/src/stores/media/single-result.ts
frontend/src/types/media.ts
frontend/src/utils/content-safety.ts
frontend/src/utils/decode-media-data.ts
frontend/test/unit/specs/utils/decode-image-data.spec.js

Fixes part of #2549 by @dhruvkb
This PR updates the `fake_sensitive` flag to work with the new `sensitivity` field. It also consolidates all faking into one place instead of the previous approach where it was scattered in a few different places.
1. Enable the fake_sensitive flag from the /preferences page.
2. Approximately half the results will now be blurred for you and the console will log which and why.
<details>
```
Version 1.1
Suite D4700 …
```

Update `fake_sensitive` feature flag based on updated API response schema

---

frontend/test/playwright/e2e/search-query-server.spec.ts

Fixes #2572 by @sarayourfriend 
Removes an irrelevant mature UI toggle test. We will add additional test coverage for new sensntivity UI elements when they are added in #2368.
<details>
```
Version 1.1
Suite D4700 …
```

Remove irrelevant mature UI toggle test

---

tsconfig.json

Prevents TypeScript distributed with Python dependencies from being type-checked by the `**/*.ts` include
Exclude all `venv` and `.venv` directories. It's easier than adding specific includes for every directory that includes typescript.
Introduced by #2482.
Checkout main and run `pipenv install` inside of `catalog`. Run `just lint types` and confirm you get heaps of errors from Airflow TypeScript files.
Checkout this branch and run `just lint types` and confirm you no longer see those errors.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelin …

Exclude venv directories from type checks

---

frontend/src/components/VHeader/VSearchBar/VSearchBar.vue
frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue

Fixes #2543 by @sarayourfriend
This PR adds `role="search"` to the search bar forms, both the standalone one (which I believe is used on things like the home page) and the one that's present on result pages. I may have missed something important as this is my first ever VueJS PR! (🥳)
1. `just f`
1. Open the home page and inspect the search form, ensure that the `form` element has `role="search"`
1. Make a search and perform the same inspection on the search box on the result page
<details>
```
Version 1.1
Suite …
```

Add "search" role to search bar forms

---

.github/workflows/ci_cd.yml

Fixes #1228 by @sarayourfriend 
See also related PR WordPress/openverse-infrastructure#562.
This PR changes the Slack webhook used by the CI + CD notifications to point to the #openverse-alerts Slack channel.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```

Send CI + CD notifications to the alerts channel

---

frontend/src/components/VHeader/VHeaderDesktop.vue
frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
frontend/src/layouts/content-layout.vue
frontend/src/layouts/search-layout.vue

Fixes #2274 by @fcoveram
This PR fixes the header bottom border: it is shown when the site is scrolled down on the content pages, search result pages and the single result pages. It moves the setting of the border from inside the header components to the parent layouts.
Go to content pages (about), search page and the single result pages, scroll down and see that the border appears when you scroll down and disappears when you scroll up. This should happen both on the mobile widths and the wider screens.
<details>
```
Version 1.1
1 …
```

Fix header bottom border when scrolled

---

frontend/src/components/VBrand/VBrand.vue
frontend/src/components/VFooter/VFooter.vue
frontend/test/playwright/e2e/search.spec.ts
frontend/test/playwright/utils/navigation.ts

Fixes #2596 by @nayanchamp7
Fixes #503 by @sarayourfriend 
This PR adds static position to the SR-only text employed by `VBrand`. The absolute positioning of the text due to the `sr-only` class was tripping Chrome somehow, leading to whitespace below the page equal in height to the search-results grid's inherent size.
1. Search for some text.
2. Scroll to the bottom of the page.
3. There should not be any white space.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```

Fix whitespace bug that only affected Chrome

---

frontend/src/components/VAudioTrack/VAudioTrack.vue
frontend/test/unit/specs/components/AudioTrack/v-audio-track.spec.js

Fixes #2561 by @dhruvkb
This PR adds `abort` error to the handled errors in the `VAudioTrack`. It also adds a check for the `.play()` promise as described in the Google [article](https://developer.chrome.com/blog/play-request-was-interrupted/) linked in the Sentry issue.
The code and added unit tests should make sense and the CI should pass. Eventually, the abort errors should not be sent to Sentry.
<details>
```
Version 1.1
Suite D4700 …
```

Handle AbortError in VAudioTrack.vue

---

.github/filters.yml

Fixes https://github.com/WordPress/openverse/issues/2575 by @dhruvkb
The docker-compose.yml file needed to be added in the .github/filters.yml file under the keys catalog, api, ingestion_server and analytics keys. This would indicate to CI + CD workflow that any change to the Docker Compose file means that these stacks have changed and their tests need to be executed. Now that I added these files it is working fine.
<details>
```
Version 1.1
Suite D4700 …
```

Added "docker-compose.yml"  in filters.yml

---

catalog/dags/data_refresh/reporting.py
ingestion_server/ingestion_server/indexer.py

Fixes #2688 by @AetherUnbound 
Hi [AetherUnbound](https://github.com/AetherUnbound),
just trying to help on this issue, please check it out
[Update message on ingestion_server/ingestion_server/indexer.py](https://github.com/WordPress/openverse/commit/4283f46638f4624201f1286177001f2815b0c99d)
[Update message on catalog/dags/data_refresh/reporting.py](https://github.com/WordPress/openverse/commit/a8fc3face0124a881fd40d5b552c03539e3c787a)
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

 Move data refresh complete Slack message from ingestion server to catalog

---

documentation/catalog/guides/deploy.md
documentation/ingestion_server/guides/deploy.md

This PR makes some corrections to the deployment runbooks for the catalog and the ingestion server, based on observations made during the catalog deployment which occurred earlier today. Namely, this corrects a few links, removes information about the staging catalog (which does not exist), and adds the cloudwatch dashboard deployment instructions.
<details>
```
Version 1.1
Suite D4700 …
```

Corrections to the catalog & ingestion server deployment run books

---

frontend/src/components/VSearchResultsGrid/VAllResultsGrid.vue
frontend/src/components/VSnackbar.vue
frontend/src/composables/use-audio-snackbar.ts
frontend/src/pages/search/audio.vue
frontend/test/playwright/e2e/all-results-keyboard.spec.ts
frontend/test/playwright/e2e/audio-results.spec.ts
frontend/test/playwright/utils/search-results.ts

Related to #2694 by @obulat
This PR extracts `use-audio-snackbar` composable to make reviewing #2695 easier. This composable is used on the All media search page and Audio search page, and will be used on Additional search views (by tag, source and creator).
The snackbar should appear when you focus an audio on the search view, and it should disappear when you "interact" with it by pressing "spacebar" or clicking on the play button.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Extract `use-audio-snackbar` component

---

frontend/feat/feature-flags.json

Fixes #2732 by @obulat
Tiny PR that adds a feature flag for the Additional search views project.
Go to `/preferences` and turn the feature on and off. It doesn't change anything yet :)
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

Add `additional_search_views` feature flag

---

frontend/.dockerignore

Fixes #856 by @dhruvkb 
Adds `test/` to the file `openverse/frontend/.dockerignore`
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Add test/ to .dockerignore to exlcude tests and test assets from frontend image build context

---

documentation/general/general_setup.md

Fixes #1166 by @zackkrida 
Fixes #1239 by @sarayourfriend 
Tests #2511 by @AetherUnbound 
This PR makes improvements to the docs as per the linked issues.
Read the updated docs from the preview.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```

Improve the docs

---

frontend/src/utils/sentry-config.ts

Fixes #2779 by @sentry-io
Adding `/mce-visual-caret-hidden/` pattern to ignored Sentry errors
<details>
```
Version 1.1
Suite D4700 …
```

fix: adding mce-visual-caret-hidden pattern to ignored Sentry errors

---

frontend/src/stories/Introduction.stories.mdx

Fast follow to #2490. 
The linked PR removes the tailwind config viewer because it is not compatible with TypeScript, so we should remove the reference to that page from our docs.
Confirm I haven't missed anywhere else we need to remove references to TCV.
<details>
```
Version 1.1
Suite D4700 …
```

Remove reference to tailwind config viewer from docs

---

.github/workflows/ci_cd.yml
api/api/apps.py
api/api/models/media.py
api/test/unit/models/test_media_report.py
docker-compose.yml
ingestion_server/gunicorn.conf.py

Fixes #2776 by @obulat
This PR updates the calls to es update to match what's expected in version 9 and remove the deprecation notice.
Check the CI logs: there should be no deprecation notice as in the linked issue. The tests checking for the update calls were updated, and they should pass.
<details>
```
Version 1.1
Suite D4700
By …
```

Remove `body` from the index.update elasticsearch requests

---

frontend/src/components/VErrorSection/VNoResults.vue
frontend/src/components/VErrorSection/meta/VErrorSection.stories.mdx
frontend/src/components/VExternalSearch/VExternalSearchForm.vue
frontend/src/components/VExternalSearch/VExternalSourceList.vue
frontend/src/components/VSearchGrid.vue
frontend/src/composables/use-external-sources.ts
frontend/test/unit/specs/components/ExternalSources/v-external-source-list.spec.js

Fixes #2825 by @obulat
This PR extracts `useExternalSources` composable, which will simplify the changes for the external sources modal (#460) and the error pages (because we have external sources buttons in the No results page).
The external sources on the image and audio results pages should be displayed correctly, have no warnings and the no results page should display correctly (you can see it if you search for "QueryWithNoResults")
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Extract use-external-sources composable

---

catalog/DAGs.md
catalog/dags/popularity/popularity_refresh_types.py
catalog/tests/dags/common/popularity/test_dag_factory.py

Fixes #2092 by @stacimc
Following the first production runs of the popularity refreshes, this PR updates the schedule and timeouts for these DAGs.
Since the image refresh ran in about 9 days, we are definitely able to set the refreshes to the `@monthly` schedule that was our original goal. This will allow us to continue refreshing popularity at the same rate that we were previously. **Note that we can choose to increase this schedule to every 2 weeks.**
It also sets the default timeout for the entire refresh to 2 weeks, or 1 day in the case of the audio refresh. The timeout for individual batches has been lowered to 5 minutes, which is still very generous considering the average speed of 10-30 seconds that we observed in production.
`just up` and run the popularity refresh DAGs. Observe …

Update popularity refresh schedule and timeouts

---

frontend/nuxt.config.ts

Fixes #1988 by @sarayourfriend 
This PR is a tangential fix to #1988, that prevents error in the server and browser consoles when the frontend is running locally without Plausible.
The proxy module now catches the `ECONNREFUSED` errors and returns a 200 message to the frontend (different from the 202 sent by real Plausible) and logs a meaningful error message in the console.
Check out the PR and run the dev server without Plausible. You should see no errors in the browser console and a helpful warning in the server console.
<details>
```
Version 1.1 …
```

Prevent errors when Plausible is not running

---

frontend/src/utils/attribution-html.ts
frontend/test/unit/specs/utils/attribution-html.spec.ts

Fixes WordPress/openverse-infrastructure#593 by @sarayourfriend 
This PR escapes the media title and creator in the attribution text to prevent script injection. It uses `String.replace` because the [HTML Sanitizer API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API) is still experimental.
You should not be able to reproduce the bug outlined in the linked issue.
<details>
```
Version 1.1
Suite D4700 …
```

Escape HTML in media title and creator

---

documentation/frontend/guides/analytics.md
documentation/frontend/guides/deploy.md
documentation/frontend/guides/develop.md
documentation/frontend/guides/index.md

There is no issue for this, I just noticed while query Plausible to research #2822 that the custom properties weren't configured. We need to do this whenever we deploy a new event with unique property names.
Document the need to add goals and configure custom property names during deployment. I also removed documentation explaining the deprecated default props and recorded their deprecation in the deployment docs. There was a nearly empty `develop.md` in the frontend docs that was just confusing to have, so I removed it as well.
Read the updated docs and confirm they are clear and make sense. …

Document Plausible configuration deployment & deprecated custom properties

---

documentation/changelogs/api/2023.08.22.04.57.04.md

This is a manually created changelog PR because the [Release workflow](https://github.com/WordPress/openverse/actions/runs/5934605029) failed midway.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

Publish changelog for api-2023.08.22.04.57.04

---

.github/workflows/ci_cd.yml
api/api/apps.py
docker-compose.yml
ingestion_server/gunicorn.conf.py

This is a follow up to the removing Elasticsearch 7
This PR reverts the changes in #2832 that allowed us to test API and ingestion server on both ES versions.
After the CI passes and the PR is approved, the comments should be deleted.
<details>
```
Version 1.1
Suite D4700 …
```

Remove ES matrix from CI

---

frontend/src/components/VExternalSearch/VExternalSearchForm.vue
frontend/src/components/VSearchResultsGrid/VAudioCollection.vue
frontend/src/composables/use-body-scroll-lock.ts
frontend/src/locales/scripts/en.json5
frontend/test/locales/ar.json
frontend/test/playwright/e2e/external-sources.spec.ts
frontend/test/playwright/visual-regression/components/external-sources-section.spec.ts

Fixes #2668 by @fcoveram 
This PR addressed the design improvement in #460 by making the external sources popup a modal and adjusting the modal title according to screen size.
1. Conduct a search
2. Scroll to the bottom to find the new external search button
3. Click on the button to let the modal display
4. Change screen size to view the different modal titles according to screen size
<details>
```
Version 1.1
Suite D4700 …
```

Update metasearch button style and use a modal for screens below `lg`

---

.github/filters.yml

Prevents #2965 by @dhruvkb
This PR adds general Node files to the `packages` changeset. This ensures that changes to the top-level Node files triggers CI jobs for packages like the ESLint plugin.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```

Include general Node files under `packages` key

---

.github/workflows/release-app.yml

Fixes #2859 by @sarayourfriend 
This PR
- moves the deployment steps before the changelog PR steps to ensure that the deployment goes through
- makes the changelog PR even if any previous step has failed
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

Move deploy steps before changelog PR

---

ingestion_server/ingestion_server/indexer.py

Fixes #2963 by @AetherUnbound 
I haven't been able to test this locally due to local environment issues preventing upstream db from building and initialising correctly.
I figured I'd open the PR and see how CI handles it and get it ready ASAP in order to prevent any further delays before the next time the reindex comes around.
Existing tests should pass. Audit Elasticsearch request logs if you want to confirm the query parameter is sent.
<details>
```
Version 1.1 …
```

Add 10k throttle to filtered index reindex query

---

frontend/src/components/VSearchResultsGrid/VImageGrid.vue

Fixes #2923 by @krysal
<details>
```
Version 1.1
Suite D4700
of …
```

Add null check for images in loading skeleton

---

catalog/DAGs.md
catalog/dags/data_refresh/data_refresh_types.py

* Fixes #2979 by @AetherUnbound 
This changes the data refresh schedule to start on Tuesdays UTC 00:00 from the original Sunday at UTC 00:0.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```

Start data refresh schedule on Tuesdays UTC 00:00

---

frontend/src/components/VSearchResultsGrid/VAudioCollection.vue

Fixes #2924 by @krysal
This PR adds a null/undefined check to the `VAudioCollection` component to fix the linked issue.
<details>
```
Version 1.1
Suite D4700 …
```

Add a null/undefined check to audio VGridSkeleton

---

frontend/src/layouts/content-layout.vue
frontend/src/layouts/default.vue
frontend/src/layouts/search-layout.vue
frontend/src/middleware/middleware.ts
frontend/src/stores/feature-flag.ts
frontend/src/types/cookies.ts
frontend/src/utils/cookies.ts
frontend/test/playwright/e2e/translation-banner.spec.ts
frontend/test/playwright/visual-regression/pages/homepage.spec.ts
frontend/test/unit/specs/stores/feature-flag-store.spec.js

Fixes #2932 by @obulat
This PR
- removes usage of `sessionStorage` from the feature flag store
- migrates session-scoped preferences to the `sessionFeatures` cookie
- makes the `features` cookie persistent (which it wasn't earlier!)
- removes unused code from store and layouts
1. Check out the PR and run the dev server.
2. Toggle some persistent preferences in `/preferences`. E.g.
- `fake_sensitive`
- `additional_search_types`
- `sensitive_content`
4. Restart the browser to see that the changes are preserved.
5. Toggle some session-scoped preferences in `/preferences`. E.g.
- `fetch_sensitive` (there's only one).
6. Restart the browser to see that the changes are not preserved. …

Separate features into persistent and session scoped cookies

---

frontend/src/stores/search.ts

Fixes #2994 by @sarayourfriend 
This PR checks for the `sensitive_content` flag alongside the `fetch_sensitive` flag in places where checking only the latter could cause a situation where sensitive content fetching would be frozen because the UI to toggle it would not be visible.
1. In `/preferences`, enable `fetch_sensitive` but not `sensitive_content`.
2. Search for sensitive content, you should not see any.
With this PR sensitive content will only be fetched when there the UI to disable it is also visible.
<details>
```
Version 1.1 …
```

Check flag 'sensitive_content' with 'fetch_sensitive'

---

frontend/src/composables/use-single-result-page-meta.ts
frontend/src/pages/audio/_id/index.vue
frontend/src/pages/image/_id/index.vue
frontend/src/pages/index.vue
frontend/src/pages/preferences.vue
frontend/src/pages/privacy.vue
frontend/src/pages/search.vue
frontend/src/utils/og.ts
frontend/test/playwright/e2e/seo.spec.ts

Fixes #2987 by @obulat
This PR fixes a couple of SEO-related problems:
`defineComponent` imported from `vue` does not work with head settings. This PR changes the import to be from `@nuxtjs/composition-api`, which updates the `robots` value correctly. Now, only the single result pages are not indexed, to prevent duplicate results with the provider pages.
The search pages titles did not update when you searched for a new term. This PR uses the title setup described on the `@nuxtjs/composition-api` docs page to make the title update on a new search.
The PR also adds an e2e test to prevent regressions.
Run the app using `just frontend/run build` and `just frontend/run start` to load the prod settings. Check the `meta` values inside the `<head>` element. Note that there are a lot of items …

Fix meta tags on pages

---

frontend/src/data/media-service.ts

Related to #2833 by @sentry-io
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
```

Media results null check

---

frontend/src/components/VImageCell/VImageCell.vue
frontend/src/components/VSearchResultsGrid/VAudioResult.vue
frontend/src/types/analytics.ts
frontend/src/utils/decode-media-data.ts
frontend/test/playwright/e2e/all-results-analytics.spec.ts

Fixes #2969 by @dhruvkb
This PR adds two fields `sensitivity` and `isBlurred` to the `SELECT_SEARCH_RESULT` event.
1. Search for some term.
2. Choose a result.
3. Observe the event in the Console and in the Network logs.
<details>
```
Version 1.1
Suite D4700 …
```

Add content safety info to `SELECT_SEARCH_RESULT` event

---

CODE_OF_CONDUCT.md

Fixes #2976 by @sarayourfriend 
This PR removes all text from the `CODE_OF_CONDUCT.md` file and replaces it with two references
- WordPress Etiquette (the source for our previous CoC)
- WordPress Community Code of Conduct
Note that this is different from Gutenberg, another WordPress project, which contains our previous text (from the etiquette) in it's CoC.
<details>
```
Version 1.1
Suite D4700 …
```

Reference WordPress CoC and etiquette in Openverse CoC

---

catalog/DAGs.md
catalog/dags/data_refresh/data_refresh_types.py

Starts the data refreshes on Mondays at UTC 0:00 instead of Tuesdays. This allows them to complete by Wednesday so that they will not block catalog deployments.
Note: we don't expect issues with the data refreshes running at the same time as popularity refreshes, but if we ever _do_ observe any performance issues here we should shift the schedule of the **popularity refresh**, not the data refresh. The popularity refreshes are resilient to failure and don't have to complete before deployments can be run.
Run `just up` and check the audio and image data refreshes in the Airflow UI to verify that their schedules look correct.
<details> …

Start data refreshes on Mondays UTC 00:00

---

api/api/serializers/media_serializers.py

Fixes #3056
The report endpoint converts the `reason` from `mature` to `sensitive`. However, it doesn't check if `reason` exists in the request or not. So, when sending a manually-formed request without the `reason` parameter, you get a 500 error. So we implement the `.get()` method on `data` so that if the value doesn't exist it will return `None` and that will be handled by validator.
<details>
```
Version 1.1
Suite D4700 …
```

Fixes `KeyError` for `media_serializers.py`

---

documentation/meta/monitoring/runbooks/index.md
documentation/meta/monitoring/runbooks/nuxt_avg_response_time_above_threshold.md
documentation/meta/monitoring/runbooks/nuxt_p99_response_time_above_threshold.md

Related to #2504 by @sarayourfriend
Adds the run books for the general Nuxt response time alarms.
Look for the preview in the comments and check that the instructions make sense.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```

Add runbooks for Nuxt response times alarms

---

docker-compose.yml

Fixes #3077 by @AetherUnbound 
The Airflow environment variable _AIRFLOW_DB_UPGRADE has been deprecated. Refer this link for details:-
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#the-db-init-db-upgrade-commands-and-database-load-default-connections-configuration-options-are-deprecated-33136
To resolve this, the yaml configuration file has been updated with _AIRFLOW_DB_MIGRATE.
With the Environment variable update to _AIRFLOW_DB_MIGRATE, just Run catalog/test-session and the environment variable deprecated warning will be removed.
<details>
```
Version 1.1
Copyright (C) …
```

Update `_AIRFLOW_DB_UPGRADE` to `_AIRFLOW_DB_MIGRATE`

---

api/api/controllers/search_controller.py

This PR increases the sources cache TTL from 20 minutes to 4 hours. We've noticed a very regular spike in ES activity and API response time every 15-20 minutes, and we believe it's related to this value being refreshed. We believe that increasing this will reduce load on Elasticsearch and our overall response time spikes. While this is an experimental change, if we wish to persist it, we'll want a mechanism for clearing the cache value from the Admin UI manually, or ensure that it gets purged when we make update to the providers in the API.
<details>
```
Version 1.1 …
```

Increase the API sources cache TTL from 20 minutes to 4 hours

---

frontend/test/playwright/visual-regression/pages/pages-single-result.spec.ts

Related to #3112 by @obulat
This PR skips the flaky test. I'm not sure how to fix the problem itself, when the layout is rendered correctly, but changes when we take the snapshot.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```

Skip flaky test

---

.github/dependabot.yml

Fixes #1025  by @AetherUnbound 
Add four github actions (build-docs, get-changes, load-img, setup-env) in dependabot because dependabot to check these versions by explicitly adding the various action folders to the dependabot config.
- [] I tried running the project locally and verified that there are no visible errors.
<details>
```
Version 1.1 …
```

Add various action folders to Dependabot

---

frontend/src/data/media-service.ts

Fixes #3027 by @stacimc 
Add an `undefined/null` check in the transform method similar to https://github.com/WordPress/openverse/pull/3016.
<details>
```
Version 1.1
Suite D4700 …
```

Undefined mediaResults Hotfix add an undefined/null check

---

frontend/src/constants/meta.ts

I'm not sure if this is a valid PR. Described below. There is no issue, just something I noticed that was weird.
I noticed this on a single results page when looking through the meta tags and realised I had no idea what it does. Reading more about the monetization meta tag, I think there are two problems with the current one (info here https://webmonetization.org/):
1. The uphold account is probably not controlled by WP Foundation. I don't know where it leads, but I've never heard us mention this _literally ever_, and the earliest code reference I can find dates back to the CC Search days: https://github.com/cc-archive/cccatalog-frontend/issues/1014
2. The same monetization tag shows on single result pages, which seems to indicate that the same uphold account gets monetization benefits …

Remove monetization meta tag

---

frontend/feat/feature-flags.json
frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue
frontend/src/layouts/search-layout.vue
frontend/src/stores/search.ts
frontend/test/playwright/e2e/filters.spec.ts
frontend/test/playwright/e2e/search-query-client.spec.ts
frontend/test/unit/specs/stores/search-store.spec.js

Fixes #3142 by @dhruvkb
This PR enables the 'sensitive_content' feature flag by deleting the flag and ensuring all usages of the flag evaluate to `true`.
1. Ensure that all features behind this flag are generally accessible.
<details>
```
Version 1.1
Suite D4700 …
```

Enable the sensitive content flag and cleanup

---

api/api/controllers/search_controller.py

Similarly to #3177, this PR changes access for the `title` field on `Hit` to `getattr` to handle ES records that do not have the title field set.
Fortunately, we already have 37 examples of records with missing `title` in our sample data. To test this PR:
1. Check out `main` locally and run `just up`
2. Try to access http://localhost:50280/v1/images/0156cc96-bb23-4961-95d6-c9658c78edff/related/ and observe the `'Hit' object has no attribute 'title'` error
3. Check out this branch and run `just up`
4. Refresh the http://localhost:50280/v1/images/0156cc96-bb23-4961-95d6-c9658c78edff/related/ page and observe that it now works.
<details> …

Handle related media with missing title

---

frontend/src/components/VMediaInfo/VMediaTags.vue

Fixes the problem in 3137 that causes the CI failure.
The styles were not applied to the wrapper `ul` of the `VMediaTag`s.
The CI should pass without any snapshot changes.
<details>
```
Version 1.1
Suite D4700
have …
```

Re-add the style to tags container

---

documentation/catalog/guides/index.md
documentation/catalog/guides/quickstart.md

This PR moves the catalog's README.md file into the documentation site. It does not update any more components beyond what's necessary; I'll make a number of tickets after this is merged pointing to specific places to update.
**This is in preparation for an upcoming contributor day**.
Documentation render should include it once CI/CD completes.
<details>
```
Version 1.1
Suite D4700 …
```

Move catalog README to docs site quickstart

---

api/README.md
automations/README.md
catalog/README.md
documentation/README.md
documentation/conf.py
frontend/README.md
ingestion_server/README.md
packages/README.md
packages/eslint-plugin/README.md

Fixes #3205  by @AetherUnbound
I add shim README files to the required service subfolders that point to the documentation site, by can create a simple README.md file in each of the subfolder of the services with the appropriate links.
```md
This service is documented at [docs.openverse.org/catalog]
(https://docs.openverse.org/catalog/index.html).
```
```md
This service is documented at [docs.openverse.org/api] 
(https://docs.openverse.org/api/index.html).
```
```md
This service is documented at [docs.openverse.org/ingestion_server] 
(https://docs.openverse.org/ingestion_server/index.html).
```
```md
This service is documented at [docs.openverse.org/frontend] 
(https://docs.openverse.org/frontend/index.html).
```
```md
This service is documented at [docs.openverse.org/documentation] …
```

Add shim `README.md` files in project directories

---

catalog/dags/data_refresh/data_refresh_task_factory.py
catalog/dags/data_refresh/data_refresh_types.py
catalog/dags/popularity/popularity_refresh_types.py

Fixes #1472 by @AetherUnbound 
Add an `poke interval` variable to `POPULARITY_REFRESH_CONFIGS` for media_type as "image".
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Allow data refresh poke interval for Image.

---

catalog/dags/common/urls.py
catalog/tests/dags/common/test_urls.py

Fixes #1279 by @AetherUnbound 
URLs which get written to TSV should not have spaces in them. I had created a class to state the error. There is a if condition to determine if a space is in the `url_string` then the raise error will populate a string message.
run `just catalog/test`
<details>
```
Version 1.1
Suite D4700
San …
```

Raise error when space is in URL

---

documentation/meta/monitoring/runbooks/api_thumbnails_avg_response_time_above_threshold.md
documentation/meta/monitoring/runbooks/api_thumbnails_avg_response_time_anomaly.md
documentation/meta/monitoring/runbooks/api_thumbnails_p99_response_time_above_threshold.md
documentation/meta/monitoring/runbooks/api_thumbnails_p99_response_time_anomaly.md

Adds recent incidents with exemplary investigations to the API thumbnail response time runbooks.
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```

Update thumbnail response time runbooks

---

api/api/controllers/elasticsearch/helpers.py
api/api/controllers/search_controller.py
api/api/utils/search_context.py

Fixes #3139 by @aetherunbound
Fixes #3298 by @obulat 
This PR extracts the function that performs ES request, and wraps it in a decorator that logs the following information:
- time it took for the request to return
- time ES reports as it `took` the query to return (internal ES request time)
- kind of query (I did not add the full query because it would take a lot of space. But the kind of query - search, sources aggs or result postprocessing - could be helpful in investigations).
This PR also includes the fix in #3299.
<details>
```
Version 1.1 …
```

Log times of ES queries

---

frontend/package.json
pnpm-lock.yaml

Related to #3242 by @obulat
Update @nuxtjs/sentry dependencies.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```

Update Nuxt sentry dependency

---

frontend/nuxt-template-overrides/App.js
frontend/nuxt-template-overrides/index.js

No issue for this, and as far as I know it isn't causing problems that we haven't updated these, but figured it would be a good idea to do it when it occurred to me today.
Updates the two templates by following the instructions in the README.md in their directory. I copied the files out of node modules and then applied the changes to the import order.
Run the app and confirm it works. Playwright and all unit tests should pass.
<details>
``` …
```

Update Nuxt template overrides to latest versions of templates

---

.github/workflows/ci_cd.yml
documentation/meta/ci_cd/jobs/frontend.md
frontend/package.json

Related to changes in #3247
The changes to Webpack and Nuxt make it so that the Storybook smoke test fails in the GitHub CI runner. Since it does not really test if the Storybook tests render correctly, and the tests are ran in the Playwright tests, this smoke test is not needed.
The CI should pass (after the infrastructure changes are applied and the smoke test is not required anymore).
<details>
```
Version 1.1
Suite D4700 …
```

Remove Storybook smoke test

---

frontend/package.json
frontend/src/components/VLicense/VLicense.vue
frontend/src/components/VLicense/VLicenseElements.vue
frontend/src/components/VSafetyWall/VSafetyWall.vue
frontend/src/components/meta/VButton.stories.mdx
frontend/src/locales/scripts/utils.js
frontend/src/stores/provider.ts
frontend/src/utils/case.ts
frontend/src/utils/decode-media-data.ts
frontend/src/utils/license.ts
frontend/src/utils/metadata.ts
frontend/test/unit/specs/utils/case.spec.js
pnpm-lock.yaml

Fixes #2464 by @obulat
This PR vendors in the implementation for `case` functions that we use (camelCase, capitalCase, titleCase) from `change-case` JS package.
In the locales scripts files, I could not use the `camelCase` function because those scripts are called by `node`, not transpiled, so they cannot import anything from `.ts` files. I added a simpler version in JS, `kebabToCamel`, because we convert only kebab cased values, and do not need the complex splitting used in `camelCase` function.
The CI should pass. 
<details>
```
Version 1.1 …
```

Vendor in case functions

---

documentation/catalog/guides/adding_a_new_provider.md

Fixes #2800 by @stacimc 
Add a test section in new provider docs. First we will have `just catalog/test-session` -> `pytest -k <provider_name>` as the recommended suggestion to test a specific provider. There is an alternative testing that can be ran `just catalog/test -k <provider_name>`
<details>
```
Version 1.1
Suite D4700
By making …
```

Add instructions on running individual test in new provider docs

---

catalog/requirements_dev.txt

Follow up #3288 - `pytest-mock` is now in the Airflow constraints file so we can just let Airflow manage the version we're using.
CI should pass, you can run `j build && j catalog/test` locally to confirm.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

Unpin pytest-mock and rely on Airflow constraints for version

---

api/api/controllers/search_controller.py
api/api/views/media_views.py
api/test/unit/controllers/test_search_controller.py
api/test/unit/views/test_media_views.py

Fixes #3189 by @AetherUnbound 
This PR
- writes log messages when `_post_process_results` recurses more than 5 levels deep (configurable via env var)
- refactors `_post_process_results` to make it responsible for 1 task
The CI includes a test case that captures the logs and verifies that the log line is emitted.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```

Add logging around `_post_process_results` recursion

---

frontend/src/components/VBanner/VAnalyticsNotice.vue
frontend/src/components/VBanner/VTranslationStatusBanner.vue
frontend/src/components/VContentReport/VReportDescForm.vue
frontend/src/components/VContentSwitcher/VSearchTypeButton.vue
frontend/src/components/VContentSwitcher/VSearchTypeItem.vue
frontend/src/components/VContentSwitcher/VSearchTypePopover.vue
frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue
frontend/src/components/VHeader/VHeaderMobile/VShowResultsButton.vue
frontend/src/components/VHeader/VPageLinks.vue
frontend/src/components/VHideButton.vue
frontend/src/components/VLink.vue
frontend/src/components/VMediaInfo/VMetadataValue.vue
frontend/src/components/VRadio/VRadio.vue
frontend/src/components/VSafetyWall/VSafetyWall.vue
frontend/test/unit/setup.js
packages/eslint-plugin/src/configs/vue.ts

Fixes #588 by @obulat
This PR enables the `vue-3/recommended` eslint rules. It also specifically turns off some of the rules that cannot be used with Vue 2.
Most of the changes are for adding `emits` option which is optional in Vue 2 but required in Vue 3.
The CI should pass
<details>
```
Version 1.1
Suite D4700 …
```

Add some Vue 3 Eslint rules

---

catalog/requirements_prod.txt

Fixes #2370 by @AetherUnbound
This PR adds the Elasticsearch Airflow provider package to our catalog Docker image. In order for the package to be available for use in DAGs, we'll need to deploy the catalog once this is merged.
1. `just build && just api/init`
1. `just catalog/ipython`
1. Run:
```python
from airflow.providers.elasticsearch.hooks.elasticsearch import ElasticsearchPythonHook
hook = ElasticsearchPythonHook("http://es:9200")
hook.get_conn.indices.get_alias(index="*")
```
You should see something along the lines of:
```
Out[9]: ObjectApiResponse({'image-init': {'aliases': {'image': {}}}, 'audio-init-filtered': {'aliases': {'audio-filtered': {}}}, 'audio-init': {'aliases': {'audio': {}}}, 'image-init-filtered': {'aliases': {'image-filtered': {}}}})
``` …

Add Elasticsearch Airflow provider

---

.github/workflows/issue_automations.yml
.github/workflows/pr_automations.yml

Follow up to #3374.
This PR fixes the paths to the `.mjs` files for the project automations. Somehow, an `src/` component got left out and will break the workflows.
The good news is that the "PR automations init" workflow works well and the output JSON file is correctly written. I didn't have a lot of confidence in the Bash script because of all the nested quotes.
<details>
```
Version 1.1
Suite D4700 …
```

Fix path to automation `.mjs` files

---

.github/workflows/issue_automations.yml
.github/workflows/pr_automations.yml

Follow up to #3392
This PR updates the workflows to use the `ACCESS_TOKEN` secret instead of `GITHUB_TOKEN` because the latter cannot access org-level projects, only ones at the repo level.
Try the testing steps from the original PR #3375 using the @openverse-bot's PAT (which is what `ACCESS_TOKEN` is).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```

Use the `ACCESS_TOKEN` secret instead of `GITHUB_TOKEN`

---

api/conf/settings/rest_framework.py

Related to #3344 
I placed the `NUM_PROXIES` setting outside the `REST_FRAMEWORK` dictionary, which is where DRF looks for its settings. This PR moves it into the correct location.
We're just setting the value, so review the DRF settings documentation and confirm it's in the correct place now. The rest is all handled by DRF, so there's nothing to test on the implementation side.
<details>
```
Version 1.1 …
```

Put `NUM_PROXIES` setting in correct location for DRF

---

.github/sync.yml

This PR syncs the code required by the project automation workflows to the infra repository. In the absence of these JS files, the workflows expectedly fail.
<details>
```
Version 1.1
Suite D4700
have the right to …
```

Sync project automation code to infra repo

---

utilities/project_planning/calculate_available_weeks.py

This PR adds a script which can be used to (imperfectly) capture the available number of weeks of development time for the Openverse maintainers for the next year. This is based off work by @sarayourfriend done here: https://gist.github.com/sarayourfriend/5f16224fe4897926209fa1a3e06905fe.
For the current configuration, this outputs **~272 available development weeks**.
1. `cd utilities/project_planning`
2. `pipenv run calculate_available_weeks.py`
<details>
```
Version 1.1
Suite D4700 …
```

Add script for calculating available development weeks

---

api/Dockerfile
frontend/Dockerfile
ingestion_server/Dockerfile

Fixes https://github.com/WordPress/openverse-infrastructure/issues/382 by @sarayourfriend (cc @krysal who originally reported it)
Adds the `SENTRY_RELEASE` environment variable to all our Docker images that run apps that use Sentry (in other words, all of them except the Airflow image).
This should allow Sentry to give "suspect commits" for all our services (though it might already work for some, it doesn't for the frontend, for example).
I was looking through old issues I opened to find ones that were no longer relevant and saw this one. It's a quick and easy change, so figured I'd go ahead and do it.
Confirm the Dockerfile syntax is correct. Build an image and confirm that `SENTRY_RELEASE` is set to whatever you've set `SEMANTIC_VERSION` to. `SEMANTIC_VERSION` is always set to the git …

Add SENTRY_RELEASE environment variable to relevant dockerfiles

---

catalog/dags/providers/provider_workflows.py

Fixes #3450 by @stacimc 
In response to some production timeouts, this PR increases Europeana timeout to 1 week.
Noting that this increases the possibility of a Europeana run being in progress when we want to do a catalog deploy. If that happens, we can let the dag fail and use the `initial_query_params` and `date` configuration options to resume from the point of failure -- so this shouldn't be a concern.
Run the Europeana DAG locally and go inspect the DAG details to see that the `execution_timeout` is now 1 week.
<details>
```
Version 1.1 …
```

Extend Europeana timeout to 1 week

---

catalog/dags/common/loader/provider_details.py

Fixes #3121 by @AetherUnbound 
Adds the Internet Archive Book Images as a subprovider for Flickr.
Once merged, we'll need to add the source in the Django admin.
Note: after this is merged, from this point _forward_ when a record is ingested that belongs to this user it will have its `source` correctly set to `internet_archive_book_images`. Records that we've already ingested won't automatically be updated, though, and the flickr reingestion DAG is not enabled. One way of handling this would be to a `batched_update` where we select flickr records with this creator and update the source.
Verify that you agree this source should be pulled out as a subprovider. You can see them on flickr here: https://www.flickr.com/photos/internetarchivebookimages/ They have 4,767,558 records. It looks like …

Add Internet Archive Book Images subprovider

---

catalog/templates/template_test.py_template

This PR fixes the path to the test resources to match the path at the top of the file.
<details>
```
Version 1.1
Suite D4700
(b) …
```

Fix path to test resources

---

documentation/general/contributing.md
documentation/general/publish.md

This PR is a small fix to the docs to point a few references to archived repositories to the monorepo.
See that the updated docs preview links to the right place for these modifications.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

Update links to archived repositories in documentation

---

.github/actions/load-img/action.yml

This PR restores CI by pinning `@actions/artifact` to v1. v2 was just released and contains breaking changes.
Check that CI works. Example of a failed CI run can be seen [here](https://github.com/WordPress/openverse/actions/runs/7186819483?pr=3505).
<details>
```
Version 1.1
Suite D4700 …
```

Pin `@actions/artifact` to version 1

---

documentation/catalog/guides/deployment.md

Small docs update PR to remove the outdated deployment documentation for the catalog and point that section to the current deployment runbook.
Check that the docs preview is correct.
<details>
```
Version 1.1
Suite D4700 …
```

Point Airflow deployment information to updated deployment runbook

---

documentation/meta/incidents/index.md
documentation/meta/incidents/runbooks/incident_response_runbook.md
documentation/meta/incidents/runbooks/index.md
documentation/meta/index.md

Fixes #2063 by @AetherUnbound 
Closes https://github.com/WordPress/openverse/issues/2060 by @zackkrida 
This PR adds incident response information and a runbook for addressing an active incident.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```

Incident Response Plan

---

catalog/Dockerfile

Follow up to #3527, this reverts commit b7337c6583a9eb7d4bc0e07ebd620de1d435fcba.
Airflow patched their image upstream in a similar way (see https://github.com/apache/airflow/issues/36231), so our workaround is causing the builds to fail. Fortunately, we no longer need to have this patched ourselves!
Similar instructions to #3527 - `just build scheduler --no-cache` on this branch should succeed.
<details>
```
Version 1.1
Suite D4700 …
```

Revert "Remove mysql from apt repository sources for catalog due to expired key (#3527)"

---

.github/workflows/pr_label_check.yml

This PR updates our label checker to accept PRs with one or more aspect labels. Previously it expected exactly one which was too restrictive.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```

Allow more than one aspect label

---

docker/cache/justfile
justfile

This PR adds a `justfile` for quickly accessing common operations on the local Redis container.
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```

Add some `just` recipes for the Redis cache service

---

catalog/dags/providers/provider_api_scripts/cc_mixter.py
catalog/tests/dags/providers/provider_api_scripts/test_cc_mixter.py

This PR fixes an issue that appears in ccMixter's response where numbers may be prefixed with multiple leading zeros. Earlier we had observed (and handled) cases with one leading zero but thanks to @krysal we know that's it is not always limited to one, see [this response](https://ccmixter.org/api/query/?format=json&limit=1&offset=26861).
Added unit test to confirm handling of multiple leading zeros.
<details>
```
Version 1.1
Suite D4700 …
```

Handle multiple leading zeros in ccMixter's JSON response

---

frontend/src/components/VImageCell/VImageCell.vue

Critical follow-up to https://github.com/WordPress/openverse/pull/3472, to fix linting in CI/CD.
<details>
```
Version 1.1
Suite D4700 …
```

Fix linting in CI

---

.github/ISSUE_TEMPLATE/project_thread.md

This PR removes the front matter from the project thread issue template. This information was based on our project process for the previous year, and it has evolved in the time since. We no longer project start dates on our projects for the year, and the team lead is identified by the assignee of the project thread. The actual ship date is reflected when the issue is moved to the "Shipped" column of the project board, so this information is no longer needed.
I also added a note about milestones on the issue template, since we've been using those more to group issues rather than enumerating each one in the project thread.
<details> …

Remove front matter from project thread issue template

---

docker-compose.yml

Addresses WordPress/openverse-infrastructure#611 by @AetherUnbound 
This PR bumps Redis to v7 locally. The tests are all passing and exploring the local Redis instance suggests that everything is working normally.
0. Check out the PR and run the API with `just api/up`.
1. Init the API if you haven't already (if you're not sure, reset everything and init with `just down -v && just api/init`).
2. Explore the API and see that things are working normally.
<details>
```
Version 1.1
Suite D4700 …
```

Bump Redis to v7 in local dev environment

---

api/api/admin/__init__.py

Fixes #3470 by @AetherUnbound 
This small PR enables the `notes` field in the Django Admin view and also sort the list of providers by 1. media type 2. provider name.
```sh
just api/up
```
- [N/a] I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700 …
```

Remove exlusion of ContentProvider's notes in ProviderAdmin

---

api/test/unit/utils/test_watermark.py
api/test/unit/utils/test_waveform.py
api/test/unit/views/test_image_views.py

Fixes #2256 by @sarayourfriend 
This PR completes the transition from `requests` mocking to `pook`.
The CI tests (specifically the unit tests) for the API should pass.
<details>
```
Version 1.1
Suite D4700
have the …
```

Replace `requests` mocking with `pook`

---

utilities/load_testing/Dockerfile
utilities/load_testing/justfile
utilities/load_testing/k6/observation.js
utilities/load_testing/k6/utils.js

Addresses WordPress/openverse-infrastructure#611 by @AetherUnbound
This PR adds a script to monitor the API during the Redis migration. This script
- counts response status codes (ideally we are looking for all 200s, some 424s but zero 429s)
- checks for response times from the stats endpoint that will no longer be cached
The PR also
- updates the `Dockerfile` to build on top of `grafana/k6` image using a multistage build like the API
- matches the code style of the API `Dockerfile`
- unifies the name of the access token to be `ACCESS_TOKEN` everywhere
0. Sign up for a test account on the staging API, verify email (or look in HelpScout for my existing test account credentials) and exchange the client ID and secret for an access token.
1. Export the `ACCESS_TOKEN` env var with the token …

Add a script to observe the API during Redis migration

---

documentation/api/reference/search_algorithm.md

This PR updates Incorrect spelling in doc blocks. 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

Docs: Fix typo

---

README.md

Small PR to update the meeting time for our weekly dev chat in our README ([as announced here](https://make.wordpress.org/openverse/2023/12/05/weekly-community-meeting-time-is-changing/)).
I also updated the Make WP "Slack" to "Chat" to make it more agnostic to the tool, and added more information on the monthly prioritization meeting.
<details>
```
Version 1.1
Suite D4700 …
```

Update meeting times in README

---

frontend/src/components/VButton.vue
frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue
frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
frontend/src/components/VHomepageContent.vue
frontend/src/components/VItemGroup/VItem.vue
frontend/src/components/VLogoLoader/VLogoLoader.vue
frontend/src/components/VMediaInfo/VByLine/VSourceCreatorButton.vue
frontend/src/components/VModal/VModalContent.vue
frontend/src/components/VSnackbar.vue
frontend/src/components/VTabs/VTab.vue
frontend/src/types/button.ts

This PR is in preparation for Nuxt 3 migration
Several rendering errors come up when adding tests to Nuxt 3 branch. They are made more complicated by the fact that Openverse components use different kind of styles (`scoped` and `module`). In some tests, scoped styles work but module styles don't. 
This PR unifies the styles in components, replacing the module styles with `scoped` styles, which are more idiomatic for Vue. This change also helped me find unused classes and remove styles that are incorrect (e.g., `py-2` in `VItem`). I also rewrote some of `VButton` code to remove redundant refs and watches and to use composables instead.
This PR also removes the `dropdown-label` button style which was previously used for the External sources button.
The CI should pass. Passing Visual …

Unify Vue components

---

api/run.py

Fixes #3237 by @obulat 
command line [options](https://www.uvicorn.org/#command-line-options) for access log is either --access-log / --no-access-log  Enable/Disable access log. I used `access_log="Disable"` I'm not sure what is the best method on test. the approach for test is run `just down -v` and `just api/init`.
run `just api/init`
if fail run:
- `just down -v` 
- `just api/init`.
<details>
```
Version 1.1
Suite D4700 …
```

Silence the gunicorn access log

---

.github/workflows/ci_cd.yml
api/justfile
docker-compose.yml
docker/upstream_db/Dockerfile
justfile

Fixes #2959  by @obulat 
This solution use the same approach on [CATALOG_AIRFLOW_VERSION](https://github.com/WordPress/openverse/blob/f4320b91c53cffed8e68ac368d63abae4f56d7f6/catalog/justfile#L20) `PGCLI_VERSION` will retrieve the current version of pgcli and an environment variable which dockerfile can use to determine pgcli version. I believe renovate will update [python dev dependencies](https://github.com/WordPress/openverse/blob/f4320b91c53cffed8e68ac368d63abae4f56d7f6/.github/renovate.json#L67). 
run `just api/up`
<details>
```
Version 1.1 …
```

pgcli version is extracted into a docker argument

---

.github/workflows/discussion_ping.yml
.github/workflows/pr_limit_reminders.yml
.github/workflows/pr_ping.yml

https://github.com/WordPress/openverse/pull/3577 added new usages of `slackapi/slack-github-action`, but we missed that the version format was incorrect. The tags on the repository have `v` at the front, so we need to use them in the action version reference as well. You can compare this to other usages of the same action in our repository that have the correct format.
Here's an example of the broken code failing: https://github.com/WordPress/openverse/actions/runs/7470300640/job/20328836725?pr=3650
Compare to other usages of the action and make sure I've got the fix correct. …

Fix slack ping action version reference

---

ingestion_server/ingestion_server/indexer.py

Since the last time the `request_per_second` setting was modified for the filtered index creation in #2975, the ES's average CPU usage has been constant below the 43%. Observe the graph for last six weeks, the high peaks correspond to the base index creation and the following lower raises to the filtered index task.
Having approximately 60% of computing power available we can try increasing this value so that the process finishes faster, or alternatively, removing the throttling entirely since indexes are not promoted until both are updated. Live users shouldn't be affected.
This PR makes this setting take its value from a new environment value with an increased default value. …

Increase ES throttling rate in Ingestion Server

---

documentation/projects/index.md
documentation/projects/yearly_planning/index.md
documentation/projects/yearly_planning/process_outline.md
documentation/projects/yearly_planning/project_themes.md

This PR adds documentation for our yearly planning process. The outline is based on a plan the maintainer team built and applied for 2024, along with a few alterations that were made during the course of planning for this year.
I didn't move the README for the scripts out of the utilities directory because I thought it might be best served next to the code. If folks have different opinions, please feel free to share them!
Check out the documentation preview and make sure everything is clear and makes sense!
<details>
```
Version 1.1 …
```

Add documentation for yearly planning

---

catalog/dags/providers/provider_api_scripts/rawpixel.py

Reported by @krysal that the rawpixel DAG was not working locally.
The rawpixel DAG was failing with 403s on every request locally, but the same URLs could be accessed in a browser. Adding the User-Agent header fixes the problem.
Run the rawpixel DAG locally on `main` and confirm that it fails immediately. Then check out this branch and try again; confirm that the DAG begins to ingest records.
<details>
```
Version 1.1
Suite D4700 …
```

Add user-agent header for rawpixel

---

documentation/terms_of_service.md

Prerequisite for #3564
This PR modifies the existing terms of service for the API to have the same terms apply to all services/content under the Openverse umbrella. This should allow us to use this page directly as the terms of service for our frontend as well as the API.
<details>
```
Version 1.1
Suite D4700 …
```

Make the terms of service apply to all services

---

.github/workflows/ci_cd.yml

This is a very small PR that combines the commands that both print something and then write it to a file to use `tee` instead, which I only learned about recently.
<details>
```
Version 1.1
Suite D4700
have the …
```

Combine write to file and STDOUT in one command using `tee`

---

catalog/dags/providers/provider_workflows.py

The WordPress Photo Directory DAG was running on a `monthly` schedule. Consequently when a user uploads to the Photo Directory, in the worst case scenario it might take a month for the record to actually be ingested into Openverse (and then made available by the following data refresh).
This PR updates the DAG to run on a `weekly` schedule. Note that because the data refreshes are offset from the weekly schedule by one day, this guarantees that the maximum amount of data will be available by the time of the refresh.
Run `just up`, then inspect the `wordpress_workflow` in Airflow and verify that the schedule now says `@weekly`.
<details> …

Update WordPress Photo Directory DAG to ingest weekly

---

.github/workflows/discussion_ping.yml
.github/workflows/pr_ping.yml

Follow up to #3699 - looks like `toJSON` doesn't work because, while it escapes quotes within the string, it also _wraps the whole string in quotes_ meaning that we're always causing the problem now instead of only sometimes causing it! 🙃
I tested this with #3703 and you can see that the actions failed.
I tested a few different formats in #3704, you can see the run output here: https://github.com/WordPress/openverse/actions/runs/7649027082/job/20842752948?pr=3704
The last option, `format('{0}', title)`, removed the double quotes but kept the single quotes. Since this is only for a slack reminder and exact character matching isn't necessary and I _absolutely do not want to spend more time figuring out how to escape all quotes in bash so that we can send it back escaped into `GITHUB_ENV` or …

Use format over toJSON for escaping quotes in GHA

---

.pre-commit-config.yaml
documentation/api/guides/https.md
documentation/api/guides/quickstart.md
documentation/api/guides/test.md
documentation/automations/guides/quickstart.md
documentation/catalog/guides/adding_a_new_provider.md
documentation/frontend/guides/analytics.md
documentation/frontend/guides/quickstart.md
documentation/general/deployment.md
documentation/general/general_setup.md
documentation/general/quickstart.md
documentation/ingestion_server/guides/quickstart.md
documentation/ingestion_server/guides/test.md
documentation/ingestion_server/guides/troubleshoot.md
documentation/ingestion_server/reference/task_api.md
documentation/meta/documentation/quickstart.md
documentation/projects/planning.md

This PR fixes an issue identified in #3728 wherein `console` blocks wouldn't use the right syntax highlighting in our documentation unless a preceding `$` was added, but the additional character then made it difficult to copy and paste commands directly into a terminal.
I've corrected all of the other instances of the `console` syntax selection, removed the preceding `$` characters, and added a pre-commit check for the ~~`console` block to ensure that `bash` is used instead. The pre-commit hook is a little janky 😅 I don't love it but it does work 🤷‍♀️~~ The pre-commit hook I added now auto-corrects uses of `console` to `bash`! I tried to add a hook for checking for `$` lines as well, but the bash escaping and multi-line grep that would be required were way too complicated so I just gave …

Remove preceding `$` in documentation code blocks, use bash for code blocks, add pre-commit check for console usage

---

documentation/terms_of_service.md

Spurred on from a discussion here: https://github.com/WordPress/openverse/issues/3564#issuecomment-1919051834
This PR adds a link to the GitHub file history for the ToS to the ToS file itself, in order to allow visitors to view the full context of the changes made to the file.
View the generated documentation link and make sure the rendered file looks good.
<details>
```
Version 1.1
Suite D4700 …
```

Add a link to the GitHub file history on the Terms of Service

---

api/api/views/media_views.py
api/test/media_integration.py
api/test/test_image_integration.py

Fixes #3495 by @Aetherunbound
This PR removes the `lower()` call from the `tag` view in the API. Now, the tags are matched exactly, and the case IS important. For instance, `images/tag/cat` and `images/tag/Cat` and `/images/tag/CAT` will return different results.
I updated the sample data to make it easy to add the integration test for this feature.
I completely forgot that I added the `tag.lower()` to the view, and was expecting to research Elasticsearch to fix this issue :) 
Run `just up` and get the tag view for `"CAT"`: `http://0.0.0.0:50270/v1/images/tag/CAT/`. There should be one result with the excavator. If you search for `"cat"` (lower case), `http://0.0.0.0:50270/v1/images/tag/cat/`, the result should not contain the previous excavator result, only the 14 results with the …

Fix tag casing match in new tag view

---

.github/workflows/draft_releases.yml
.github/workflows/release-app.yml

Fixes double hyphens in drafted release tags
See above.
Confirm the changes make sense according to the issue currently appearing on drafted releases.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```

Fix release tag formatting

---

catalog/dags/common/loader/provider_details.py

Fixes alert in production.
This PR adds the Ralph Rinzler Folklife Archives and Collections subprovider to the Smithsonian DAG, as prompted by the `validate_unit_codes_from_api` step which recently alerted in production.
Run the Smithsonian DAG on main and see that it fails immediately with the error:
> Updates needed to the SMITHSONIAN_SUB_PROVIDERS dictionary*:
New unit codes must be added:
>  - `CFCHFOLKLIFE`
Check out this branch and run the DAG again and see that it passes that step and begins ingesting records.
Note that after the next run of the Smithsonian DAG in production we should check the count of records with this subprovider, and enable the source in production Django admin if there are sufficient records. …

Add Ralph Rinzler Folklife Archives and Collections to Smithsonian subproviders

---

.github/actions/get-changes/action.yml
.github/actions/load-img/action.yml
.github/actions/setup-env/action.yml
.github/workflows-disabled/sentry-release.yml
.github/workflows/ci_cd.yml
.github/workflows/migration_safety_warning.yml
.github/workflows/pr_limit_reminders.yml
.github/workflows/project_thread_update_reminders.yml
.github/workflows/release-app.yml
.github/workflows/renovate.yml

This PR updates the actions that are still running on Node 16 and raising deprecation warnings. They have been updated to their latest versions.
In the case of now-unmaintained action `extractions/setup-just`, I have switched to a different maintained one.
One action `peaceiris/actions-gh-pages` has not been updated to Node v20 yet (PR https://github.com/peaceiris/actions-gh-pages/pull/1067 merged, no release since). There is a possibility to drop it altogether, in favour of official actions https://github.com/actions/upload-pages-artifact and https://github.com/actions/deploy-pages but those that can be a separate issue.
0. Check that CI continues to run. 
1. Refer to the breaking changes for the action from their docs and ensure we're not affected by them. …

Update actions running on deprecated Node v16

---

.github/workflows/pr_ping.yml

Fixes CI failures such as https://github.com/WordPress/openverse/actions/runs/8130926914/job/22219676620
There was a typo in the `pr_ping` script: `repo.repo` instead of `context.repo` was used. This caused the following error:
```
ReferenceError: repo is not defined
Error: Unhandled error: ReferenceError: repo is not defined
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:5:18)
at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:20)
```
The CI should pass? I tried adding this change in the original PR, but it was using the old version of this file. The same is happenning here. Will the CI only start using the updated script after it's merged to main? …

Fix pr_ping typo

---

frontend/src/components/VSearchResultsGrid/VAudioCollection.vue

Fixes the linting error on main.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
```

Fix prettier errors

---

api/conf/settings/security.py

Fixes failed staging deployment caused by the incorrect variable name in the API settings file.
`ALTERNATIVE_DOMAINS` is the correct name, so this PR updates the `security.py` settings file to use this name. It should match what the infrastructure uses, so please check that and confirm it matches.
The other mention of this is in `api/env.docker`, but it was already correct!
Review usage of the environment variables and confirm the API now matches the variables defined by the infrastructure.
<details>
```
Version 1.1
1 Letterman …
```

Correct `ADDITIONAL_DOMAINS` to `ALTERNATIVE_DOMAINS`

---

catalog/dags/providers/provider_api_scripts/cc_mixter.py
catalog/tests/dags/providers/provider_api_scripts/resources/cc_mixter/expected_single_record.json
catalog/tests/dags/providers/provider_api_scripts/resources/cc_mixter/single_item.json

Fixes #3906 by @AetherUnbound
This PR borrows from #3439 and uses a similar mechanism for encoding spaces in all the URLs that get processed.
1. Tests should pass
2. Start the DAG locally with `initial_query_params` set to `{"format": "json", "limit": 100, "offset": 31000}` and ensure it passes
<details>
```
Version 1.1
Suite D4700
By …
```

ccMixter: Handle spaces in URLs

---

documentation/index.md

Really simple change to link the word "Openverse" in the index.md of our docs site.
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Link to Openverse in Documentation site root

---

documentation/projects/proposals/ingestion_server_removal/20240319-project_proposal.md
documentation/projects/proposals/ingestion_server_removal/index.md

Fixes #3935 by @stacimc 
Project proposal for the Ingestion Server Removal project.
I've selected @zackkrida and @AetherUnbound as reviewers for their involvement in the discussion of this project prioritization, and experience with the relevant processes.
[on the Openverse documentation site](https://docs.openverse.org/meta/decision_making/index.html).
The deadline for review of this round is **March 28** …

Add Project Proposal for ingestion server removal project

---

.github/auto-label.json

This PR adds the glob pattern for implementation plans to our auto-labeller so that PRs that add (or modify) implementation plans automatically get applied the "🧭 project: implementation plan" label.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```

Automatically apply the project proposal and IP labels to PRs

---

catalog/dags/providers/provider_api_scripts/wikimedia_commons.py

Fixes #4003 by @AetherUnbound
This PR increases the request timeout for Wikimedia requests from 60s to 120s. See #4003 for motivation.
Run the wikimedia DAG locally and check that it behaves as expected.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

Increase Wikimedia request timeout

---

catalog/dags/common/storage/audio.py
catalog/dags/common/storage/image.py
catalog/dags/common/storage/media.py
catalog/dags/providers/provider_api_scripts/flickr.py
catalog/tests/dags/common/storage/test_audio.py
catalog/tests/dags/common/storage/test_media.py
catalog/tests/dags/providers/provider_api_scripts/resources/flickr/image_data_long_tags_string.json
catalog/tests/dags/providers/provider_api_scripts/resources/flickr/image_data_varying_tags_whitespace.json
catalog/tests/dags/providers/provider_api_scripts/test_flickr.py

Fixes  #3926 by @krysal
In substitution of #3927, this PR uses a `set` to remove duplicates only in the `MediaStore` class, as discussed previously.
This PR also:
- renames variables for denied tags
- adds terms to denied tags lists
- homogenizes the signatures of the `add_item` method of the `ImageStore` `AudioStore` classes
- sorts the list of tags for further consistency between runs
Observe the updated tests, run any dag if desired, and check there are no duplicated tags inserted.
<details>
```
Version 1.1 …
```

Filter out duplicates from `raw_tags` in the catalog v2

---

catalog/dags/database/batched_update/batched_update_dag.py
documentation/catalog/reference/DAGs.md

I forgot how to use the manual recovery for the batched update DAG, and found that the docs could be clarified slightly.
Updates docs.
<details>
```
Version 1.1
Suite D4700 …
```

Clarify Batched Update DAG docs with use cases for failure recovery

---

api/api/utils/asyncio.py
api/api/utils/image_proxy/__init__.py
api/api/utils/image_proxy/extension.py

Related to the recent API outage we had.
This is the main place in our code where we create asyncio tasks that could potentially be the tasks in question in the "Task was destroyed" errors related to the recent outage.
I don't know for sure that these are the problem, but the approach with `do_not_wait_for` is not necessary for our thumbnails endpoint to be sufficiently performant.
Even if this doesn't address whatever the problem was, I'd call this a code quality improvement by simplify the code and removing something potentially arcane and confusing that isn't strictly necessary.
CI should pass. Everything changed here is tested in unit tests.
- [N/A] I ran …

Remove potentially problematic `do_not_wait_for`

---

frontend/src/components/VAudioTrack/VWaveform.vue
frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue
frontend/src/components/VHomeGallery/VHomeGallery.vue
frontend/src/components/VInputField/VInputField.vue
frontend/src/components/VItemGroup/VItem.vue
frontend/src/components/VRadio/VRadio.vue

Related to #4052
This PR replaces the occurrences of `focus:` with `focus-visible:` to fix the problems with double or triple focus rings after updating the `postcss-focus-visible` in #4052.
That PR is blocked on the changes from this PR.
The CI should pass and should not have the problems in the search inputs as in #4052. You can also update the `postcc-focus-visible` as in #4052 and run the tests to check that the VR tests don't have the errors as in that PR.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```

Replace `focus:` with `focus-visible:`

---

utilities/ps.py

Fixes #4045  by @sarayourfriend 
Instead of using `docker ps` and creating a custom tabulated table, `docker compose ps --format json` is used to parse the output.
There are slight adjustments with the `docker compose ps` returned format:
- Containers were originally sorted by recency, they are now returned in alphabetical order
- Container image names originally excluded `docker.io/` (Docker's public repository) but included 3rd party hostnames, now each container name contains hostnames unless it is a `openverse` generated container.
1. Checkout this PR and run `just up`.
2. See the list of services being printed automatically after `up` is complete.
3. Run `just ps`.
4. See the list of services
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_c …

Update print_ps() to use Docker Compose ps JSON output

---

catalog/dags/common/slack.py

Fixes #3987 by @zackkrida
<details>
```
Version 1.1
Suite D4700 …
```

Reduce visual footprint of DAG Alerts in Slack

---

frontend/src/components/VMediaInfo/VCopyLicense.vue
frontend/src/utils/attribution-html.ts

Fixes #553 by @ krysal
There are two issues that contributed to unwanted leading/trailing whitespaces around the attribution copy:
1. The translation used expects a `viewLegal` property, which is empty
2. The interpolated string has leading/trailing whitespace within the parent `<p>` element
1. Visit https://openverse.org/image/0fc8d459-6c59-4370-ae20-cc83c4a64e65 and copy all 3 of the options for attribution. Observe that they each have extra whitespace at the end, and both the HTML and plain text versions also have whitespace at the beginning
2. Run `just f` to start the frontend
3. Visit http://localhost:8443/image/0fc8d459-6c59-4370-ae20-cc83c4a64e65 and perform the same actions in step 1, observing that all 3 cases have no leading/trailing whitespace …

Fix: Remove unwanted leading/trailing whitespaces in attributions

---

automations/js/src/project_thread_updates.js

At some point in the last few months, it seems like the project thread reminder bot stopped working. Note that at the time of posting this PR, https://github.com/WordPress/openverse/issues/3592 was last updated more than 14 days ago but has not received a reminder.
I suspect that this is because we added emojis to the columns, but never added the emojis to the "active development statuses" check. Since this is a [simple list inclusion check](https://github.com/WordPress/openverse/blob/f61eb97dbd85ea266d80a4ecc84b4bc4ed28674f/automations/js/src/project_thread_updates.js#L95), the status always differed and were always skipped.
I can't really easily test this, but hopefully this resolves the issue!
Merge and find out? …

Add emojis to the project thread reminder bot acceptable statuses

---

frontend/feat/feature-flags.json
frontend/test/playwright/e2e/preferences.spec.ts
frontend/test/playwright/visual-regression/pages/pages-single-result.spec.ts

Switches on the additional search views in production
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

Set additional search views to enabled

---

documentation/meta/monitoring/runbooks/nuxt_avg_response_time_above_threshold.md

This PR adds some context and a useful query I (painstakingly 😂) figured out for grouping request count by route for requests that took longer than a certain amount of time. It also adds a historical false positive note for the runbook.
Read the runbook and make sure it makes sense.
<details>
```
Version 1.1
Suite D4700
By making a …
```

Add useful Log Insights query to Nuxt avg response time runbook

---

catalog/tests/utilities/dag_doc_gen/test_dag_doc_generation.py
catalog/utilities/dag_doc_gen/dag_doc_generation.py
documentation/catalog/reference/DAGs.md
documentation/projects/proposals/data_normalization/20240227-implementation_plan_catalog_data_cleaning.md

Fixes #3207 by @AetherUnbound 
`dag_doc_generation.py` no longer produces documentation for DAGs with markdown that is identical to what it has seen before (iterating in alphabetical order by type). For example, "Audio" DAGs have docs generated, "Image" DAGs do not since they come after "Audio" in the alphabet. Same for "Prod" vs. "Staging" and "Provider" vs. "Provider Reingestion." In the `# Provider` section, it will still generate a row for these duplicate DAG docs, but will link to the common doc.
All tests pass.  
Run the documentation server locally and make sure the updated DAG documentation makes sense.
<details>
``` …
```

Do not reproduce reingestion workflow documentation

---

docker-compose.yml

This PR removes the `-U` and `-d` params from the healthcheck as they are not required. The [documentation notes](https://www.postgresql.org/docs/current/app-pg-isready.html) say that the arguments are not required but incorrect arguments will be logged.
<details>
```
Version 1.1
Suite D4700 …
```

Remove unnecessary params from healthcheck

---

documentation/projects/planning.md

Follow up to [a discussion that occurred in the Make WP Slack](https://wordpress.slack.com/archives/C02012JB00N/p1713800177722589?thread_ts=1713799829.110769&cid=C02012JB00N) this morning, this adds another possible option for why a project might be in the "On Hold" column.
<details>
```
Version 1.1
Suite D4700 …
```

Add more cases for "On Hold" project state

---

api/pdm.lock
api/pyproject.toml
packages/python/openverse-attribution/pyproject.toml

This PR makes some corrections to the `pyproject.toml` files in the API and in the `openverse-attribution` package.
- The API name has the `openverse-` prefix (which is the Python equivalent of the `@openverse/` namespace used by our JS packages.
- The `openverse-attribution` package as a version of 0.0.0 which matches the version from `package.json` in our other projects and subprojects.
Nothing to test here.
<details>
```
Version 1.1
Suite D4700 …
```

Refine Python package names and versions

---

api/pdm.lock
api/pyproject.toml

Fixes #4185 by @zackkrida 
This PR adds `setuptools` as a dev-dependency of the API so that it will be present whenever `pgcli` needs it.
Try to reproduce #4185 on this branch. You should not be able to do so.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```

Install `setuptools` needed by `pgcli`

---

catalog/dags/common/cloudwatch.py
catalog/dags/common/sensors/utils.py
catalog/dags/common/slack.py
catalog/dags/common/storage/media.py
catalog/dags/database/batched_update/batched_update_dag.py
catalog/dags/database/staging_database_restore/staging_database_restore.py
catalog/dags/database/staging_database_restore/staging_database_restore_dag.py
catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
catalog/dags/providers/provider_api_scripts/auckland_museum.py
catalog/dags/providers/provider_api_scripts/cc_mixter.py
catalog/dags/providers/provider_api_scripts/europeana.py
catalog/dags/providers/provider_api_scripts/finnish_museums.py
catalog/dags/providers/provider_api_scripts/flickr.py
catalog/dags/providers/provider_api_scripts/freesound.py
catalog/dags/providers/provider_api_scripts/inaturalist.py
catalog/dags/providers/provider_api_scripts/jamendo.py
catalog/dags/providers/provider_api_scripts/justtakeitfree.py
catalog/dags/providers/provider_api_scripts/metropolitan_museum.py
catalog/dags/providers/provider_api_scripts/nappy.py
catalog/dags/providers/provider_api_scripts/phylopic.py
catalog/dags/providers/provider_api_scripts/rawpixel.py
catalog/dags/providers/provider_api_scripts/science_museum.py
catalog/dags/providers/provider_api_scripts/smithsonian.py
catalog/dags/providers/provider_api_scripts/smk.py
catalog/dags/providers/provider_api_scripts/stocksnap.py
catalog/dags/providers/provider_api_scripts/time_delineated_provider_data_ingester.py
catalog/dags/providers/provider_api_scripts/wordpress.py
catalog/dags/retired/providers/provider_api_scripts/thingiverse.py
catalog/dags/retired/providers/provider_api_scripts/walters.py
documentation/catalog/reference/DAGs.md

Fixes #4173 by @obulat 
This MR seeks to make links in all docstrings in the `catalog/dags/` folder correctly render as hyperlinks in the documentation. This is achieved by wrapping links with `<` `>` in the form `<https://{link}>`.
This is a non logic change and can be visually observed in the docs through the link: [/catalog/reference/DAGs.html](/catalog/reference/DAGs.html)
1. Run `just documentation/live`
1. Navigate to http://localhost:50230/catalog/reference/DAGs.html to observe the new links
1. (Optionally) Run `just c` to start the catalog and navigate to http://localhost:9090 and view various DAG markdown files to ensure the links still look correct
<details> …

Make links in docstring display as hyperlinks in docs site

---

frontend/src/server-middleware/robots.js

Fixes #4204 by @zackkrida
Fixes our robots.txt file to correctly block all of the translated routes we should have been previously. 
<details>
```
Version 1.1
Suite D4700 …
```

Add translated routes to block to robots.txt

---

documentation/Pipfile
documentation/Pipfile.lock
documentation/conf.py

Fixes #4208 by @AetherUnbound 
Automatically convert unformatted urls in docstrings to hyperlinks using the `linkify` MyST extension.
This can be observed by: 
- Removing Sphinx's existing hyperlinking syntax from any url in a DAG's docstring. This is the leading `<` and trailing `>` wrapping URLs.
- Note the affected DAG docstring
- Regenerate the documentation file(`DAG.md`) by running `just catalog/generate-docs`
- Run `just documentation/live` and navigate to (http://localhost:50230/catalog/reference/DAGs.html)[http://localhost:50230/catalog/reference/DAGs.html]
You should now still see the docstring link you had earlier removed the hyperlinking syntax from still correctly render as hyperlink due to MyST's `linkify` extension.
P.S: This also applies for Airflow docs. …

Automatically convert URLs to hyperlinks using `linkify` extension

---

.github/filters.yml
.github/workflows/ci_cd.yml
justfile
packages/python/openverse-attribution/justfile
packages/python/openverse-attribution/pyproject.toml

Fixes #4167 by @dhruvkb
This PR adds CI jobs to run test and build for Python subpackages in `pacakges/python/*`.
Since this is an addition to the CI workflow, a passing CI pipeline should be adequate.
<details>
```
Version 1.1
Suite D4700 …
```

Run checks for Python packages in CI

---

docker/plausible/env.docker
setup_plausible.sh

Fixes #4217 by @obulat 
Replace sample secret key for plausible with a more obviously safe value.
This change can be observed by taking a look at the value of `SCRET_KEY_BASE` environment variable in `docker/plausible/env.docker`
The local development `sha256` key hash for plausible using this new value has also been updated in `setup_plausible.sh` 
<details>
```
Version 1.1
Suite D4700 …
```

Replace sample secret key for plausible with a more obviously safe value

---

frontend/package.json
package.json
pnpm-lock.yaml

This PR updates node to the LTS version.
The CI should pass, and the frontend should run as usual, without any additional warnings.
<details>
```
Version 1.1
Suite D4700
By making a …
```

Update Node to v.20

---

api/conf/settings/logging.py

Fixes #4347 by @AetherUnbound 
This PR updates a leftover use of the "console" logger to "console_structured" allowing the `DJANGO_DB_LOGGING` setting to work again.
You should not be able to repro the linked issue on this branch.
<details>
```
Version 1.1
Suite D4700 …
```

Fix stray use of `console` logger to `console_structured`

---

frontend/package.json
pnpm-lock.yaml

Fixes #4367 by @zackkrida 
Explicitly adds `caniuse-lite` as a devDependency to the frontend so we can keep it up to date. 
Make sure `just frontend/run dev` works and tests pass.
<details>
```
Version 1.1
Suite D4700 …
```

Install caniuse-lite as a frontend dev dependency

---

frontend/src/data/api-service.ts

Fixes #2904 by @dhruvkb 
Fixes #2766 by @zackkrida 
This PR updates the `api-service` to only set the `User-Agent` on the server.
Run the app and make some searches. You should not longer see the following error messages in the console:
<details>
```
Version 1.1
Suite D4700 …
```

Only set the user-agent header on the server

---

packages/python/openverse-attribution/README.md

I was responding to an email and noticed that the link to the documentation 404'd. This PR updates the link in the README for the package.
Check to make sure that the link is correct.
<details>
```
Version 1.1
Suite D4700 …
```

Update link to openverse-attribution documentation

---

README.md

This PR updates the banner image URL in `README.md`. Apparently the move of branding assets inside docs broke a lot of references #4073. I'm partly responsible for this, I should've done a more thorough review of the PR to identify where these assets were being used. A broken image link in the `README.md` looks very bad.
<details>
```
Version 1.1
Suite D4700
San …
```

Fix path to banner in `README.md`

---

justfile

This PR adds recipes for cleaning up dependencies/packages such as Node modules and Python virtualenvs. Good for recovering from a nuked setup.
These recipes, without a final "true" will do a dry-run and only list the folders.
<details>
```
Version 1.1
Suite D4700 …
```

Add recipes for cleaning up

---

.gitignore

During the course of using the `ov` development environment, I noticed a `v8-compile-cache-0/` folder in the root of the repository. This PR ignores it, I have not investigated why it is created and how it can be avoided.
<details>
```
Version 1.1
Suite D4700
license …
```

Ignore v8 compile cache

---

frontend/.gitignore

This PR adds the Nuxt 3 build and coverage folders to gitignore.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```

Add Nuxt 3 folders to gitignore

---

documentation/api/guides/quickstart.md
documentation/frontend/guides/quickstart.md
documentation/general/quickstart.md
documentation/ingestion_server/guides/quickstart.md
documentation/meta/documentation/quickstart.md

Fixes #4329 by @zackkrida 
Update our quickstart guides to recommend blobless cloning, saving contributors much data and time. Success!
<details>
```
Version 1.1
Suite D4700
By …
```

Update docs to recommend blobless cloning strategy

---

.github/workflows/ci_cd.yml
setup_plausible.sh

Fixes #4400 by @obulat 
A step in `setup_plausible.sh` uses `encode` which is a method of the `pgcrypto` extension to do a `sha256` encoding of the secret key and API key before insertion into the database. Attempting to directly call `encode` without first installing or verifying if the parent extension is installed causes this step to fail. This PR adds a `CREATE EXTENSION IF NOT EXISTS` statement before the insertion step to prevent this.
Running `just init` should successfully set up and bring up the services.
<details> …

Ensure required DB extension is installed before attempting to setup plausible

---

documentation/general/contribution/becoming_a_committer.md

Small PR to add a link to our Committer announcements on the "Become a Committer" documentation page.
View the rendered documentation preview
<details>
```
Version 1.1
Suite D4700
By …
```

Add a link to the committer announcements in the committer docs

---

catalog/tests/utilities/media_props_gen/test_md.py
catalog/utilities/media_props_gen/docs/media_props.md
catalog/utilities/media_props_gen/docs/postamble.md
catalog/utilities/media_props_gen/generate_media_properties.py
catalog/utilities/media_props_gen/helpers/md.py
documentation/meta/media_properties/catalog.md

Fixes #2187 by @obulat
This PR adds the media properties documentation to the catalog docs.
I am not sure about `update_on`:  What is the difference between `last_sync_with_source` and `updated_on`?
Read through the descriptions and confirm that they are accurate and full.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```

Add catalog media properties documentation

---

api/api/admin/media_report.py

Fixes #4439 by @sarayourfriend 
This PR handles tags without the field "provider" from raising errors in the media report view, using the fix mentioned in the issue description.
You should not be able to reproduce #4439 when this PR is checked out.
<details>
```
Version 1.1
Suite D4700 …
```

Handle tags without provider in media admin view

---

.github/workflows/pr_automations.yml

This PR fixes the project automations broken by my previous PR #4438.
Please read the script carefully to spot any syntax errors.
<details>
```
Version 1.1
Suite D4700
By making a …
```

Fix incorrect brackets in PR automation

---

.github/workflows/pr_automations.yml

Fixes the PR automations so that artifacts are saved with the correct names.

Update pr_automations.yml with missing character

---

documentation/frontend/reference/testing_guidelines.md

Fixed the broken link for Jest docs, as the correct link is https://jestjs.io/docs/getting-started
<details>
```
Version 1.1
Suite D4700
By …
```

Jest docs broken link fixed

---

documentation/frontend/reference/playwright_tests.md

The current link is broken, so replacing it with the link mentioning the steps to run the Codegen.
<details>
```
Version 1.1
Suite D4700
By …
```

Updated Playwright Codegen broken link

---

documentation/general/quickstart.md

Fixes #4479 by @dhruvkb
I ordered the links alphabetically and added the catalog start guide link
<details>
```
Version 1.1
Suite D4700 …
```

Order quickstart links, add missing catalog link

---

docker/dev_env/run.sh

Fixes #4468 by @sarayourfriend 
Fixes #4469 by @sarayourfriend 
Fixes both issues by first checking if the executable exists on the host. That solves the pdm issue and also the issue with needing to silence errors when running `pnpm`. Corepack logs to stderr, so redirecting it to /dev/null silences its output. To fix that (and because now we know pnpm exists), we can stop redirecting stderr from `pnpm store path` and let Corepack's message show for the user to interact with.
Run `corepack cache clean` locally and confirm the `pnpm` command is now interactive. You'll need pnpm installed with corepack to test that, of course.
To test the PDM changes, uninstall PDM locally, and then `ov just` should no longer log the command not found error for `pdm`.
- [N/A] I added or updated tests for the …

Fix ov corepack and pdm existence issues

---

documentation/general/contribution/current_maintainers.md

Update current_maintainers.md to add @zackkrida

---

ov

This PR
- adds `|| true` to clean commands to make them pass when a particular container, image or volume does not exist.
- I needed this today to clean my volume but I had already removed the container.
- changes `kill` to `stop` to allow the commands to gracefully exit.
- Use of `kill` lead to a stuck Git process on my computer.
- uses the full form of the commands.
- This one is just personal preference but I find `docker image rm` clearer than `docker rmi`.
<details> …

Make `ov clean` work when a container, image or volume does not exist

---

.github/sync.yml

PR #4504 was able to fix the permissions issues, but it looks like we aren't actually syncing some of the dependencies for the `pr_automations_init.yml` workflow to the infrastructure repository which uses it now, which means that it can't find what to run (from [this run](https://github.com/WordPress/openverse-infrastructure/actions/runs/9605721006/job/26493877256)):
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/openverse-infrastructure/openverse-infrastructure/.github/actions/get-changes'. Did you forget to run actions/checkout before running your local action?
```
This PR should address this by syncing the `get-changes` action _and_ the `filters.yml` file which is also necessary for running that action.
We'll have to merge this, but then we …

Sync the dependencies for PR automation init workflow to infra repo

---

docker/dev_env/Dockerfile

This PR adds tools jq and HTTPie that I use frequently during development to the `ov` container. I believe other people in the team will appreciate these tools. On that note, we should define some criteria for what tools should be included in the dev-env image.
0. Build a new `ov` image using `ov build`.
1. Get rid of the old `ov` container using `ov stop && docker container rm openverse-dev-env`.
2. Run `ov bash` to get a fresh instance.
3. Run `http` or `jq` or both:
<details> …

Add dev tools jq and HTTPie to `ov`

---

catalog/dags/providers/provider_api_scripts/inaturalist.py
catalog/tests/dags/common/loader/test_s3.py
catalog/tests/dags/providers/provider_api_scripts/test_inaturalist.py
docker/minio/env.template
docker/minio/load_to_s3_entrypoint.sh

Fixes #4494 by @krysal 
This PR adds the iNatualist bucket to the defaults and passess the correct variables to put the test S3 files.
1. `just catalog/recreate`
2. Go to http://localhost:5011/browser/inaturalist-open-data and see the files.
<details>
```
Version 1.1
Suite D4700 …
```

Fix placing test S3 data into MinIO

---

frontend/src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
frontend/src/components/VMediaInfo/VMetadata.vue
frontend/src/components/VMediaInfo/VRelatedMedia.vue
frontend/src/composables/use-match-routes.ts
frontend/src/pages/audio/_id/index.vue
frontend/src/pages/image/_id/index.vue

Fixes #4522 by @krysal
Small fixes to several of these cases. The main one that Sentry reported is in the `src/composables/use-match-routes.ts` file.
Not sure. Check if the logic makes sense to you.
<details>
```
Version 1.1
Suite D4700 …
```

Fix possible TypeError when accessing properties of `route.value`

---

catalog/dags/maintenance/decode_and_deduplicate_image_tags.py

Follow up to #4475.
After running in the live Airflow, it fails with this when trying to create the function:
> psycopg2.errors.UndefinedObject: language "plpython3u" does not exist
It works locally, not sure why, but the fix is easy and well documented: just create the extension if it doesn't exist:
https://www.postgresql.org/docs/13/plpython.html and https://www.postgresql.org/docs/13/sql-createextension.html for reference.
Marked high because the DAG is broken until this is fixed.
Run the DAG locally and confirm it works.
- [N/A] I ran the DAG documentation generator (`./ov just catalog/generate-docs` for catalog
PRs) or the media properties generator …

Ensure plpython3u exists in live db when using it

---

.gitignore
frontend/justfile
package.json

Removes the pnpm and volta settings that are no longer necessary.
`volta` is replaced with `corepack` which is [built-in to Node.js](https://nodejs.org/docs/latest-v20.x/api/corepack.html#enabling-the-feature), reliable, popular among the team and is also present in [environments like](https://github.com/WordPress/openverse/blob/cda4f55a423fe1e95001f97f13112f867010f152/docker/dev_env/Dockerfile#L61) ov that are on track to being the default dev environment
`engines.pnpm` [field](https://github.com/WordPress/openverse/blob/cda4f55a423fe1e95001f97f13112f867010f152/package.json#L19) can also be dropped because all known usages use the `packageManager` field.
The issue was reported by @dhruvkb 
Set the priority to high because it would be nice to merge into main before the other dependency …

Remove volta and engines.pnpm settings

---

api/Dockerfile
catalog/Dockerfile
docker/upstream_db/Dockerfile
frontend/Dockerfile
frontend/Dockerfile.nginx
indexer_worker/Dockerfile
ingestion_server/Dockerfile
utilities/load_testing/Dockerfile

This PR stop receiving the following warnings during Docker builds.
- [FromAsCasing](https://docs.docker.com/reference/build-checks/from-as-casing/)
```
'as' and 'FROM' keywords' casing do not match
```
- [LegacyKeyValueFormat](https://docs.docker.com/reference/build-checks/legacy-key-value-format/)
```
"LABEL key=value" should be used instead of legacy "LABEL key value" format
```
- [UndefinedVar](https://docs.docker.com/reference/build-checks/undefined-var/)
```
Usage of undefined variable '$PYTHONPATH'
```
0. See the logs for this CI + CD run: https://github.com/WordPress/openverse/actions/runs/9718038475/job/26825080240
1. For each of the "Build Docker images (image name)" jobs, look at the "Build image `image name`" step logs.
2. Near the end of the logs, spot the warnings in yellow. …

Fix Docker build warnings

---

documentation/projects/proposals/rekognition_data/20240530-implementation_plan_augment_catalog_with_rekognition_tags.md

Fixes #4642 by @AetherUnbound
This PR rephrases our policy around demographics in the catalog Rekognition data IP to be explicit about considering every label that falls into one of the latter demographic categories on a case-by-case basis. This allows us to retain certain labels if they'll help relevancy without making a blanket policy for all labels in these categories at this time.
<details>
```
Version 1.1 …
```

Clarify policy around which demographics to exclude in Rekognition IP

---

justfile

Fixes #4668 by @AetherUnbound
This PR fixes an issues which was causing an infinite loop when printing all of the available `just` recipes. `docker/nginx` no longer exists (removed in #4605), and so that line was failing and causing the command to restart over and over again. This now appropriately prints all of the available recipes.
Check out the branch and run `ov just`. On `main` this would loop, but on this branch it should print everything once.
<details>
``` …
```

Remove nonexistent directory from `just` recipe display list

---

frontend/package.json
frontend/src/components/VExternalSearch/VExternalSearchForm.vue
frontend/src/components/VModal/VModal.vue
frontend/src/components/VModal/VModalContent.vue
pnpm-lock.yaml

Fixes #4681 by @obulat
This PR updates Vue to the latest version, removes the teleports hotfix (the `v-if="visible" condition on the root component).
It also converts the `VModal` component to script setup.
The `VExternalSourcesForm` component was using the slot props incorrectly, and this was caught by TypeScript check.
<details>
```
Version 1.1
Suite …
```

Update Vue and remove modal hotfix

---

frontend/nuxt.config.ts
frontend/src/constants/disallowed-bots.ts

@obulat some tiny changes here to add documentation and improve the reading flow of the Nuxt configuration.

Nuxt.config documentation improvements

---

frontend/test/playwright/utils/components.ts
frontend/test/playwright/visual-regression/pages/pages.spec.ts

Fixes #4699 by @obulat
Improves the flaky test by first waiting for the URL, and then waiting for the `h1` element.
Also extracts reusable functions to get the elements.
The CI (and especially `visual-regression/pages/pages.spec.ts:52:9 › layout color is set correctly › screen at breakpoint lg with width 1024 › change language on homepage and search`) should pass.
I rebased #4685, which was failing CI due to this test, onto this PR, and now CI is green there.
<details> …

Fix the flaky pages test

---

.github/workflows/pr_limit_reminders.yml

We've recently changed the maintainer requirements around reviews to only require 1 review for merging instead of two. As such, the computation done for estimated number of reviewers for the PR limit reminder bot was inaccurate. This PR updates that calculation, as well as increasing the number of PRs before a ping from 3 to 5. The reason for this is that the total number of reviews for 3 PRs with 2 reviewers each was 6. With 1 reviewer each, 5 seemed like a sensible limit before pinging again.
Merge and see!
<details> …

Increase PR count for PR limit bot reminder to 5

---

ingestion_server/ingestion_server/cleanup.py

Fixes #700 by @obulat
This PR removes the URL cleanup from the ingestion server data refresh.
Delete the local index if you have any using ElasticVue.
Run `ov just init` to run the data refresh locally. It should work as expected.
<details>
```
Version 1.1
Suite D4700 …
```

Remove the url cleanup steps from data refresh

---

api/conf/settings/sentry.py

Fixes #https://github.com/WordPress/openverse/issues/4758 by @sarayourfriend 
See issue for rationale.
N/A. CI should pass, the app should run, but there's no testing to do for this. We set it to 0 in live environments.
<details>
```
Developer …
```

Use default of 0 for SENTRY_SAMPLE_RATE

---

catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
catalog/dags/providers/provider_api_scripts/science_museum.py

Fixes #4710 by @AetherUnbound
Fixes #4712 by @AetherUnbound
This PR adds retries on all requests for both the Science Museum and Brooklyn Museum DAGs (see the issues for motivation).
> [!WARNING]
> This is based on #4663 and that will need to be merged (and deployed) before this can be merged
Tests and CI should pass, you can also try running the DAGs locally to make sure the function as expected!
<details>
```
Version 1.1
Copyright (C) …
```

Add request retries for 5XX errors on Science Museum & Brooklyn Museum

---

frontend/tailwind.config.ts

Fixes #4755 by @obulat
This PR fixes the incorrect tailwind CSS variable name to fix the focus outline colors for buttons.
Run the app and navigate it using the keyboard. You should see a pink outline on every active tabbable element, and should not see blue outline or no outline as in the video from the linked issue.
<details>
```
Version 1.1
Suite D4700 …
```

Fix the focus outline for buttons

---

documentation/projects/proposals/rekognition_data/20240320-project_proposal_rekognition_data.md

See this discussion for motivation: https://github.com/WordPress/openverse/issues/431#issuecomment-2288265332
As the title notes, this PR adds an explicit note to the project proposal that we intend to keep the Rekognition data bucket in perpetuity after the project is complete.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Add a note about keeping the bucket to the Rekognition project proposal

---

catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
catalog/tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py

Part of #4717 by @obulat 
Adds a validation step for image file types in the Wikimedia provider DAG. I considered making this validation global (in the MediaStore class), but we must be really sure of the file types that will be accepted as valid on each media type (maintaining the `EXTENSIONS` dictionary up to date or validated in some way). So, for now, I limited the scope to Wikimedia images, which have been the most problematic.
Run the Wikimedia DAG and check the filetypes in the upstream database.
<details>
```
Version 1.1
1 …
```

Filter `filetype` of Wikimedia's images

---

catalog/dags/providers/provider_reingestion_workflows.py

Some of the failures for the Wikimedia reingestion DAG are due to timeouts, as the reingestion DAG has a significantly lower `pull_data_timeout` (90 minutes) than the regular ingestion DAG (12 hours).
This PR increases the timeout to 4 hours. When I look through previous _ingestion_ runs I'm not seeing any that take longer than 2 hours in the last year, so hopefully this increase is enough to avoid the timeouts. At the same time, we do need to be a little cautious of increasing timeouts all the way to 12 for a reingestion DAG, as ideally the entire DAG would complete within 24 hours. It's not _critical_ that it do so, especially if it's only long-running every now and then, but this is something we'll want to check back in on.
PRs) or the media properties generator (`ov just …

Increase Wikimedia reingestion pull_data timeout

---

frontend/src/utils/get-additional-sources.ts

The external sources link for Google Image search on the Openverse frontend has been broken, apparently. This PR adjusts to use Google's current query params. 
To clarify, the search was working but results were _not_ filtered to only include CC-licensed works.
1. Visit https://openverse.org/search/image?q=there-are-no-results-for-this-dfagsfasD
2. Click the "Google Images" button
3. Observe that the results are not correctly filtered to CC-licensed works only.
4. Repeat locally on this PR with `ov just frontend/run dev`
5. Observe results are filtered correctly. …

Fix Google Images external source link

---

ov

This PR adds `ov just install` to the list of commands run when `ov init` is kicked off. Our common advice for tackling issues is `ov clean && ov init`, but this still doesn't cover the case for truly initializing everything that's necessary to get off the ground with the project (see #4770).
1. Run `ov clean && ov init`
2. Run `ov just documentation/live` and see that the command runs correctly the first time
<details>
```
Version 1.1 …
```

Run `ov just install` as part of `ov init`

---

frontend/src/components/VAudioTrack/VAudioControl.vue
frontend/src/components/VAudioTrack/VAudioTrack.vue
frontend/src/components/VAudioTrack/VGlobalAudioTrack.vue
frontend/src/components/VAudioTrack/VWaveform.vue
frontend/src/components/VAudioTrack/layouts/VBoxLayout.vue
frontend/src/components/VAudioTrack/layouts/VFullLayout.vue
frontend/src/components/VAudioTrack/layouts/VGlobalLayout.vue
frontend/src/components/VAudioTrack/layouts/VRowLayout.vue
frontend/src/components/VIcon/VIcon.vue

This PR converts the components related to `VAudioTrack`.
There following conversions are done:
- remove defineComponent and returns
- convert props to defineProps with withDefaults if necessary
- the types of `featureNotices` were incorrect, fixed to `string` instead of `boolean`.
The CI should pass
<details>
```
Version 1.1 …
```

Convert audio track components

---

frontend/src/components/VMediaInfo/VByLine/VByLine.vue
frontend/src/components/VMediaInfo/VByLine/VScroller.vue
frontend/src/components/VMediaInfo/VByLine/VSourceCreatorButton.vue
frontend/src/components/VMediaInfo/VCollapsibleTagSection.vue
frontend/src/components/VMediaInfo/VCopyLicense.vue
frontend/src/components/VMediaInfo/VGetMediaButton.vue
frontend/src/components/VMediaInfo/VLicenseTabPanel.vue
frontend/src/components/VMediaInfo/VMediaInfo.vue
frontend/src/components/VMediaInfo/VMediaLicense.vue
frontend/src/components/VMediaInfo/VMediaReuse.vue
frontend/src/components/VMediaInfo/VMediaTags.vue
frontend/src/components/VMediaInfo/VMetadata.vue
frontend/src/components/VMediaInfo/VMetadataValue.vue
frontend/src/components/VMediaInfo/VRelatedMedia.vue
frontend/src/components/VMediaInfo/VSourceProviderTooltip.vue
frontend/src/components/VSafeBrowsing/VSafeBrowsing.vue
frontend/src/components/VSafetyWall/VSafetyWall.vue
frontend/src/components/VScrollableLine.vue

This PR converts the components used on the single result pages to `script setup`.
There following conversions are done:
- remove `defineComponent` and returns
- convert props to `defineProps` with `withDefaults` if necessary
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```

Convert single result page components

---

documentation/general/general_setup.md

Officially recommend OrbStack for mac users, due to issues some maintainers have reported with Docker Desktop on mac.
View docs and see if they look good. Consider suggestions for improving the wording.
<details>
```
Version 1.1
Suite D4700 …
```

Update documentation to recommend OrbStack for mac users

---

frontend/src/components/VContentSwitcher/VSearchTypePopover.vue
frontend/src/components/VItemGroup/VItem.vue
frontend/src/components/VLicense/VLicenseElements.vue
frontend/src/components/VPopover/VPopover.vue
frontend/src/components/VPopover/VPopoverContent.vue
frontend/src/constants/z-indices.ts
frontend/src/types/provides.ts

This PR converts the components touched by #4800 to script setup, to make that PR easier to review, and to prevent further merge conflicts.
The CI should pass. The popovers (pages menu, content switcher on desktop) and license explanation popover should work correctly.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```

Convert components for license explanation modal

---

documentation/meta/release_and_deployment/index.md

The deployment guides for the API and Frontend link to the in-depth documentation for how to do rollbacks. When a rollback is needed in production, it's helpful to have a very quick summary of the steps. I've added a quick Tip section to the docs at the top of the rollback section.
View docs, suggest any improvements for clarity.
<details>
```
Version 1.1 …
```

Add Quick Tip section to rollback docs

---

documentation/projects/proposals/rekognition_data/appendix/appendix.md
documentation/projects/proposals/rekognition_data/appendix/rekognition_labels.md
documentation/projects/proposals/rekognition_data/index.md

Fixes #4643 by @AetherUnbound
This PR adds an explicit list of excluded, corrected, and all reviewed labels from the Rekognition dataset to the project's appendix on the documentation set. This is intended to be an exhaustive record of the discussion resulting from #4643.
Check out the rendered pages and see if it makes sense!
<details>
```
Version 1.1 …
```

Add reviewed Rekognition labels to project appendix

---

frontend/src/app.vue
frontend/src/components/TableSortIcon.vue
frontend/src/components/VAudioTrack/VWaveform.vue
frontend/src/components/VButton.vue
frontend/src/components/VHeader/VSearchBar/VSearchButton.vue
frontend/src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue
frontend/src/components/VModal/VModalContent.vue
frontend/src/components/VSkeleton/VAudioTrackSkeleton.vue
frontend/src/components/VSkeleton/VBone.vue
frontend/src/constants/favicons.ts
frontend/src/error.vue

Fixes some problems with the dark mode.
The error page is a separate entry point that doesn't use `app.vue`, so the dark mode detection and set up should run there, too. The search button border is now transparent for dark theme, and black for the light one.
Table sort icons were the same color, and the currently sorted column wasn't discernible.
Global player waveform background wasn't updated for the dark mode.
The loading skeleton colors are updated for the dark mode.
Check that in the dark theme the listed issues are fixed, and not broken in the light one. …

Fix dark theme grays

---

frontend/feat/feature-flags.json

Fixes #4306 by @zackkrida 
Adds a new feature flag to the frontend for toggling the visiblity of the dark mode UI toggle. Currently this doesn't actually do anything.
Confirm the presence of the new checkbox on the /preferences page locally after `ov just frontend/run dev`	
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Add feature flag to display the dark mode UI toggle

---

frontend/src/stores/media/index.ts
frontend/src/types/analytics.ts
frontend/test/unit/fixtures/audio.js
frontend/test/unit/specs/stores/media-store.spec.ts
frontend/test/unit/specs/stores/provider.spec.ts
frontend/test/unit/specs/stores/search-store.spec.ts
frontend/test/unit/specs/stores/single-result-store.spec.ts

Related to #4838 by @zackkrida 
This PR converts a few semi-random frontend store tests to use TypeScript.
- Review that tests pass and that changes mostly look okay.
<details>
```
Version 1.1
Suite D4700 …
```

Convert some store unit tests to TypeScript

---

.github/workflows/ci_cd.yml
.github/workflows/discussion_ping.yml
.github/workflows/pr_limit_reminders.yml
.github/workflows/pr_ping.yml
.github/workflows/renovate.yml

In the repository we have conventionally only specified the major version for our actions (specifically for actions that are stable, v1+). Since the Slack actions are in that category, we can drop the minor and patch versions and let the newer releases be used automatically.
This will reduce the changes in future "Update workflows" PR (like [this one](https://github.com/WordPress/openverse/pull/4845)).
<details>
```
Version 1.1
Copyright …
```

Only specify major version for post-v1 actions

---

catalog/dags/providers/provider_api_scripts/science_museum.py

We are continuing to see DAG runs fail after #4710. Since this is a DAG that runs monthly, we can give these requests a lot more time to resolve before we allow them to fail.
<details>
```
Version 1.1
Suite D4700
license document, but changing it …
```

Increase Science Museum backoff timeout from 2 minutes to 30 minutes

---

frontend/src/stores/ui.ts
frontend/test/unit/specs/stores/ui-store.spec.ts
utilities/load_testing/Dockerfile

This PR fixes the current frontend memory leak by addressing an issue with the initialization of the ui store. For increased ease of testing, I created an object outside of the store to capture the default state (so it could be imported into the test spec) and then spread the properties of that object into the store's state object. Apparently, that is very bad. I'd like to figure out exactly why, so I'll try and look at Pinia's internals tomorrow. It might be very obvious to someone else. 
This should be fairly straightforward to prove it works but there are many steps. You also might need the change I made locally to `utilities/load_testing/Dockerfile` before running these steps, if you're not able to pull the load testing Docker image. 
- With the `main` branch checked out, build the …

Fix frontend memory leak

---

.github/workflows/renovate.yml

Fixes #4870 by @obulat
This PR reverts the change in #4848 for Renovate only, always specifying the fully-qualified versions of the GitHub actions.
Should be okay since this is a return to the previous state. Once this is merged, the renovate action should run successfully.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Revert minor version removal from Renovate action

---

api/nginx/nginx.conf.template
frontend/src/stores/media/related-media.ts

Fixes #4890 by @sarayourfriend 
As indicated in the issue, this PR changes the frontend to use `useApiClient` for related media requests to ensure the API token is sent.
I've also gone ahead and removed some unnecessary JSON log properties from the Nginx API logs, which have been unnecessary since #4635.
CI should pass, no other testing is needed. …

Ensure correct API usage for frontend related media requests

---

api/api/views/oauth2_views.py

While investigating certain strange request patterns today, I've found that it would be nice to be able to see the client application information when one creates a token. This isn't available now because we only log `client_application_authenticated` when the client _authenticates_ (in the authentication area), and clients do not "authenticate", strictly speaking, and at the very least don't go through the authentication flow, when they request a token. In any case, they do gain authorisation, and the oauth2_provider has a signal which provides the `AccessToken` object, which we can use to easily log in that case.
This will make it easier to audit what applications are doing things like sending heaps of token requests and nothing else that we can see from that source (to give a real …

Log when API client apps authorize

---

documentation/changelogs/catalog/2024.09.09.23.00.57.md

Doing this manually due to failure in https://github.com/WordPress/openverse/actions/runs/10782697007/job/29903186115 fixed by https://github.com/WordPress/openverse/pull/4899; but we do not need to create a new release just for the changelog file, so this works!
N/A.
<details>
``` …
```

Add catalog changelog

---

documentation/general/general_setup.md

This PR fixes some bugs in the Markdown of the general setup guide such as broken links and unmatched backticks <code>`</code>.
Check that the markup is now fixed, with links working again and code blocks highlighted appropriately.
<details>
```
Version 1.1
Suite D4700 …
```

Fix markup in the general setup guide

---

frontend/test/playwright/e2e/search-navigation.spec.ts

Fixes #4981 by @sarayourfriend
This PR adds a wait for URL to ensure that the page has fully loaded before checking the test conditions with expect.
<details>
```
Version 1.1
Suite D4700 …
```

Fix flaky test

---

README.md
documentation/general/contribution/current_maintainers.md

This PR updates our current maintainers document and moves the names of folks who are no longer members to the root `README.md` under the "Acknowledgements" section.
I tried to be careful so as to not downplay their contributions but improvements to the copy are welcome.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```

Move team alumni from current maintainers to `README.md`

---

.github/actions/setup-env/action.yml
.pre-commit-config.yaml

This PR
- bumps the Python version to 3.12.
This is the Python version required by Vale in the `pyproject.toml` file.
- updates the stage in pre-commit config from "push" to "pre-push".
This should resolve the warning regarding deprecated stage names.
Collectively, this should restore CI functionality which is currently broken.
<details>
```
Version 1.1 …
```

Bump installed Python and fix stage name

---

frontend/src/components/VButton.vue
frontend/src/components/VContentReport/VReportDescForm.vue

Fixes #5026 by @obulat
This PR updates the colors of the text area inside the content report form to match the [Figma designs](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=6941-38780&m=dev).
https://github.com/user-attachments/assets/87c3096d-d655-4b70-b54e-94bd3dd413c9
Run the app using `ov just frontend/run dev`
Go to a single result page and click on "Report content".
Select a reason other than the first one. You should see the text area. It should look well in both dark and light themes, and should match the designs. …

Update the text area colors

---

.github/workflows/ci_cd.yml

Fast follow on #4991
`convictional/trigger-workflow-and-wait` expects `github_token`, and we are sending `token`.
Merge and see
<details>
```
Version 1.1
Suite D4700
By making …
```

Fix token in #4991

---

catalog/dags/data_refresh/distributed_reindex.py

Fixes parameter LaunchTemplateNames, which [must be a list](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_launch_templates.html).
<details>
```
Version 1.1
Suite D4700 …
```

Fix parameter type for fetching launch template number

---

catalog/dags/data_refresh/distributed_reindex.py

The indexer workers use port 8003 locally, but 8002 in production/staging. This is the smallest lift solution for handling the difference in environments. We should clean it up later, when the legacy data refresh is removed, by changing the local port to 8002 as well.
Ensure data refresh runs locally. 
<details>
```
Version 1.1
1 …
```

Use port 8002 for indexer worker in non-local environment

---

catalog/dags/data_refresh/distributed_reindex.py

Updates data refresh task dependencies to ensure that we wait for the indexer workers to finish initializing before we attempt to trigger the reindex.
Checkout the data refresh locally and look at the Graph view. Verify the dependencies look right:
<details>
```
Version 1.1
Suite D4700 …
```

Wait for worker to initialize before trying to trigger reindexing task

---

catalog/dags/data_refresh/distributed_reindex.py

Adds logging for the response from the describe_instance_status endpoint, and prevents an IndexError if the list is empty.
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Log instance status in distributed reindex, pass if empty

---

frontend/package.json
package.json
pnpm-lock.yaml

Necessary for Storybook Playwright tests to build and pass. See failure in https://github.com/WordPress/openverse/actions/runs/11529074974/job/32097106744?pr=5025
This PR updates the node version to v.22 (which is supposed to become LTS in October 2024), and also updates `pnpm`
Run `ov clean` and `ov init` to make sure that your ov node version is updated. Then, all the JS/TS code should work as usual.
<details>
```
Version 1.1
Copyright …
```

Update node and pnpm

---

package.json

Follow up to #5084 (set the Node version to 22, not 21)
#5084 incorrectly set the version specifier so that the Node version was updated to 21 instead of 22. This fixes it.
<details>
```
Version 1.1
Suite D4700
license document, but changing it …
```

Update node to v.22

---

catalog/dags/data_refresh/distributed_reindex.py
catalog/tests/dags/data_refresh/test_distributed_reindex.py

Fixes #5082 by @stacimc
Updates the `wait_for_worker` code in the new data refresh to correctly check that a given worker instance is running and that all systems are reported reachable.
This is very difficult to test manually, so refer to the added unit tests.
<details>
```
Version 1.1
Suite D4700 …
```

Update wait_for_worker checks to check instance is running and reachable

---

catalog/dags/data_refresh/distributed_reindex.py

Fixes the param name to `terminate_instances`, matching [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/terminate_instances.html).
This cannot be tested locally; once merged, we'll test manually on the staging data refresh DAG.
<details>
```
Version 1.1
Suite …
```

Fix param name in `terminate_indexer_worker` task

---

frontend/test/playwright/utils/expect-snapshot.ts

Fixes #5087 by @obulat
This PR increases the `sleep` time from 100ms to 200ms to ensure that the rendering is finished before taking the dark snapshot.
The CI should pass (I will re-run the VR tests several times)
<details>
```
Version 1.1
Suite D4700
license …
```

Increase the timeout before taking a dark snapshot

---

catalog/dags/data_refresh/copy_data.py
catalog/dags/data_refresh/data_refresh_types.py

This PR adjusts the timeout for the `add_primary_key` task of the image data refresh to allow it to complete. It also extends the indexer worker timeout just in case; we can tighten that up in the future once we see what the timing looks like.
Try running the staging image data refresh and verify the timeouts have been set in the `Details` view of the relevant task instances.
<details>
```
Version 1.1 …
```

Adjust timeouts for image data refresh

---

catalog/dags/data_refresh/alter_data.py

No limit was put on the number of `alter_data` batches run concurrently during the data refresh, causing Airflow to be overloaded during an image data refresh. This PR updates the DAG to allow a max of 2 concurrent `alter_data` batches. We can evaluate later if this can be increased (or even if it should be decreased to 1).
Run the `staging_image_data_refresh` DAG locally. Watch the `alter_batches[]` step and observe that no more than 2 tasks are put into the running state at a time.
<details> …

Limit to 2 `alter_data_batches` concurrently

---

catalog/dags/data_refresh/data_refresh_types.py

As a hypothesis, we'll increase the size of batches on the `alter_data_batch` step (for images) to prevent Airflow from collapsing from the overhead created by the mapped tasks. Trying with the double of the current value: `2_000_000`.
Spin up the stack.
```
just c && just a
```
Set the `IMAGE_DATA_REFRESH_ALTER_BATCH_SIZE` variable via the Airflow UI, run the `staging_image_data_refresh` DAG, and confirm the task takes the new number in the "Details" tab of the `get_alter_batches` step.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guide …

Increase batch size for image data refresh alter step

---

api/pyproject.toml
documentation/pdm.lock
documentation/pyproject.toml

Fixes #5146 by @AetherUnbound
This PR pins the `watchfiles` dependency, which seems like it's necessary for rust compatibility on install. I also added a comment for the API's dependencies which were modified in #5095, since that library isn't used directly in testing and can be unpinned once the dependency issues are resolved upstream.
Run `ov just documentation/install` and observe that it no longer fails!
<details>
```
Version 1.1 …
```

Pin watchfiles dependency in documentation for rust compatibility

---

README.md
documentation/general/contribution/current_maintainers.md

This PR updates the list of maintainers and moves Staci to the Acknowledgements section in the `README.md` file. 
<details>
```
Version 1.1
Suite D4700 …
```

Move Staci from current maintainers to `README.md`

---

documentation/index.md

Fixes #4967 by @zackkrida
This PR adds a meta description for our docs home page. A similar process can be applied to any page whose [auto-generated meta description](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#:~:text=Typically%20search%20engines%20will%20use%20the%20first%20few%20sentences%20of%20a%20page%20if%20no%20meta%20description%20is%20provided.) is unsatisfactory.
0. Check out the PR and start the Sphinx server: `just s`
1. View the source of the home page.
2. You should see the `<meta>` tag in the page header, that was not there before. …

Add meta description for documentation index page

---

catalog/compose.yml
docker/minio/env.template

This PR updates the healthcheck used by the MinIO container to `mc` which is the preferred healthcheck tool.
0. Check out the PR.
1. Start the catalog containers with `just catalog/up`.
2. Wait for a few seconds.
3. Run `just dc ps` to see the status of the Docker Compose services.
4. The MinIO service `s3` should show the status as healthy.
<details>
```
Version 1.1
1 …
```

Use healthcheck command preferred by MinIO

---

documentation/meta/release_and_deployment/runbooks/catalog.md

The filters were changed at some point with an Airflow update, so this is a small fix for updating the link to running DAGs in the Catalog deployment runbook.
Follow the link to the updated docs in the comment below, and observe it gets you to the correct view in Airflow, even if you had something else selected before, like the `status=paused` DAGs.
<details>
```
Version 1.1 …
```

Update link to running DAGs in runbook

---

api/api/admin/oauth.py

We were reviewing registered applications today and noticed that this list view could benefit from having these filters.
Run the API and go to http://localhost:50280/admin/api/throttledapplication/ to see the filters in the right bar.
<details>
```
Version 1.1
Suite D4700 …
```

Add filters to throttled application admin view

---

documentation/meta/maintenance/elasticsearch_cluster.md

This PR updates the documentation for node replacement to fix the problems identified in the last node replacement run.
Read the docs to verify that the new information is more accurate and fixes shortcomings in the old documentation.
<details>
```
Version 1.1
Suite D4700 …
```

Update node replacement docs based on last run

---

.github/renovate.json5

We perform these updates manually while Renovate keeps reporting them (see all the related docker updates in #255), creating noise.
N/A.
<details>
```
Version 1.1
Suite D4700 …
```

Disable renovate updates for ES, PG and Redis docker images

---

docker/dev_env/Dockerfile

Fixes #5246 by @obulat
This PR:
- downgrades Fedora to 41 (42 does not have a supported Docker version yet)
- replaces `dnf` with `dnf5` as that is the new default in Fedora 41
- updates the config command.
Run `ov init` on main and see the errors listed in the issue
Run `ov init` on this PR and see that it builds correctly.
<details>
```
Version 1.1
Suite …
```

Fix ov Dockerfile

---

documentation/projects/templates/implementation_plan.md
documentation/projects/templates/project_proposal.md

Fixes #4619 by @zackkrida
This PR adds a changelog section to the bottom of the project proposal and implementation plans. It uses the format that @AetherUnbound suggested. It seems as if there was good consensus around the idea as well as the proposed format, only that wasn't formally indicated on the issue.
There's not really a need to test this change but if you want you can run the `documentation/create-project` recipe to see if the output is correct.
<details>
``` …
```

Add changelog section to project proposal and implementation plan

---

.pre-commit-config.yaml

This PR updates the shfmt hook to remove the following warning:
```
[WARNING] repo `https://github.com/scop/pre-commit-shfmt` uses deprecated stage names (commit, merge-commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/scop/pre-commit-shfmt` will fix this.  if it does not -- consider reporting an issue to that repo.
```
<details>
```
Version 1.1
Copyright (C) 2004, 2006 …
```

Update `shfmt` hook to remove warning

---

api/api/serializers/base.py
api/api/serializers/image_serializers.py
api/api/serializers/media_serializers.py
api/api/utils/asyncio.py
api/api/views/audio_views.py
api/api/views/image_views.py
api/api/views/media_views.py
api/pdm.lock
api/pyproject.toml

Addresses #4851 by @sarayourfriend 
Bumping `adrf`, as the issue suggests, allowed to:
- Drop backported async methods, like `aget_object_or_404`
- Convert serializers to async for async views
- Simplify params from `thumbnail` view
Regarding cleaning up `MediaViewSet`, it's not possible to replace view sets because in that case, _all handler methods must be async_, too, requiring that all the submethods be async as well, and that is a significant amount of work pending on #3449.
Observe CI. It should continue to pass.
<details>
```
Version 1.1 …
```

Bump `adrf` to 0.1.8 and `aiohttp` to 3.11.10

---

automations/js/src/last_week_tonight.mjs

This PR updates the `last_week_tonight.mjs` script to not post if there isn't any change to post about. This is a edge case that was an impossibility so far so we hadn't considered it.
<details>
```
Version 1.1
Suite D4700 …
```

Skip posting if there is no change to post about

---

api/conf/settings/sentry.py

Related to WordPress/openverse-infrastructure#1125 by @obulat 
This PR aims to reduce our sentry **spans** quota usage by excluding the health checks. We can evaluate later how to tweak the other parts.
It's not clear what is in the Sentry's `sampling_context`. I found these references:
- [Sampling Context Data (Sentry for Python)](https://docs.sentry.io/platforms/python/configuration/sampling/#sampling-context-data)
- getsentry/sentry-python#3774/files
❓ 
<details>
``` …
```

Exclude health checks from Sentry profiles sampling

---

api/api/utils/image_proxy/__init__.py

Closes #5334 by @krysal though the actual fix was #5332, so this is just a cleanup.
This reverts commit f41f20d27615a52d538c3772b64da4c3f1fed0a2. Removes a piece of code that did nothing.
```
just api/test
```
<details>
```
Version 1.1
Suite D4700
license …
```

Revert "Close old db connections after getting thumbnails (#5335)"

---

catalog/dags/providers/provider_reingestion_workflows.py

Fixes #5358 by @obulat 
- In this update, the `three_month_list_length` value has been changed from 18 to 38, and the `six_month_list_length` value has been adjusted from 20 to 20 for the `ProviderReingestionWorkflow` that corresponds to the workflow with 64 total reingestion days.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Update the Met Museum reingestion partitions

---

frontend/src/app.vue
frontend/src/error.vue

Fixes #5377 by @sentry-io
This PR removes the usage of `Head`, `Meta` and `Body` components, which are causing problems when the comments are being hydrated. 
Run the app and see that the comments are no longer in the body.  The i18n-related meta and links should still be available, as well as the i18n properties on the html and body elements.
<details>
```
Version 1.1
1 …
```

Move Head, Meta, Body props to `useHead`

---

README.md

Fixes #5462 by @oliviaz134
Fixes the README's broken links for Project Board, Handbook, and Brand.
Project Board Link Redirection Before:
Project Board Link Redirection After:
Handbook Link Redirection Before:
Handbook Link Redirection After:
Brand Link Redirection Before:
Brand Link Redirection After:
Click on the updated links to test.
<details>
```
Version 1.1
1 …
```

Update Project Board, Handbook, and Brand links in README
